Repository spryker/spryker-docs, pull requests merged in 2021-12, with the labels that each got.

#598 Add mp-upcoming-major-module-releases
  _data/sidebars/marketplace_user_sidebar.yml
  docs/marketplace/user/intro-to-the-spryker-marketplace/upcoming-major-module-releases.md
  docs/scos/user/intro-to-spryker/whats-new/upcoming-major-module-releases.md
Labels: tech review needed, TW review needed

#602 Remove superfluous whitespace character
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
Labels: in TW review

#599 SUPESC-274: updated Heidelpay integration.
  docs/scos/user/technology-partners/202108.0/payment-partners/heidelpay/scos-integration/heidelpay-integration-into-scos.md
Labels: in TW review

#628 Add note
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-windows.md
Labels: in TW review

#610 Add a warning about project folder
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-windows.md
Labels: in TW review

#635 Fixed typo
  docs/scos/user/features/202108.0/product-labels-feature-overview.md
Labels: in TW review

#594 CC-12884 support configurable products in the wishlist
  docs/scos/dev/glue-api-guides/202108.0/managing-products/abstract-products/retrieving-abstract-product-prices.md
  docs/scos/dev/glue-api-guides/202200.0/managing-wishlists/managing-wishlist-items.md
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-content-and-search-attribute-cart-based-catalog-personalization-spryker-commerce-os/tutorial-content-and-search-attribute-cart-based-catalog-personalization-spryker-commerce-os/tutorial-boosting-cart-based-search-tutorial-content-and-search-attribute-cart-based-catalog-personalization.md
  docs/scos/user/features/202108.0/configurable-product-feature-overview.md
  docs/scos/user/features/202200.0/configurable-product-feature-overview.md
Labels: in progress

#634 [CC-14622] ac doc documentation display discounted price on promotional product
  docs/scos/user/back-office-user-guides/202200.0/merchandising/discount/creating-cart-rules.md
  docs/scos/user/back-office-user-guides/202200.0/merchandising/discount/creating-vouchers.md
  docs/scos/user/back-office-user-guides/202200.0/merchandising/discount/managing-discounts.md
  docs/scos/user/features/202200.0/promotions-discounts-feature-overview.md
Labels: in progress, in TW review

#638 [CC-14556] AC Doc Documentation Discount valid from/to supports time definition
  docs/scos/user/back-office-user-guides/202200.0/merchandising/discount/creating-vouchers.md
  docs/scos/user/features/202200.0/promotions-discounts-feature-overview.md
Labels: in progress, in TW review
