Repository spryker/spryker-docs, pull requests merged in 2021-11, with the labels that each got.

#516 Update configuring-services.md
  docs/scos/dev/the-docker-sdk/202108.0/configuring-services.md
Labels: documentation

#514 Fix MP requirements for yarn version
  docs/marketplace/dev/front-end/setting-up-the-merchant-portal.md
Labels: documentation

#366 MP-5723: added walkthrough guide for merchant category
  docs/marketplace/dev/feature-walkthroughs/202108.0/merchant-category-feature-walkthrough.md
Labels: documentation

#371 MP-5711: Walkthrough guide for Marketplace Merchant feature
  docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-merchant-feature-walkthrough.md
Labels: documentation

#376 MP-5706 How to upgrade Spryker instance to Marketplace.
  _data/sidebars/marketplace_dev_sidebar.yml
  docs/marketplace/dev/feature-integration-guides/202108.0/merchant-portal-marketplace-product-option-management-feature-integration.md
  docs/marketplace/dev/howtos/how-to-upgrade-spryker-instance-to-marketplace.md
Labels: documentation

#367 MP-4522: Walkthrough guide for Merchant Opening Hours
  docs/marketplace/dev/feature-walkthroughs/202108.0/merchant-opening-hours-feature-walkthrough.md
Labels: documentation

#522 CC-12637: Support configurable products in the wish list.
  docs/scos/dev/feature-integration-guides/202200.0/glue-api/glue-api-product-configuration-feature-integration.md
  docs/scos/dev/feature-integration-guides/202200.0/product-configuration-feature-integration.md
Labels: documentation

#527 Add release history link
  docs/scos/user/intro-to-spryker/releases/releases.md
Labels: enhancement

#572 Add missing instructions on securing GLUE API.
  docs/scos/dev/guidelines/making-your-spryker-shop-secure.md
Labels: ready for merge

#561 Missing migration guide step
  docs/scos/dev/module-migration-guides/202108.0/migration-guide-category.md
Labels: ready for merge, TW review needed

#582 Add getFormFactory() method to Factory class
  docs/scos/dev/back-end-development/forms/creating-forms.md
Labels: tech review needed, TW review needed

#587 Update b2b demo shop url
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-windows.md
Labels: in TW review

#592 Update installing-in-demo-mode-on-macos-and-linux.md
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-macos-and-linux.md
Labels: in progress
