Repository spryker/spryker-docs, pull requests merged in 2022-09, with the labels that each got.

#742 CC-14561: Support multiple abstract products in discount promotional products.
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202204.0/install-multiple-abstract-products-as-promotional-products-and-discounts-feature.md
  docs/scos/dev/feature-integration-guides/202204.0/multiple-abstract-products-as-promotional-products-and-discounts-feature-integration.md
Labels: ready for merge

#1201 CC-17227 Restrict access to merchant portal for main merchant user
  _data/sidebars/marketplace_dev_sidebar.yml
  docs/marketplace/dev/feature-integration-guides/202212.0/marketplace-merchant-portal-core-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202212.0/merchant-portal-feature-integration.md
  docs/marketplace/user/intro-to-spryker-marketplace/marketplace-personas.md
  docs/marketplace/user/merchant-portal-user-guides/202108.0/logging-in-to-the-merchant-portal.md
  docs/marketplace/user/merchant-portal-user-guides/202204.0/logging-in-to-the-merchant-portal.md
Labels: ready for merge

#1204 CC-20877 Migration guide - Remove support of IE11
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/migration-guide-remove-support-of-ie11.md
  docs/scos/dev/front-end-development/migration-guide-switch-from-yarn-to-npm.md
Labels: ready for merge

#1205 CC-13273 Disaply Number in Zed documentation.
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202212.0/install-the-cart.md
  _includes/pbc/all/install-features/202212.0/install-the-shipment-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-spryker-core-back-office-feature.md
  _includes/pbc/all/upgrade-modules/upgrade-the-productmanagement-module.md
  docs/scos/dev/feature-integration-guides/202212.0/shipment-feature-integration.md
  docs/scos/dev/feature-integration-guides/202212.0/spryker-core-back-office-feature-integration.md
  docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/howto-add-support-of-number-formatting-in-the-back-office.md
Labels: ready for merge

#1217 Contributor: Remove Payone
  docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer.md
Labels: contributor

#1206 CC-20876 Docs update - Remove support of IE11
  docs/marketplace/dev/howtos/how-to-create-a-new-module-with-application.md
  docs/scos/dev/back-end-development/console-commands/console-commands.md
  docs/scos/dev/front-end-development/yves/atomic-frontend/atomic-front-end-general-overview.md
  docs/scos/dev/front-end-development/yves/atomic-frontend/customizing-spryker-front-end.md
  docs/scos/dev/front-end-development/yves/frontend-assets-building-and-loading.md
  docs/scos/dev/technical-enhancement-integration-guides/integrating-css-lazy-loading-for-the-front-end.md
  docs/scos/dev/technology-partner-guides/202212.0/marketing-and-conversion/analytics/fact-finder/installing-and-configuring-fact-finder-web-components.md
Labels: ready for merge

#1152 Bugfix/cc 16642 marketplace wishlist item delete api
  docs/marketplace/dev/feature-integration-guides/202204.0/glue/marketplace-product-offer-wishlist-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202212.0/glue/marketplace-product-offer-wishlist-feature-integration.md
Labels: ready for merge

#1216 Contributor: Fixing doc blocks and casing
  docs/pbc/all/payment-service-providers/unzer/extend-and-customize/implement-new-payment-methods-on-the-project-level.md
  docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer.md
Labels: in progress, contributor

#1221 Replace spryker videos page
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/spryker-academy.md
  docs/scos/user/shop-user-guides/201811.0/about-shop-user-guide.md
  docs/scos/user/shop-user-guides/201903.0/about-shop-user-guide.md
  docs/scos/user/shop-user-guides/201907.0/about-shop-user-guide.md
  docs/scos/user/shop-user-guides/202001.0/about-shop-user-guide.md
  docs/scos/user/shop-user-guides/202005.0/about-shop-user-guide.md
Labels: ready for merge

#1224 SUPESC-612 Updated CrefoPay IG with Notes related to checkout validation.
  docs/scos/dev/technology-partner-guides/202204.0/payment-partners/crefopay/integrating-crefopay.md
Labels: ready for merge

#1207 Added a title, so I can create a link to this section
  _data/sidebars/marketplace_dev_sidebar.yml
  _data/sidebars/pbc_all_sidebar.yml
  _data/sidebars/scos_dev_sidebar.yml
  docs/marketplace/dev/data-import/202204.0/data-import.md
  docs/pbc/all/price-management/extend-and-customize/priceproduct-module-details-reference-information.md
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/data-ingestion.md
  docs/scos/dev/data-import/202204.0/data-import.md
  docs/scos/user/back-office-user-guides/202009.0/catalog/products/references/reference-information-concrete-product.md
Labels: ready for merge

#1214 SUPESC-425: Removed non-searchable products from product search suggestions.
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202212.0/install-the-product-feature.md
  docs/scos/dev/feature-integration-guides/202212.0/product-feature-integration.md
Labels: in TW review

#1219 CC-21132 AC Documentation Support configurable products in the shopping list
  _data/sidebars/scos_dev_sidebar.yml
  docs/pbc/all/shopping-list-and-wishlist/manage-via-glue-api/manage-shopping-list-items-via-glue-api.md
Labels: ready for merge, in progress

#1240 Contributor localheinz
  docs/marketplace/dev/feature-integration-guides/202204.0/marketplace-merchant-feature-integration.md
Labels: ready for merge, contributor

#1244 Fixed doc from Customer request.
  docs/pbc/all/payment-service-providers/unzer/configuration-in-the-back-office/add-unzer-marketplace-credentials.md
  docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue-api.md
Labels: ready for merge

#1253 Remove beta mention
  docs/scos/dev/sdk/data-export.md
Labels: ready for merge

#1246 B2B. YVES. Wrong info in printing return details
  docs/scos/user/features/202204.0/product-barcode-feature-overview.md
Labels: ready for merge

#1254 Landing page for /scos/dev/data export section
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/data-export/202204.0/data-export-orders-.csv-files-format.md
  docs/scos/dev/data-export/202204.0/data-export.md
  docs/scos/dev/data-export/202204.0/index.md
Labels: in progress

#1256 Add link to performance tips
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: ready for merge

#1141 Ratings & Review PBC
  _data/sidebars/pbc_all_sidebar.yml
  _data/sidebars/scos_dev_sidebar.yml
  _data/sidebars/scos_user_sidebar.yml
  _includes/pbc/all/install-features/202204.0/install-the-product-rating-and-reviews-feature.md
  docs/marketplace/dev/glue-api-guides/202204.0/abstract-products/retrieving-abstract-products.md
  docs/marketplace/dev/glue-api-guides/202204.0/concrete-products/retrieving-concrete-products.md
  docs/pbc/all/pbc.md
  docs/pbc/all/ratings-reviews/import-and-export-data/file-details-product-review.csv.md
  docs/pbc/all/ratings-reviews/install-and-upgrade/install-the-product-rating-and-reviews-feature.md
  docs/pbc/all/ratings-reviews/install-and-upgrade/install-the-product-rating-and-reviews-glue-api.md
  docs/pbc/all/ratings-reviews/install-and-upgrade/install-the-product-rating-and-reviews-product-group-feature.md
  docs/pbc/all/ratings-reviews/manage-in-the-back-office/manage-product-reviews-in-the-back-office.md
  docs/pbc/all/ratings-reviews/manage-using-glue-api/manage-product-reviews-using-glue-api.md
  docs/pbc/all/ratings-reviews/manage-using-glue-api/retrieve-product-reviews-when-retrieving-abstract-products.md
  docs/pbc/all/ratings-reviews/manage-using-glue-api/retrieve-product-reviews-when-retrieving-concrete-products.md
  docs/pbc/all/ratings-reviews/ratings-reviews.md
  docs/pbc/all/ratings-reviews/third-party-integrations/bazaarvoice.md
  docs/pbc/all/ratings-reviews/third-party-integrations/configure-bazaarvoice.md
  docs/pbc/all/ratings-reviews/third-party-integrations/disconnect-bazaarvoice.md
  docs/pbc/all/ratings-reviews/third-party-integrations/integrate-bazaarvoice.md
  docs/pbc/all/ratings-reviews/tutorials-and-howtos/howto-configure-product-reviews.md
  docs/pbc/all/ratings-reviews/whats-changed-in-ratings-and-reviews.md
  docs/scos/dev/feature-integration-guides/201811.0/product-rating-and-reviews-feature-integration.md
  docs/scos/dev/feature-integration-guides/201903.0/product-rating-and-reviews-feature-integration.md
  docs/scos/dev/feature-integration-guides/201907.0/product-rating-and-reviews-feature-integration.md
  docs/scos/dev/feature-integration-guides/202001.0/product-rating-and-reviews-feature-integration.md
  docs/scos/dev/feature-integration-guides/202005.0/product-rating-and-reviews-feature-integration.md
  docs/scos/dev/feature-integration-guides/202009.0/product-rating-and-reviews-feature-integration.md
  docs/scos/dev/feature-integration-guides/202108.0/product-rating-and-reviews-feature-integration.md
  docs/scos/dev/feature-walkthroughs/202204.0/product-rating-reviews-feature-walkthrough.md
  docs/scos/dev/glue-api-guides/202204.0/managing-products/abstract-products/retrieving-abstract-products.md
  docs/scos/dev/glue-api-guides/202204.0/managing-products/concrete-products/retrieving-concrete-products.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/run-the-evaluator-tool.md
  docs/scos/dev/tutorials-and-howtos/howtos/about-howtos.md
  docs/scos/user/features/202204.0/product-rating-and-reviews-feature-overview.md
  docs/scos/user/intro-to-spryker/intro-to-spryker.md
  docs/scos/user/intro-to-spryker/whats-new/documentation-updates.md
  docs/scos/user/technology-partners/202204.0/customer-service/live-chat-service.md
Labels: in progress

#1257 [WIP] CC-21378 Cleanup major module release pages
  docs/marketplace/user/intro-to-spryker-marketplace/upcoming-major-module-releases.md
  docs/scos/user/intro-to-spryker/whats-new/upcoming-major-module-releases.md
Labels: ready for merge

#1261 Fixed Unzer glue api integration
  docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue-api.md
Labels: in TW review
