Repository spryker/spryker-docs, pull requests merged in 2022-08, with the labels that each got.

#1134 Scos user guides review
  docs/scos/user/features/202204.0/approval-process-feature-overview.md
  docs/scos/user/features/202204.0/cart-feature-overview/cart-feature-overview.md
  docs/scos/user/features/202204.0/category-management-feature-overview.md
  docs/scos/user/features/202204.0/checkout-feature-overview/order-thresholds-overview.md
  docs/scos/user/features/202204.0/cms-feature-overview/email-as-a-cms-block-overview.md
  docs/scos/user/features/202204.0/cms-feature-overview/templates-and-slots-overview.md
  docs/scos/user/features/202204.0/comments-feature-overview.md
  docs/scos/user/features/202204.0/company-account-feature-overview/business-on-behalf-overview.md
  docs/scos/user/features/202204.0/company-account-feature-overview/company-account-feature-overview.md
  docs/scos/user/features/202204.0/company-account-feature-overview/company-accounts-overview.md
  docs/scos/user/features/202204.0/company-account-feature-overview/company-user-roles-and-permissions-overview.md
  docs/scos/user/features/202204.0/company-account-feature-overview/customer-login-by-token-overview.md
  docs/scos/user/features/202204.0/customer-account-management-feature-overview/password-management-overview.md
  docs/scos/user/features/202204.0/features.md
  docs/scos/user/features/202204.0/file-manager-feature-overview/file-uploader.md
  docs/scos/user/features/202204.0/gift-cards-feature-overview.md
  docs/scos/user/features/202204.0/inventory-management-feature-overview.md
  docs/scos/user/features/202204.0/mailing-and-notifications-feature-overview.md
  docs/scos/user/features/202204.0/measurement-units-feature-overview.md
  docs/scos/user/features/202204.0/merchant-custom-prices-feature-overview.md
  docs/scos/user/features/202204.0/multiple-carts-feature-overview.md
  docs/scos/user/features/202204.0/non-splittable-products-feature-overview.md
  docs/scos/user/features/202204.0/order-management-feature-overview/custom-order-reference-overview.md
  docs/scos/user/features/202204.0/order-management-feature-overview/invoice-generation-overview.md
  docs/scos/user/features/202204.0/order-management-feature-overview/oms-order-management-system-matrix.md
  docs/scos/user/features/202204.0/order-management-feature-overview/order-cancellation-overview.md
  docs/scos/user/features/202204.0/order-management-feature-overview/order-management-feature-overview.md
  docs/scos/user/features/202204.0/order-management-feature-overview/split-delivery-overview.md
  docs/scos/user/features/202204.0/order-management-feature-overview/splittable-order-items-overview.md
  docs/scos/user/features/202204.0/packaging-units-feature-overview.md
  docs/scos/user/features/202204.0/persistent-cart-sharing-feature-overview.md
  docs/scos/user/features/202204.0/prices-feature-overview/prices-feature-overview.md
  docs/scos/user/features/202204.0/prices-feature-overview/volume-prices-overview.md
  docs/scos/user/features/202204.0/product-barcode-feature-overview.md
  docs/scos/user/features/202204.0/product-bundles-feature-overview.md
  docs/scos/user/features/202204.0/product-feature-overview/product-attributes-overview.md
  docs/scos/user/features/202204.0/product-feature-overview/product-feature-overview.md
  docs/scos/user/features/202204.0/product-feature-overview/search-widget-for-concrete-products-overview.md
  docs/scos/user/features/202204.0/product-groups-feature-overview.md
  docs/scos/user/features/202204.0/product-relations-feature-overview.md
  docs/scos/user/features/202204.0/promotions-discounts-feature-overview.md
  docs/scos/user/features/202204.0/quick-add-to-cart-feature-overview.md
  docs/scos/user/features/202204.0/quotation-process-feature-overview.md
  docs/scos/user/features/202204.0/reclamations-feature-overview.md
  docs/scos/user/features/202204.0/return-management-feature-overview/building-a-return-management-process-best-practices.md
  docs/scos/user/features/202204.0/return-management-feature-overview/return-management-feature-overview.md
  docs/scos/user/features/202204.0/search-feature-overview/category-filters-overview.md
  docs/scos/user/features/202204.0/search-feature-overview/search-types-overview.md
  docs/scos/user/features/202204.0/search-feature-overview/standard-filters-overview.md
  docs/scos/user/features/202204.0/shared-carts-feature-overview.md
  docs/scos/user/features/202204.0/shopping-lists-feature-overview/shopping-list-notes-overview.md
  docs/scos/user/features/202204.0/shopping-lists-feature-overview/shopping-list-printing-overview.md
  docs/scos/user/features/202204.0/shopping-lists-feature-overview/shopping-list-widget-overview.md
  docs/scos/user/features/202204.0/shopping-lists-feature-overview/shopping-lists-feature-overview.md
  docs/scos/user/features/202204.0/spryker-core-back-office-feature-overview/back-office-translations-overview.md
  docs/scos/user/features/202204.0/spryker-core-back-office-feature-overview/spryker-core-back-office-feature-overview.md
  docs/scos/user/features/202204.0/spryker-core-feature-overview/vault-for-tokens-overview.md
Labels: in progress

#1148 SUPESC-392 Added warning for store specific generate validation cache command.
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/glue-api/validating-rest-request-format.md
Labels: ready for merge

#1149 СС-18569 Fix docs - Switch from Yarn to NPM
  docs/scos/dev/front-end-development/migration-guide-switch-from-yarn-to-npm.md
Labels: ready for merge

#1153 Contributor 2
  docs/scos/dev/analyzing-and-upgrading-your-project-with-spryker-jarvis.md
  docs/scos/dev/developer-getting-started-guide.md
Labels: contributor

#1145 Contributor
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/developer-getting-started-guide.md
  docs/scos/dev/feature-walkthroughs/202204.0/cart-feature-walkthrough/calculation-3-0.md
  docs/scos/dev/feature-walkthroughs/202204.0/cart-feature-walkthrough/calculation-data-structure.md
  docs/scos/dev/feature-walkthroughs/202204.0/cart-feature-walkthrough/calculator-plugins.md
  docs/scos/dev/feature-walkthroughs/202204.0/cart-feature-walkthrough/cart-module-reference-information.md
  docs/scos/dev/feature-walkthroughs/202204.0/cms-feature-walkthrough/cms-extension-points-reference-information.md
  docs/scos/dev/feature-walkthroughs/202204.0/company-account-feature-walkthrough/company-account-feature-walkthrough.md
  docs/scos/dev/feature-walkthroughs/202204.0/company-account-feature-walkthrough/company-account-module-relations.md
  docs/scos/dev/feature-walkthroughs/202204.0/company-account-feature-walkthrough/customer-login-by-token-reference-information.md
  docs/scos/dev/feature-walkthroughs/202204.0/configurable-product-feature-walkthrough/configuration-process-flow-of-configurable-product.md
  docs/scos/dev/feature-walkthroughs/202204.0/content-items-feature-walkthrough/content-item-types-module-relations.md
  docs/scos/dev/feature-walkthroughs/202204.0/customer-account-management-feature-walkthrough/customer-module-overview-reference-information.md
  docs/scos/dev/feature-walkthroughs/202204.0/inventory-management-feature-walkthrough/inventory-management-feature-walkthrough.md
  docs/scos/dev/feature-walkthroughs/202204.0/inventory-management-feature-walkthrough/managing-stocks-in-a-multi-store-environment-best-practices.md
  docs/scos/dev/feature-walkthroughs/202204.0/measurement-units-feature-walkthrough.md
  docs/scos/dev/feature-walkthroughs/202204.0/merchant-product-restrictions-feature-walkthrough/restricted-products-behavior.md
  docs/scos/dev/feature-walkthroughs/202204.0/navigation-feature-walkthrough/navigation-module-reference-information.md
  docs/scos/dev/feature-walkthroughs/202204.0/order-management-feature-walkthrough/sales-module-reference-information.md
  docs/scos/dev/feature-walkthroughs/202204.0/prices-feature-walkthrough/money-module-reference-information.md
  docs/scos/dev/feature-walkthroughs/202204.0/prices-feature-walkthrough/priceproduct-module-details-reference-information.md
  docs/scos/dev/feature-walkthroughs/202204.0/product-feature-walkthrough.md
  docs/scos/dev/feature-walkthroughs/202204.0/resource-sharing-feature-walkthrough.md
  docs/scos/dev/feature-walkthroughs/202204.0/search-feature-walkthrough.md
  docs/scos/dev/feature-walkthroughs/202204.0/shipment-feature-walkthrough/shipment-feature-walkthrough.md
  docs/scos/dev/feature-walkthroughs/202204.0/shipment-feature-walkthrough/shipment-method-plugins-reference-information.md
  docs/scos/dev/feature-walkthroughs/202204.0/spryker-core-back-office-feature-walkthrough/spryker-core-back-office-feature-walkthrough.md
Labels: ready for merge, contributor

#1147 SUPESC-600: Modified docs and diagram due to the changed functionality
  _config.yml
  docs/marketplace/dev/glue-api-guides/upcoming-release/guest-carts/managing-guest-carts.md
  docs/scos/dev/glue-api-guides/upcoming-release/managing-carts/guest-carts/managing-guest-carts.md
Labels: tech review needed

#1156 Update preparation-for-going-live.md
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: ready for merge

#1123 CC-19289 Added new Unzer doc
  _data/sidebars/pbc_all_sidebar.yml
  css/pages/_content.scss
  docs/pbc/all/payment-service-providers/unzer/extend-and-customize/customize-the-credit-card-display-in-your-payment-step.md
  docs/pbc/all/payment-service-providers/unzer/extend-and-customize/implement-new-payment-methods-on-the-project-level.md
Labels: ready for merge

#1162 Contributor
  docs/cloud/dev/spryker-cloud-commerce-os/environments-overview.md
Labels: ready for merge, contributor

#1167 CC-16934 Glue support for Unzer IG.
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer-glue-api.md
Labels: ready for merge

#1157 [SUPESC-259] Crefo-pay integration guide isn't up-to-date
  docs/scos/dev/technology-partner-guides/202204.0/payment-partners/crefopay/integrating-crefopay.md
Labels: ready for merge

#1163 [APPS-4816] [Payone PBC] Credit card page has hard-coded company name…
  docs/pbc/all/payment-service-providers/payone/payone.md
Labels: in TW review

#1169 SUPESC-621 Updated Unzer IG.
  docs/pbc/all/payment-service-providers/unzer/configuration-in-the-back-office/add-unzer-marketplace-credentials.md
  docs/pbc/all/payment-service-providers/unzer/configuration-in-the-back-office/add-unzer-standard-credentails.md
  docs/pbc/all/payment-service-providers/unzer/install-unzer/integrate-unzer.md
Labels: in TW review

#1154 SUPESC-400 Updated Heideplay IG to show payment forms.
  docs/scos/dev/technology-partner-guides/202204.0/payment-partners/heidelpay/integrating-heidelpay.md
Labels: in TW review

#1182 contributor-2
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/structural-preparations/creating-using-and-extending-the-transfer-objects.md
Labels: ready for merge, contributor

#1168 Contributor
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/structural-preparations/creating-using-and-extending-the-transfer-objects.md
  docs/scos/dev/data-import/202204.0/data-import-categories/about-data-import-categories.md
Labels: ready for merge, contributor

#1166 add missing verb to the sentence
  docs/cloud/dev/spryker-cloud-commerce-os/environments-overview.md
Labels: do not merge, contributor

#1181 Update available-test-helpers.md
  docs/scos/dev/guidelines/testing-guidelines/available-test-helpers.md
Labels: ready for merge

#1194 Contributor 3
  docs/scos/dev/back-end-development/zed-ui-tables/creating-and-configuring-zed-tables.md
  docs/scos/dev/guidelines/testing-guidelines/available-test-helpers.md
Labels: contributor

#1189 Contributor: Update state-machine-cookbook-part-i-state-machine-fundamentals.md
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
  docs/scos/dev/back-end-development/zed-ui-tables/creating-and-configuring-zed-tables.md
  docs/scos/dev/best-practices/state-machine-cookbook/state-machine-cookbook-part-i-state-machine-fundamentals.md
Labels: ready for merge, contributor

#1190 Fixed typo
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
Labels: do not merge, contributor

#1192 Wrong headlines and streamlining text
  docs/scos/dev/guidelines/testing-guidelines/available-test-helpers.md
Labels: do not merge, contributor

#1176 Update whats-changed-in-discount-management.md
  docs/pbc/all/discount-management/whats-changed-in-discount-management.md
Labels: TW review needed

#1175 Update whats-changed-in-tax-management.md
  docs/pbc/all/tax-management/whats-changed-in-tax-management.md
Labels: TW review needed

#1043 Update integrating-separate-endpoint-bootstraps.md
  docs/scos/dev/technical-enhancement-integration-guides/integrating-separate-endpoint-bootstraps.md
Labels: TW review needed

#1199 Fix typo in README
  README.md
Labels: ready for merge, contributor

#1198 Fix typo in README
  README.md
Labels: do not merge, contributor

#1161 CC-9276: Support configurable products in the shopping list.
  _includes/pbc/all/install-features/202204.0/install-glue-api/install-the-product-configuration-glue-api.md
  _includes/pbc/all/install-features/202204.0/install-the-product-configuration-feature.md
Labels: ready for merge

#1177 Update whats-changed-in-carrier-management.md
  docs/pbc/all/carrier-management/whats-changed-in-carrier-management.md
  docs/pbc/all/discount-management/whats-changed-in-discount-management.md
  docs/pbc/all/tax-management/whats-changed-in-tax-management.md
  docs/scos/dev/technical-enhancement-integration-guides/integrating-separate-endpoint-bootstraps.md
Labels: ready for merge

#1183 SUPESC-144: Added integration of `CartItemPricePreCheckPlugin` plugin
  Rakefile
  _config.yml
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202212.0/install-the-cart.md
  docs/scos/dev/feature-integration-guides/202212.0/cart-integration.md
Labels: ready for merge
