Repository spryker/spryker-docs, pull requests merged in 2022-07, with the labels that each got.

#1037 Define 80% as minimum for image width
  css/pages/_content.scss
Labels: TW review needed

#1042 Updates endpoints
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-windows.md
Labels: in TW review

#1023 SUPESC-514: Added a missing part in Approval process feature IG
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/feature-integration-guides/202204.0/approval-process-feature-integration.md
Labels: TW review needed

#1050 Create dependabot.yml
  .github/dependabot.yml
Labels: TW review needed

#1039 Update reference-information-shipment-method-plugins.md
  docs/scos/dev/feature-walkthroughs/202204.0/shipment-feature-walkthrough/reference-information-shipment-method-plugins.md
Labels: ready for merge

#1065 Contributor
  docs/marketplace/dev/setup/spryker-marketplace-setup.md
  docs/scos/dev/feature-walkthroughs/202204.0/shipment-feature-walkthrough/reference-information-shipment-method-plugins.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/private-api-is-extended.md
  docs/scos/dev/technical-enhancement-integration-guides/integrating-health-checks.md
  docs/scos/user/features/202204.0/category-management-feature-overview.md
Labels: ready for merge, contributor

#886 Update discontinued-products-overview.md
  docs/scos/user/features/202108.0/product-feature-overview/discontinued-products-overview.md
Labels: TW review needed

#1075 Remove outdated page and add redirect
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/whats-new/vat-rates-reduction-in-germany-between-july-2020-and-january-2021.md
  docs/scos/user/intro-to-spryker/whats-new/whats-new.md
Labels: TW review needed

#1072 Add modules cleanup
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/dev/developer-getting-started-guide.md
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-api-product-feature-integration.md
  docs/scos/user/features/202108.0/product-feature-overview/discontinued-products-overview.md
  docs/scos/user/intro-to-spryker/whats-new/vat-rates-reduction-in-germany-between-july-2020-and-january-2021.md
  docs/scos/user/intro-to-spryker/whats-new/whats-new.md
  docs/sdk/dev/spryker-sdk.md
Labels: ready for merge

#1108 fixed broken link
  docs/pbc/all/payment-service-providers/unzer/unzer.md
Labels: ready for merge

#1116 scos/user review
  docs/scos/user/features/202204.0/cms-feature-overview/cms-pages-in-search-results-overview.md
  docs/scos/user/features/202204.0/company-account-feature-overview/business-on-behalf-overview.md
  docs/scos/user/features/202204.0/customer-access-feature-overview.md
  docs/scos/user/features/202204.0/gift-cards-feature-overview.md
  docs/scos/user/features/202204.0/inventory-management-feature-overview.md
  docs/scos/user/features/202204.0/mailing-and-notifications-feature-overview.md
  docs/scos/user/features/202204.0/measurement-units-feature-overview.md
  docs/scos/user/features/202204.0/merchant-b2b-contracts-feature-overview.md
  docs/scos/user/features/202204.0/merchant-custom-prices-feature-overview.md
  docs/scos/user/features/202204.0/merchant-product-restrictions-feature-overview.md
  docs/scos/user/features/202204.0/multiple-carts-feature-overview.md
  docs/scos/user/features/202204.0/navigation-feature-overview.md
  docs/scos/user/features/202204.0/non-splittable-products-feature-overview.md
  docs/scos/user/features/202204.0/order-management-feature-overview/invoice-generation-overview.md
  docs/scos/user/features/202204.0/order-management-feature-overview/split-delivery-overview.md
  docs/scos/user/features/202204.0/packaging-units-feature-overview.md
  docs/scos/user/features/202204.0/payments-feature-overview.md
  docs/scos/user/features/202204.0/persistent-cart-sharing-feature-overview.md
  docs/scos/user/features/202204.0/product-barcode-feature-overview.md
  docs/scos/user/features/202204.0/product-feature-overview/product-feature-overview.md
  docs/scos/user/features/202204.0/product-groups-feature-overview.md
  docs/scos/user/features/202204.0/product-options-feature-overview.md
  docs/scos/user/features/202204.0/promotions-discounts-feature-overview.md
  docs/scos/user/features/202204.0/quick-add-to-cart-feature-overview.md
  docs/scos/user/features/202204.0/quotation-process-feature-overview.md
  docs/scos/user/features/202204.0/return-management-feature-overview/building-a-return-management-process-best-practices.md
  docs/scos/user/features/202204.0/return-management-feature-overview/return-management-feature-overview.md
  docs/scos/user/features/202204.0/scheduled-prices-feature-overview.md
  docs/scos/user/features/202204.0/spryker-core-back-office-feature-overview/spryker-core-back-office-feature-overview.md
Labels: in progress

#1113 СС-18569 Migration guide - Switch from Yarn to NPM v8
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/migration-guide-switch-from-yarn-to-npm.md
Labels: TW review needed

#1117 scos/user-review
  docs/pbc/all/tax-management/tax-management.md
  docs/scos/user/features/202204.0/cart-feature-overview/cart-feature-overview.md
  docs/scos/user/features/202204.0/cart-feature-overview/cart-notes-overview.md
  docs/scos/user/features/202204.0/cart-feature-overview/cart-widget-overview.md
  docs/scos/user/features/202204.0/cart-feature-overview/quick-order-from-the-catalog-page-overview.md
  docs/scos/user/features/202204.0/checkout-feature-overview/checkout-feature-overview.md
  docs/scos/user/features/202204.0/checkout-feature-overview/multi-step-checkout-overview.md
  docs/scos/user/features/202204.0/checkout-feature-overview/order-thresholds-overview.md
  docs/scos/user/features/202204.0/cms-feature-overview/cms-blocks-overview.md
  docs/scos/user/features/202204.0/cms-feature-overview/cms-feature-overview.md
  docs/scos/user/features/202204.0/cms-feature-overview/cms-pages-in-search-results-overview.md
  docs/scos/user/features/202204.0/cms-feature-overview/cms-pages-overview.md
  docs/scos/user/features/202204.0/cms-feature-overview/email-as-a-cms-block-overview.md
  docs/scos/user/features/202204.0/cms-feature-overview/templates-and-slots-overview.md
  docs/scos/user/features/202204.0/company-account-feature-overview/business-on-behalf-overview.md
  docs/scos/user/features/202204.0/company-account-feature-overview/business-units-overview.md
  docs/scos/user/features/202204.0/company-account-feature-overview/company-account-feature-overview.md
  docs/scos/user/features/202204.0/company-account-feature-overview/company-accounts-overview.md
  docs/scos/user/features/202204.0/company-account-feature-overview/company-user-roles-and-permissions-overview.md
  docs/scos/user/features/202204.0/company-account-feature-overview/customer-login-by-token-overview.md
  docs/scos/user/features/202204.0/customer-account-management-feature-overview/customer-account-management-feature-overview.md
  docs/scos/user/features/202204.0/customer-account-management-feature-overview/customer-accounts-overview.md
  docs/scos/user/features/202204.0/customer-account-management-feature-overview/customer-login-overview.md
  docs/scos/user/features/202204.0/customer-account-management-feature-overview/customer-registration-overview.md
  docs/scos/user/features/202204.0/customer-account-management-feature-overview/password-management-overview.md
  docs/scos/user/features/202204.0/file-manager-feature-overview/asset-management.md
  docs/scos/user/features/202204.0/file-manager-feature-overview/file-manager-feature-overview.md
  docs/scos/user/features/202204.0/file-manager-feature-overview/file-uploader.md
  docs/scos/user/features/202204.0/measurement-units-feature-overview.md
  docs/scos/user/features/202204.0/order-management-feature-overview/custom-order-reference-overview.md
  docs/scos/user/features/202204.0/order-management-feature-overview/oms-order-management-system-matrix.md
  docs/scos/user/features/202204.0/packaging-units-feature-overview.md
  docs/scos/user/features/202204.0/payments-feature-overview.md
  docs/scos/user/features/202204.0/persistent-cart-sharing-feature-overview.md
  docs/scos/user/features/202204.0/product-barcode-feature-overview.md
  docs/scos/user/features/202204.0/product-groups-feature-overview.md
  docs/scos/user/features/202204.0/product-labels-feature-overview.md
  docs/scos/user/features/202204.0/product-lists-feature-overview.md
  docs/scos/user/features/202204.0/product-options-feature-overview.md
  docs/scos/user/features/202204.0/product-rating-and-reviews-feature-overview.md
  docs/scos/user/features/202204.0/product-relations-feature-overview.md
  docs/scos/user/features/202204.0/product-sets-feature-overview.md
  docs/scos/user/features/202204.0/promotions-discounts-feature-overview.md
  docs/scos/user/features/202204.0/quick-add-to-cart-feature-overview.md
  docs/scos/user/features/202204.0/quotation-process-feature-overview.md
  docs/scos/user/features/202204.0/reclamations-feature-overview.md
  docs/scos/user/features/202204.0/refunds-feature-overview.md
  docs/scos/user/features/202204.0/reorder-feature-overview.md
  docs/scos/user/features/202204.0/resource-sharing-feature-overview.md
  docs/scos/user/features/202204.0/scheduled-prices-feature-overview.md
  docs/scos/user/features/202204.0/shared-carts-feature-overview.md
  docs/scos/user/features/202204.0/shipment-feature-overview.md
  docs/scos/user/features/202204.0/wishlist-feature-overview.md
Labels: in progress

#1125 Contributor PR
  docs/scos/dev/data-export/202204.0/data-export.md
Labels: ready for merge, contributor

#1126 СС-18569 Fix docs - Switch from Yarn to NPM
  docs/scos/dev/front-end-development/migration-guide-switch-from-yarn-to-npm.md
Labels: TW review needed

#1136 HowTo: Do better deployments
  docs/scos/dev/tutorials-and-howtos/howtos/howto-do-better-deployments.md
Labels: in TW review

#1133 Contributor-pr
  docs/scos/dev/back-end-development/client/client.md
Labels: ready for merge, contributor

#1132 Update client.md
  docs/cloud/dev/spryker-cloud-commerce-os/create-and-restore-database-backups.md
Labels: do not merge, contributor

#1120 CC-17064 replaced deprecated plugin with a new one
  docs/marketplace/dev/feature-integration-guides/upcoming-release/glue/marketplace-product-offer-wishlist-feature-integration.md
Labels: TW review needed

#1135 HowTo: Debug Payment Integrations Locally and HowTo: Do better deployments
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/tutorials-and-howtos/howtos/howto-debug-payment-integrations-locally.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-do-better-deployments.md
Labels: in TW review

#1130 HowTo: Debug Payment Integrations Locally
  docs/cloud/dev/spryker-cloud-commerce-os/create-and-restore-database-backups.md
Labels: in TW review, do not merge

#1140 Add more data for the tax management and change the format for better…
  docs/pbc/all/payment-service-providers/unzer/whats-changed-in-unzer.md
  docs/pbc/all/tax-management/whats-changed-in-tax-management.md
Labels: in TW review

#1137 Update backend-api-feature-integration.md
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/integrate-features/202204.0/integrate-the-zed-api-feature.md
  _includes/pbc/all/integrate-features/202204.0/integrate-the-zed-api-for-merchant-relationships-feature.md
  docs/scos/dev/feature-integration-guides/202204.0/backend-api-feature-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/backend-api-for-merchant-relationships-integration-guide.md
  docs/scos/dev/feature-integration-guides/202204.0/zed-api-feature-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/zed-api-for-merchant-relationships-integration-guide.md
Labels: in TW review
