Repository spryker/spryker-docs, pull requests merged in 2022-11, with the labels that each got.

#1330 Makes line-size limit in hosts file for windows users more highlighted
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-windows.md
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-windows.md
Labels: ready for merge

#1328 Created troubleshooting article for messages in error queues
  _data/sidebars/scos_dev_sidebar.yml
  docs/acp/user/async-api.md
  docs/acp/user/developing-an-app.md
  docs/acp/user/sync-api.md
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
  docs/cloud/dev/spryker-cloud-commerce-os/release-notes.md
  docs/cloud/dev/spryker-cloud-commerce-os/starting-asynchronous-commands.md
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/class-silex-controllerproviderinterface-not-found.md
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/fail-whale-on-the-frontend.md
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-general-technical-issues.md
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-rabbitmq/messages-are-moved-to-error-queues.md
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-rabbitmq/messages-are-stuck-in-the-unacked-state.md
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-rabbitmq/messages-are-stuck-without-error-notifications.md
  docs/scos/dev/troubleshooting/troubleshooting.md
Labels: ready for merge

#1325 Cart and checkout PBC edits
  docs/pbc/all/cart-and-checkout/cart-and-checkout.md
  docs/pbc/all/cart-and-checkout/cart-feature-overview/cart-feature-overview.md
  docs/pbc/all/cart-and-checkout/cart-feature-overview/cart-notes-overview.md
  docs/pbc/all/cart-and-checkout/cart-feature-overview/cart-widget-overview.md
  docs/pbc/all/cart-and-checkout/checkout-feature-overview/checkout-feature-overview.md
  docs/pbc/all/cart-and-checkout/checkout-feature-overview/multi-step-checkout-overview.md
  docs/pbc/all/cart-and-checkout/checkout-feature-overview/order-thresholds-overview.md
  docs/pbc/all/cart-and-checkout/extend-and-customize/calculation-3-0.md
  docs/pbc/all/cart-and-checkout/extend-and-customize/calculation-data-structure.md
  docs/pbc/all/cart-and-checkout/extend-and-customize/cart-module-reference-information.md
  docs/pbc/all/cart-and-checkout/extend-and-customize/checkout-process-review-and-implementation.md
  docs/pbc/all/cart-and-checkout/extend-and-customize/checkout-steps.md
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/check-out/check-out-purchases.md
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/check-out/checkout-workflow.md
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/check-out/submit-checkout-data.md
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/check-out/update-payment-data.md
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/manage-carts-of-registered-users/manage-carts-of-registered-users.md
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/manage-carts-of-registered-users/manage-items-in-carts-of-registered-users.md
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/manage-guest-carts/manage-guest-cart-items.md
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/manage-guest-carts/manage-guest-carts.md
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/retrieve-customer-carts.md
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/share-company-user-carts/manage-shared-company-user-carts.md
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/share-company-user-carts/retrieve-cart-permission-groups.md
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/share-company-user-carts/share-company-user-carts.md
  docs/pbc/all/cart-and-checkout/multiple-carts-feature-overview.md
  docs/pbc/all/cart-and-checkout/persistent-cart-sharing-feature-overview.md
  docs/pbc/all/cart-and-checkout/quick-add-to-cart-feature-overview.md
  docs/pbc/all/cart-and-checkout/shared-carts-feature-overview.md
Labels: in TW review

#1339 contributor: Knuppe:patch-2
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-sending-an-email.md
Labels: ready for merge, contributor

#1333 Fix Product Configuration feature installation guide:
  _includes/pbc/all/install-features/202204.0/install-the-product-configuration-feature.md
Labels: ready for merge

#1341 contributors: yazanasiedmms and tknuppe
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-architectural-walkthrough-spryker-commerce-os.md
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-sending-an-email.md
Labels: in progress, contributor

#1319 Contributor newrelicinstructions
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202212.0/install-the-shipment-feature.md
  docs/marketplace/dev/technical-enhancement/202204.0/migration-guide-upgrade-to-angular-v12.md
  docs/marketplace/dev/technical-enhancement/202212.0/migration-guide-upgrade-to-angular-v12.md
  docs/pbc/all/cart-and-checkout/checkout-feature-overview/checkout-feature-overview.md
  docs/pbc/all/cart-and-checkout/install-and-upgrade/install-features/install-the-quick-add-to-cart-packaging-units-feature.md
  docs/pbc/all/cart-and-checkout/install-and-upgrade/install-features/install-the-quick-add-to-cart-shopping-lists-feature.md
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/manage-carts-of-registered-users/manage-carts-of-registered-users.md
  docs/pbc/all/price-management/merchant-custom-prices-feature-overview.md
  docs/pbc/all/warehouse-management-system/availability-notification-feature-overview.md
  docs/pbc/all/warehouse-management-system/import-and-export-data/file-details-warehouse.csv.md
  docs/scos/dev/back-end-development/data-manipulation/payment-methods/direct-debit-example-implementation/implement-direct-debit-payment.md
  docs/scos/dev/back-end-development/data-manipulation/payment-methods/invoice/implement-invoice-payment.md
  docs/scos/dev/back-end-development/data-manipulation/payment-methods/prepayment/implement-prepayment.md
  docs/scos/dev/feature-walkthroughs/202204.0/search-feature-walkthrough.md
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-architectural-walkthrough-spryker-commerce-os.md
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-sending-an-email.md
  docs/scos/user/features/202204.0/merchant-product-restrictions-feature-overview.md
Labels: ready for merge, contributor

#1340 Update tutorial-architectural-walkthrough-spryker-commerce-os.md
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-architectural-walkthrough-spryker-commerce-os.md
Labels: do not merge, contributor

#1347 CC-13275: Display numbers in Yves based on the current user locale.
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/data-imports/howto-add-support-for-number-formatting-in-the-storefront.md
Labels: ready for merge

#1350 Add prerequisites to use Bazaarvoice app
  docs/pbc/all/ratings-reviews/third-party-integrations/bazaarvoice.md
Labels: ready for merge

#1355 Add prerequisites to use UserCentrics app
  docs/pbc/all/ratings-reviews/third-party-integrations/bazaarvoice.md
  docs/pbc/all/usercentrics/usercentrics.md
Labels: ready for merge

#1357 Fixed the guideline to include the new GLUE authentication approach
  docs/scos/dev/tutorials-and-howtos/howtos/glue-api-howtos/glue-api-howtos.md
  docs/scos/dev/tutorials-and-howtos/howtos/glue-api-howtos/howto-integrate-a-ciam-provider.md
Labels: ready for merge

#1356 Add prerequisites to use Payone app
  docs/pbc/all/payment-service-providers/payone/payone.md
  docs/pbc/all/ratings-reviews/third-party-integrations/bazaarvoice.md
  docs/pbc/all/usercentrics/usercentrics.md
Labels: ready for merge

#1370 Added red notification
  docs/scos/dev/back-end-development/extending-spryker/development-strategies/spryker-os-module-customisation/extend-a-core-module-that-is-used-by-another.md
Labels: ready for merge

#1368 SC-11052 Update security guidelines
  docs/scos/dev/guidelines/security-guidelines.md
Labels: TW review needed

#1369 PHP8.0 announcement for customers
  _data/sidebars/scos_user_sidebar.yml
  docs/pbc/all/user-management/202204.0/user-management.md
  docs/scos/user/intro-to-spryker/whats-new/php8-as-a-minimum-version-for-all-spryker-projects.md
Labels: TW review needed

#1377 Update php8-as-a-minimum-version-for-all-spryker-projects.md
  docs/scos/user/intro-to-spryker/whats-new/php8-as-a-minimum-version-for-all-spryker-projects.md
Labels: TW review needed

#1354 SDK docs Spryk section review and edits
  docs/sdk/dev/development-tools/architecture-sniffer.md
  docs/sdk/dev/development-tools/code-sniffer.md
  docs/sdk/dev/development-tools/formatter.md
  docs/sdk/dev/development-tools/performance-audit-tool-benchmark.md
  docs/sdk/dev/development-tools/phpstan.md
  docs/sdk/dev/development-tools/scss-linter.md
  docs/sdk/dev/development-tools/static-security-checker.md
  docs/sdk/dev/development-tools/tooling-config-file.md
  docs/sdk/dev/development-tools/ts-linter.md
  docs/sdk/dev/spryks/adding-a-new-spryk.md
  docs/sdk/dev/spryks/checking-and-debugging-spryks.md
  docs/sdk/dev/spryks/enabling-and-disabling-the-code-sniffer-for-spryks.md
  docs/sdk/dev/spryks/fileresolver.md
  docs/sdk/dev/spryks/qa-automation.md
  docs/sdk/dev/spryks/spryk-configuration-reference.md
  docs/sdk/dev/spryks/spryks.md
Labels: in progress

#1385 FRW-449 Refactored public documentation regarding GLUE infrastructure
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/decoupled-glue-infrastructure/glue-api-authentication-integration.md
  docs/scos/dev/glue-api-guides/202204.0/decoupled-glue-infrastructure/how-to-guides/how-to-use-glue-api-authorization-scopes.md
  docs/scos/dev/glue-api-guides/202204.0/decoupled-glue-infrastructure/how-to-guides/routing/how-to-create-a-backend-resource.md
  docs/scos/dev/glue-api-guides/202204.0/decoupled-glue-infrastructure/how-to-guides/routing/how-to-create-a-storefront-resource.md
Labels: in TW review

#1343 contributor:Updated instructions which were outdated in the closed PR #1296
  docs/scos/dev/technology-partner-guides/202204.0/operational-tools-monitoring-legal-etc/new-relic/installing-and-configuring-new-relic–with–vagrant.md
  docs/scos/dev/the-docker-sdk/202204.0/configure-services.md
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-integrating-any-search-engine-into-a-project.md
Labels: in TW review, contributor

#1345 Corrects typo
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-integrating-any-search-engine-into-a-project.md
Labels: do not merge, contributor

#1353 Add m1 mac jekyll install steps
  docs/scos/user/intro-to-spryker/contribute-to-documentation/build-the-documentation-site.md
Labels: in TW review

#1381 CC-21435: Configurable Product integration & migration guides
  _includes/pbc/all/install-features/202212.0/install-glue-api/install-the-product-configuration-glue-api.md
  _includes/pbc/all/install-features/202212.0/install-the-product-configuration-feature.md
  _includes/pbc/all/upgrade-modules/upgrade-the-productconfiguration-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-productconfigurationcart-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-productconfigurationgui-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-productconfigurationpersistentcart-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-productconfigurationshoppinglist-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-productconfigurationsrestapi-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-productconfigurationstorage-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-productconfigurationwishlist-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-productconfiguratorgatewaypage-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-salesproductconfiguration-module.md
  docs/scos/dev/feature-integration-guides/202212.0/glue-api/glue-api-product-configuration-feature-integration.md
  docs/scos/dev/feature-integration-guides/202212.0/product-configuration-feature-integration.md
  docs/scos/dev/feature-walkthroughs/202212.0/configurable-product-feature-walkthrough/configurable-product-feature-walkthrough.md
Labels: ready for merge, urgent

#1393 Update acp-overview.md
  docs/acp/user/intro-to-acp/acp-overview.md
Labels: TW review needed

#1378 CC-9280: Adjusted CMS feature install guide
  _includes/pbc/all/install-features/202204.0/install-the-cms-feature.md
  docs/scos/dev/feature-integration-guides/202204.0/cms-feature-integration.md
Labels: ready for merge

#1386 explicitly mentioned env variables
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: ready for merge

#1375 Update app-manifest.md
  docs/acp/user/app-manifest.md
Labels: ready for merge

#1394 Release notes for 202211.0
  _data/sidebars/marketplace_user_sidebar.yml
  _data/sidebars/scos_user_sidebar.yml
  docs/marketplace/user/intro-to-spryker-marketplace/release-notes/release-notes-202211.0.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202211.0/release-notes-202211.0.md
Labels: do not merge

#1398 Contributor: SUPESC-443: Adjust "HowTo: Set up stores with multiple locales" page
  docs/scos/dev/tutorials-and-howtos/howtos/howto-set-up-stores-with-multiple-locales.md
Labels: ready for merge

#1413 is_available -> isAvailable (second try)
  docs/acp/user/app-manifest.md
Labels: ready for merge

#1389 FRW-229: SymfonyMailer updates
  docs/scos/dev/feature-integration-guides/202204.0/mailing-and-notifications-feature-integration.md
  docs/scos/dev/feature-walkthroughs/202001.0/mailing-and-notifications-feature-walkthrough.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-create-and-register-a-mail-provider.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-create-and-register-a-mail-type-builder-plugin.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-create-and-register-a-mailtypeplugin.md
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-sending-an-email.md
  docs/scos/user/features/201903.0/mailing-and-notifications-feature-overview.md
Labels: in progress
