Repository spryker/spryker-docs, pull requests merged in 2022-05, with the labels that each got.

#898 Update getting-started for 202204.0
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-macos-and-linux.md
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-windows.md
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-macos-and-linux.md
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-windows.md
Labels: in TW review

#836 [WIP] RES-1293: add draft of evaluator and upgrader tools documentation
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/architecture/module-api/declaration-of-module-apis-public-and-private.md
  docs/scos/dev/architecture/module-api/definition-of-module-api.md
  docs/scos/dev/back-end-development/extending-spryker/development-strategies/development-strategies.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/keeping-a-project-upgradable.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/running-the-evaluator-tool.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/running-the-upgrader-tool.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/entity-name-is-not-unique.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/private-api-is-extended.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/private-api-is-used-on-the-project-level.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/private-api-method-is-overridden-on-the-project-level.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/upgradability-guidelines.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-services.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgrader-tool-overview.md
  docs/scos/dev/guidelines/project-development-guidelines.md
  docs/scos/dev/upgradability-services/customization-tiers.md
  docs/scos/dev/upgradability-services/upgradability-guidelines.md
Labels: in progress

#866 MP-6047 Product Approval Process + Merchant Context
  docs/marketplace/dev/data-import/202200.0/file-details-merchant-product-approval-status-default.csv.md
  docs/marketplace/dev/feature-walkthroughs/202200.0/marketplace-product-approval-process-feature-walkthrough.md
  docs/scos/dev/data-import/202200.0/data-import-categories/catalog-setup/products/file-details-product-abstract-approval-status.csv.md
  docs/scos/dev/feature-integration-guides/202200.0/product-approval-process-feature-integration.md
  docs/scos/dev/feature-walkthroughs/202200.0/product-approval-process-feature-walkthrough.md
Labels: in TW review

#894 [AC-1349] Prepare release notes for publishing
  Rakefile
  _config.yml
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202204.0/release-notes-202204.0.md
Labels: in progress, do not merge

#896 Update getting start guide
  docs/scos/dev/developer-getting-started-guide.md
Labels: in TW review

#916 [AC-1353] Review and prepare for publishing release notes for MP
  _data/sidebars/marketplace_user_sidebar.yml
  docs/marketplace/user/intro-to-spryker-marketplace/release-notes/release-notes-2022040.md
Labels: in progress, do not merge

#928 Update supported-versions-of-php.md
  docs/scos/user/intro-to-spryker/whats-new/supported-versions-of-php.md
Labels: tech review needed

#796 MP-3957: Marketplace Shopping Lists feature integration
  Rakefile
  _data/sidebars/marketplace_dev_sidebar.yml
  docs/marketplace/dev/feature-integration-guides/202204.0/marketplace-shopping-lists-feature-integration.md
Labels: in tech review

#930 SUPESC-583: Migration guide from CodeItNow to BarcodeLaminas
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/feature-walkthroughs/202204.0/product-barcode-feature-walkthrough.md
  docs/scos/dev/module-migration-guides/migration-guide-codeitnow-to-barcodelaminas.md
Labels: ready for merge, in TW review

#797 MP-6072: Glue API: Marketplace Shopping Lists feature integration
  _data/sidebars/marketplace_dev_sidebar.yml
  docs/marketplace/dev/feature-integration-guides/202204.0/glue/marketplace-shopping-lists-feature-integration.md
Labels: in TW review

#907 MP-6059: Add technical documentation for merchant portal customer specific prices.
  _data/sidebars/marketplace_dev_sidebar.yml
  docs/marketplace/dev/feature-walkthroughs/202204.0/marketplace-merchant-custom-prices-feature-walkthrough.md
Labels: PO review needed

#798 Add Offer and Merchant Product to Shopping List (Marketplace Shopping List)
  _data/sidebars/marketplace_user_sidebar.yml
  docs/marketplace/user/features/202204.0/marketplace-shopping-list-feature-overview.md
Labels: TW review needed

#943 Documentation spryker elastic computing
  Rakefile
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/guidelines/testing-guidelines/test-framework.md
  docs/scos/dev/technical-enhancement-integration-guides/integrate-elastic-computing.md
Labels: ready for merge

#922 MP-6055 Marketplace Shopping Lists feature walkthrough added.
  Rakefile
  _data/sidebars/marketplace_dev_sidebar.yml
  docs/marketplace/dev/data-import/202204.0/file-details-product-offer-shopping-list.csv.md
  docs/marketplace/dev/data-import/202204.0/marketplace-setup.md
  docs/marketplace/dev/feature-walkthroughs/202204.0/marketplace-shopping-lists-feature-walkthrough.md
Labels: PO review needed

#870 [MP-6062] Products Search Widget (Quick Order, Quick add to Cart, Shopping List)
  docs/marketplace/user/features/202108.0/marketplace-product-feature-overview.md
  docs/marketplace/user/features/202204.0/marketplace-product-feature-overview.md
  docs/marketplace/user/features/202204.0/marketplace-product-offer-feature-overview.md
  docs/marketplace/user/intro-to-spryker-marketplace/marketplace-storefront.md
Labels: TW review needed

#876 [MP-6058] ac doc merchant portal add and edit customer specific prices to merchant products
  _data/sidebars/marketplace_user_sidebar.yml
  docs/marketplace/user/features/202204.0/marketplace-merchant-custom-prices-feature-overview.md
  docs/marketplace/user/merchant-portal-user-guides/202108.0/products/concrete-products/managing-marketplace-concrete-product-prices.md
  docs/marketplace/user/merchant-portal-user-guides/202204.0/products/abstract-products/managing-marketplace-abstract-product-prices.md
  docs/marketplace/user/merchant-portal-user-guides/202204.0/products/concrete-products/managing-marketplace-concrete-product-prices.md
  docs/scos/user/features/202204.0/merchant-custom-prices-feature-overview.md
Labels: TW review needed

#827 [MP-5763] API: Add Offer and Merchant Product to Shopping List
  _data/sidebars/marketplace_dev_sidebar.yml
  docs/marketplace/dev/glue-api-guides/202204.0/shopping-lists/managing-shopping-list-items.md
  docs/marketplace/dev/glue-api-guides/202204.0/shopping-lists/managing-shopping-lists.md
Labels: PO review needed

#763 Product Approval Process + Merchant Context
  _data/sidebars/marketplace_dev_sidebar.yml
  _data/sidebars/marketplace_user_sidebar.yml
  docs/marketplace/user/back-office-user-guides/202204.0/catalog/products/managing-products/managing-products.md
  docs/marketplace/user/features/202204.0/marketplace-product-approval-process-feature-overview.md
  docs/marketplace/user/features/202204.0/marketplace-product-feature-overview.md
  docs/marketplace/user/merchant-portal-user-guides/202108.0/products/abstract-products/creating-marketplace-abstract-product.md
  docs/marketplace/user/merchant-portal-user-guides/202204.0/offers/managing-product-offers.md
  docs/marketplace/user/merchant-portal-user-guides/202204.0/products/abstract-products/creating-marketplace-abstract-product.md
  docs/marketplace/user/merchant-portal-user-guides/202204.0/products/abstract-products/managing-marketplace-abstract-product.md
  docs/marketplace/user/merchant-portal-user-guides/202204.0/products/concrete-products/managing-marketplace-concrete-product.md
Labels: TW review needed

#945 CC-16746: Write migration guides from v1 to v2 for the following modules.
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/module-migration-guides/migration-guide-contentfilegui.md
  docs/scos/dev/module-migration-guides/migration-guide-contentfilewidget.md
  docs/scos/dev/module-migration-guides/migration-guide-elastica.md
  docs/scos/dev/module-migration-guides/migration-guide-filemanager.md
  docs/scos/dev/module-migration-guides/migration-guide-filemanagerstorage.md
  docs/scos/dev/module-migration-guides/migration-guide-filemanagerwidget.md
  docs/scos/dev/module-migration-guides/migration-guide-flysystem.md
  docs/scos/dev/module-migration-guides/migration-guide-oauth.md
Labels: ready for merge

#625 AOP docs
  .github/workflows/ci.yml
  Rakefile
  _config.yml
  _data/sidebars/acp_user_sidebar.yml
  _includes/topnav.html
  _layouts/home.html
  docs/acp/user/apps/bazaarvoice.md
  docs/acp/user/apps/payone.md
  docs/acp/user/apps/usercentrics.md
  docs/acp/user/intro-to-acp/acp-overview.md
  docs/acp/user/intro-to-acp/aop-security-assessment.md
  docs/cloud/dev/spryker-cloud-commerce-os/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-403-error.md
  docs/scos/dev/feature-walkthroughs/202009.0/company-account-feature-walkthrough/customer-login-by-token-reference-information.md
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/choosing-an-installation-mode.md
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-macos-and-linux.md
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-windows.md
  docs/scos/dev/technology-partner-guides/201811.0/operational-tools-monitoring-legal-etc/installing-and-configuring-tideways-with-vagrant.md
  docs/scos/dev/technology-partner-guides/201811.0/operational-tools-monitoring-legal-etc/new-relic/configuring-new-relic-logging.md
  docs/scos/dev/technology-partner-guides/201811.0/operational-tools-monitoring-legal-etc/new-relic/installing-and-configuring-new-relic–with–vagrant.md
  docs/scos/dev/technology-partner-guides/201811.0/payment-partners/adyen/installing-and-configuring-adyen.md
  docs/scos/dev/technology-partner-guides/201903.0/operational-tools-monitoring-legal-etc/installing-and-configuring-tideways-with-vagrant.md
  docs/scos/dev/technology-partner-guides/201903.0/operational-tools-monitoring-legal-etc/new-relic/configuring-new-relic-logging.md
  docs/scos/dev/technology-partner-guides/201903.0/operational-tools-monitoring-legal-etc/new-relic/installing-and-configuring-new-relic–with–vagrant.md
  docs/scos/dev/technology-partner-guides/201903.0/payment-partners/adyen/installing-and-configuring-adyen.md
  docs/scos/dev/technology-partner-guides/201907.0/operational-tools-monitoring-legal-etc/installing-and-configuring-tideways-with-vagrant.md
  docs/scos/dev/technology-partner-guides/201907.0/operational-tools-monitoring-legal-etc/new-relic/configuring-new-relic-logging.md
  docs/scos/dev/technology-partner-guides/201907.0/operational-tools-monitoring-legal-etc/new-relic/installing-and-configuring-new-relic–with–vagrant.md
  docs/scos/dev/technology-partner-guides/201907.0/payment-partners/adyen/installing-and-configuring-adyen.md
  docs/scos/dev/technology-partner-guides/202001.0/operational-tools-monitoring-legal-etc/installing-and-configuring-tideways-with-vagrant.md
  docs/scos/dev/technology-partner-guides/202001.0/operational-tools-monitoring-legal-etc/new-relic/configuring-new-relic-logging.md
  docs/scos/dev/technology-partner-guides/202001.0/operational-tools-monitoring-legal-etc/new-relic/installing-and-configuring-new-relic–with–vagrant.md
  docs/scos/dev/technology-partner-guides/202001.0/payment-partners/adyen/installing-and-configuring-adyen.md
  docs/scos/dev/technology-partner-guides/202005.0/operational-tools-monitoring-legal-etc/installing-and-configuring-tideways-with-vagrant.md
  docs/scos/dev/technology-partner-guides/202005.0/operational-tools-monitoring-legal-etc/new-relic/configuring-new-relic-logging.md
  docs/scos/dev/technology-partner-guides/202005.0/operational-tools-monitoring-legal-etc/new-relic/installing-and-configuring-new-relic–with–vagrant.md
  docs/scos/user/intro-to-spryker/contributing-to-documentation/adding-product-sections-to-the-documentation.md
Labels: do not merge

#959 Ac 1354 fix punctuation contributor
  docs/fes/dev/launching-storefronts.md
  docs/scos/dev/data-import/202108.0/data-import-categories/catalog-setup/products/file-details-product-concrete.csv.md
  docs/scos/dev/tutorials-and-howtos/advanced-tutorials/tutorial-zed-rest-api.md
Labels: ready for merge, contributor

#964 Updating "Migration guide - Extending the project"
  _data/sidebars/marketplace_dev_sidebar.yml
  docs/marketplace/dev/front-end/extending-the-project/index.md
  docs/marketplace/dev/front-end/extending-the-project/migration-guide-extending-the-project.md
Labels: TW review needed
