Repository spryker/spryker-docs, pull requests merged in 2022-10, with the labels that each got.

#1272 Suggested to remove data operations from deployment
  docs/cloud/dev/spryker-cloud-commerce-os/configure-deployment-pipelines/deployment-pipelines.md
Labels: ready for merge

#1275 Contributor: Update tutorial-checkout-and-step-engine.md
  docs/pbc/all/cart-and-checkout/tutorials-and-howtos/tutorial-checkout-and-step-engine.md
Labels: contributor

#1274 documentation channel fix requests
  docs/pbc/all/cart-and-checkout/tutorials-and-howtos/tutorial-checkout-and-step-engine.md
  docs/scos/dev/system-requirements/202108.0/system-requirements.md
  docs/scos/dev/system-requirements/202204.0/system-requirements.md
  docs/scos/user/back-office-user-guides/202009.0/catalog/products/references/reference-information-concrete-product.md
  docs/scos/user/shop-user-guides/202005.0/shop-guide-customer-account/shop-guide-order-history.md
Labels: in progress

#1245 Add link to an observer pattern
  docs/scos/dev/back-end-development/data-manipulation/event/event.md
Labels: ready for merge

#1277 Adjusts naming convention for extending class
  docs/scos/dev/front-end-development/yves/front-end-builder-for-yves.md
Labels: ready for merge

#1282 Update rabbitmq-zed.critical-phpamqplib-exception-amqpchannelclosedex…
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/rabbitmq-zed.critical-phpamqplib-exception-amqpchannelclosedexception-channel-connection-is-closed.md
Labels: in TW review

#1271 Replaces wording for "global"
  docs/scos/dev/front-end-development/yves/atomic-frontend/atomic-front-end-general-overview.md
Labels: ready for merge

#1276 Contributor: Add missing interface definition
  docs/scos/dev/back-end-development/extending-spryker/development-strategies/project-modules/add-a-new-module.md
Labels: ready for merge, contributor

#1292 Update howto-do-better-deployments.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-do-better-deployments.md
Labels: ready for merge

#1269 AC-1394 Review Glue API backend docs
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-backend-api/glue-api-authentication-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-backend-api/glue-api-authorization-scopes-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-backend-api/glue-api-glue-storefront-and-backend-api-applications-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-backend-api/glue-api-json-api-convention-integration.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/authorization-scopes.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/backend-and-storefront-api-module-differences.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/create-a-resource-with-parent.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/create-a-route.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/create-protected-endpoints.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/create_change-convention.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/documenting-glue-api-endpoints.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/glue-parameters-usage.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-a-json-api-relationship.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-a-resource.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-a-route.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-api-applications.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-or-change-a-convention.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-protected-endpoints.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-resources-with-parent-child-relationships.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-document-glue-api-endpoints.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-use-authorization-framework.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-use-glue-api-authorization-scopes.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-use-ootb-glue-parameters.md
Labels: in progress

#1294 Update add-unzer-marketplace-credentials.md
  docs/pbc/all/payment-service-providers/unzer/configuration-in-the-back-office/add-unzer-marketplace-credentials.md
Labels: ready for merge

#1048 Remove endpoint list and add info about the default user credentials
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-macos-and-linux.md
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-development-mode-on-macos-and-linux.md
Labels: TW review needed

#1286 Review of Carrier Management .md files
  docs/pbc/all/carrier-management/carrier-management.md
  docs/pbc/all/carrier-management/extend-and-customize/shipment-method-plugins-reference-information.md
  docs/pbc/all/carrier-management/import-and-export-data/file-details-shipment-method-store.csv.md
  docs/pbc/all/carrier-management/import-and-export-data/file-details-shipment-price.csv.md
  docs/pbc/all/carrier-management/import-and-export-data/file-details-shipment.csv.md
  docs/pbc/all/carrier-management/install-and-upgrade/integrate-the-shipment-approval-process-feature.md
  docs/pbc/all/carrier-management/manage-in-the-back-office/add-carrier-companies.md
  docs/pbc/all/carrier-management/manage-in-the-back-office/add-delivery-methods.md
  docs/pbc/all/carrier-management/manage-in-the-back-office/edit-delivery-methods.md
  docs/pbc/all/carrier-management/manage-via-glue-api/retrieve-shipments-and-shipment-methods-when-submitting-checkout-data.md
  docs/pbc/all/carrier-management/manage-via-glue-api/retrieve-shipments-in-orders.md
  docs/pbc/all/carrier-management/manage-via-glue-api/retrieve-shipments-when-checking-out-purchases.md
  docs/pbc/all/carrier-management/third-party-integrations/paazl.md
  docs/pbc/all/carrier-management/third-party-integrations/seven-senders/install-and-configure-seven-senders.md
  docs/pbc/all/carrier-management/third-party-integrations/seven-senders/seven-senders-mappers.md
Labels: ready for merge

#1301 added missing docs to sidebar
  _data/sidebars/scos_dev_sidebar.yml
Labels: ready for merge

#1307 how-to guide for a CIAM provider integration
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/tutorials-and-howtos/howtos/glue-api-howtos/howto-integrate-a-ciam-provider.md
Labels: ready for merge

#1314 Update tutorial-testing-and-tdd-spryker-commerce-os.md
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
  docs/scos/dev/guidelines/testing-guidelines/setting-up-tests.md
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-testing-and-tdd-spryker-commerce-os.md
Labels: ready for merge, contributor

#1303 fix typo
  docs/scos/user/intro-to-spryker/whats-new/supported-versions-of-php.md
Labels: do not merge, contributor

#1304 fixed typo in spryker-middleware.md
  docs/scos/user/intro-to-spryker/whats-new/supported-versions-of-php.md
Labels: do not merge, contributor

#1313 Update tutorial-testing-and-tdd-spryker-commerce-os.md
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
Labels: do not merge, contributor

#1311 Update command job name and example usage regarding current state in order-management-system-multi-thread.md
  docs/scos/dev/back-end-development/data-manipulation/datapayload-conversion/state-machine/order-management-system-multi-thread.md
Labels: ready for merge

#1302 glue-backend-api-fix
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/backend-and-storefront-api-module-differences.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-a-resource.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-a-route.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-api-applications.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-protected-endpoints.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-resources-with-parent-child-relationships.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-document-glue-api-endpoints.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-use-authorization-framework.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-use-glue-api-authorization-scopes.md
Labels: ready for merge

#1299 Including Migration helpers
  docs/scos/user/intro-to-spryker/whats-new/supported-versions-of-php.md
Labels: ready for merge

#1318 FRW-450 Auth documentation requirements
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-backend-api/glue-api-authentication-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-backend-api/glue-api-authorization-protected-endpoints-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/glue-backend-api/glue-api-authorization-scopes-integration.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/authentication-and-authorization.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-create-grant-type-parameters.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/how-to-guides/how-to-use-an-authentication-server.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/security-and-authentication.md
Labels: in TW review

#1291 Updating the sdk docs
  _data/sidebars/sdk_dev_sidebar.yml
  docs/sdk/dev/build-flavored-spryker-sdks.md
  docs/sdk/dev/develop-the-sdk.md
  docs/sdk/dev/developing-the-sdk.md
  docs/sdk/dev/extend-the-sdk.md
  docs/sdk/dev/initialize-and-run-workflows.md
  docs/sdk/dev/integrate-sdk-commands-to-php-storm-command-line-tools.md
  docs/sdk/dev/manifest-validation.md
  docs/sdk/dev/profiler.md
  docs/sdk/dev/sdk-conventions.md
  docs/sdk/dev/settings.md
  docs/sdk/dev/spryker-sdk.md
  docs/sdk/dev/spryks/qa-automation.md
  docs/sdk/dev/task-lifecycle-management.md
  docs/sdk/dev/task-set.md
  docs/sdk/dev/task.md
  docs/sdk/dev/telemetry.md
  docs/sdk/dev/value-resolvers.md
Labels: in progress

#1320 Update understand-payment-method-in-checkout-process.md
  docs/pbc/all/payment-service-providers/unzer/howto-tips-use-cases/understand-payment-method-in-checkout-process.md
Labels: ready for merge

#1322 added disclaimer about support and partner portal
  docs/scos/user/intro-to-spryker/support/how-to-use-the-support-portal.md
Labels: ready for merge

#1327 Create new troubleshooting article about messages stuck in unacked state
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-rabbitmq/messages-stuck-in-unacked-state
Labels: TW review needed

#1326 Added new article on how to deal with stuck messages w/o errors
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-rabbitmq/messages-stuck-without-error
Labels: in TW review
