Repository spryker/spryker-docs, pull requests merged in 2022-06, with the labels that each got.

#953 Docker SDK overview
  docs/scos/dev/the-docker-sdk/202204.0/the-docker-sdk.md
Labels: tech review needed

#901 MP-6064 Marketplace Product Search Widget feature integration guide
  _data/sidebars/marketplace_dev_sidebar.yml
  docs/marketplace/dev/feature-integration-guides/202204.0/marketplace-product-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202204.0/marketplace-product-marketplace-product-offer-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202204.0/marketplace-product-offer-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202204.0/marketplace-product-offer-quick-add-to-cart-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202204.0/marketplace-product-quick-add-to-cart-feature-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/product-feature-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/quick-add-to-cart-feature-integration.md
Labels: in TW review

#969 MP-6215 Overriding CSS variables
  docs/marketplace/dev/front-end/extending-the-project/index.md
  docs/marketplace/dev/front-end/table-design/table-column-types/table-column-type-image.md
Labels: in TW review

#978 Update prices-feature-overview.md
  docs/scos/user/features/202108.0/prices-feature-overview/prices-feature-overview.md
Labels: ready for merge

#897 Feature/cc 15301 transform dropdowns in the company management in zed
  docs/scos/dev/feature-integration-guides/202204.0/company-account-feature-integration.md
Labels: ready for merge

#932 SUPESC-315 Fix CMS Block connector modules integration guides
  _data/sidebars/scos_dev_sidebar.yml
  _data/sidebars/scos_user_sidebar.yml
  _includes/scos/user/back-office-user-guides/content/blocks/reference-information-add-content-to-the-placeholders-of-a-cms-block.md
  docs/scos/dev/feature-walkthroughs/202204.0/cms-feature-walkthrough/cms-feature-walkthrough.md
  docs/scos/dev/technical-enhancement-integration-guides/integrate-category-cms-blocks.md
  docs/scos/dev/technical-enhancement-integration-guides/integrate-product-cms-blocks.md
  docs/scos/dev/technical-enhancement-integration-guides/integrating-category-cms-blocks.md
  docs/scos/dev/technical-enhancement-integration-guides/integrating-product-cms-blocks.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-define-positions-for-category-cms-blocks.md
  docs/scos/user/back-office-user-guides/202204.0/content/blocks/create-category-cms-blocks.md
  docs/scos/user/back-office-user-guides/202204.0/content/blocks/create-cms-blocks.md
  docs/scos/user/back-office-user-guides/202204.0/content/blocks/create-product-cms-blocks.md
Labels: in TW review

#985 СС-11151: Added description of new plugin to control orphaned price product store records removal
  docs/scos/dev/feature-walkthroughs/202204.0/prices-feature-walkthrough/priceproduct-module-details-reference-information.md
Labels: in TW review

#991 Add page about ie11 deprecation
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/whats-new/ie11-end-of-life.md
Labels: in TW review

#1000 Extend a bit "demo data cleanup" section
  docs/scos/dev/guidelines/making-your-spryker-shop-secure.md
Labels: in TW review

#999 Added reference to our security guidelines
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: in TW review

#1004 Contributor-gustosVa
  docs/scos/dev/back-end-development/yves/yves-routes.md
Labels: contributor

#996 SUPESC-33: Adjusted the description of Braintree payment plugins and facade methods
  docs/scos/dev/technology-partner-guides/202108.0/payment-partners/braintree/braintree-performing-requests.md
  docs/scos/dev/technology-partner-guides/202204.0/payment-partners/braintree/installing-and-configuring-braintree.md
Labels: ready for merge

#1001 Update switch-to-arm-architecture-m1-chip.md
  docs/scos/dev/technical-enhancement-integration-guides/switch-to-arm-architecture-m1-chip.md
Labels: in TW review

#1005 SUPESC-544: Added description of united bundled items approach in cart
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/feature-integration-guides/202204.0/product-bundles-cart-feature-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/splittable-order-items-feature-integration.md
Labels: ready for merge

#925 Updating docs to reflect to change FeS to FES
  docs/fes/dev/front-end-enablement-service.md
Labels: ready for merge

#944 Update for performance guideline due to the latest changes
  docs/scos/dev/guidelines/performance-guidelines/general-performance-guidelines.md
  docs/scos/dev/module-migration-guides/migration-guide-eventdispatcher.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-install-spryker-in-aws-environment.md
Labels: in TW review

#1014 Unzer UI fix
  _data/sidebars/pbc_all_roles_sidebar.yml
  _includes/topnav.html
  docs/pbc/all/payment/unzer/configuration-in-the-back-office/add-unzer-standard-credentails.md
  docs/pbc/all/payment/unzer/customise-the-credit-card-display-in-your-payment-step.md
  docs/pbc/all/payment/unzer/frontend-for-a-credit-card.md
  docs/pbc/all/payment/unzer/whats-changed-in-unzer.md
  docs/pbc/all/pbc-landing.md
  docs/scos/dev/guidelines/performance-guidelines/general-performance-guidelines.md
  docs/scos/dev/module-migration-guides/migration-guide-eventdispatcher.md
  docs/scos/dev/technical-enhancement-integration-guides/integrating-cache-of-unresolved-entities-for-zed.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-install-spryker-in-aws-environment.md
Labels: ready for merge
