Repository spryker/spryker-docs, pull requests merged in 2022-01, with the labels that each got.

#618 Pplus 413/a core method is used on project level
  docs/scos/dev/upgradability-services/upgradability-guidelines.md
Labels: in TW review

#604 [TE-10299] Style, formatting and general rules for docs
  Rakefile
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/contributing-to-documentation/markdown-syntax.md
  docs/scos/user/intro-to-spryker/contributing-to-documentation/style-formatting-general-rules.md
Labels: in TW review

#621 Pplus 412/method is overriden
  docs/scos/dev/upgradability-services/upgradability-guidelines.md
Labels: in TW review

#679 Added basic console command test description.
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/guidelines/testing-guidelines/testing-console-commands.md
Labels: in TW review

#644 Pplus 416/non public api classs was extended or used
  docs/scos/dev/upgradability-services/upgradability-guidelines.md
Labels: in TW review

#661 [CC-15794] AC Doc Documentation API: Min/Soft/Max Threshold support
  docs/scos/dev/glue-api-guides/202200.0/checking-out/checking-out-purchases.md
  docs/scos/dev/glue-api-guides/202200.0/checking-out/submitting-checkout-data.md
  docs/scos/dev/glue-api-guides/202200.0/managing-carts/carts-of-registered-users/managing-carts-of-registered-users.md
  docs/scos/dev/glue-api-guides/202200.0/managing-carts/carts-of-registered-users/managing-discount-vouchers-in-carts-of-registered-users.md
  docs/scos/dev/glue-api-guides/202200.0/managing-carts/carts-of-registered-users/managing-gift-cards-of-registered-users.md
  docs/scos/dev/glue-api-guides/202200.0/managing-carts/carts-of-registered-users/managing-items-in-carts-of-registered-users.md
  docs/scos/dev/glue-api-guides/202200.0/managing-carts/guest-carts/managing-discount-vouchers-in-guest-carts.md
  docs/scos/dev/glue-api-guides/202200.0/managing-carts/guest-carts/managing-gift-cards-of-guest-users.md
  docs/scos/dev/glue-api-guides/202200.0/managing-carts/guest-carts/managing-guest-cart-items.md
  docs/scos/dev/glue-api-guides/202200.0/managing-carts/guest-carts/managing-guest-carts.md
Labels: in progress, TW review needed

#702 Update installing-docker-prerequisites-on-macos.md
  docs/scos/dev/setup/installing-spryker-with-docker/docker-installation-prerequisites/installing-docker-prerequisites-on-macos.md
Labels: in TW review

#693 CC-14555 Add IG for BAPI and BAPI Merchant Relationships.
  docs/scos/dev/feature-integration-guides/202200.0/glue-api/backend-api-for-merchant-relationships-integration-guide.md
  docs/scos/dev/feature-integration-guides/202200.0/glue-api/backend-api-integration-guide.md
Labels: PO review needed, TW review needed

#615 CC-14560 Discount Priority IG
  docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
Labels: TW review needed

#684 CC-14555 Discount valid from/to supports time definition IG
  docs/scos/dev/feature-integration-guides/202200.0/promotions-and-discounts-feature-integration.md
Labels: TW review needed

#716 [AC-1325] Create a landing page for the code guidelines section
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/back-end-development/client/client.md
  docs/scos/dev/back-end-development/zed/adding-navigation-in-the-back-office.md
  docs/scos/dev/glue-api-guides/202108.0/retrieving-orders.md
  docs/scos/dev/guidelines/coding-guidelines/coding-guidelines.md
Labels: in progress, do not merge
