Repository spryker/spryker-docs, pull requests merged in 2022-04, with the labels that each got.

#849 MP-6085 AC Migration Guide fixes
  docs/marketplace/dev/front-end/extending-the-project/migration-guide-upgrade-to-angular-v12.md
Labels: in TW review

#850 Emphasize that a .git.docker file is required for Spryker Cloud Commerce OS
  docs/cloud/dev/spryker-cloud-commerce-os/connecting-the-docker-sdk.md
  docs/marketplace/user/intro-to-spryker-marketplace/intro-to-spryker-marketplace.md
  docs/scos/dev/the-docker-sdk/202009.0/choosing-a-docker-sdk-version.md
  docs/scos/dev/the-docker-sdk/202108.0/choosing-a-docker-sdk-version.md
Labels: TW review needed

#860 Contr patch 10
  docs/scos/dev/back-end-development/data-manipulation/datapayload-conversion/checkout/checkout-process-review-and-implementation.md
Labels: ready for merge, contributor

#859 Added info blocks
  docs/aop/dev/aop-security-assessment.md
Labels: in progress

#803 Payone docs
  _config.yml
  docs/aop/user/apps/bazzarvoice.md
  docs/aop/user/apps/payone.md
Labels: PO review needed

#865 Remove the beta mention
  docs/scos/dev/data-export/202108.0/data-export.md
Labels: in TW review

#888 Update readme
  README.md
Labels: TW review needed

#878 P&S update
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/handling-data-with-publish-and-synchronization.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/implementing-publish-and-synchronization.md
  docs/scos/dev/back-end-development/data-manipulation/event/adding-events.md
  docs/scos/dev/back-end-development/data-manipulation/event/configuring-an-events-queue.md
  docs/scos/dev/back-end-development/data-manipulation/event/listening-to-events.md
Labels: in TW review

#892 SCCOS compatibility checklist for preparation-for-going-live.md review
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: ready for merge
