Repository spryker/spryker-docs, pull requests merged in 2022-02, with the labels that each got.

#722 Configurig search - instructions
  Rakefile
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/contributing-to-documentation/adding-a-new-product-to-the-documentation-site.md
  docs/scos/user/intro-to-spryker/contributing-to-documentation/style-formatting-general-rules.md
Labels: in progress

#732 Update installing-docker-prerequisites-on-macos.md
  Rakefile
  docs/scos/dev/setup/installing-spryker-with-docker/docker-installation-prerequisites/installing-docker-prerequisites-on-macos.md
Labels: in TW review

#725 [TE-10628] сreate a doc on how external users can contribute to docs
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/contributing-to-documentation/contributing-to-spryker-documentation.md
Labels: in progress, TW review needed

#689 Add bulk event processing paragraph
  docs/scos/dev/guidelines/performance-guidelines/architecture-performance-guidelines.md
Labels: TW review needed

#707 AC IG Integration Guide API: Request for Quote
  docs/scos/dev/feature-integration-guides/202200.0/glue-api/glue-api-quotation-process-feature-integration.md
  docs/scos/dev/feature-integration-guides/202200.0/quotation-process-approval-process-feature-integration.md
Labels: PO review needed, TW review needed

#740 Fix small typo
  README.md
  _data/tags.yml
Labels: ready for merge

#747 contributors-pr-erop-patch-3
  docs/scos/dev/back-end-development/yves/implementing-url-routing-in-yves.md
Labels: ready for merge, contributor

#746 contributors-pr-michael-schmetter-patch-6
  docs/scos/dev/data-import/202108.0/data-import-categories/catalog-setup/catalog-setup.md
Labels: ready for merge, contributor

#750 contributors-pr-erop-patch-2
  docs/scos/dev/data-import/202108.0/data-import-categories/catalog-setup/catalog-setup.md
  docs/scos/dev/setup/installing-spryker-with-docker/docker-installation-prerequisites/installing-docker-prerequisites-on-macos.md
Labels: ready for merge, contributor

#752 Update product-quantity-restrictions-overview.md
  docs/scos/user/features/202005.0/product-information-management/product-quantity-restrictions/product-quantity-restrictions-overview.md
Labels: ready for merge

#735 Managing custom prices for big amount of products
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/data-imports/how-to-manage-business-unit-specific-prices-via-data-import.md
  docs/scos/user/features/202108.0/merchant-custom-prices-feature-overview.md
Labels: PO review needed

#766 Update code-contribution-guide.md
  docs/scos/dev/code-contribution-guide.md
Labels: contributor

#772 Contributors erop patch 4
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/structural-preparations/flysystem.md
  docs/scos/dev/back-end-development/yves/yves-routes.md
  docs/scos/dev/code-contribution-guide.md
  docs/scos/dev/glue-api-guides/202108.0/glue-infrastructure.md
Labels: do not merge, contributor

#768 Update glue-infrastructure.md
  docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/data-imports/how-to-manage-business-unit-specific-prices-via-data-import.md
Labels: contributor

#769 Update glue-infrastructure.md
  docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/data-imports/how-to-manage-business-unit-specific-prices-via-data-import.md
Labels: contributor

#350 improve page speed score
  _includes/footer.html
  _includes/head.html
  _includes/topnav.html
  _layouts/default.html
  _layouts/page.html
  _plugins/wistia.rb
  css/components/_code.scss
  css/components/_icons.scss
  css/components/_search-section.scss
  css/customstyles.css
  css/font-awesome.min.css
  css/main.scss
  css/pages/_content.scss
  images/logo.svg
  images/search-section-bg-sm.png
  images/search-section-bg.jpg
  js/customscripts.js
  js/lightbox.js
Labels: contributor

#779 contributor-erop-patch-6
  _includes/footer.html
  _includes/head.html
  _includes/topnav.html
  _layouts/default.html
  _layouts/page.html
  _plugins/wistia.rb
  css/components/_code.scss
  css/components/_icons.scss
  css/components/_search-section.scss
  css/customstyles.css
  css/font-awesome.min.css
  css/main.scss
  css/pages/_content.scss
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/handling-data-with-publish-and-synchronization.md
  docs/scos/dev/back-end-development/data-manipulation/datapayload-conversion/state-machine/order-management-system-multi-thread.md
  docs/scos/dev/glue-api-guides/202108.0/glue-infrastructure.md
  docs/scos/dev/setup/installing-spryker-with-docker/installation-guides/installing-in-demo-mode-on-macos-and-linux.md
  images/logo.svg
  images/search-section-bg-sm.png
  images/search-section-bg.jpg
  js/customscripts.js
  js/lightbox.js
Labels: in progress, contributor

#776 Update handling-data-with-publish-and-synchronization.md
  docs/scos/dev/back-end-development/data-manipulation/datapayload-conversion/state-machine/order-management-system-multi-thread.md
Labels: contributor

#801 contributor-patch-9
  docs/scos/dev/the-docker-sdk/202108.0/deploy-file/deploy-file.md
Labels: contributor
