Repository spryker/spryker-docs, pull requests merged in 2022-03, with the labels that each got.

#738 [CC-15601] AC Doc Documentation Support multiple abstract products as Promotional Products
  docs/scos/user/back-office-user-guides/202108.0/merchandising/discount/creating-cart-rules.md
  docs/scos/user/back-office-user-guides/202200.0/merchandising/discount/creating-cart-rules.md
  docs/scos/user/back-office-user-guides/202200.0/merchandising/discount/creating-vouchers.md
  docs/scos/user/back-office-user-guides/202200.0/merchandising/discount/managing-discounts.md
  docs/scos/user/features/202200.0/promotions-discounts-feature-overview.md
Labels: in progress, TW review needed, do not merge

#805 Remove error box
  docs/scos/dev/technology-partner-guides/202108.0/payment-partners/crefopay/integrating-crefopay.md
Labels: TW review needed

#809 Contributor alftredbez patch 1
  docs/scos/dev/back-end-development/data-manipulation/configuration-management.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/debugging-listeners.md
  docs/scos/dev/setup/installing-spryker-with-docker/database-access-credentials.md
  docs/scos/dev/troubleshooting/troubleshooting-spryker-in-docker-issues/troubleshooting-spryker-in-docker-issues.md
Labels: contributor

#813 Added redirects
  docs/scos/dev/feature-integration-guides/202108.0/spryker-core-feature-integration.md
  docs/scos/dev/setup/setup.md
  docs/scos/dev/troubleshooting/troubleshooting.md
Labels: ready for merge

#703 Usercentrics
  docs/aop/user/apps/usercentrics.md
Labels: in PO review

#822 Update marketplace-merchant-portal-core-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-merchant-portal-core-feature-integration.md
Labels: ready for merge

#818 MP-5770: MerchantProductOfferStorage refactoring TD : ProductOffer and Merchant context leakage [migration guides].
  docs/marketplace/dev/module-migration-guides/glue-api/migration-guide-merchantproductoffersrestapi.md
  docs/marketplace/dev/module-migration-guides/glue-api/migration-guide-productofferpricesrestapi.md
  docs/marketplace/dev/module-migration-guides/migration-guide-merchantproductofferdataimport.md
  docs/marketplace/dev/module-migration-guides/migration-guide-merchantproductofferstorage.md
Labels: in TW review

#816 MP-3934: Product Approval Process + Merchant Context [migration guides].
  docs/marketplace/dev/module-migration-guides/migration-guide-productmerchantportalgui.md
Labels: in TW review

#829 contributor-patch-1
  docs/scos/user/features/202108.0/refunds-feature-overview.md
Labels: ready for merge, contributor

#828 grammar corrected
  docs/marketplace/dev/module-migration-guides/migration-guide-productmerchantportalgui.md
Labels: contributor

#811 MP-3934: Product Approval Process + Merchant Context.
  Rakefile
  _data/sidebars/marketplace_dev_sidebar.yml
  _data/sidebars/marketplace_user_sidebar.yml
  docs/marketplace/dev/feature-integration-guides/202200.0/marketplace-product-approval-process-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202200.0/marketplace-product-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202200.0/product-approval-process-feature-integration.md
Labels: in TW review

#825 MP-6083 AC Technical Documentation
  docs/marketplace/dev/front-end/table-design/index.md
  docs/marketplace/dev/front-end/table-design/table-column-types/index.md
  docs/marketplace/dev/front-end/table-design/table-column-types/table-column-type-autocomplete.md
  docs/marketplace/dev/front-end/table-design/table-column-types/table-column-type-chip.md
  docs/marketplace/dev/front-end/table-design/table-column-types/table-column-type-date.md
  docs/marketplace/dev/front-end/table-design/table-column-types/table-column-type-dynamic.md
  docs/marketplace/dev/front-end/table-design/table-column-types/table-column-type-image.md
  docs/marketplace/dev/front-end/table-design/table-column-types/table-column-type-input.md
  docs/marketplace/dev/front-end/table-design/table-column-types/table-column-type-list.md
  docs/marketplace/dev/front-end/table-design/table-column-types/table-column-type-select.md
  docs/marketplace/dev/front-end/table-design/table-column-types/table-column-type-text.md
  docs/marketplace/dev/front-end/table-design/table-features/index.md
  docs/marketplace/dev/front-end/table-design/table-features/table-feature-batch-actions.md
  docs/marketplace/dev/front-end/table-design/table-features/table-feature-editable.md
  docs/marketplace/dev/front-end/table-design/table-features/table-feature-pagination.md
  docs/marketplace/dev/front-end/table-design/table-features/table-feature-row-actions.md
  docs/marketplace/dev/front-end/table-design/table-features/table-feature-search.md
  docs/marketplace/dev/front-end/table-design/table-features/table-feature-selectable.md
  docs/marketplace/dev/front-end/table-design/table-features/table-feature-settings.md
  docs/marketplace/dev/front-end/table-design/table-features/table-feature-sync-state.md
  docs/marketplace/dev/front-end/table-design/table-features/table-feature-title.md
  docs/marketplace/dev/front-end/table-design/table-features/table-feature-total.md
  docs/marketplace/dev/front-end/table-design/table-filters/table-filter-date-range.md
  docs/marketplace/dev/front-end/table-design/table-filters/table-filter-select.md
  docs/marketplace/dev/front-end/table-design/table-filters/table-filter-tree-select.md
  docs/marketplace/dev/front-end/ui-components-library/actions/actions-close-drawer.md
  docs/marketplace/dev/front-end/ui-components-library/actions/actions-drawer.md
  docs/marketplace/dev/front-end/ui-components-library/actions/actions-http.md
  docs/marketplace/dev/front-end/ui-components-library/actions/actions-notification.md
  docs/marketplace/dev/front-end/ui-components-library/actions/actions-redirect.md
  docs/marketplace/dev/front-end/ui-components-library/actions/actions-refresh-drawer.md
  docs/marketplace/dev/front-end/ui-components-library/actions/actions-refresh-parent-table.md
  docs/marketplace/dev/front-end/ui-components-library/actions/actions-refresh-table.md
  docs/marketplace/dev/front-end/ui-components-library/cache/static.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/array-map.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/chain.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/collate/data-configurators/index.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/collate/data-configurators/table.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/collate/filters/equals.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/collate/filters/index.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/collate/filters/range.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/collate/filters/text.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/date-parse.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/date-serialize.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/index.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/lens.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/object-map.md
  docs/marketplace/dev/front-end/ui-components-library/data-transformers/pluck.md
  docs/marketplace/dev/front-end/ui-components-library/datasources/datasource-http.md
  docs/marketplace/dev/front-end/ui-components-library/datasources/datasource-inline-table.md
  docs/marketplace/dev/front-end/ui-components-library/datasources/datasource-inline.md
  docs/marketplace/dev/front-end/ui-components-library/persistence/in-memory-persistence-strategy.md
  docs/marketplace/dev/front-end/ui-components-library/persistence/local-storage-persistence-strategy.md
  docs/marketplace/dev/front-end/ui-components-library/persistence/url-persistence-strategy.md
  package-lock.json
Labels: in TW review

#810 MP-6052: MerchantProductOfferStorage refactoring TD : ProductOffer and Merchant context leakage.
  docs/marketplace/dev/feature-integration-guides/202200.0/marketplace-merchant-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202200.0/marketplace-product-marketplace-product-offer-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202200.0/marketplace-product-offer-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202200.0/marketplace-product-offer-prices-feature-integration.md
Labels: in TW review

#708 Added code sample with the ability to search for product offers
  docs/marketplace/dev/glue-api-guides/202108.0/searching-the-product-catalog.md
Labels: in progress

#835 MP-6653 Fix FE part of MP core IG version 202108.0
  docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-merchant-portal-core-feature-integration.md
Labels: ready for merge, in TW review

#832 MP-6085 AC Migration Guide
  _data/sidebars/marketplace_dev_sidebar.yml
  docs/marketplace/dev/front-end/extending-the-project/migration-guide-upgrade-to-angular-v12.md
Labels: in TW review
