Repository spryker/spryker-docs, pull requests merged in 2022-12, with the labels that each got.

#1417 Contributor: Fix code snippet in Product Bundles feature integration guide
  _includes/pbc/all/install-features/202204.0/install-the-product-bundles-feature.md
Labels: ready for merge, contributor

#1408 Update configurable-product-feature-overview.md
  docs/scos/user/features/202204.0/configurable-product-feature-overview.md
Labels: ready for merge

#1373 [AC-1406] Request for quote use case documentation
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/request-for-quote/use-cases-request-for-quote-processes.md
Labels: ready for merge

#1420 Update integrate-payone.md
  docs/pbc/all/payment-service-providers/payone/integrate-payone.md
Labels: in TW review

#1421 Update integrate-bazaarvoice.md
  docs/pbc/all/payment-service-providers/payone/integrate-payone.md
  docs/pbc/all/ratings-reviews/third-party-integrations/integrate-bazaarvoice.md
Labels: ready for merge

#1427 fixing file name issue
  docs/scos/dev/glue-api-guides/202204.0/decoupled-glue-infrastructure/how-to-guides/routing/how-to-create-a-backend-resource.md
Labels: TW review needed

#1428 Contributor:Fix wrong strategy explanation
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
Labels: ready for merge, contributor

#1447 fixed broken links
  docs/acp/user/app-manifest.md
  docs/pbc/all/payment-service-providers/payone/integrate-payone.md
  docs/scos/user/technology-partners/202204.0/payment-partners/bs-payone/bs-payone.md
Labels: urgent

#1419 [CC-21880] Update cart totals based on shipment selector
  docs/pbc/all/cart-and-checkout/manage-using-glue-api/check-out/submit-checkout-data.md
Labels: ready for merge

#1448 Added info box on memory limits
  docs/scos/dev/the-docker-sdk/202204.0/deploy-file/deploy-file-reference-1.0.md
Labels: ready for merge

#1445 CC-24951 Updated Customer Account Management and Agent Assist IGs with customer session validation plugins.
  Rakefile
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202204.0/install-the-splittable-order-items-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-customer-account-management-agent-assist-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-customer-account-management-feature.md
  docs/scos/dev/feature-integration-guides/202212.0/customer-account-management-feature-integration.md
  docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/howto-add-support-of-number-formatting-in-the-back-office.md
Labels: ready for merge

#1412 CC-23709: Added update cart totals based on shipment selector IG.
  Rakefile
  _includes/pbc/all/install-features/202204.0/install-glue-api/install-the-cart-glue-api.md
  _includes/pbc/all/install-features/202204.0/install-glue-api/install-the-checkout-glue-api.md
  _includes/pbc/all/install-features/202204.0/install-glue-api/install-the-product-configuration-glue-api.md
  _includes/pbc/all/install-features/202204.0/install-glue-api/install-the-shipment-glue-api.md
  _includes/pbc/all/install-features/202212.0/install-glue-api/install-the-product-configuration-glue-api.md
  docs/scos/dev/feature-integration-guides/202212.0/glue-api/glue-api-product-configuration-feature-integration.md
Labels: ready for merge

#1323 FRW-436 Added newly added spryk functionality to the documentation
  docs/scos/dev/glue-api-guides/202204.0/glue-spryks.md
Labels: do not merge

#1436 Update tutorial-new-relic-monitoring.md
  docs/scos/dev/tutorials-and-howtos/advanced-tutorials/tutorial-new-relic-monitoring.md
Labels: in TW review

#1437 Discount Management edits
  docs/pbc/all/discount-management/discount-management.md
  docs/pbc/all/discount-management/import-and-export-data/discount-import.md
  docs/pbc/all/discount-management/import-and-export-data/file-details-discount-store.csv.md
  docs/pbc/all/discount-management/import-and-export-data/file-details-discount-voucher.csv.md
  docs/pbc/all/discount-management/manage-in-the-back-office/best-practices-promote-products-with-discounts.md
  docs/pbc/all/discount-management/manage-in-the-back-office/create-discounts.md
  docs/pbc/all/discount-management/manage-in-the-back-office/edit-discounts.md
  docs/pbc/all/discount-management/manage-via-glue-api/add-items-with-discounts-to-carts-of-registered-users.md
  docs/pbc/all/discount-management/manage-via-glue-api/add-items-with-discounts-to-guest-carts.md
  docs/pbc/all/discount-management/manage-via-glue-api/manage-discount-vouchers-in-carts-of-registered-users.md
  docs/pbc/all/discount-management/manage-via-glue-api/manage-discount-vouchers-in-guest-carts.md
  docs/pbc/all/discount-management/manage-via-glue-api/manage-discounts-via-glue-api.md
  docs/pbc/all/discount-management/manage-via-glue-api/retrieve-discounts-in-carts-of-registered-users.md
  docs/pbc/all/discount-management/manage-via-glue-api/retrieve-discounts-in-customer-carts.md
  docs/pbc/all/discount-management/manage-via-glue-api/retrieve-discounts-in-guest-carts.md
  docs/pbc/all/discount-management/tutorials-and-howtos/howto-create-discounts-based-on-shipment.md
  docs/pbc/all/discount-management/whats-changed-in-discount-management.md
Labels: in progress

#1425 Remove transfer definition
  docs/scos/dev/back-end-development/forms/create-forms.md
  docs/scos/dev/glue-api-guides/202204.0/decoupled-glue-infrastructure/how-to-guides/routing/how-to-create-a-backend-resource.md
  docs/scos/dev/the-docker-sdk/202204.0/deploy-file/deploy-file-reference-1.0.md
Labels: ready for merge

#1387 Contributor: Create spryker-cloud-commerce-management.md
  _data/sidebars/cloud_dev_sidebar.yml
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202204.0/install-the-product-bundles-feature.md
  docs/cloud/dev/spryker-cloud-commerce-os/spryker-cloud-commerce-os-management.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/handle-data-with-publish-and-synchronization.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-set-up-stores-with-multiple-locales.md
  docs/scos/user/shop-user-guides/201907.0/shop-guide-shopping-carts/managing-shopping-carts.md
Labels: ready for merge, contributor

#1410 Update acp-overview.md
  docs/acp/user/intro-to-acp/acp-overview.md
Labels: TW review needed

#1462 Update acp-overview.md
  docs/acp/user/intro-to-acp/acp-overview.md
Labels: TW review needed

#1464 Added reference to NewRelic
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: ready for merge

#1433 Add landing page
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/back-end-development/index.md
  docs/scos/dev/back-end-development/messages-and-errors/messages-and-errors.md
  docs/scos/dev/back-end-development/zed-ui-tables/zed-ui-tables.md
  docs/scos/dev/best-practices/index.md
  docs/scos/dev/best-practices/search-best-practices/search-best-practices.md
  docs/scos/dev/best-practices/state-machine-cookbook/state-machine-cookbook.md
  docs/scos/dev/data-export/202204.0/index.md
  docs/scos/dev/front-end-development/index.md
  docs/scos/dev/glue-api-guides/202204.0/glue-backend-api/glue-backend-api.md
  docs/scos/dev/glue-api-guides/202204.0/index.md
  docs/scos/dev/guidelines/index.md
  docs/scos/dev/migration-concepts/about-migration-concepts.md
  docs/scos/dev/migration-concepts/migration-concepts.md
  docs/scos/dev/sdk/index.md
  docs/scos/dev/technical-enhancement-integration-guides/index.md
  docs/scos/dev/technology-partner-guides/202204.0/index.md
  docs/scos/dev/technology-partner-guides/202204.0/marketing-and-conversion/marketing-and-conversion.md
  docs/scos/dev/tutorials-and-howtos/tutorials-and-howtos.md
Labels: in TW review

#1454 Contributor:Update approval-process-feature-overview.md
  docs/pbc/all/cart-and-checkout/202204.0/approval-process-feature-overview.md
Labels: ready for merge

#1467 Added explanation about stores: true in recipes
  docs/scos/dev/tutorials-and-howtos/howtos/howto-set-up-multiple-stores.md
Labels: in TW review

#1473 CC-21664 Angular v15: Update documentation
  _data/sidebars/marketplace_dev_sidebar.yml
  docs/marketplace/dev/front-end/202204.0/building-the-project.md
  docs/marketplace/dev/front-end/202212.0/building-the-project.md
  docs/marketplace/dev/front-end/202212.0/table-design/table-features/table-feature-editable.md
Labels: ready for merge

#1480 Configurable Product update
  docs/scos/dev/module-migration-guides/migration-guide-publish-and-synchronization.md
  docs/scos/user/features/202204.0/configurable-product-feature-overview.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202212.0/release-notes-202212.0.md
Labels: ready for merge
