Repository spryker/spryker-docs, pull requests merged in 2023-07, with the labels that each got.

#1961 Docs release notes June 2023
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/cart-and-checkout/202212.0/base-shop/install-and-upgrade/install-features/install-the-approval-process-feature.md
  docs/pbc/all/warehouse-management-system/202304.0/base-shop/install-and-upgrade/install-the-warehouse-user-management-feature.md
  docs/scos/user/intro-to-spryker/docs-release-notes.md
Labels: new

#1946 Update algolia.md
  docs/pbc/all/search/202212.0/base-shop/third-party-integrations/algolia.md
Labels: TW review needed, updated

#1963 Add pictures and video for Usercentrics
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/usercentrics/configure-usercentrics.md
  docs/pbc/all/usercentrics/integrate-usercentrics.md
  docs/pbc/all/usercentrics/usercentrics.md
Labels: updated

#1966 SDK-2885: Extend the list of required GitHub permissions for upgrader
  docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-ci-to-a-github-managed-project.md
Labels: small changes

#1960 added reserved variable sub-section. Plus, removed deprecated text.
  docs/cloud/dev/spryker-cloud-commerce-os/add-variables-in-the-parameter-store.md
Labels: updated

#1970 Add 'Missing security HTTP headers' in security-release-notes-202306
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202306.0/security-release-notes-202306.0.md
Labels: in TW review, updated

#1971 Update merchant-users-overview.md
  docs/pbc/all/merchant-management/202212.0/marketplace/marketplace-merchant-feature-overview/merchant-users-overview.md
Labels: in TW review, updated

#1974 Minor changes in security-release-notes-202306.0.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202306.0/security-release-notes-202306.0.md
Labels: ready for merge, small changes

#1975 Update configure-a-search-query.md
  docs/pbc/all/search/202212.0/base-shop/tutorials-and-howtos/configure-a-search-query.md
Labels: small changes

#1962 fixing 404s
  _data/sidebars/scos_dev_sidebar.yml
  docs/pbc/all/back-office/202304.0/install-spryker-core-back-office-warehouse-user-management-feature.md
  docs/scos/dev/front-end-development/202212.0/front-end-development.md
  docs/scos/dev/front-end-development/202212.0/migration-guide-upgrade-nodejs-to-v18-and-npm-to-v9.md
  docs/scos/dev/front-end-development/202304.0/front-end-development.md
  docs/scos/dev/front-end-development/202304.0/zed/zed.md
Labels: ready for merge, small changes

#1910 docs: Oryx compositions
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-compositions.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-feature-sets.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-presets.md
Labels: new

#1979 Update acp-overview.md with direct links to integration page of apps
  docs/acp/user/intro-to-acp/acp-overview.md
Labels: small changes

#1982 Fixing the variables for acp docs
  docs/pbc/all/payment-service-provider/202212.0/third-party-integrations/payone/integration-in-the-back-office/payone-integration-in-the-back-office.md
  docs/pbc/all/search/202212.0/base-shop/third-party-integrations/algolia.md
Labels: small changes

#1976 Update install-the-warehouse-picking-product-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-warehouse-picking-product-feature.md
Labels: small changes

#1983 SDK-000 Added missed Profiler integration guide pieces.
  docs/scos/dev/technical-enhancement-integration-guides/Integrate-profiler-module.md
Labels: small changes

#1964 Install the Service Points feature
  _includes/pbc/all/install-features/202304.0/install-the-product-offer-service-points-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-service-points-feature.md
  _includes/pbc/all/install-features/202304.0/marketplace/install-the-marketplace-product-offer-service-points-feature.md
  docs/pbc/all/offer-management/202304.0/marketplace/install-and-upgrade/install-the-marketplace-product-offer-service-points-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-product-offer-service-points-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-service-points-feature.md
Labels: ready for merge, updated

#1990 Improve the validation list.
  docs/pbc/all/product-information-management/202212.0/base-shop/tutorials-and-howtos/howto-make-a-product-searchable-and-shown-on-the-storefront.md
Labels: ready for merge, small changes

#1988 Update bazaarvoice.md
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/bazaarvoice.md
Labels: ready for merge, small changes

#1991 Install the Marketplace Merchant Portal Core feature
  _includes/pbc/all/install-features/202304.0/marketplace/install-the-marketplace-merchant-portal-core-feature.md
  docs/pbc/all/merchant-management/202304.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-core-feature.md
Labels: ready for merge, updated, 202306

#1969 added warning on top for security reasons
  docs/cloud/dev/spryker-cloud-commerce-os/configuring-debugging.md
Labels: ready for merge, small changes

#1911 Choosing a Docker SDK version
  docs/scos/dev/the-docker-sdk/202212.0/choosing-a-docker-sdk-version.md
Labels: ready for merge, updated

#1941 Fixed mistype
  docs/cloud/dev/spryker-cloud-commerce-os/add-variables-in-the-parameter-store.md
Labels: ready for merge, small changes

#1994 Tutorial: Architectural walkthrough - Spryker Commerce OS
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-architectural-walkthrough-spryker-commerce-os.md
Labels: ready for merge, small changes

#1993 Security release notes 202306.0
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202306.0/security-release-notes-202306.0.md
Labels: ready for merge, updated

#2000 Tutorial: Checkout and step engine
  docs/pbc/all/cart-and-checkout/202204.0/base-shop/tutorials-and-howtos/tutorial-checkout-and-step-engine.md
Labels: updated

#1985 docs: Colors in Oryx
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202212.0/oryx/styling/oryx-color-system.md
Labels: ready for merge, new

#2002 Handle data with Publish and Synchronization
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/handle-data-with-publish-and-synchronization.md
Labels: updated

#1981 Create best-practises-jenkins-stability.md
  _data/sidebars/cloud_dev_sidebar.yml
  docs/cloud/dev/spryker-cloud-commerce-os/best-practices/best-practices.md
  docs/cloud/dev/spryker-cloud-commerce-os/best-practices/best-practises-jenkins-stability.md
Labels: ready for merge, new

#1944 FRW-1893: Dynamic Data Exchange API
  docs/scos/dev/feature-integration-guides/202304.0/glue-api/dynamic-data-api/dynamic-data-api-integration.md
  docs/scos/dev/glue-api-guides/202304.0/dynamic-data-api/how-to-guides/how-to-configure-dynamic-data-api.md
  docs/scos/dev/glue-api-guides/202304.0/dynamic-data-api/how-to-guides/how-to-send-request-in-dynamic-data-api.md
Labels: in progress, new

#2003 Security updates
  docs/scos/user/intro-to-spryker/whats-new/security-updates.md
Labels: ready for merge, small changes

#1943 Standartise evaluator pages
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/additional-logic-in-dependency-provider.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/dead-code-checker.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/minimum-allowed-shop-version.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/multidimensional-array.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/php-version.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/plugin-registration-with-restrintions.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/security.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/single-plugin-argument.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/upgradability-guidelines.md
Labels: in TW review, updated

#1995 Update install-in-development-mode-on-macos-and-linux.md
  docs/scos/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-macos-and-linux.md
  docs/scos/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-windows.md
  docs/scos/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-macos-and-linux.md
  docs/scos/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-windows.md
Labels: in tech review, small changes

#2015 Update JSON example
  docs/pbc/all/search/202212.0/base-shop/third-party-integrations/algolia.md
Labels: small changes

#1997 FRW-2369 Added error codes.
  docs/scos/dev/glue-api-guides/202212.0/glue-infrastructure.md
  docs/scos/dev/glue-api-guides/202304.0/dynamic-data-api/how-to-guides/how-to-send-request-in-dynamic-data-api.md
Labels: updated

#1958 database name is not consistent, in the multi-db configuration
  docs/scos/dev/technical-enhancement-integration-guides/integrate-multi-database-logic.md
Labels: ready for merge, small changes

#2012 Marketplace Promotions and Discounts feature overview
  docs/marketplace/user/features/202108.0/marketplace-promotions-and-discounts-feature-overview.md
  docs/marketplace/user/features/202204.0/marketplace-promotions-and-discounts-feature-overview.md
  docs/pbc/all/discount-management/202212.0/marketplace/marketplace-promotions-discounts-feature-overview.md
Labels: ready for merge, small changes

#2018 CC-25992: Adjusted login mechanism for agent and customer.
  _includes/pbc/all/install-features/202304.0/install-the-spryker-core-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/spryker-core-feature-integration.md
Labels: ready for merge, updated

#2016 Install Docker prerequisites on Linux
  docs/scos/dev/set-up-spryker-locally/install-spryker/install-docker-prerequisites/install-docker-prerequisites-on-linux.md
Labels: ready for merge, updated

#2013 Install the Product Rating and Reviews Glue API
  _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-product-rating-and-reviews-glue-api.md
  docs/pbc/all/ratings-reviews/202304.0/install-and-upgrade/install-the-product-rating-and-reviews-glue-api.md
Labels: ready for merge, 202306

#2020 add missing redirects
  docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/glue-infrastructure.md
  docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/glue-rest-api.md
  docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/handling-concurrent-rest-requests-and-caching-with-entity-tags.md
  docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/reference-information-glueapplication-errors.md
  docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/resolving-search-engine-friendly-urls.md
  docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/rest-api-b2b-reference.md
  docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/rest-api-b2c-reference.md
Labels: ready for merge, small changes

#1894 FAQ: Migration to OpenSearch
  _internal/faq-migration-to-opensearch.md
Labels: new

#2021 CC-26138 Install the Shipment feature
  _includes/pbc/all/install-features/202400.0/install-the-shipment-feature.md
  docs/pbc/all/carrier-management/202400.0/unified-commerce/install-and-upgrade/install-the-shipment-feature.md
Labels: ready for merge, tech review needed, updated

#2030 Security release notes 202306.0
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202306.0/security-release-notes-202306.0.md
Labels: ready for merge, small changes

#2028 Security release notes 202306.0
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202306.0/security-release-notes-202306.0.md
Labels: ready for merge, small changes

#2040 Fixes typo in persistence folder's name
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/handle-data-with-publish-and-synchronization.md
Labels: ready for merge, small changes

#2023 Update app-composition-platform-installation.md
  docs/acp/user/app-composition-platform-installation.md
Labels: updated

#1899 Update prepare-a-project-for-spryker-code-upgrader.md
  docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
Labels: updated

#1986 Update app-composition-platform-installation.md
  docs/acp/user/app-composition-platform-installation.md
Labels: small changes

#1977 update app manifest categories
  docs/acp/user/app-manifest.md
Labels: updated, 202306

#1243 Adding Instructions for Load Testing Tool
  docs/cloud/dev/spryker-cloud-commerce-os/performance-testing-in-staging-enivronments.md
Labels: contributor, updated

#2039 Remove AHA references
  _data/sidebars/scos_user_sidebar.yml
  _drafts/deprecated/handling-new-feature-requests.md
  docs/scos/dev/back-end-development/extend-spryker/development-strategies.md
  docs/scos/dev/drafts-dev/roadmap.md
  docs/scos/dev/guidelines/project-development-guidelines.md
  docs/scos/user/intro-to-spryker/support/getting-support.md
  docs/scos/user/intro-to-spryker/support/handling-security-issues.md
Labels: updated

#2043 Measurement units
  docs/pbc/all/product-information-management/202212.0/base-shop/install-and-upgrade/install-features/install-the-measurement-units-feature.md
  docs/pbc/all/product-information-management/202307.0/base-shop/install-and-upgrade/install-features/install-the-measurement-units-feature.md
Labels: contributor, updated

#2011 HowTo guide - one worker for all stores and it's benefits
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/tutorials-and-howtos/howtos/howto-reduce-jenkins-execution-costs-without-refactoring.md
Labels: tech review needed, new

#2034 Update integrate-algolia.md (new modules version)
  docs/pbc/all/search/202212.0/base-shop/third-party-integrations/integrate-algolia.md
Labels: ready for merge, small changes

#2031 Install in Development mode on MacOS and Linux
  docs/scos/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-macos-and-linux.md
Labels: ready for merge, small changes
