Repository spryker/spryker-docs, pull requests merged in 2023-05, with the labels that each got.

#1817 Docs release notes
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/docs-release-notes.md
Labels: new

#1815 Overriding Webpack, JS, SCSS for ZED on project level
  _includes/scos/dev/front-end-development/zed/202212.0/overriding-webpack-js-scss-for-zed-on-project-level.md
  _includes/scos/dev/front-end-development/zed/202304.0/overriding-webpack-js-scss-for-zed-on-project-level.md
  docs/scos/dev/front-end-development/202212.0/zed/overriding-webpack-js-scss-for-zed-on-project-level.md
  docs/scos/dev/front-end-development/202304.0/zed/overriding-webpack-js-scss-for-zed-on-project-level.md
Labels: in TW review, small changes

#1821 APPS-6752: Added `developedBy` property support.
  docs/acp/user/app-manifest.md
Labels: TW review needed, updated

#1822 HowTo: Allow Zed SCSS/JS on a project level
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/tutorials-and-howtos/howtos/howto-allow-zed-css-js-on-a-project-for-oryx-for-zed-2.12.0-and-earlier.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-allow-zed-css-js-on-a-project-for-oryx-for-zed-2.13.0-and-later.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-allow-zed-css-js-on-a-project.md
Labels: in TW review, updated

#1823 How to use the Support Portal
  docs/scos/user/intro-to-spryker/support/how-to-use-the-support-portal.md
Labels: ready for merge, small changes

#1818 Troubleshooting RabbitMQ
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-rabbitmq/troubleshooting-rabbitmq.md
Labels: ready for merge, small changes

#1820 Learn how to fix the issue when events are not consumed or are consumed slowly
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/rabbitmq-zed.critical-phpamqplib-exception-amqpchannelclosedexception-channel-connection-is-closed.md
Labels: ready for merge, small changes

#1824 Install the Service Points feature
  Rakefile
  _includes/pbc/all/install-features/202304.0/install-the-service-points-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-service-points-feature.md
Labels: ready for merge, updated, 202306

#1834 Install the Service Points feature
  _includes/pbc/all/install-features/202304.0/install-the-service-points-feature.md
Labels: ready for merge, updated, 202306

#1833 EVM
  Rakefile
  _data/sidebars/cloud_dev_sidebar.yml
  _data/sidebars/scos_dev_sidebar.yml
  docs/cloud/dev/spryker-cloud-commerce-os/add-variables.md
  docs/cloud/dev/spryker-cloud-commerce-os/define-parameter-and-secret-values-in-sccos-environments.md
  docs/scos/dev/the-docker-sdk/202212.0/define-parameters-and-secrets.md
Labels: updated

#1830 SDK-2400: Add disclaimer on Code Contribution page
  docs/scos/dev/code-contribution-guide.md
Labels: small changes

#1766 SDK-2062. Process small feedback to our documentation
  _data/sidebars/scu_dev_sidebar.yml
  docs/scu/dev/how-the-spryker-code-upgrader-works.md
  docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-ci-to-a-azure-managed-project.md
  docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-ci-to-a-github-managed-project.md
  docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-ci-to-a-gitlab-managed-project.md
  docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-ci-to-a-project-self-hosted-with-gitlab.md
  docs/scu/dev/onboard-to-spryker-code-upgrader/onboard-to-spryker-code-upgrader.md
  docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
  docs/scu/dev/run-spryker-code-upgrader.md
  docs/scu/dev/spryker-ci.md
  docs/scu/dev/spryker-code-upgrader-in-a-development-workflow.md
  docs/scu/dev/spryker-code-upgrader.md
  docs/scu/dev/troubleshooting/the-process-exceeded-the-timeout.md
  docs/scu/dev/troubleshooting/transportexception-cannot-move-pack.md
Labels: updated

#1839 Spryker Code Upgrader in a development workflow
  docs/scu/dev/spryker-code-upgrader-in-a-development-workflow.md
Labels: ready for merge, updated

#1838 Spryker Code Upgrader
  docs/scu/dev/spryker-code-upgrader.md
Labels: ready for merge, updated

#1809 File Manager feature overview
  docs/pbc/all/merchant-management/202212.0/marketplace/tutorials-and-howtos/create-gui-modules.md
  docs/scos/user/features/202108.0/file-manager-feature-overview/file-manager-feature-overview.md
Labels: ready for merge, contributor, small changes

#1808 Changed Asset Measurement to Management
  docs/pbc/all/merchant-management/202212.0/marketplace/tutorials-and-howtos/create-gui-modules.md
Labels: contributor, small changes

#1845 Update security-release-notes-202304.0.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202304.0/security-release-notes-202304.0.md
Labels: small changes

#1848 removing Scalable application infrastructure doc
  _drafts/scalable-application-infrastructure-for-publish-and-sync-workers.md
  docs/scos/dev/guidelines/performance-guidelines/elastic-computing/new-relic-transaction-grouping-by-queue-names.md
Labels: small changes

#1790 Multistore setups
  _data/sidebars/cloud_dev_sidebar.yml
  docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/checklist-for-a-new-store-implementation.md
  docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/multi-store-setups.md
  docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/multistore-setup-options.md
  docs/scos/dev/drafts-dev/multistore-infrastructure-options.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-set-up-multiple-stores.md
Labels: in progress, new

#1832 Update scos_user_sidebar.yml
  _data/sidebars/scos_user_sidebar.yml
Labels: small changes

#1853 Multistore docs fixes
  docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/checklist-for-a-new-store-implementation.md
  docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/multistore-setup-options.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-set-up-multiple-stores.md
Labels: small changes

#1849 Install the Shipment feature
  _includes/pbc/all/install-features/202304.0/install-the-shipment-feature.md
Labels: ready for merge, updated

#1840 Update file-details-product-concrete.csv.md
  docs/pbc/all/product-information-management/202212.0/import-and-export-data/products-data-import/file-details-product-concrete.csv.md
Labels: ready for merge, small changes

#1855 Configuring debugging in Docker
  Rakefile
  docs/scos/dev/the-docker-sdk/202212.0/configuring-debugging-in-docker.md
Labels: ready for merge, updated

#1846 Install the Marketplace Inventory Management feature
  _includes/pbc/all/install-features/202304.0/marketplace/install-the-marketplace-inventory-management-feature.md
  docs/pbc/all/warehouse-management-system/202304.0/marketplace/install-features/install-the-marketplace-inventory-management-feature.md
Labels: ready for merge, 202306

#1735 Dependency injection in Oryx
  CODEOWNERS
  _drafts/oryx/dependency-injection/dependency-injection-advanced-strategies.md
  _drafts/oryx/dependency-injection/dependency-injection-defining-services.md
  _drafts/oryx/dependency-injection/dependency-injection-providing-services.md
  _drafts/oryx/dependency-injection/dependency-injection-using-services.md
  _drafts/oryx/dependency-injection/dependency-injection.md
  _drafts/oryx/dependency-injection/oryx-service-layer.md
Labels: new

#1723 App Orchestration
  _drafts/oryx/oryx-application-orchestration/oryx-application-environment.md
  _drafts/oryx/oryx-application-orchestration/oryx-application-feature.md
  _drafts/oryx/oryx-application-orchestration/oryx-application-orchestration.md
  _drafts/oryx/oryx-application-orchestration/oryx-application-plugins.md
  _drafts/oryx/oryx-application-orchestration/oryx-application.md
Labels: in progress, new

#1856 Environment provisioning
  docs/cloud/dev/spryker-cloud-commerce-os/environment-provisioning.md
  docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/multistore-setup-options.md
Labels: updated

#1860 Update checklist-for-a-new-store-implementation.md
  docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/checklist-for-a-new-store-implementation.md
Labels: updated

#1756 Re-review of the four docs
  docs/scos/dev/guidelines/keeping-a-project-upgradable/keeping-a-project-upgradable.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/event-subscribers-registration.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/modules-configuration.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/supported-extension-scenarios/plugins-registration.md
Labels: updated

#1850 Acp installation guides
  _data/sidebars/acp_user_sidebar.yml
  _drafts/ACP_enablement_flow_simple_20230504.png
  docs/acp/user/intro-to-acp/acp-overview.md
  docs/acp/user/intro-to-acp/app-composition-platform-installation.md
Labels: in TW review, new

#1866 removing the blackfire link
  docs/scos/dev/the-docker-sdk/202204.0/configure-services.md
Labels: small changes

#1765 docs: oryx versioning
  _drafts/oryx/oryx-versioning.md
Labels: new

#1874 sidebar fix
  _data/sidebars/scos_dev_sidebar.yml
Labels: small changes

#1835 Add routing doc
  _drafts/oryx/routing.md
Labels: new

#1728 docs(oryx): add browser compatibility documentation for oryx
  _drafts/oryx/browser-compatibility.md
Labels: new

#1826 docs: Feature sets documentation
  CODEOWNERS
  _drafts/oryx/feature-sets.md
  _drafts/oryx/presets.md
Labels: new

#1801 Add landing pages
  _data/sidebars/pbc_all_sidebar.yml
  _data/sidebars/scos_dev_sidebar.yml
  _scripts/sidebar_checker/sidebar_checker.sh
  docs/pbc/all/back-office/202212.0/howto-add-support-of-number-formatting-in-the-back-office.md
  docs/pbc/all/miscellaneous/202212.0/spryker-core-feature-overview/howto-add-support-for-number-formatting-in-the-storefront.md
  docs/pbc/all/product-information-management/202204.0/base-shop/tutorials-and-howtos/howto-make-a-product-searchable-and-shown-on-the-storefront.md
  docs/scos/dev/architecture/module-api/module-api.md
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/structural-preparations/structural-preparations.md
  docs/scos/dev/back-end-development/data-manipulation/data-manipulation.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/add-publish-events.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/data-publishing.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/debug-listeners.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/handle-data-with-publish-and-synchronization.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/implement-event-trigger-publisher-plugins.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/implement-publish-and-synchronization.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/implement-synchronization-plugins.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/publish-and-synchronization.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/publish-and-synchronize-and-multi-store-shop-systems.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/publish-and-synchronize-repeated-export.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/synchronization-behavior-enabling-multiple-mappings.md
  docs/scos/dev/back-end-development/extend-spryker/extend-spryker.md
  docs/scos/dev/back-end-development/extend-spryker/spryker-os-module-customisation/spryker-os-module-customisation.md
  docs/scos/dev/back-end-development/messages-and-errors/messages-and-errors.md
  docs/scos/dev/back-end-development/zed-ui-tables/zed-ui-tables.md
  docs/scos/dev/guidelines/guidelines.md
  docs/scos/dev/guidelines/testing-guidelines/testing-guidelines.md
  docs/scos/dev/migration-concepts/silex-replacement/router/router.md
  docs/scos/dev/module-migration-guides/about-migration-guides.md
  docs/scos/dev/module-migration-guides/glue-api/about-glue-api-migration-guides.md
  docs/scos/dev/sdk/zed-api/zed-api.md
  docs/scos/dev/setup/installing-spryker-with-docker/configuration/configuration.md
  docs/scos/dev/setup/installing-spryker-with-docker/docker-installation-prerequisites/installing-docker-prerequisites.md
  docs/scos/dev/technology-partner-guides/202204.0/technology-partner-guides.md
  docs/scos/dev/technology-partner-guides/202212.0/marketing-and-conversion/analytics/fact-finder/fact-finder.md
  docs/scos/dev/technology-partner-guides/202212.0/marketing-and-conversion/customer-communication/episerver/episerver.md
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/introduction-tutorials.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202212.0/release-notes-202212.0.md
Labels: ready for merge, new, small changes

#1836 Update create-users.md
  docs/pbc/all/user-management/202212.0/manage-in-the-back-office/manage-users/create-users.md
Labels: new

#1870 SDK-2172. Typos were fixed
  docs/marketplace/user/intro-to-spryker-marketplace/release-notes/release-notes-202211.0.md
  docs/scos/dev/back-end-development/extend-spryker/development-strategies.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202211.0/release-notes-202211.0.md
  docs/scos/user/intro-to-spryker/whats-new/php8-as-a-minimum-version-for-all-spryker-projects.md
Labels: small changes

#1880 caveats-info
  docs/cloud/dev/spryker-cloud-commerce-os/manage-maintenance-mode/enable-and-disable-maintenance-mode.md
Labels: small changes

#1883 Publish oryx docs
  _data/sidebars/scos_dev_sidebar.yml
  _drafts/oryx/reactivity/index.md
  _includes/diagrams/oryx/backend-integration.svg
  _includes/diagrams/oryx/packages.svg
  _includes/diagrams/oryx/reactivity-high-level.svg
  _includes/diagrams/oryx/reactivity-interaction.svg
  docs/scos/dev/front-end-development/202212.0/oryx/dependency-injection/dependency-injection-advanced-strategies.md
  docs/scos/dev/front-end-development/202212.0/oryx/dependency-injection/dependency-injection-defining-services.md
  docs/scos/dev/front-end-development/202212.0/oryx/dependency-injection/dependency-injection-providing-services.md
  docs/scos/dev/front-end-development/202212.0/oryx/dependency-injection/dependency-injection-using-services.md
  docs/scos/dev/front-end-development/202212.0/oryx/dependency-injection/dependency-injection.md
  docs/scos/dev/front-end-development/202212.0/oryx/dependency-injection/oryx-service-layer.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-application-orchestration/oryx-application-environment.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-application-orchestration/oryx-application-feature.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-application-orchestration/oryx-application-orchestration.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-application-orchestration/oryx-application-plugins.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-application-orchestration/oryx-application.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-boilerplate.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-feature-sets.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-packages.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-presets.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-routing.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-supported-browsers.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-versioning.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx.md
  docs/scos/dev/front-end-development/202212.0/oryx/reactivity/key-concepts-of-reactivity.md
  docs/scos/dev/front-end-development/202212.0/oryx/reactivity/oryx-integration-of-backend-apis.md
  docs/scos/dev/front-end-development/202212.0/oryx/reactivity/reactive-components.md
  docs/scos/dev/front-end-development/202212.0/oryx/reactivity/reactivity.md
  docs/scos/dev/front-end-development/202212.0/oryx/set-up-oryx.md
Labels: updated

#1887 Fixing push to Algolia
  docs/scos/dev/front-end-development/202212.0/oryx/reactivity/key-concepts-of-reactivity.md
Labels: small changes

#1886 Doc release notes May 2023
  Rakefile
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/additional-logic-in-dependency-provider.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/dead-code-checker.md
  docs/scos/user/intro-to-spryker/docs-release-notes.md
Labels: new

#1888 Fixing product names an search
  _config.yml
  algolia_config/_sdk_dev.yml
Labels: small changes
