Repository spryker/spryker-docs, pull requests merged in 2023-04, with the labels that each got.

#1717 PBC-887: Bump modules required versions and fix step 3
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
Labels: ready for merge

#1020 added vale files
  .gitignore
  .vale.ini
  .vscode/settings.json
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/install-recommended-vs-code-extensions.md
  vale/styles/Google/AMPM.yml
  vale/styles/Google/Acronyms.yml
  vale/styles/Google/Colons.yml
  vale/styles/Google/Contractions.yml
  vale/styles/Google/DateFormat.yml
  vale/styles/Google/Ellipses.yml
  vale/styles/Google/EmDash.yml
  vale/styles/Google/EnDash.yml
  vale/styles/Google/Exclamation.yml
  vale/styles/Google/FirstPerson.yml
  vale/styles/Google/Gender.yml
  vale/styles/Google/GenderBias.yml
  vale/styles/Google/HeadingPunctuation.yml
  vale/styles/Google/Headings.yml
  vale/styles/Google/Latin.yml
  vale/styles/Google/LyHyphens.yml
  vale/styles/Google/OptionalPlurals.yml
  vale/styles/Google/Ordinal.yml
  vale/styles/Google/OxfordComma.yml
  vale/styles/Google/Parens.yml
  vale/styles/Google/Passive.yml
  vale/styles/Google/Periods.yml
  vale/styles/Google/Quotes.yml
  vale/styles/Google/Ranges.yml
  vale/styles/Google/Semicolons.yml
  vale/styles/Google/Slang.yml
  vale/styles/Google/Spacing.yml
  vale/styles/Google/Spelling.yml
  vale/styles/Google/Units.yml
  vale/styles/Google/We.yml
  vale/styles/Google/Will.yml
  vale/styles/Google/WordList.yml
  vale/styles/Google/meta.json
  vale/styles/Google/qurly-quotes.yml
  vale/styles/Google/vocab.txt
  vale/styles/Spryker/glossary.yml
  vale/styles/Spryker/yves-versus-frontstore.yml
  vale/styles/Spryker/zed-versus-back-office.yml
  vale/styles/Vocab/Base/accept.txt
  vale/styles/Vocab/Base/reject.txt
Labels: ready for merge, new

#1755 Enforce PR labels
  .github/workflows/enforce-labels.yml
Labels: 202306

#1684 docs: Oryx boilerplate
  _drafts/oryx/boilerplate.md
Labels: new

#1683 Setup doc for oryx
  _drafts/oryx/set-up-oryx.md
  docs/scos/dev/glue-api-guides/202204.0/glue-rest-api.md
Labels: new

#1743 Fix migration guide switch from tslint to eslint
  docs/scos/dev/front-end-development/migration-guide-switch-from-tslint-to-eslint.md
Labels: ready for merge, updated

#1731 Merchant onboarding guide
  _data/sidebars/marketplace_user_sidebar.yml
  docs/marketplace/user/intro-to-spryker-marketplace/merchant-onboarding.md
  docs/marketplace/user/merchant-portal-user-guides/202108.0/products/products.md
  docs/marketplace/user/merchant-portal-user-guides/202204.0/products/products.md
  docs/marketplace/user/merchant-portal-user-guides/202212.0/products/products.md
Labels: ready for merge, new

#1744 Add sidebar_checker.sh
  .gitignore
  _scripts/sidebar_checker/run-sidebar-checker.md
  _scripts/sidebar_checker/sidebar_checker.sh
Labels: ready for merge, new

#1749 PBC-1333: Add DCC required fields column
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
Labels: ready for merge, updated

#1750 How to import big DBs
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/tutorials-and-howtos/howtos/howto-import-big-databases-between-environments.md
Labels: in TW review, new

#1759 CC-26219: adjusted MultiCartConfig.
  _includes/pbc/all/install-features/202304.0/install-the-multiple-carts-feature.md
Labels: ready for merge, updated

#1762 Update prepare-a-project-for-spryker-code-upgrader.md
  docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
Labels: small changes

#1774 Scheduled release notes
  .github/workflows/release.yml
Labels: small changes

#1773 Simple release notes file
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: small changes

#1778 changing the release drafter version
  .github/workflows/release-drafter.yml
Labels: small changes

#1779 adjust the release drafter workflow
  .github/workflows/release-drafter.yml
Labels: small changes

#881 Fixing search 404s for tech partners
  docs/scos/dev/technology-partner-guides/202108.0/product-information-pimerp/akeneo/akeneo-console-commands.md
Labels: updated

#1444 Adjusted storefront api explanation
  docs/scos/dev/architecture/conceptual-overview.md
Labels: small changes

#1782 changelog builder
  .github/configuration.yml
  .github/release-drafter.yml
  .github/workflows/build-changelog.yml
  .github/workflows/release-drafter.yml
Labels: small changes

#1784 Build changelog file
  .github/configuration.yml
  .github/workflows/build-changelog.yml
  docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-code-upgrader-to-a-azure-managed-project.md
Labels: new

#1785 Changelog configuration file fix
  .github/workflows/build-changelog.yml
Labels: updated

#1786 fixing syntax of the json file
  .github/workflows/build-changelog.yml
Labels: updated

#1553 APPS-5652: SPA dialogs
  docs/acp/user/app-manifest.md
Labels: in TW review, urgent, updated

#1475 APPS-5919: Module dependencies
  docs/acp/user/app-manifest.md
Labels: do not merge, updated

#1757 Sc 12322/switch demo shop version
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/updating-a-spryker-based-project.md
  docs/scos/dev/updating-spryker/analyzing-and-upgrading-projects-with-spryker-jarvis.md
  docs/scos/dev/updating-spryker/feature-or-module-updates.md
  docs/scos/dev/updating-spryker/installing-features-and-updating-modules.md
  docs/scos/dev/updating-spryker/plan-updates.md
  docs/scos/dev/updating-spryker/preventing-update-issues.md
  docs/scos/dev/updating-spryker/switch-demo-shop-version.md
  docs/scos/dev/updating-spryker/testing-updates.md
  docs/scos/dev/updating-spryker/troubleshooting-updates.md
  docs/scos/dev/updating-spryker/updating-spryker.md
Labels: new, updated

#1793 Update acp-overview.md
  docs/acp/user/intro-to-acp/acp-overview.md
Labels: small changes

#1768 Warehouse picking feature integration guides.
  _data/sidebars/pbc_all_sidebar.yml
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202304.0/install-the-cart-notes-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-order-management-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-order-management-inventory-management-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-packaging-units-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-spryker-core-back-office-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-warehouse-picking-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-warehouse-picking-inventory-management-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-warehouse-picking-order-management-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-warehouse-picking-product-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-warehouse-picking-shipment-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-warehouse-picking-spryker-core-back-office-feature.md
  docs/pbc/all/cart-and-checkout/202304.0/base-shop/install-and-upgrade/install-features/install-the-cart-notes-feature.md
  docs/pbc/all/cart-and-checkout/202304.0/base-shop/install-and-upgrade/install-features/install-the-cart-prices-feature.md
  docs/pbc/all/cart-and-checkout/202304.0/base-shop/install-and-upgrade/install-features/install-the-multiple-carts-feature.md
  docs/pbc/all/order-management-system/202304.0/install-and-update/install-features/install-the-order-management-feature.md
  docs/pbc/all/product-information-management/202304.0/install-and-upgrade/install-features/install-the-packaging-units-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/feature-integration-guides.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-warehouse-picking-inventory-management-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-warehouse-picking-order-management-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-warehouse-picking-product-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-warehouse-picking-shipment-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-warehouse-picking-spryker-core-back-office-feature.md
Labels: ready for merge, new, updated, 202306

#1781 Marketplace Return Management feature integration
  _includes/pbc/all/install-features/202304.0/marketplace/install-the-marketplace-return-management-feature.md
  _scripts/sidebar_checker/sidebar_checker.sh
  docs/pbc/all/return-management/202304.0/marketplace/install-and-upgrade/install-the-marketplace-return-management-feature.md
Labels: ready for merge, updated, 202306

#1747 docs: Getting started documentation
  _drafts/oryx/getting-started-with-oryx.md
Labels: new

#1795 Product + Category feature integration
  _includes/pbc/all/install-features/202304.0/install-the-product-category-feature.md
Labels: ready for merge, updated, 202306

#1770 Update connect-spryker-code-upgrader-to-a-github-managed-project.md
  docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-code-upgrader-to-a-github-managed-project.md
Labels: small changes

#1769 Update prepare-a-project-for-spryker-code-upgrader.md
  docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
Labels: small changes

#1789 How to create a route
  docs/scos/dev/glue-api-guides/202212.0/decoupled-glue-infrastructure/how-to-guides/routing/how-to-create-a-route.md
Labels: ready for merge, small changes

#1796 Security release notes 202304.0
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202304.0/security-release-notes-202304.0.md
Labels: ready for merge, new, 202306

#1800 Install the Shipment feature
  _includes/pbc/all/install-features/202304.0/install-the-shipment-feature.md
  docs/pbc/all/carrier-management/202204.0/base-shop/install-and-upgrade/install-features/install-the-shipment-feature.md
  docs/pbc/all/carrier-management/202212.0/base-shop/install-and-upgrade/install-features/install-the-shipment-feature.md
  docs/pbc/all/carrier-management/202304.0/base-shop/install-and-upgrade/install-the-shipment-feature.md
Labels: in TW review, updated, 202306

#1799 SDK-2342 Explain Releases vs Customization types
  docs/sdk/dev/releases-vs-customization-types.md
Labels: new

#1563 FRW-1442 Migration guide for Country, Currencty, Locale modules
  _includes/pbc/all/upgrade-modules/upgrade-the-country-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-currency-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-locale-module.md
  docs/pbc/all/price-management/202212.0/install-and-upgrade/upgrade-modules/upgrade-the-country-module.md
Labels: new, updated

#1810 Create GUI modules
  docs/pbc/all/merchant-management/202212.0/marketplace/tutorials-and-howtos/create-gui-modules.md
Labels: ready for merge, contributor, small changes

#1812 Revert "FRW-1442 Migration guide for Country, Currencty, Locale modules"
  _includes/pbc/all/upgrade-modules/upgrade-the-country-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-currency-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-locale-module.md
  docs/pbc/all/price-management/202212.0/install-and-upgrade/upgrade-modules/upgrade-the-country-module.md
Labels: new

#1811 Update releases-vs-customization-types.md
  docs/sdk/dev/releases-vs-customization-types.md
Labels: small changes
