Repository spryker/spryker-docs, pull requests merged in 2023-06, with the labels that each got.

#1605 CC-25819 Integration Guide for backoffice login brute force security issue
  _includes/pbc/all/install-features/202304.0/install-the-agent-assist-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-spryker-core-back-office-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-spryker-core-feature.md
  docs/marketplace/dev/feature-integration-guides/202304.0/marketplace-merchant-portal-core-feature-integration.md
  docs/pbc/all/identity-access-management/202304.0/install-and-upgrade/install-the-spryker-core-back-office-feature.md
  docs/pbc/all/user-management/202304.0/install-and-upgrade/install-the-agent-assist-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/spryker-core-feature-integration.md
Labels: ready for merge, updated, 202306

#1884 CC-28712 Introduce Shipment + Service Points IG
  _includes/pbc/all/install-features/202304.0/install-the-shipment-service-points-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-shipment-service-points-feature.md
Labels: ready for merge, new, 202306

#1889 Adjusting the docs release notes page
  docs/scos/user/intro-to-spryker/docs-release-notes.md
Labels: small changes

#1891 Update the format of Oryx diagrams
  _includes/diagrams/oryx/backend-integration.md
  _includes/diagrams/oryx/packages.md
  _includes/diagrams/oryx/reactivity-high-level.md
  _includes/diagrams/oryx/reactivity-interaction.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-packages.md
  docs/scos/dev/front-end-development/202212.0/oryx/reactivity/key-concepts-of-reactivity.md
  docs/scos/dev/front-end-development/202212.0/oryx/reactivity/oryx-integration-of-backend-apis.md
  docs/scos/dev/front-end-development/202212.0/oryx/reactivity/reactivity.md
Labels: updated

#1890 Update pbc.md
  docs/pbc/all/pbc.md
Labels: small changes

#1873 Install the Shipment feature
  _includes/pbc/all/install-features/202304.0/install-the-shipment-feature.md
Labels: ready for merge, updated, 202306

#1865 Add data import documents
  Rakefile
  docs/pbc/all/carrier-management/202304.0/base-shop/import-and-export-data/file-details-shipment-method-shipment-type.csv.md
  docs/pbc/all/carrier-management/202304.0/base-shop/import-and-export-data/file-details-shipment-type-store.csv.md
  docs/pbc/all/carrier-management/202304.0/base-shop/import-and-export-data/file-details-shipment-type.csv.md
Labels: ready for merge, new, 202306

#1854 Migration guide - Upgrade Node.js to v18 and npm to v9
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202304.0/migration-guide-upgrade-nodejs-to-v18-and-npm-to-v9.md
Labels: ready for merge, new, 202306

#1893 Update install-the-warehouse-picking-shipment-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-warehouse-picking-shipment-feature.md
Labels: small changes

#1896 Update environments-overview.md
  docs/cloud/dev/spryker-cloud-commerce-os/environments-overview.md
Labels: TW review needed, updated

#1877 Install the Service Points feature
  _includes/pbc/all/install-features/202304.0/install-the-service-points-feature.md
Labels: ready for merge, updated, 202306

#1876 CC-26804: Add an integration guide for product offer shipment type feature
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202304.0/install-the-product-offer-shipment-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-shipment-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-product-offer-shipment-feature.md
Labels: in tech review, 202306

#1885 Connecting a code repository
  docs/cloud/dev/spryker-cloud-commerce-os/connecting-a-code-repository.md
Labels: ready for merge, small changes

#1772 Install the Service Points feature
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202304.0/install-the-service-points-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-service-points-feature.md
Labels: ready for merge, new, 202306

#1907 Update multistore-setup-options.md
  docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/multistore-setup-options.md
Labels: ready for merge, small changes

#1902 SDK-2081: Add minimum technical requirements to the upgrader documentation
  docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
Labels: updated

#1901 Move MG to 202212.0 and add it to the sidebar
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202212.0/migration-guide-upgrade-nodejs-to-v18-and-npm-to-v9.md
Labels: ready for merge, small changes

#1905 Install the Service Points feature
  _includes/pbc/all/install-features/202304.0/install-the-service-points-feature.md
Labels: ready for merge, updated, 202306

#1909 Next steps for ACP guides
  docs/acp/user/app-composition-platform-installation.md
  docs/acp/user/intro-to-acp/acp-overview.md
  docs/pbc/all/payment-service-provider/202212.0/third-party-integrations/payone/integration-in-the-back-office/integrate-payone.md
  docs/pbc/all/payment-service-provider/202212.0/third-party-integrations/payone/integration-in-the-back-office/payone-integration-in-the-back-office.md
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/bazaarvoice.md
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
  docs/pbc/all/search/202212.0/third-party-integrations/algolia.md
  docs/pbc/all/search/202212.0/third-party-integrations/integrate-algolia.md
  docs/pbc/all/usercentrics/integrate-usercentrics.md
  docs/pbc/all/usercentrics/usercentrics.md
Labels: small changes

#1912 Update multistore-setup-options.md
  docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/multistore-setup-options.md
Labels: small changes

#1915 GTM adjustments
  _includes/head.html
  _layouts/default.html
Labels: small changes

#1908 Update environments-overview.md
  docs/cloud/dev/spryker-cloud-commerce-os/environments-overview.md
Labels: ready for merge, small changes

#1919 Update app-composition-platform-installation.md
  docs/acp/user/app-composition-platform-installation.md
  docs/acp/user/intro-to-acp/acp-overview.md
Labels: small changes

#1875 Introducing fixes to upgradability docs
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/guidelines/keeping-a-project-upgradable/extension-scenarios/event-subscribers-registration.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/extension-scenarios/extenstion-scenarios.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/extension-scenarios/modules-configuration.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/extension-scenarios/plugins-registration.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/keeping-a-project-upgradable.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/additional-logic-in-dependency-provider.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/dead-code-checker.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/minimum-allowed-shop-version.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/multidimensional-array.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/php-version.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/plugin-registration-with-restrintions.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/upgradability-guidelines.md
Labels: small changes

#1920 Create security-release-notes-template.md
  _templates/security-release-notes-template.md
Labels: TW review needed, small changes

#1861 Adding naming conventions for PRs
  .github/workflows/build-changelog.yml
  docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/multistore-setup-options.md
  docs/scos/dev/data-import/202212.0/data-import-categories/about-data-import-categories.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/edit-documentation-via-pull-requests.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/edit-the-documentation-locally.md
Labels: small changes

#1906 Install the Service Points feature
  _includes/pbc/all/install-features/202304.0/install-the-service-points-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-service-points-feature.md
Labels: ready for merge, updated

#1923 Add missing docs sidebar
  _data/sidebars/pbc_all_sidebar.yml
  _scripts/sidebar_checker/sidebar_checker.sh
  docs/pbc/all/back-office/202212.0/manage-in-the-back-office/view-dashboard.md
  docs/pbc/all/cart-and-checkout/202212.0/base-shop/install-and-upgrade/install-features/install-the-checkout-quotation-process-feature.md
  docs/pbc/all/content-management-system/202204.0/domain-model-and-relationships/product-sets-domain-model-and-relationships.md
  docs/pbc/all/content-management-system/202204.0/domain-model-and-relationships/product-sets-feature-domain-model-and-relationships.md
  docs/pbc/all/content-management-system/202212.0/domain-model-and-relationships/product-sets-feature-domain-model-and-relationships.md
Labels: ready for merge, small changes

#1913 Docs style guide
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/add-product-sections-to-the-documentation.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/general-rules-and-guidance-for-adding-new-documents.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/spryker-documentation-style-guide/examples.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/spryker-documentation-style-guide/spelling.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/spryker-documentation-style-guide/spryker-documentation-style-guide.md
Labels: new

#1926 Update scu_dev_sidebar.yml
  _data/sidebars/scu_dev_sidebar.yml
Labels: small changes

#1794 Adding a keyword for acp
  docs/acp/user/intro-to-acp/acp-overview.md
Labels: small changes

#1934 Adding explanation on number formatting
  docs/pbc/all/miscellaneous/202212.0/spryker-core-feature-overview/howto-add-support-for-number-formatting-in-the-storefront.md
Labels: small changes

#1929 Correct templates
  _templates/feature-integration-guide-template.md
  _templates/glue-api-storefront-guide-template.md
  _templates/howto-guide-template.md
  _templates/security-release-notes-template.md
  _templates/troubleshooting-guide-template.md
Labels: ready for merge, small changes

#1924 Install the Product Offer Shipment feature
  _includes/pbc/all/install-features/202304.0/install-the-product-offer-shipment-feature.md
  _includes/pbc/all/install-features/202304.0/marketplace/install-the-marketplace-product-offer-feature.md
  docs/pbc/all/offer-management/202304.0/marketplace/install-and-upgrade/marketplace-product-offer-feature-integration.md
Labels: ready for merge, updated, 202306

#1935 Install the Service Points feature, Install the Product offer shipment feature
  _includes/pbc/all/install-features/202304.0/install-the-product-offer-shipment-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-service-points-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-product-offer-shipment-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-service-points-feature.md
Labels: in TW review, updated, 202306

#1942 Add disclaimer about customer-owned and spryker-owned variables
  docs/cloud/dev/spryker-cloud-commerce-os/add-variables-in-the-parameter-store.md
Labels: in tech review, in TW review, small changes

#1948 Small corrections in security-release-notes-202306.0.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202306.0/security-release-notes-202306.0.md
Labels: small changes

#1950 Update cms-feature-overview.md
  docs/scos/user/features/202108.0/cms-feature-overview/cms-feature-overview.md
Labels: small changes

#1940 FRW-1610 Adjusted docs
  _includes/pbc/all/install-features/202304.0/install-glue-api/install-the-dynamic-store-glue-api.md
Labels: in tech review

#1953 Extend the list of GitHub permissions required for integration of the repository into BuddyCI
  docs/scu/dev/onboard-to-spryker-code-upgrader/connect-spryker-ci-to-a-github-managed-project.md
Labels: small changes

#1951 CC-28417: IG Missing BAPI Endpoints & Refactoring
  _includes/pbc/all/install-features/202304.0/install-the-push-notification-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-warehouse-picking-feature.md
Labels: updated, 202306

#1954 SDK-2600 profiler docs
  docs/scos/dev/technical-enhancement-integration-guides/Integrate-profiler-module.md
Labels: updated

#1947 Install the Approval Process feature
  _includes/pbc/all/install-features/202212.0/install-the-approval-process-feature.md
  docs/pbc/all/cart-and-checkout/202212.0/base-shop/approval-process-feature-overview.md
  docs/pbc/all/cart-and-checkout/202212.0/base-shop/install-and-upgrade/install-features/install-the-approval-process-feature.md
Labels: updated
