Repository spryker/spryker-docs, pull requests merged in 2023-09, with the labels that each got.

#2132 Updating the build changelog file
  .github/workflows/build-changelog.yml
Labels: small changes

#2104 Dynamic Data API guides
  docs/scos/dev/feature-integration-guides/202307.0/glue-api/dynamic-data-api/dynamic-data-api-integration.md
  docs/scos/dev/glue-api-guides/202307.0/dynamic-data-api/how-to-guides/how-to-configure-dynamic-data-api.md
Labels: in progress, in TW review, updated

#2133 Polishing the Early Access Release definition for DMS
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-availability-notification-feature.md
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-cart-feature.md
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-cms-feature.md
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-customer-account-management-feature.md
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-prices-feature.md
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-product-feature.md
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore.md
  _includes/pbc/all/install-features/202307.0/marketplace/install-the-marketplace-merchant-portal-core-dynamic-multistore.md
  _includes/pbc/all/install-glue-api/202307.0/install-the-dynamic-multistore-glue-api.md
  _includes/pbc/all/upgrade-modules/upgrade-the-country-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-currency-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-locale-module.md
  docs/pbc/all/dynamic-multistore/202307.0/base-shop/delete-stores.md
  docs/pbc/all/dynamic-multistore/202307.0/base-shop/dynamic-multistore-feature-overview.md
  docs/pbc/all/dynamic-multistore/202307.0/dynamic-multistore.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202307.0/release-notes-202307.0.md
Labels: small changes

#2128 Updates the getting-started guides to the latest product release
  docs/scos/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-macos-and-linux.md
  docs/scos/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-windows.md
  docs/scos/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-macos-and-linux.md
  docs/scos/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-windows.md
  docs/scos/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-macos-and-linux.md
  docs/scos/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-windows.md
Labels: updated

#2136 Doc release notes 08.2023
  _data/sidebars/scos_dev_sidebar.yml
  docs/pbc/all/dynamic-multistore/202307.0/base-shop/install-and-upgrade/install-features/install-dynamic-multistore-availability-notification-feature.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/npm-checker.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/spryker-security-checker.md
  docs/scos/user/intro-to-spryker/docs-release-notes.md
Labels: small changes

#2051 docs: document creating pages in Oryx
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202212.0/oryx/building-pages/oryx-compositions.md
  docs/scos/dev/front-end-development/202212.0/oryx/building-pages/oryx-pages.md
  docs/scos/dev/front-end-development/202212.0/oryx/building-pages/oryx-routing.md
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-feature-sets.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-pages/oryx-compositions.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-pages/oryx-pages.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-pages/oryx-routing.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-feature-sets.md
  docs/scos/user/intro-to-spryker/docs-release-notes.md
Labels: in TW review, new

#2140 Update security-release-notes-202306.0.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202306.0/security-release-notes-202306.0.md
Labels: updated

#2141 Adding details to a release notes item
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202307.0/release-notes-202307.0.md
Labels: small changes

#2144 Update dynamic data API to data exchange API
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/feature-integration-guides/202307.0/glue-api/dynamic-data-api/data-exchange-api-integration.md
  docs/scos/dev/glue-api-guides/202307.0/dynamic-data-api/how-to-guides/how-to-configure-data-exchange-api.md
  docs/scos/dev/glue-api-guides/202307.0/dynamic-data-api/how-to-guides/how-to-send-request-in-data-exchange-api.md
  docs/scos/user/intro-to-spryker/docs-release-notes.md
Labels: TW review needed, in TW review, small changes

#2149 Update run-the-evaluator-tool.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/run-the-evaluator-tool.md
Labels: small changes

#2135 Install the Product Offer Shipment Availability, Product Offer Service Points Availability, Product Offer + Service Points features
  _includes/pbc/all/install-features/202400.0/install-the-product-offer-service-points-availability-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-product-offer-service-points-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-product-offer-shipments-availability-feature.md
  docs/pbc/all/offer-management/202400.0/unified-commerce/install-and-upgrade/install-the-product-offer-service-points-feature.md
  docs/pbc/all/service-points/202400.0/unified-commerce/install-and-upgrade/install-the-product-offer-service-points-availability-feature.md
  docs/pbc/all/service-points/202400.0/unified-commerce/install-and-upgrade/install-the-product-offer-shipments-availability-feature.md
Labels: new, updated, 202400

#2160 Install the merchant relationship product lists Glue API
  _includes/pbc/all/install-features/202307.0/install-glue-api/install-the-merchant-relationship-product-lists-glue-api.md
  docs/pbc/all/cart-and-checkout/202307.0/base-shop/install-and-upgrade/install-glue-api/install-the-merchant-relationship-product-lists-glue-api.md
Labels: new

#2134 SDK-4410: Extend upgrader project preparation documentation page
  docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
Labels: in TW review, updated

#2158 PBC-2858: Updates channel names
  docs/pbc/all/ratings-reviews/202307.0/third-party-integrations/integrate-bazaarvoice.md
Labels: TW review needed, updated

#2162 Adding the feature IG to sidebar
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/merchant-management/202307.0/base-shop/install-and-upgrade/install-glue-api/install-the-merchant-relationship-product-lists-glue-api.md
  docs/pbc/all/search/202307.0/marketplace/glue-api-search-the-product-catalog.md
Labels: new

#2121 [PBC-2558] Update Algolia integration guide
  docs/pbc/all/search/202400.0/base-shop/third-party-integrations/integrate-algolia.md
Labels: updated

#2163 renaming the IGs
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202307.0/install-glue-api/install-the-catalog-merchant-product-restrictions.md
  docs/cloud/dev/spryker-cloud-commerce-os/multi-store-setups/checklist-for-a-new-store-implementation.md
  docs/pbc/all/merchant-management/202307.0/base-shop/install-and-upgrade/install-glue-api/install-the-merchant-relationship-product-lists-glue-api.md
  docs/pbc/all/search/202212.0/base-shop/third-party-integrations/algolia/algolia.md
  docs/pbc/all/search/202212.0/base-shop/third-party-integrations/algolia/configure-algolia.md
  docs/pbc/all/search/202212.0/base-shop/third-party-integrations/algolia/disconnect-algolia.md
  docs/pbc/all/search/202212.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
  docs/pbc/all/search/202307.0/base-shop/install-and-upgrade/install-features-and-glue-api/install-the-catalog-merchant-product-restrictions-feature.md
  docs/pbc/all/search/202307.0/base-shop/third-party-integrations/algolia/algolia.md
  docs/pbc/all/search/202307.0/base-shop/third-party-integrations/algolia/configure-algolia.md
  docs/pbc/all/search/202307.0/base-shop/third-party-integrations/algolia/disconnect-algolia.md
  docs/pbc/all/search/202307.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
  docs/pbc/all/search/202307.0/marketplace/glue-api-search-the-product-catalog.md
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/decoupled-glue-infrastructure/glue-api-authentication-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/decoupled-glue-infrastructure/glue-api-authorization-protected-endpoints-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/decoupled-glue-infrastructure/glue-api-authorization-scopes-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/decoupled-glue-infrastructure/glue-api-documentation-generation.md
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/decoupled-glue-infrastructure/glue-api-glue-storefront-and-backend-api-applications-integration.md
  docs/scos/dev/feature-integration-guides/202204.0/glue-api/decoupled-glue-infrastructure/glue-api-json-api-convention-integration.md
  docs/scos/dev/feature-integration-guides/202307.0/glue-api/dynamic-data-api/data-exchange-api-integration.md
  docs/scos/dev/glue-api-guides/202307.0/dynamic-data-api/how-to-guides/how-to-configure-data-exchange-api.md
  docs/scos/dev/glue-api-guides/202307.0/dynamic-data-api/how-to-guides/how-to-send-request-in-data-exchange-api.md
  docs/scos/dev/migration-concepts/migrate-to-decoupled-glue-infrastructure/decoupled-glue-infrastructure-integrate-storefront-and-backend-glue-api-applications.md
  docs/scos/dev/migration-concepts/migrate-to-decoupled-glue-infrastructure/decoupled-glue-infrastructure-integrate-the-documentation-generator.md
  docs/scos/dev/migration-concepts/migrate-to-decoupled-glue-infrastructure/decoupled-glue-infrastructure-integrate-the-protected-endpoints-authorization.md
  docs/scos/user/intro-to-spryker/docs-release-notes.md
Labels: new

#2118 CC-26541 Adjusted IGs according changes related to code api conventions refactoring
  _includes/pbc/all/install-features/202400.0/install-the-cart-notes-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-order-management-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-packaging-units-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-product-offer-service-points-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-push-notification-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-service-points-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-warehouse-user-management-feature.md
Labels: TW review needed, updated, 202400

#2175 Fix typo in the packaging units feature IG
  _includes/pbc/all/install-features/202400.0/install-the-packaging-units-feature.md
Labels: small changes

#2161 Install the Push Notification feature
  _includes/pbc/all/install-features/202400.0/install-the-push-notification-feature.md
Labels: TW review needed, updated, 202400

#2159 SDK-2432. Added container-set-function.md
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/additional-logic-in-dependency-provider.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/container-set-function.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/dead-code-checker.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/minimum-allowed-shop-version.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/multidimensional-array.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/npm-checker.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/open-source-vulnerabilities.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/php-version.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/plugin-registration-with-restrintions.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/single-plugin-argument.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/spryker-security-checker.md
Labels: new

#2164 Update howto-reduce-jenkins-execution-costs-without-refactoring.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-reduce-jenkins-execution-costs-without-refactoring.md
Labels: tech review needed, updated

#2181 Update howto-import-big-databases-between-environments.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-import-big-databases-between-environments.md
Labels: tech review needed, updated

#2047 docs: remove Oryx builder overview and setup docs
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202212.0/zed/oryx-builder-overview-and-setup.md
  docs/scos/dev/front-end-development/202212.0/zed/oryx-for-zed.md
  docs/scos/dev/front-end-development/202212.0/zed/zed.md
  docs/scos/dev/front-end-development/202307.0/zed/oryx-builder-overview-and-setup.md
  docs/scos/dev/front-end-development/202307.0/zed/oryx-for-zed.md
  docs/scos/dev/front-end-development/202307.0/zed/zed.md
Labels: updated

#2183 Update howto-import-big-databases-between-environments.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-import-big-databases-between-environments.md
Labels: updated

#2169 CC-31033 Adjusted FA related IGs before the release of stable versions
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202400.0/install-the-cart-notes-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-inventory-management-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-order-management-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-order-management-inventory-management-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-packaging-units-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-picker-user-login-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-push-notification-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-shipment-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-warehouse-picking-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-warehouse-picking-inventory-management-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-warehouse-picking-order-management-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-warehouse-picking-product-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-warehouse-picking-shipment-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-warehouse-picking-spryker-core-back-office-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-warehouse-user-management-feature.md
  docs/pbc/all/warehouse-management-system/202400.0/unified-commerce/install-and-upgrade/install-the-order-management-inventory-management-feature.md
  docs/pbc/all/warehouse-picking/202400.0/unified-commerce/install-and-upgrade/install-the-picker-user-login-feature.md
  docs/pbc/all/warehouse-picking/202400.0/unified-commerce/install-and-upgrade/install-the-warehouse-picking-inventory-management-feature.md
  docs/pbc/all/warehouse-picking/202400.0/unified-commerce/install-and-upgrade/install-the-warehouse-picking-order-management-feature.md
  docs/pbc/all/warehouse-picking/202400.0/unified-commerce/install-and-upgrade/install-the-warehouse-picking-shipment-feature.md
  docs/pbc/all/warehouse-picking/202400.0/unified-commerce/install-and-upgrade/install-the-warehouse-picking-spryker-core-back-office-feature.md
  docs/scos/user/intro-to-spryker/docs-release-notes.md
Labels: tech review needed, updated, 202400

#2189 Upadating the video for Algolia
  docs/pbc/all/search/202307.0/base-shop/third-party-integrations/algolia/algolia.md
Labels: small changes

#2152 PBC-2693: Update vertex integration guide.
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/tax-management/202307.0/base-shop/avalara/apply-avalara-tax-codes.md
  docs/pbc/all/tax-management/202307.0/base-shop/avalara/avalara.md
  docs/pbc/all/tax-management/202307.0/base-shop/avalara/install-avalara-product-options.md
  docs/pbc/all/tax-management/202307.0/base-shop/avalara/install-avalara-shipment.md
  docs/pbc/all/tax-management/202307.0/base-shop/avalara/install-avalara.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/domain-model-and-relationships/tax-domain-model-and-relationships.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/extend-and-customize/tax-module-reference-information.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/import-and-export-data/import-file-details-product-abstract.csv.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/import-and-export-data/import-file-details-product-option.csv.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/import-and-export-data/import-file-details-shipment.csv.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/import-and-export-data/import-file-details-tax-sets.csv.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/import-and-export-data/tax-management-data-import.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/install-and-upgrade/install-the-product-tax-sets-glue-api.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/install-and-upgrade/install-the-tax-glue-api.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/install-and-upgrade/upgrade-the-producttaxsetsrestapi-module.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/install-and-upgrade/upgrade-the-tax-module.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/manage-in-the-back-office/create-tax-rates.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/manage-in-the-back-office/create-tax-sets.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/manage-in-the-back-office/edit-tax-rates.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/manage-in-the-back-office/edit-tax-sets.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/manage-in-the-back-office/log-into-the-back-office.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/manage-using-glue-api/retrieve-tax-sets-when-retrieving-abstract-products.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/manage-using-glue-api/retrieve-tax-sets.md
  docs/pbc/all/tax-management/202307.0/base-shop/spryker-tax/tax-feature-overview.md
  docs/pbc/all/tax-management/202307.0/marketplace/install-the-tax-merchant-portal-marketplace-product-feature.md
  docs/pbc/all/tax-management/202307.0/tax-management.md
  docs/pbc/all/tax-management/202400.0/base-shop/vertex/install-vertex.md
  docs/pbc/all/tax-management/202400.0/base-shop/vertex/vertex.md
  docs/pbc/all/tax-management/202400.0/tax-management.md
  docs/scos/user/intro-to-spryker/docs-release-notes.md
Labels: TW review needed, updated

#2112 Dynamic Multistore
  CODEOWNERS
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-availability-notification-feature.md
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-cart-feature.md
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-cms-feature.md
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-customer-account-management-feature.md
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-prices-feature.md
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore-the-product-feature.md
  _includes/pbc/all/install-features/202307.0/install-dynamic-multistore.md
  docs/pbc/all/dynamic-multistore/202307.0/base-shop/delete-stores.md
  docs/pbc/all/dynamic-multistore/202307.0/base-shop/dynamic-multistore-feature-overview.md
Labels: new

#2190 Redirects generator v1
  _scripts/redirects_generator/redirect_from_generator.sh
  _scripts/redirects_generator/redirects_generator.sh
  docs/scos/dev/guidelines/coding-guidelines/coding-guidelines.md
  docs/scos/dev/guidelines/guidelines.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/extension-scenarios/extenstion-scenarios.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/keeping-a-project-upgradable.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/run-the-evaluator-tool.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/additional-logic-in-dependency-provider.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/dead-code-checker.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/minimum-allowed-shop-version.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/multidimensional-array.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/npm-checker.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/open-source-vulnerabilities.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/php-version.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/plugin-registration-with-restrintions.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/single-plugin-argument.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/upgradability-guidelines.md
  docs/scos/dev/guidelines/performance-guidelines/architecture-performance-guidelines.md
  docs/scos/dev/guidelines/performance-guidelines/elastic-computing/ram-aware-batch-processing.md
  docs/scos/dev/guidelines/performance-guidelines/elastic-computing/storage-caching-for-primary-replica-db-setups.md
  docs/scos/dev/guidelines/performance-guidelines/performance-guidelines.md
  docs/scos/dev/guidelines/testing-guidelines/testing-console-commands.md
  docs/scos/dev/guidelines/testing-guidelines/testing-guidelines.md
Labels: new

#2179 SDK-2568: Evaluator configuration file docs
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/guidelines/keeping-a-project-upgradable/ignore-evaluation-errors.md
Labels: TW review needed, new

#2191 Removing the punchout docs
  Rakefile
  _config.yml
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202212.0/install-the-product-bundles-feature.md
  _includes/pbc/all/install-features/202307.0/install-the-product-bundles-feature.md
  docs/pbc/all/pbc.md
  docs/pbc/all/punchout/202307.0/install-features/install-the-eco-punchout-catalogs-feature.md
  docs/pbc/all/punchout/202307.0/install-features/install-the-eco-punchout-catalogs-product-bundles-feature.md
  docs/pbc/all/punchout/202307.0/install-features/install-the-punchout-catalog-feature.md
  docs/pbc/all/punchout/202307.0/manage-in-the-back-office/log-into-the-back-office.md
  docs/pbc/all/punchout/202307.0/manage-in-the-back-office/manage-punch-out-connections.md
  docs/pbc/all/punchout/202307.0/manage-in-the-back-office/manage-transactions-log.md
  docs/pbc/all/punchout/202307.0/punchout-catalogs-overview.md
  docs/pbc/all/punchout/202307.0/punchout-catalogs.md
  docs/pbc/all/search/202400.0/base-shop/third-party-integrations/integrate-algolia.md
  docs/pbc/all/tax-management/202400.0/base-shop/vertex/install-vertex.md
Labels: small changes

#2101 Update CORS configurations
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202212.0/install-glue-api/install-the-spryker-core-glue-api.md
  docs/scos/dev/tutorials-and-howtos/howtos/glue-api-howtos/configure-cross-origin-resource-sharing-for-glue-api.md
  docs/scos/dev/tutorials-and-howtos/howtos/glue-api-howtos/configuring-glue-for-cross-origin-requests.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/spryker-documentation-style-guide/word-list.md
Labels: new, updated

#2192 Removing punchout
  _data/sidebars/scos_dev_sidebar.yml
  _data/sidebars/scos_user_sidebar.yml
  _includes/pbc/all/install-features/202204.0/install-the-product-bundles-feature.md
  docs/acp/user/intro-to-acp/acp-overview.md
  docs/pbc/all/customer-relationship-management/202212.0/base-shop/domain-model-and-relationships/customer-login-by-token-reference-information.md
  docs/pbc/all/customer-relationship-management/202307.0/base-shop/domain-model-and-relationships/customer-login-by-token-reference-information.md
  docs/pbc/all/punchout/202212.0/install-features/install-the-eco-punchout-catalogs-feature.md
  docs/pbc/all/punchout/202212.0/install-features/install-the-eco-punchout-catalogs-product-bundles-feature.md
  docs/pbc/all/punchout/202212.0/install-features/install-the-punchout-catalog-feature.md
  docs/pbc/all/punchout/202212.0/manage-in-the-back-office/log-into-the-back-office.md
  docs/pbc/all/punchout/202212.0/manage-in-the-back-office/manage-punch-out-connections.md
  docs/pbc/all/punchout/202212.0/manage-in-the-back-office/manage-transactions-log.md
  docs/pbc/all/punchout/202212.0/punchout-catalogs-overview.md
  docs/pbc/all/punchout/202212.0/punchout-catalogs.md
  docs/pbc/all/search/202307.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
  docs/pbc/all/tax-management/202400.0/base-shop/vertex/install-vertex.md
  docs/scos/dev/feature-walkthroughs/202204.0/company-account-feature-walkthrough/customer-login-by-token-reference-information.md
  docs/scos/dev/technology-partner-guides/202204.0/order-management-erpoms/punchout-catalogs/eco-punchout-catalogs-feature-integration.md
  docs/scos/dev/technology-partner-guides/202204.0/order-management-erpoms/punchout-catalogs/eco-punchout-catalogs-product-bundles-feature-integration.md
  docs/scos/dev/technology-partner-guides/202204.0/order-management-erpoms/punchout-catalogs/punchout-catalog-feature-integration.md
  docs/scos/user/back-office-user-guides/202204.0/punch-out/managing-punch-out-connections.md
  docs/scos/user/back-office-user-guides/202204.0/punch-out/managing-transactions-log.md
  docs/scos/user/technology-partners/202204.0/order-management-erpoms/punchout-catalogs/punchout-catalogs-overview.md
  docs/scos/user/technology-partners/202204.0/order-management-erpoms/punchout-catalogs/punchout-catalogs.md
  docs/scos/user/technology-partners/202204.0/technology-partners.md
Labels: small changes

#2197 Algolia video fix
  docs/pbc/all/search/202307.0/base-shop/third-party-integrations/algolia/algolia.md
Labels: small changes

#1604 Fixing the diagram
  docs/scos/dev/feature-walkthroughs/202204.0/order-management-feature-walkthrough/sales-module-reference-information.md
Labels: tech review needed, small changes

#2200 SDK-4885: Fixed link that for GitHab
  docs/scu/dev/run-spryker-code-upgrader.md
Labels: updated

#2194 Fix titles
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202307.0/marketplace/extend-the-merchant-portal-frontend.md
Labels: TW review needed, small changes

#2198 SDK-2359 spryker dev packages checker docs
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/spryker-dev-packages-checker.md
Labels: new

#2108 FRW-2211: UI Data Exchange API Configuration.
  _data/sidebars/scos_dev_sidebar.yml
  _scripts/sidebar_checker/excludelist.yml
  docs/scos/dev/feature-integration-guides/202307.0/glue-api/data-exchange-api/install-the-data-exchange-api.md
  docs/scos/dev/glue-api-guides/202212.0/old-glue-infrastructure/glue-infrastructure.md
  docs/scos/dev/glue-api-guides/202307.0/data-exchange-api/how-to-guides/how-to-configure-data-exchange-api.md
  docs/scos/dev/glue-api-guides/202307.0/data-exchange-api/how-to-guides/how-to-send-request-in-data-exchange-api.md
  docs/scos/dev/glue-api-guides/202307.0/old-glue-infrastructure/glue-infrastructure.md
  docs/scos/user/intro-to-spryker/docs-release-notes.md
Labels: in TW review, updated

#2199 PBC-3053: Update Vertex integration guide.
  docs/pbc/all/tax-management/202400.0/base-shop/vertex/install-vertex.md
Labels: ready for merge, 202400

#2206 Update best-practises-jenkins-stability.md
  docs/cloud/dev/spryker-cloud-commerce-os/best-practices/best-practises-jenkins-stability.md
Labels: TW review needed, updated
