Repository spryker/spryker-docs, pull requests merged in 2023-01, with the labels that each got.

#1498 How DependencyHelper works and how to use it
  docs/scos/dev/guidelines/testing-guidelines/available-test-helpers.md
Labels: ready for merge

#1509 added proper line breaks
  docs/scos/dev/guidelines/testing-guidelines/available-test-helpers.md
Labels: ready for merge

#1442 Integration guides review
  _includes/pbc/all/install-features/202204.0/enable-gift-cards.md
  _includes/pbc/all/install-features/202204.0/enable-the-content-widget.md
  _includes/pbc/all/install-features/202204.0/feature-integration-guides.md
  _includes/pbc/all/install-features/202204.0/install-glue-api/install-the-promotions-and-discounts-glue-api.md
  _includes/pbc/all/install-features/202204.0/install-microsoft-azure-active-directory.md
  _includes/pbc/all/install-features/202204.0/install-multiple-abstract-products-as-promotional-products-and-discounts-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-acl-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-agent-assist-cart-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-agent-assist-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-agent-assist-shopping-list-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-alternative-products-discontinued-products-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-alternative-products-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-alternative-products-inventory-management-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-alternative-products-product-label-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-alternative-products-wishlist-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-approval-process-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-availability-notification-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-cart-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-cart-non-splittable-products-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-catalog-category-management-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-catalog-order-management-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-category-filters-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-category-image-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-category-management-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-category-management-promotions-and-discounts-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-checkout-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-checkout-quotation-process-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-checkout-workflow.md
  _includes/pbc/all/install-features/202204.0/install-the-cms-catalog-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-cms-category-management-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-cms-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-cms-product-lists-catalog-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-comments-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-comments-order-management-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-comments-persistent-cart-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-company-account-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-company-account-order-management-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-configurable-bundle-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-product-bundles-cart-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-splittable-order-items-feature.md
  docs/scos/dev/feature-integration-guides/202108.0/cart-integration.md
Labels: in progress

#1510 Add landing pages to 202212 0
  docs/scos/dev/glue-api-guides/202212.0/managing-b2b-account/managing-b2b-account.md
  docs/scos/dev/glue-api-guides/202212.0/managing-products/managing-products.md
Labels: ready for merge

#1483 Contributor:Fixed some typos and redundant sentences
  _data/sidebars/scos_dev_sidebar.yml
  _drafts/run-the-upgrader-tool.md
  _drafts/upgrader-tool-overview.md
  docs/pbc/all/price-management/202212.0/import-and-export-data/file-details-product-price.csv.md
  docs/pbc/all/warehouse-management-system/202212.0/import-and-export-data/file-details-product-stock.csv.md
  docs/scos/dev/front-end-development/yves/atomic-frontend/atomic-front-end-general-overview.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/define-customs-prefixes-for-core-entity-names.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/define-evaluation-rules-to-ignore.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/keeping-a-project-upgradable.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/run-the-evaluator-tool.md
Labels: ready for merge, contributor

#1515 Add Angular modules to the upcoming major release list.
  docs/scos/user/intro-to-spryker/whats-new/upcoming-major-module-releases.md
Labels: in TW review

#1504 Update how-to-create-a-new-merchant-oms-flow.md
  docs/marketplace/dev/howtos/how-to-create-a-new-merchant-oms-flow.md
Labels: ready for merge

#1495 Update scos_dev_sidebar.yml
  _data/sidebars/scos_dev_sidebar.yml
Labels: TW review needed

#1494 Update scos_dev_sidebar.yml
  _data/sidebars/scos_dev_sidebar.yml
Labels: TW review needed

#1513 New how-to
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/tutorials-and-howtos/howtos/feature-howtos/howto-create-a-custom-discount-calculator.md
Labels: ready for merge

#1488 Add frntend dev sub landing pages
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/index.md
  docs/scos/dev/front-end-development/yves/yves.md
  docs/scos/dev/front-end-development/zed/zed.md
Labels: tech review needed

#1524 Added recommendation to double check for passwords
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: ready for merge

#1530 Split into 8/4 weeks
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: ready for merge

#1455 Apps 5982 schema tags used for bazaarvoice pbc
  docs/pbc/all/ratings-reviews/202204.0/third-party-integrations/integrate-bazaarvoice.md
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
Labels: in TW review

#1522 fix(mp): use Angular Modules wording in howto page
  _data/sidebars/marketplace_dev_sidebar.yml
  docs/marketplace/dev/front-end/202108.0/web-components.md
  docs/marketplace/dev/front-end/202204.0/web-components.md
  docs/marketplace/dev/front-end/202212.0/web-components.md
  docs/marketplace/dev/howtos/how-to-create-a-new-angular-module-with-application.md
  docs/marketplace/dev/howtos/how-to-create-a-new-module-with-application.md
Labels: ready for merge

#1525 Add landing pages
  _data/sidebars/marketplace_dev_sidebar.yml
  _data/sidebars/sdk_dev_sidebar.yml
  docs/marketplace/dev/architecture-overview/index.md
  docs/marketplace/dev/feature-integration-guides/202212.0/glue/glue.md
  docs/marketplace/dev/feature-integration-guides/202212.0/index.md
  docs/marketplace/dev/feature-walkthroughs/202212.0/index.md
  docs/marketplace/dev/feature-walkthroughs/202212.0/merchant-portal-feature-walkthrough.md
  docs/marketplace/dev/front-end/202212.0/index.md
  docs/marketplace/dev/glue-api-guides/202212.0/carts-of-registered-users/carts-of-registered-users.md
  docs/marketplace/dev/glue-api-guides/202212.0/concrete-products/concrete-products.md
  docs/marketplace/dev/glue-api-guides/202212.0/guest-carts/guest-carts.md
  docs/marketplace/dev/glue-api-guides/202212.0/index.md
  docs/marketplace/dev/glue-api-guides/202212.0/merchants/merchants.md
  docs/marketplace/dev/glue-api-guides/202212.0/product-offers/product-offers.md
  docs/marketplace/dev/glue-api-guides/202212.0/shopping-lists/marketplace-shopping-lists.md
  docs/marketplace/dev/glue-api-guides/202212.0/wishlists/wishlists.md
  docs/marketplace/dev/howtos/index.md
  docs/marketplace/dev/setup/202212.0/index.md
  docs/marketplace/dev/technical-enhancement/202212.0/index.md
  docs/sdk/dev/development-tools/index.md
Labels: TW review needed

#1544 Update scos-supported-browsers.md
  docs/scos/dev/system-requirements/202212.0/scos-supported-browsers.md
Labels: ready for merge

#1541 Fix spryk usage commands
  docs/sdk/dev/spryks/spryks.md
Labels: ready for merge

#1542 Changed DNS Setup recommendations
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: ready for merge

#1552 fixed typos in import document
  docs/scos/dev/data-import/202108.0/importing-data-with-the-queue-data-importer.md
  docs/scos/dev/data-import/202204.0/importing-data-with-the-queue-data-importer.md
  docs/scos/dev/data-import/202212.0/importing-data-with-the-queue-data-importer.md
  docs/scos/dev/tutorials-and-howtos/advanced-tutorials/tutorial-replacing-a-default-data-importer-with-the-queue-data-importer.md
Labels: ready for merge, contributor

#1549 remove old information
  docs/scos/dev/technology-partner-guides/202212.0/operational-tools-monitoring-legal-etc/new-relic/configuring-new-relic-logging.md
Labels: ready for merge

#1547 Fix new relic installation guide
  docs/scos/dev/technical-enhancement-integration-guides/integrate-elastic-computing.md
Labels: ready for merge

#1523 fixed table and added link to feature installation
  docs/pbc/all/content-management-system/202204.0/manage-in-the-back-office/blocks/create-email-cms-blocks.md
Labels: ready for merge

#1220 API request fails with an exception `Session has not been set`
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/api-request-fails-with-the-exception-session-has-not-been-set.md
Labels: ready for merge

#1546 Contributor:Fix missing project namespace
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-architectural-walkthrough-spryker-commerce-os.md
Labels: ready for merge, contributor

#1551 fixed doc
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/upgrade-modules/upgrade-the-monitoring-module.md
  docs/pbc/all/content-management-system/202204.0/manage-in-the-back-office/blocks/create-email-cms-blocks.md
  docs/scos/dev/technical-enhancement-integration-guides/integrate-elastic-computing.md
  docs/scos/dev/technology-partner-guides/202212.0/operational-tools-monitoring-legal-etc/new-relic/configuring-new-relic-logging.md
  docs/scos/dev/the-docker-sdk/202212.0/configure-services.md
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/api-request-fails-with-the-exception-session-has-not-been-set.md
Labels: ready for merge

#1476 CC-21664 Migration guide - Upgrade to Webpack v5
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/migration-guide-upgrade-to-webpack-v5.md
Labels: ready for merge

#1482 CC-21664 Migration guide - Upgrade to Angular v15.
  Rakefile
  _config.yml
  _data/sidebars/marketplace_dev_sidebar.yml
  docs/marketplace/dev/technical-enhancement/202304.0/migration-guide-upgrade-to-angular-v15.md
Labels: ready for merge

#1545 Update modules-and-layers.md
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/architecture/conceptual-overview.md
  docs/scos/dev/architecture/modules-and-application-layers.md
  docs/scos/dev/architecture/programming-concepts.md
  docs/scos/dev/developer-getting-started-guide.md
Labels: ready for merge

#1512 CC-21931 Integration guide for Warehouse User epic
  _includes/pbc/all/install-features/202304.0/install-the-spryker-core-back-office-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-spryker-core-back-office-warehouse-user-management-feature.md
  _includes/pbc/all/install-features/202304.0/install-warehouse-user-management-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-warehouse-user-management-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/spryker-core-back-office-feature-integration.md
  docs/scos/dev/feature-integration-guides/202304.0/spryker-core-back-office-warehouse-user-management-feature-integration.md
Labels: ready for merge

#1278 correct ngrok command
  docs/scos/dev/tutorials-and-howtos/howtos/howto-debug-payment-integrations-locally.md
Labels: ready for merge

#1557 Add redirects for 404s
  _data/sidebars/scos_dev_sidebar.yml
  docs/marketplace/user/intro-to-spryker-marketplace/intro-to-spryker-marketplace.md
  docs/pbc/all/cart-and-checkout/202212.0/manage-using-glue-api/manage-carts-of-registered-users/manage-carts-of-registered-users.md
  docs/pbc/all/content-management-system/202204.0/manage-in-the-back-office/pages/create-cms-pages.md
  docs/pbc/all/content-management-system/202212.0/tutorials-and-howtos/howto-create-cms-templates.md
  docs/pbc/all/emails/202212.0/howto-create-and-register-a-mail-provider.md
  docs/pbc/all/emails/202212.0/tutorial-sending-an-email.md
  docs/pbc/all/identity-access-management/202212.0/manage-using-glue-api/glue-api-authentication-and-authorization.md
  docs/pbc/all/identity-access-management/202212.0/manage-using-glue-api/glue-api-security-and-authentication.md
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
  docs/scos/dev/developer-getting-started-guide.md
  docs/scos/dev/front-end-development/zed/oryx-for-zed.md
  docs/scos/dev/glue-api-guides/202204.0/glue-api-tutorials/implement-versioning-for-rest-api-resources.md
  docs/scos/user/intro-to-spryker/roadmap.md
Labels: ready for merge

#1566 APPS:6120 updated module dependencies with new versions
  docs/pbc/all/payment-service-providers/payone/payone.md
  docs/pbc/all/ratings-reviews/202204.0/third-party-integrations/integrate-bazaarvoice.md
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
  docs/pbc/all/usercentrics/integrate-usercentrics.md
Labels: in TW review

#1564 Add redirects 404 continued
  docs/cloud/dev/spryker-cloud-commerce-os/configure-deployment-pipelines/configuring-github-actions.md
  docs/pbc/all/carrier-management/202212.0/install-and-upgrade/integrate-the-shipment-glue-api.md
  docs/pbc/all/cart-and-checkout/202212.0/extend-and-customize/cart-module-reference-information.md
  docs/pbc/all/cart-and-checkout/202212.0/extend-and-customize/checkout-steps.md
  docs/pbc/all/discount-management/202212.0/discount-management.md
  docs/pbc/all/identity-access-management/202212.0/log-into-the-back-office.md
  docs/pbc/all/identity-access-management/202212.0/manage-using-glue-api/glue-api-authenticate-as-a-customer.md
  docs/pbc/all/identity-access-management/202212.0/manage-using-glue-api/glue-api-delete-expired-refresh-tokens.md
  docs/pbc/all/price-management/202212.0/extend-and-customize/configuration-of-price-modes-and-types.md
  docs/pbc/all/product-information-management/202212.0/install-and-upgrade/install-features/install-the-product-bundles-return-management-feature.md
  docs/pbc/all/product-information-management/202212.0/install-and-upgrade/install-features/install-the-product-configuration-feature.md
  docs/pbc/all/product-information-management/202212.0/third-party-integrations/akeneo/install-and-configure-akeneo.md
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/configure-bazaarvoice.md
  docs/pbc/all/request-for-quote/202212.0/request-for-quote.md
  docs/pbc/all/return-management/202212.0/howto-set-number-of-days-for-a-return-policy.md
  docs/pbc/all/tax-management/202212.0/third-party-integrations/integrate-avalara.md
  docs/pbc/all/user-management/202212.0/agent-assist-feature-overview.md
  docs/scos/dev/developer-getting-started-guide.md
  docs/scos/dev/glue-api-guides/202108.0/managing-customers/managing-customer-authentication-tokens-via-oauth-2.0.md
  docs/scos/dev/glue-api-guides/202212.0/decoupled-glue-infrastructure/security-and-authentication.md
  docs/scos/dev/setup/installing-spryker-with-docker/configuration/setting-up-a-self-signed-ssl-certificate.md
  docs/scos/dev/setup/installing-spryker-with-docker/installing-spryker-with-docker.md
  docs/scos/dev/tutorials-and-howtos/introduction-tutorials/tutorial-architectural-walkthrough-spryker-commerce-os.md
  docs/scos/user/features/202108.0/mailing-and-notifications-feature-overview.md
  docs/scos/user/technology-partners/202212.0/payment-partners/heidelpay.md
Labels: ready for merge

#1533 Landing pages marketplace users
  _data/sidebars/marketplace_user_sidebar.yml
  docs/marketplace/user/back-office-user-guides/202212.0/catalog/catalog.md
  docs/marketplace/user/back-office-user-guides/202212.0/catalog/product-options/product-options.md
  docs/marketplace/user/back-office-user-guides/202212.0/catalog/products/abstract-products/abstract-products.md
  docs/marketplace/user/back-office-user-guides/202212.0/catalog/products/products.md
  docs/marketplace/user/back-office-user-guides/202212.0/index.md
  docs/marketplace/user/back-office-user-guides/202212.0/marketplace/marketplace.md
  docs/marketplace/user/back-office-user-guides/202212.0/marketplace/merchants/merchants.md
  docs/marketplace/user/back-office-user-guides/202212.0/sales/sales.md
Labels: in TW review
