Repository spryker/spryker-docs, pull requests merged in 2023-03, with the labels that each got.

#1634 CC-25813: Tech Debt for AclMerchantPortal module.
  docs/marketplace/dev/feature-integration-guides/202304.0/marketplace-merchant-portal-core-feature-integration.md
Labels: ready for merge

#1630 SDK-1915: SDK docs updates
  docs/sdk/dev/spryker-sdk.md
Labels: TW review needed

#1644 Corrected CNAME record information
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: ready for merge

#1289 [APPS-5459] Update manifest public doc
  docs/acp/user/app-manifest.md
Labels: ready for merge

#1611 explain versioning in the path
  docs/scos/dev/glue-api-guides/202212.0/glue-api-tutorials/implement-versioning-for-rest-api-resources.md
Labels: ready for merge

#1641 Updating BazaarVoice integrate and configure docs
  docs/pbc/all/ratings-reviews/202204.0/third-party-integrations/integrate-bazaarvoice.md
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/bazaarvoice.md
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/configure-bazaarvoice.md
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
Labels: ready for merge

#1648 СС-25813: Renamed plugins after AA review.
  docs/marketplace/dev/feature-integration-guides/202304.0/marketplace-merchant-portal-core-feature-integration.md
Labels: ready for merge

#1621 Documentation improvement for Algolia v1.1.0
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
  docs/pbc/all/search/202212.0/third-party-integrations/algolia.md
  docs/pbc/all/search/202212.0/third-party-integrations/configure-algolia.md
  docs/pbc/all/search/202212.0/third-party-integrations/disconnect-algolia.md
  docs/pbc/all/search/202212.0/third-party-integrations/integrate-algolia.md
Labels: in TW review

#1609 CC-20611: Warehouse picking feature integration guide.
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202304.0/install-the-shipment-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-warehouse-picking-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-warehouse-user-management-feature.md
  docs/pbc/all/carrier-management/202304.0/install-and-upgrade/install-the-shipment-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-warehouse-picking-feature.md
Labels: ready for merge

#1663 Included warning about coordination required for additional endpoints
  docs/scos/dev/technical-enhancement-integration-guides/integrating-separate-endpoint-bootstraps.md
Labels: TW review needed

#1654 Fixed type in the links
  docs/pbc/all/customer-relationship-management/202212.0/reorder-feature-overview.md
Labels: ready for merge

#1657 fix scos_dev_sidebar
  _data/sidebars/scos_dev_sidebar.yml
  _data/sidebars/scos_user_sidebar.yml
  _includes/pbc/all/install-features/202304.0/install-the-push-notification-feature.md
  docs/pbc/all/customer-relationship-management/202212.0/install-and-upgrade/install-features/install-the-customer-account-management-feature.md
  docs/pbc/all/customer-relationship-management/202304.0/install-and-upgrade/install-features/install-the-customer-account-management-feature.md
  docs/pbc/all/identity-access-management/202304.0/install-and-upgrade/install-the-spryker-core-back-office-feature.md
  docs/scos/dev/feature-integration-guides/202204.0/product-relations-feature-integration.md
  docs/scos/dev/feature-integration-guides/202304.0/install-spryker-core-back-office-warehouse-user-management-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-push-notification-feature.md
Labels: ready for merge

#1676 Add price mode doc
  docs/pbc/all/search/202212.0/manage-using-glue-api/glue-api-search-the-product-catalog.md
Labels: ready for merge

#1682 Contributor: set pathmapping with vscode variable
  docs/scos/dev/the-docker-sdk/202212.0/configuring-debugging-in-docker.md
Labels: ready for merge, contributor

#1679 remove duplicate quotes
  docs/scos/dev/technical-enhancement-integration-guides/integrating-separate-endpoint-bootstraps.md
Labels: ready for merge

#1674 Adjusting the page for features overview
  _config.yml
  docs/scos/user/overview-of-features/201811.0/overview-of-features.md
  docs/scos/user/overview-of-features/201903.0/overview-of-features.md
  docs/scos/user/overview-of-features/201907.0/overview-of-features.md
  docs/scos/user/overview-of-features/202001.0/overview-of-features.md
  docs/scos/user/overview-of-features/202005.0/overview-of-features.md
  docs/scos/user/overview-of-features/202009.0/overview-of-features.md
  docs/scos/user/overview-of-features/202108.0/overview-of-features.md
  docs/scos/user/overview-of-features/202204.0/overview-of-features.md
  docs/scos/user/overview-of-features/202212.0/overview-of-features.md
Labels: do not merge

#1693 Fix a broken link
  docs/scos/dev/feature-integration-guides/202212.0/feature-integration-guides.md
Labels: ready for merge

#1668 PBC-887: Bump modules required versions
  Rakefile
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
Labels: ready for merge

#1666 Update algolia.md
  docs/pbc/all/search/202212.0/third-party-integrations/algolia.md
Labels: TW review needed

#1698 Fix the Migration guide - Remove support of IE11
  docs/scos/dev/front-end-development/migration-guide-remove-support-of-ie11.md
Labels: ready for merge, updated

#1691 CC-23635 Introduced cart prices feature IG.
  _includes/pbc/all/install-features/202304.0/install-the-cart-prices-feature.md
  docs/pbc/all/cart-and-checkout/202304.0/install-and-upgrade/install-features/install-the-cart-prices-feature.md
Labels: ready for merge, new, 202306

#1692 SUPESC-685 Adjust Multiple Cart IG
  _includes/pbc/all/install-features/202304.0/install-the-multiple-carts-feature.md
  docs/pbc/all/cart-and-checkout/202304.0/install-and-upgrade/install-features/install-the-multiple-carts-feature.md
Labels: ready for merge, updated, 202306

#1664 Update publish-and-synchronization.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/publish-and-synchronization.md
Labels: in TW review

#1706 Update patch-releases-202212.0.md
  _includes/scos/user/intro-to-spryker/releases/release-notes/release-notes-202212.0/patch-releases-202212.0.md
Labels: updated

#1712 CC-25963 Migration guide - Switch from TSLint to ESLint
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/migration-guide-switch-from-tslint-to-eslint.md
Labels: ready for merge, new

#1649 SDK-1905: Remove link on evaluator
  docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
Labels: ready for merge

#1714 SDK-2049 profiler module documentation
  docs/scos/dev/technical-enhancement-integration-guides/Integrate-profiler-module.md
Labels: TW review needed

#1671 Created Docs Explaining Onboarding Questionnaire
  _data/sidebars/cloud_dev_sidebar.yml
  docs/cloud/dev/spryker-cloud-commerce-os/environment-provisioning.md
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-set-up-multiple-stores.md
Labels: ready for merge, new, updated

#1721 SUPESC-606 Add note about Availability Notification deploy file configuration
  _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
  docs/pbc/all/warehouse-management-system/202304.0/install-and-upgrade/install-features/install-the-availability-notification-feature.md
Labels: ready for merge, updated, 202306

#1729 Fix typo in the Customizing Spryker Frontend
  docs/scos/dev/front-end-development/yves/atomic-frontend/customizing-spryker-front-end.md
Labels: ready for merge

#1704 AC-1415-publish-security-release-notes-202302
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202302.0/security-release-notes-202302.0.md
Labels: ready for merge, new, 202306

#1734 Update integrate-bazaarvoice.md
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
Labels: ready for merge
