Repository spryker/spryker-docs, pull requests merged in 2023-08, with the labels that each got.

#2045 Install the Service Points feature
  _includes/pbc/all/install-features/202400.0/install-the-service-points-feature.md
  docs/pbc/all/service-points/202400.0/unified-commerce/install-the-service-points-feature.md
Labels: ready for merge, updated

#2042 Release notes 202307.0
  _data/sidebars/pbc_all_sidebar.yml
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202307.0/release-notes-202307.0.md
Labels: ready for merge, new

#2036 SDK-4018: Clean the page of evaluator minimum allowed shop version check
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/minimum-allowed-shop-version.md
Labels: in TW review, updated

#2052 Handle data with Publish and Synchronization
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/handle-data-with-publish-and-synchronization.md
Labels: ready for merge, small changes

#2057 Add variables in the Parameter Store
  docs/cloud/dev/spryker-cloud-commerce-os/add-variables-in-the-parameter-store.md
Labels: ready for merge, small changes

#2048 Update publish-and-synchronize-and-multi-store-shop-systems.md
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/publish-and-synchronize-and-multi-store-shop-systems.md
Labels: ready for merge, small changes

#1984 docs: Typography in Oryx
  CODEOWNERS
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202212.0/oryx/styling/oryx-color-system.md
  docs/scos/dev/front-end-development/202212.0/oryx/styling/typography.md
  docs/scos/dev/front-end-development/202307.0/oryx/styling/oryx-color-system.md
  docs/scos/dev/front-end-development/202307.0/oryx/styling/typography.md
Labels: in TW review, new

#2064 CC-26571: Update Product Offer Shipment feature
  _includes/pbc/all/install-features/202400.0/install-the-product-offer-shipment-feature.md
  docs/pbc/all/offer-management/202400.0/unified-commerce/install-and-upgrade/install-the-product-offer-shipment-feature.md
  docs/scos/user/intro-to-spryker/docs-release-notes.md
Labels: updated

#2063 CC-26571: Update Shipment + Service Points feature
  _includes/pbc/all/install-features/202400.0/install-the-shipment-service-points-feature.md
  docs/pbc/all/carrier-management/202400.0/unified-commerce/install-and-upgrade/install-the-shipment-service-points-feature.md
Labels: updated

#2066 SDK-4093. Added Security update checker doc
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/security-update.md
Labels: new

#2054 SUPESC-769 Install the Product Rating and Reviews feature
  _includes/pbc/all/install-features/202307.0/install-the-product-rating-and-reviews-feature.md
  docs/pbc/all/ratings-reviews/202307.0/install-and-upgrade/install-the-product-rating-and-reviews-feature.md
Labels: ready for merge, updated

#2071 Update install-the-merchant-product-restrictions-feature.md
  _includes/pbc/all/install-features/202204.0/install-the-merchant-product-restrictions-feature.md
Labels: ready for merge, small changes

#2069 Tables for rules and scopes + execution flow fix
  docs/marketplace/dev/feature-walkthroughs/202307.0/persistence-acl-feature-walkthrough/execution-flow.md
  docs/marketplace/dev/feature-walkthroughs/202307.0/persistence-acl-feature-walkthrough/rules-and-scopes/rules-and-scopes.md
Labels: small changes

#2060 July Release Notes for public docs
  docs/scos/user/intro-to-spryker/docs-release-notes.md
Labels: updated

#2065 Install the Service Points + Order Management feature
  _includes/pbc/all/install-features/202400.0/install-the-service-points-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-service-points-order-management-feature.md
  docs/pbc/all/order-management-system/202400.0/unified-commerce/install-and-update/install-features/install-the-order-management-service-points-feature.md
  docs/pbc/all/service-points/202400.0/unified-commerce/install-the-service-points-feature.md
  docs/pbc/all/service-points/202400.0/unified-commerce/install-the-service-points-order-management-feature.md
Labels: ready for merge, updated

#2061 Install the Shipment + Customer Account Management feature
  _includes/pbc/all/install-features/202400.0/install-the-shipment-customer-account-management-feature.md
  docs/pbc/all/carrier-management/202400.0/base-shop/install-and-upgrade/install-features/install-the-shipment-customer-account-management-feature.md
  docs/pbc/all/customer-relationship-management/202400.0/install-and-update/install-features/install-the-customer-account-management-shipment-feature.md
Labels: ready for merge, new, 202400

#2067 SDK-2492 add npm checker docs
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/npm-checker.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/security.md
Labels: new

#2072 SDK-4093. Added Security update checker doc / checkers renamed
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/open-source-vulnerabilities.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/security-update.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/security.md
Labels: ready for merge, updated

#2059 Update best-practices-manage-users-and-their-permissions-with-roles-a…
  docs/pbc/all/user-management/202212.0/manage-in-the-back-office/best-practices-manage-users-and-their-permissions-with-roles-and-groups.md
  docs/pbc/all/user-management/202307.0/manage-in-the-back-office/best-practices-manage-users-and-their-permissions-with-roles-and-groups.md
Labels: small changes

#2058 CC-29675 Shipment Type support on Checkout & OMS
  _includes/pbc/all/install-features/202400.0/install-the-order-management-inventory-management-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-shipment-cart-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-shipment-feature.md
Labels: TW review needed, updated

#2073 Move docs to proper folders
  docs/pbc/all/order-management-system/202400.0/unified-commerce/install-and-upgrade/install-the-order-management-service-points-feature.md
  docs/pbc/all/service-points/202400.0/unified-commerce/install-and-upgrade/install-the-service-points-feature.md
  docs/pbc/all/service-points/202400.0/unified-commerce/install-and-upgrade/install-the-service-points-order-management-feature.md
  docs/pbc/all/service-points/202400.0/unified-commerce/install-and-upgrade/install-the-service-points-shipment-feature.md
Labels: ready for merge, small changes

#2026 SDK-2466 security releases docs
  docs/scu/dev/how-the-spryker-code-upgrader-works.md
Labels: ready for merge, small changes

#2074 Comments + Order Management feature integration
  docs/pbc/all/cart-and-checkout/202212.0/base-shop/install-and-upgrade/install-features/install-the-comments-order-management-feature.md
Labels: ready for merge, small changes

#1930 HowTo: Set up XDebug profiling
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/tutorials-and-howtos/howtos/howto-setup-xdebug-profiling.md
Labels: ready for merge, new

#2070 PBC-2073: Integration guide
  _data/sidebars/pbc_all_sidebar.yml
  css/customstyles.css
  docs/pbc/all/tax-management/202307.0/vertex/install-vertex.md
  docs/pbc/all/tax-management/202307.0/vertex/vertex.md
Labels: ready for merge, new

#2079 Fixed oryx presets url
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-presets.md
Labels: ready for merge, small changes

#2082 Delete fact finder docs from scos
  docs/pbc/all/miscellaneous/202307.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/exporting-product-data-for-fact-finder.md
  docs/pbc/all/miscellaneous/202307.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/fact-finder.md
  docs/pbc/all/miscellaneous/202307.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/installing-and-configuring-fact-finder-web-components.md
  docs/pbc/all/miscellaneous/202307.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/installing-and-configuring-fact-finder.md
  docs/pbc/all/miscellaneous/202307.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/installing-and-configuring-the-fact-finder-ng-api.md
  docs/pbc/all/miscellaneous/202307.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/integrating-fact-finder.md
  docs/pbc/all/miscellaneous/202307.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/using-fact-finder-campaigns.md
  docs/pbc/all/miscellaneous/202307.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/using-fact-finder-recommendation-engine.md
  docs/pbc/all/miscellaneous/202307.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/using-fact-finder-search-suggestions.md
  docs/pbc/all/miscellaneous/202307.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/using-fact-finder-search.md
  docs/pbc/all/miscellaneous/202307.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/using-fact-finder-tracking.md
Labels: ready for merge, small changes

#2084 SDK-4487: Fixed npm-checker.md example format.
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/npm-checker.md
Labels: small changes

#2088 delete fact finder docs
  docs/scos/dev/technology-partner-guides/202307.0/marketing-and-conversion/analytics/fact-finder/exporting-product-data-for-fact-finder.md
  docs/scos/dev/technology-partner-guides/202307.0/marketing-and-conversion/analytics/fact-finder/fact-finder.md
  docs/scos/dev/technology-partner-guides/202307.0/marketing-and-conversion/analytics/fact-finder/installing-and-configuring-fact-finder-web-components.md
  docs/scos/dev/technology-partner-guides/202307.0/marketing-and-conversion/analytics/fact-finder/installing-and-configuring-fact-finder.md
  docs/scos/dev/technology-partner-guides/202307.0/marketing-and-conversion/analytics/fact-finder/installing-and-configuring-the-fact-finder-ng-api.md
  docs/scos/dev/technology-partner-guides/202307.0/marketing-and-conversion/analytics/fact-finder/integrating-fact-finder.md
  docs/scos/dev/technology-partner-guides/202307.0/marketing-and-conversion/analytics/fact-finder/using-fact-finder-campaigns.md
  docs/scos/dev/technology-partner-guides/202307.0/marketing-and-conversion/analytics/fact-finder/using-fact-finder-recommendation-engine.md
  docs/scos/dev/technology-partner-guides/202307.0/marketing-and-conversion/analytics/fact-finder/using-fact-finder-search-suggestions.md
  docs/scos/dev/technology-partner-guides/202307.0/marketing-and-conversion/analytics/fact-finder/using-fact-finder-search.md
  docs/scos/dev/technology-partner-guides/202307.0/marketing-and-conversion/analytics/fact-finder/using-fact-finder-tracking.md
Labels: ready for merge, small changes

#2076 Install the File Manager feature
  _includes/pbc/all/install-features/202307.0/install-the-file-manager-feature.md
  docs/pbc/all/content-management-system/202307.0/base-shop/install-and-upgrade/install-features/install-the-file-manager-feature.md
Labels: ready for merge, updated

#2086 Algolia
  docs/pbc/all/search/202307.0/base-shop/third-party-integrations/algolia.md
Labels: ready for merge, updated

#2087 Add Bazaarvoice demo
  docs/pbc/all/ratings-reviews/202307.0/third-party-integrations/bazaarvoice.md
Labels: ready for merge, small changes

#2077 Install the Service Points feature
  _includes/pbc/all/install-features/202400.0/install-the-service-points-feature.md
Labels: ready for merge, updated

#2085 Install Vertex
  docs/pbc/all/tax-management/202307.0/vertex/install-vertex.md
Labels: ready for merge, updated

#2091 SDK-4055: Add page how to set the default branch
  _data/sidebars/scu_dev_sidebar.yml
  docs/scu/dev/select-target-branch-for-prs.md
Labels: ready for merge, new

#1989 docs: signals in Oryx
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202212.0/oryx/reactivity/key-concepts-of-reactivity.md
  docs/scos/dev/front-end-development/202212.0/oryx/reactivity/reactive-components.md
  docs/scos/dev/front-end-development/202212.0/oryx/reactivity/signals.md
  docs/scos/dev/front-end-development/202307.0/oryx/reactivity/signals.md
Labels: in progress, small changes

#2089 removed VPN from the text, diagram still left
  docs/scos/dev/back-end-development/running-production.md
Labels: ready for merge, small changes

#2095 SDK-4572: Fix the broken link
  docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
Labels: ready for merge, small changes

#2094 Update decoupled-glue-infrastructure-integrate-the-authentication.md
  docs/scos/dev/migration-concepts/migrate-to-decoupled-glue-infrastructure/decoupled-glue-infrastructure-integrate-the-authentication.md
Labels: ready for merge, updated

#2093 SDK-2913: New documentation page of how to set the Spryker Code Upgrader variables
  _data/sidebars/scu_dev_sidebar.yml
  docs/scu/dev/configure-spryker-code-upgrader.md
Labels: in TW review, new

#2098 Add Vertex to the Tax management table
  docs/pbc/all/tax-management/202307.0/tax-management.md
Labels: ready for merge, updated

#2025 docs: Oryx design tokens
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-presets.md
  docs/scos/dev/front-end-development/202212.0/oryx/styling/oryx-color-system.md
  docs/scos/dev/front-end-development/202212.0/oryx/styling/oryx-design-tokens.md
  docs/scos/dev/front-end-development/202212.0/oryx/styling/oryx-typography.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-presets.md
  docs/scos/dev/front-end-development/202307.0/oryx/styling/oryx-color-system.md
  docs/scos/dev/front-end-development/202307.0/oryx/styling/oryx-design-tokens.md
  docs/scos/dev/front-end-development/202307.0/oryx/styling/oryx-typography.md
Labels: new

#2107 Adding Partner Safari to footer
  _includes/footer.html
Labels: small changes

#2105 Adding time period to the changelog file
  .github/workflows/build-changelog.yml
Labels: small changes

#2103 Add variables in the Parameter Store
  docs/cloud/dev/spryker-cloud-commerce-os/add-variables-in-the-parameter-store.md
Labels: ready for merge, updated

#2097 Implement Sidebar Checker workflow
  .github/workflows/check_sidebar.yml
  _scripts/sidebar_checker/excludelist.yml
  _scripts/sidebar_checker/run-sidebar-checker.md
  _scripts/sidebar_checker/sidebar_checker.sh
  docs/pbc/all/product-information-management/202204.0/product-information-management.md
  docs/pbc/all/product-information-management/202212.0/base-shop/feature-overviews/pim-feature-overviews.md
  docs/pbc/all/product-information-management/202212.0/product-information-management.md
  docs/pbc/all/product-information-management/202307.0/base-shop/feature-overviews/pim-feature-overviews.md
  docs/pbc/all/product-information-management/202307.0/product-information-management.md
Labels: ready for merge, small changes

#2114 CC-26235 Add file upload extension validation
  _includes/pbc/all/install-features/202400.0/install-the-file-manager-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-product-lists-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-scheduled-prices-feature.md
  docs/pbc/all/content-management-system/202400.0/base-shop/install-and-upgrade/install-features/install-the-file-manager-feature.md
  docs/pbc/all/price-management/202400.0/base-shop/install-and-upgrade/install-features/install-the-scheduled-prices-feature.md
  docs/pbc/all/product-information-management/202400.0/base-shop/install-and-upgrade/install-features/install-the-product-lists-feature.md
Labels: ready for merge, updated, 202400

#2116 Install the shipment feature
  _includes/pbc/all/install-features/202400.0/install-the-shipment-feature.md
  docs/pbc/all/carrier-management/202400.0/base-shop/install-and-upgrade/install-features/install-the-shipment-feature.md
Labels: ready for merge, updated, 202400

#1904 Add i18n doc
  CODEOWNERS
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202212.0/oryx/oryx-localization.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-localization.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/spryker-documentation-style-guide/examples.md
Labels: in TW review, new

#2110 Install the Shipment + Service Points feature, Install the Service Points feature
  _includes/pbc/all/install-features/202400.0/install-the-service-points-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-shipment-service-points-feature.md
  docs/pbc/all/carrier-management/202400.0/unified-commerce/install-and-upgrade/install-the-shipment-service-points-feature.md
  docs/pbc/all/service-points/202400.0/unified-commerce/install-and-upgrade/install-the-service-points-feature.md
Labels: ready for merge, updated, 202400

#2123 Note about the discontinued Spryker Middleware
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
Labels: small changes

#2124 Update preparation-for-going-live.md
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: tech review needed, small changes

#2119 fix: align package documentation with latest changes
  docs/scos/dev/front-end-development/202307.0/oryx/dependency-injection/dependency-injection-advanced-strategies.md
  docs/scos/dev/front-end-development/202307.0/oryx/dependency-injection/dependency-injection-defining-services.md
  docs/scos/dev/front-end-development/202307.0/oryx/dependency-injection/dependency-injection-providing-services.md
  docs/scos/dev/front-end-development/202307.0/oryx/dependency-injection/dependency-injection-using-services.md
  docs/scos/dev/front-end-development/202307.0/oryx/dependency-injection/dependency-injection.md
  docs/scos/dev/front-end-development/202307.0/oryx/dependency-injection/oryx-service-layer.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-application-orchestration/oryx-application-environment.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-application-orchestration/oryx-application-feature.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-application-orchestration/oryx-application-orchestration.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-application-orchestration/oryx-application-plugins.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-application-orchestration/oryx-application.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-boilerplate.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-compositions.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-feature-sets.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-packages.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-presets.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-routing.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-server-side-rendering.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-supported-browsers.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx-versioning.md
  docs/scos/dev/front-end-development/202307.0/oryx/oryx.md
  docs/scos/dev/front-end-development/202307.0/oryx/reactivity/key-concepts-of-reactivity.md
  docs/scos/dev/front-end-development/202307.0/oryx/reactivity/oryx-integration-of-backend-apis.md
  docs/scos/dev/front-end-development/202307.0/oryx/reactivity/reactive-components.md
  docs/scos/dev/front-end-development/202307.0/oryx/reactivity/reactivity.md
  docs/scos/dev/front-end-development/202307.0/oryx/set-up-oryx.md
  docs/scos/dev/front-end-development/202307.0/oryx/styling/oryx-color-system.md
  docs/scos/dev/front-end-development/202307.0/oryx/styling/oryx-design-tokens.md
  docs/scos/dev/front-end-development/202307.0/oryx/styling/oryx-typography.md
Labels: updated

#2126 Updated references of Slack with CommerceQuest
  docs/acp/user/intro-to-acp/aop-security-assessment.md
  docs/scos/dev/developer-getting-started-guide.md
  docs/scos/user/intro-to-spryker/support/getting-support.md
  docs/scos/user/intro-to-spryker/support/understand-slas.md
Labels: small changes
