Repository spryker/spryker-docs, pull requests merged in 2023-02, with the labels that each got.

#1497 CC-21940 Propel migration rollback.
  docs/scos/dev/back-end-development/zed/persistence-layer/database-schema-definition.md
Labels: ready for merge

#1583 APPS-6324: Update BazaarVoice integration docs
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
Labels: in TW review

#1567 Add redirects 3
  docs/cloud/dev/spryker-cloud-commerce-os/configure-deployment-pipelines/configuring-gitlab-pipelines.md
  docs/pbc/all/content-management-system/202212.0/manage-in-the-back-office/pages/create-cms-pages.md
  docs/pbc/all/identity-access-management/202212.0/manage-using-glue-api/glue-api-security-and-authentication.md
  docs/pbc/all/price-management/202212.0/extend-and-customize/configuration-of-price-modes-and-types.md
  docs/pbc/all/return-management/202212.0/manage-using-glue-api/glue-api-manage-returns.md
  docs/scos/dev/front-end-development/zed/oryx-for-zed.md
  docs/scos/dev/glue-api-guides/202108.0/managing-customers/managing-customer-authentication-tokens-via-oauth-2.0.md
  docs/scos/dev/glue-api-guides/202212.0/decoupled-glue-infrastructure/how-to-guides/routing/how-to-create-a-backend-resource.md
  docs/scos/dev/glue-api-guides/202212.0/glue-api-tutorials/implement-versioning-for-rest-api-resources.md
Labels: ready for merge

#1592 Explain how to get Bazaarvoice credentials
  Rakefile
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/configure-bazaarvoice.md
  docs/scos/user/features/201811.0/order-management-feature-overview/oms-order-management-system-matrix.md
  docs/scos/user/features/201903.0/order-management-feature-overview/oms-order-management-system-matrix.md
  docs/scos/user/features/201907.0/order-management-feature-overview/oms-order-management-system-matrix.md
  docs/scos/user/features/202001.0/order-management-feature-overview/oms-order-management-system-matrix.md
  docs/scos/user/features/202005.0/order-management-feature-overview/oms-order-management-system-matrix.md
  docs/scos/user/features/202009.0/order-management-feature-overview/oms-order-management-system-matrix.md
  docs/scos/user/features/202108.0/order-management-feature-overview/oms-order-management-system-matrix.md
  docs/scos/user/features/202204.0/order-management-feature-overview/oms-order-management-system-matrix.md
  docs/scos/user/features/202212.0/order-management-feature-overview/oms-order-management-system-matrix.md
Labels: TW review needed

#1593 Add Bazaarvoice hero
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/bazaarvoice.md
Labels: ready for merge

#1589 Update abbitmq-zed.critical-phpamqplib-exception-amqpchannelclosedexception-channel-connection-is-closed.md
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/rabbitmq-zed.critical-phpamqplib-exception-amqpchannelclosedexception-channel-connection-is-closed.md
  docs/scos/user/technology-partners/201811.0/finance-and-accounting/collectai.md
  docs/scos/user/technology-partners/201903.0/finance-and-accounting/collectai.md
  docs/scos/user/technology-partners/201907.0/finance-and-accounting/collectai.md
  docs/scos/user/technology-partners/202001.0/finance-and-accounting/collectai.md
  docs/scos/user/technology-partners/202005.0/finance-and-accounting/collectai.md
  docs/scos/user/technology-partners/202009.0/finance-and-accounting/collectai.md
  docs/scos/user/technology-partners/202108.0/finance-and-accounting/collectai.md
  docs/scos/user/technology-partners/202204.0/finance-and-accounting/collectai.md
  docs/scos/user/technology-partners/202212.0/finance-and-accounting/collectai.md
Labels: ready for merge, contributor

#1571 Update tutorials-and-howtos.md
  docs/scos/dev/tutorials-and-howtos/tutorials-and-howtos.md
Labels: ready for merge

#1576 Update scos_user_sidebar.yml
  _data/sidebars/scos_user_sidebar.yml
Labels: ready for merge

#1575 Rename index pages
  _data/sidebars/cloud_dev_sidebar.yml
  _data/sidebars/marketplace_dev_sidebar.yml
  _data/sidebars/marketplace_user_sidebar.yml
  _data/sidebars/scos_dev_sidebar.yml
  _data/sidebars/sdk_dev_sidebar.yml
  docs/cloud/dev/spryker-cloud-commerce-os/access/access.md
  docs/cloud/dev/spryker-cloud-commerce-os/configure-deployment-pipelines/configure-deployment-pipelines.md
  docs/cloud/dev/spryker-cloud-commerce-os/monitoring/monitoring.md
  docs/cloud/dev/spryker-cloud-commerce-os/security/security.md
  docs/marketplace/dev/architecture-overview/architecture-overview.md
  docs/marketplace/dev/feature-integration-guides/202212.0/feature-integration-guides.md
  docs/marketplace/dev/feature-walkthroughs/202212.0/feature-walkthroughs.md
  docs/marketplace/dev/front-end/202212.0/front-end.md
  docs/marketplace/dev/glue-api-guides/202212.0/glue-api-guides.md
  docs/marketplace/dev/howtos/howtos.md
  docs/marketplace/dev/setup/202212.0/setup.md
  docs/marketplace/dev/technical-enhancement/202212.0/technical-enhancement.md
  docs/marketplace/user/back-office-user-guides/202212.0/back-office-user-guides.md
  docs/scos/dev/back-end-development/back-end-development.md
  docs/scos/dev/best-practices/best-practices.md
  docs/scos/dev/front-end-development/front-end-development.md
  docs/scos/dev/glue-api-guides/202212.0/glue-api-guides.md
  docs/scos/dev/guidelines/guidelines.md
  docs/scos/dev/sdk/sdk.md
  docs/scos/dev/technical-enhancement-integration-guides/technical-enhancement-integration-guides.md
  docs/scos/dev/technology-partner-guides/202212.0/technology-partner-guides.md
  docs/sdk/dev/development-tools/development-tools.md
Labels: ready for merge

#1560 CC-20997: Push notification integration guide.
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202304.0/install-push-notification-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-spryker-core-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-push-notification-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/spryker-core-feature-integration.md
Labels: ready for merge

#1577 Update system-requirements.md
  docs/scos/dev/system-requirements/202212.0/system-requirements.md
Labels: TW review needed

#1578 Note about us english
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/edit-documentation-via-pull-requests.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/style-formatting-general-rules.md
Labels: ready for merge

#1572 Add redirects 4
  docs/marketplace/dev/setup/202212.0/spryker-marketplace-setup.md
  docs/marketplace/user/intro-to-spryker-marketplace/marketplace-concept.md
  docs/pbc/all/carrier-management/202212.0/manage-via-glue-api/retrieve-shipments-when-checking-out-purchases.md
  docs/pbc/all/cart-and-checkout/202212.0/approval-process-feature-overview.md
  docs/pbc/all/cart-and-checkout/202212.0/checkout-feature-overview/multi-step-checkout-overview.md
  docs/pbc/all/cart-and-checkout/202212.0/extend-and-customize/checkout-process-review-and-implementation.md
  docs/pbc/all/cart-and-checkout/202212.0/install-and-upgrade/install-features/install-the-checkout-feature.md
  docs/pbc/all/cart-and-checkout/202212.0/install-and-upgrade/install-glue-api/install-the-cart-glue-api.md
  docs/pbc/all/cart-and-checkout/202212.0/install-and-upgrade/upgrade-modules/upgrade-the-cart-module.md
  docs/pbc/all/cart-and-checkout/202212.0/manage-using-glue-api/manage-guest-carts/manage-guest-carts.md
  docs/pbc/all/cart-and-checkout/202212.0/non-splittable-products-feature-overview.md
  docs/pbc/all/cart-and-checkout/202212.0/persistent-cart-sharing-feature-overview.md
  docs/pbc/all/cart-and-checkout/202212.0/tutorials-and-howtos/howto-add-additional-countries-to-spryker-checkout.md
  docs/pbc/all/content-management-system/202212.0/install-and-upgrade/upgrade-modules/upgrade-the-cms-module.md
  docs/pbc/all/content-management-system/202212.0/install-and-upgrade/upgrade-modules/upgrade-the-navigationgui-module.md
  docs/pbc/all/content-management-system/202212.0/manage-in-the-back-office/redirects/manage-cms-redirects.md
  docs/pbc/all/discount-management/202212.0/install-and-upgrade/integrate-the-promotions-and-discounts-glue-api.md
  docs/pbc/all/discount-management/202212.0/manage-in-the-back-office/create-discounts.md
  docs/pbc/all/discount-management/202212.0/manage-in-the-back-office/export-voucher-codes.md
  docs/pbc/all/discount-management/202212.0/manage-via-glue-api/add-items-with-discounts-to-guest-carts.md
  docs/pbc/all/emails/202212.0/howto-create-and-register-a-mailtypeplugin.md
  docs/pbc/all/price-management/202212.0/extend-and-customize/money-module-reference-information.md
  docs/pbc/all/price-management/202212.0/extend-and-customize/priceproduct-module-details-reference-information.md
  docs/pbc/all/price-management/202212.0/manage-using-glue-api/retrieve-concrete-product-prices.md
  docs/pbc/all/price-management/202212.0/price-management.md
  docs/pbc/all/price-management/202212.0/prices-feature-overview/volume-prices-overview.md
  docs/pbc/all/product-information-management/202212.0/configurable-product-feature-overview/configuration-process-flow-of-configurable-product.md
  docs/pbc/all/product-information-management/202212.0/manage-in-the-back-office/product-options/create-product-options.md
  docs/pbc/all/product-information-management/202212.0/manage-in-the-back-office/products/manage-abstract-products-and-product-bundles/create-abstract-products-and-product-bundles.md
  docs/pbc/all/product-information-management/202212.0/packaging-units-feature-overview.md
  docs/pbc/all/product-information-management/202212.0/third-party-integrations/akeneo/install-and-configure-akeneo.md
  docs/pbc/all/ratings-reviews/202212.0/ratings-and-reviews.md
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
  docs/pbc/all/shopping-list-and-wishlist/202212.0/shopping-list-and-wishlist.md
  docs/pbc/all/tax-management/202212.0/manage-in-the-back-office/create-tax-rates.md
  docs/pbc/all/tax-management/202212.0/tax-management.md
  docs/pbc/all/tax-management/202212.0/third-party-integrations/integrate-avalara-tax-shipment.md
  docs/pbc/all/warehouse-management-system/202212.0/extend-and-customize/inventory-management-feature-modules-overview.md
  docs/pbc/all/warehouse-management-system/202212.0/import-and-export-data/file-details-product-stock.csv.md
  docs/pbc/all/warehouse-management-system/202212.0/install-and-upgrade/install-features/install-the-availability-notification-feature.md
  docs/pbc/all/warehouse-management-system/202212.0/inventory-management-feature-overview.md
  docs/pbc/all/warehouse-management-system/202212.0/manage-in-the-back-office/create-warehouses.md
  docs/pbc/all/warehouse-management-system/202212.0/warehouse-management-system.md
  docs/scos/dev/back-end-development/data-manipulation/data-manipulation.md
  docs/scos/dev/feature-integration-guides/202009.0/payment-provider-integration.md
  docs/scos/dev/feature-integration-guides/202304.0/spryker-core-back-office-feature-integration.md
  docs/scos/dev/glue-api-guides/202108.0/managing-customers/confirming-customer-registration.md
  docs/scos/dev/glue-api-guides/202204.0/glue-rest-api.md
  docs/scos/dev/glue-api-guides/202212.0/glue-api-guides.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgrader-tool-overview.md
  docs/scos/dev/the-docker-sdk/202212.0/configure-services.md
  docs/scos/user/back-office-user-guides/202108.0/merchandising/product-sets/delete-product-sets.md
  docs/scos/user/technology-partners/202212.0/marketing-and-conversion/analytics/minubo.md
  docs/scos/user/technology-partners/202212.0/marketing-and-conversion/customer-communication/inxmail.md
  docs/scos/user/technology-partners/202212.0/payment-partners/adyen.md
Labels: ready for merge

#1598 Update integrate-bazaarvoice.md
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
Labels: ready for merge

#1601 Update 8 4 split
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: ready for merge

#1600 Includes Windows 11 as supported OS
  docs/scos/dev/setup/installing-spryker-with-docker/docker-installation-prerequisites/installing-docker-prerequisites-on-windows-with-wsl1.md
  docs/scos/dev/setup/installing-spryker-with-docker/docker-installation-prerequisites/installing-docker-prerequisites-on-windows-with-wsl2.md
  docs/scos/dev/the-docker-sdk/202212.0/configuring-a-mount-mode.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-decrease-the-memory-usage-of-spryker-with-docker-on-wsl2.md
Labels: ready for merge

#1591 Review IGs 202212.0
  _data/sidebars/marketplace_dev_sidebar.yml
  _includes/pbc/all/install-features/202204.0/install-the-alternative-products-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-acl-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-alternative-products-discontinued-products-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-alternative-products-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-alternative-products-inventory-management-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-alternative-products-product-labels-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-alternative-products-wishlist-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-approval-process-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-availability-notification-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-cart-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-cart-non-splittable-products-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-catalog-category-management-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-catalog-order-management-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-category-filters-feature.md
  _includes/pbc/all/install-features/202212.0/install-the-category-image-feature.md
  docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-product-options-cart-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-product-options-checkout-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202108.0/marketplace-product-options-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202108.0/merchant-portal-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202108.0/merchant-portal-marketplace-product-options-management-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202204.0/marketplace-product-options-cart-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202204.0/marketplace-product-options-checkout-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202204.0/marketplace-product-options-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202204.0/merchant-portal-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202204.0/merchant-portal-marketplace-product-options-management-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202212.0/feature-integration-guides.md
  docs/marketplace/dev/feature-integration-guides/202212.0/marketplace-product-options-cart-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202212.0/marketplace-product-options-checkout-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202212.0/marketplace-product-options-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202212.0/merchant-portal-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202212.0/merchant-portal-marketplace-product-options-management-feature-integration.md
  docs/marketplace/dev/feature-walkthroughs/202108.0/marketplace-product-options-feature-walkthrough.md
  docs/marketplace/dev/feature-walkthroughs/202204.0/marketplace-product-options-feature-walkthrough.md
  docs/marketplace/dev/feature-walkthroughs/202212.0/marketplace-product-options-feature-walkthrough.md
  docs/marketplace/dev/howtos/how-to-upgrade-spryker-instance-to-marketplace.md
  docs/marketplace/user/back-office-user-guides/202108.0/catalog/product-options/creating-product-options.md
  docs/marketplace/user/back-office-user-guides/202204.0/catalog/product-options/creating-product-options.md
  docs/marketplace/user/back-office-user-guides/202212.0/catalog/product-options/creating-product-options.md
  docs/pbc/all/product-information-management/202212.0/alternative-products-feature-overview.md
  docs/pbc/all/product-information-management/202212.0/install-and-upgrade/install-features/install-the-alternative-products-feature.md
  docs/pbc/all/product-information-management/202212.0/install-and-upgrade/install-features/install-the-alternative-products-product-labels-feature.md
  docs/pbc/all/product-information-management/202212.0/install-and-upgrade/install-features/install-the-alternative-products-wishlist-feature.md
Labels: in progress

#1619 Warning for Data Import and Email Quota
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: ready for merge

#1615 CC-25971: Update push notification integration guide
  _includes/pbc/all/install-features/202304.0/install-push-notification-feature.md
Labels: ready for merge

#1618 Updated the description on how to share secrets.
  docs/scos/user/intro-to-spryker/support/how-to-share-secrets-with-the-spryker-support-team.md
Labels: ready for merge

#1607 CC-25924: Update Customer Account Management feature integration documentation.
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202304.0/install-the-customer-account-management-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/customer-account-management-feature-integration.md
Labels: ready for merge

#1610 Update glue-api-search-the-product-catalog.md
  docs/pbc/all/search/202212.0/manage-using-glue-api/glue-api-search-the-product-catalog.md
Labels: ready for merge

#1594 SUPESC-676 changes in gift card feature installation
  _includes/pbc/all/install-features/202304.0/install-the-gift-cards-feature.md
  docs/pbc/all/gift-cards/202304.0/install-and-upgrade/install-the-gift-cards-feature.md
Labels: ready for merge

#1520 CC-25314: IG warehouse assignment to sales order items
  _includes/pbc/all/install-features/202304.0/install-the-inventory-management-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-order-management-inventory-management-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-warehouse-user-management-feature.md
  docs/pbc/all/warehouse-management-system/202304.0/install-and-upgrade/install-features/install-the-inventory-management-feature.md
  docs/pbc/all/warehouse-management-system/202304.0/install-and-upgrade/install-features/install-the-order-management-inventory-management-feature.md
  docs/scos/dev/feature-integration-guides/202304.0/install-the-warehouse-user-management-feature.md
Labels: ready for merge

#1625 Fix the connection steps for Bazaarvoice
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/configure-bazaarvoice.md
  docs/pbc/all/ratings-reviews/202212.0/third-party-integrations/integrate-bazaarvoice.md
Labels: TW review needed

#1631 Added documentation from SOL-315 (parent ticket - SOL-265)
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/guidelines/performance-guidelines/performance-guidelines.md
  docs/scos/dev/troubleshooting/troubleshooting-performance-issues/external-calls-several-calls-to-zed.md
  docs/scos/dev/troubleshooting/troubleshooting-performance-issues/external-calls-take-a-lot-of-time.md
  docs/scos/dev/troubleshooting/troubleshooting-performance-issues/n+1-problem.md
  docs/scos/dev/troubleshooting/troubleshooting-performance-issues/not-optimised-composer-for-production-env.md
  docs/scos/dev/troubleshooting/troubleshooting-performance-issues/technology-restrictions.md
  docs/scos/dev/troubleshooting/troubleshooting-performance-issues/troubleshooting-performance-issues.md
Labels: TW review needed

#1633 SUPESC-667 Updated product labels promotions and discounts IG.
  _includes/pbc/all/install-features/202304.0/install-the-product-labels-promotions-and-discounts-feature.md
  docs/pbc/all/discount-management/202212.0/install-and-upgrade/install-the-promotions-and-discounts-product-labels-feature.md
  docs/pbc/all/discount-management/202304.0/install-and-upgrade/install-the-promotions-and-discounts-product-labels-feature.md
Labels: ready for merge

#1627 Mentioned update to spryker/twig 3.15.2
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: ready for merge

#1629 SUPESC-606 Updated Availability Notification IG with stores to Yves host mapping configuration.
  _includes/pbc/all/install-features/202304.0/install-the-availability-notification-feature.md
  docs/pbc/all/warehouse-management-system/202304.0/install-and-upgrade/install-features/install-the-availability-notification-feature.md
Labels: ready for merge

#1637 Contributor gabriel 3
  docs/scos/dev/back-end-development/data-manipulation/data-publishing/handle-data-with-publish-and-synchronization.md
Labels: ready for merge, contributor

#1506 CC-25347: publisher trigger plugins integration guide
  _data/sidebars/marketplace_dev_sidebar.yml
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202304.0/install-the-alternative-products-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-category-image-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-file-manager-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-product-labels-feature.md
  _includes/pbc/all/install-features/202304.0/install-the-product-lists-feature.md
  docs/marketplace/dev/feature-integration-guides/202304.0/marketplace-product-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202304.0/marketplace-product-offer-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202304.0/marketplace-product-offer-prices-feature-integration.md
  docs/marketplace/dev/feature-integration-guides/202304.0/marketplace-product-options-feature-integration.md
  docs/pbc/all/content-management-system/202212.0/file-manager-feature-overview.md
  docs/pbc/all/content-management-system/202304.0/install-and-upgrade/install-features/install-the-file-manager-feature.md
  docs/pbc/all/product-information-management/202304.0/install-and-upgrade/install-features/install-the-alternative-products-feature.md
  docs/pbc/all/product-information-management/202304.0/install-and-upgrade/install-features/install-the-category-image-feature.md
  docs/pbc/all/product-information-management/202304.0/install-and-upgrade/install-features/install-the-product-labels-feature.md
  docs/pbc/all/product-information-management/202304.0/install-and-upgrade/install-features/install-the-product-lists-feature.md
Labels: ready for merge

#1638 Slightly adjusted Next steps section
  docs/scos/dev/troubleshooting/troubleshooting-performance-issues/troubleshooting-performance-issues.md
Labels: ready for merge

#1636 include link to the integration guide.
  docs/scos/dev/glue-api-guides/202212.0/decoupled-glue-infrastructure/how-to-guides/how-to-create-protected-endpoints.md
Labels: ready for merge

#1639 Added documentation from SOL-315 (parent ticket - SOL-265)
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/troubleshooting/troubleshooting-performance-issues/redis-session-lock.md
  docs/scos/dev/troubleshooting/troubleshooting-performance-issues/slow-p-and-s.md
Labels: ready for merge

#1635 CC-26077 Updated Product Category IG with changes in relation update plugin stack.
  _includes/pbc/all/install-features/202304.0/install-the-product-category-feature.md
  docs/pbc/all/product-information-management/202304.0/install-and-upgrade/install-features/install-the-product-category-feature.md
Labels: ready for merge

#1642 Contributor: Wrong importer type
  docs/scos/dev/data-import/202212.0/creating-a-data-importer.md
Labels: ready for merge, contributor
