Repository spryker/spryker-docs, pull requests merged in 2023-12, with the labels that each got.

#2367 Adjusting the result set value
  _includes/search/algolia_quicksearch.html
Labels: small changes

#2334 CC-31739 Update FE parts of Service Point and Shipment Type integrations
  _includes/pbc/all/install-features/202311.0/install-the-service-points-customer-account-management-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-shipment-customer-account-management-feature.md
Labels: TW review needed, updated, 202400

#2339 CC-31758: Show service point name on summary page
  _includes/pbc/all/install-features/202311.0/install-the-service-points-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-service-points-order-management-feature.md
Labels: TW review needed, updated, 202400

#2365 Update akeneo.md
  docs/pbc/all/product-information-management/202311.0/base-shop/third-party-integrations/akeneo/akeneo.md
Labels: small changes

#2368 Security release notes for Q4
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/releases/release-notes/security-release-notes-202312.0.md
Labels: tech review needed, new

#2288 [DRAFT] Feature/mig 100 migrate migration program documentation v2
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/migration-concepts/migrate-to-paas/migrate-to-paas.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-1-integrate-the-docker-sdk.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-10-add-frontend-assets.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-11-wire-custom-services.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-12-choose-a-multi-store-setup.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-13-migrate-database.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-14-finalize-the-migration.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-2-upgrade-the-php-version.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-3-migrate-non-standard-services.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-4-provision-the-spryker-paas-environments.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-5-define-the-deployment-strategy.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-6-define-environment-variables.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-7-restore-es-and-redis.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-8-adapt-the-filesystem-based-features.md
  docs/scos/dev/migration-concepts/migrate-to-paas/step-9-implement-security-and-performance-guidelines.md
Labels: new

#2371 Generate docs release notes for 11.2023
  .github/workflows/build-changelog.yml
  docs/scos/dev/migration-concepts/migrate-to-paas/migrate-to-paas.md
Labels: small changes

#1741 docs: technology
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202212.0/oryx/getting-started/oryx-technology.md
  docs/scos/dev/front-end-development/202307.0/oryx/getting-started/oryx-technology.md
  docs/scos/dev/front-end-development/202311.0/oryx/getting-started/oryx-technology.md
Labels: 202400

#2380 Docs updates 11.2023
  docs/pbc/all/product-information-management/202311.0/base-shop/install-and-upgrade/decimal-stock-migration-concept.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/configure-vertex.md
  docs/scos/user/intro-to-spryker/docs-updates.md
Labels: small changes

#2261 Update integrating-authorization-enabler.md
  docs/scos/dev/technical-enhancement-integration-guides/integrating-authorization-enabler.md
Labels: small changes

#2330 Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: TW review needed, updated

#2385 Update configure-vertex.md - fix broken link
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/configure-vertex.md
Labels: small changes

#2386 Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: updated

#2377 CnC api guides
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/glue-api-guides/202311.0/carts-response-attributes.md
  _includes/pbc/all/glue-api-guides/202311.0/checkout-data-request-attributes.md
  _includes/pbc/all/glue-api-guides/202311.0/checkout-data-response-attributes.md
  _includes/pbc/all/glue-api-guides/202311.0/order-shipments-response-attributes.md
  _includes/pbc/all/glue-api-guides/202311.0/orders-response-attributes.md
  _includes/pbc/all/glue-api-guides/202311.0/service-point-addresses-response-attributes.md
  _includes/pbc/all/glue-api-guides/202311.0/service-points-response-attributes.md
  _includes/pbc/all/glue-api-guides/202311.0/service-types-response-attributes.md
  _includes/pbc/all/glue-api-guides/202311.0/services-response-attributes.md
  _includes/pbc/all/glue-api-guides/202311.0/shipment-types-response-attributes.md
  _includes/pbc/all/glue-api-guides/202311.0/submit-checkout-data-response-attributes.md
  _includes/pbc/all/install-features/202204.0/install-glue-api/install-the-checkout-glue-api.md
  _includes/pbc/all/install-features/202212.0/install-glue-api/install-the-checkout-glue-api.md
  _includes/pbc/all/install-features/202307.0/install-glue-api/install-the-checkout-glue-api.md
  _includes/pbc/all/install-features/202311.0/install-glue-api/install-the-checkout-glue-api.md
  docs/pbc/all/carrier-management/202204.0/base-shop/install-and-upgrade/install-the-shipment-glue-api.md
  docs/pbc/all/carrier-management/202204.0/base-shop/shipment-feature-overview.md
  docs/pbc/all/carrier-management/202212.0/base-shop/install-and-upgrade/install-the-shipment-glue-api.md
  docs/pbc/all/carrier-management/202212.0/base-shop/shipment-feature-overview.md
  docs/pbc/all/carrier-management/202307.0/base-shop/install-and-upgrade/install-the-shipment-glue-api.md
  docs/pbc/all/carrier-management/202307.0/base-shop/shipment-feature-overview.md
  docs/pbc/all/carrier-management/202311.0/base-shop/install-and-upgrade/install-the-shipment-glue-api.md
  docs/pbc/all/carrier-management/202311.0/base-shop/manage-using-glue-api/glue-api-retrieve-shipments-and-shipment-methods-when-submitting-checkout-data.md
  docs/pbc/all/carrier-management/202311.0/base-shop/manage-using-glue-api/glue-api-retrieve-shipments-in-orders.md
  docs/pbc/all/carrier-management/202311.0/base-shop/manage-using-glue-api/manage-shipment-types/glue-api-add-shipment-types.md
  docs/pbc/all/carrier-management/202311.0/base-shop/manage-using-glue-api/manage-shipment-types/glue-api-retrieve-shipment-types.md
  docs/pbc/all/carrier-management/202311.0/base-shop/manage-using-glue-api/manage-shipment-types/glue-api-update-shipment-types.md
  docs/pbc/all/carrier-management/202311.0/base-shop/shipment-feature-overview.md
  docs/pbc/all/cart-and-checkout/202311.0/base-shop/manage-using-glue-api/check-out/glue-api-submit-checkout-data.md
  docs/pbc/all/cart-and-checkout/202311.0/base-shop/manage-using-glue-api/glue-api-retrieve-customer-carts.md
  docs/pbc/all/discount-management/202311.0/base-shop/manage-using-glue-api/glue-api-retrieve-discounts-in-customer-carts.md
  docs/pbc/all/offer-management/202311.0/marketplace/render-merchant-product-offers-on-the-storefront.md
  docs/pbc/all/offer-management/202311.0/unified-commerce/glue-api-retrieve-product-offer-service-point-availability.md
  docs/pbc/all/order-management-system/202212.0/base-shop/install-and-upgrade/install-glue-api/install-the-shipment-glue-api.md
  docs/pbc/all/order-management-system/202307.0/base-shop/install-and-upgrade/install-glue-api/install-the-shipment-glue-api.md
  docs/pbc/all/order-management-system/202311.0/base-shop/glue-api-retrieve-orders.md
  docs/pbc/all/order-management-system/202311.0/base-shop/install-and-upgrade/install-glue-api/install-the-shipment-glue-api.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-service-point-addresses/glue-api-add-service-point-addresses.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-service-point-addresses/glue-api-retrieve-service-point-addresses.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-service-point-addresses/glue-api-update-service-point-addresses.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-service-points/glue-api-add-service-points.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-service-points/glue-api-retrieve-service-points.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-service-points/glue-api-update-service-points.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-service-types/glue-api-add-service-types.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-service-types/glue-api-retrieve-service-types.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-service-types/glue-api-update-service-types.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-services/glue-api-add-services.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-services/glue-api-retrieve-services.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-services/glue-api-update-services.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/service-points-feature-overview.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/manage-using-glue-api/glue-api-authenticate-as-a-warehouse-user.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/manage-using-glue-api/manage-picklists/glue-api-pick-picklist-items.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/manage-using-glue-api/manage-picklists/glue-api-retrieve-picklists.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/manage-using-glue-api/manage-picklists/glue-api-start-picking.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/manage-using-glue-api/manage-warehouse-user-assignments/glue-api-create-warehouse-user-assignments.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/manage-using-glue-api/manage-warehouse-user-assignments/glue-api-delete-warehouse-user-assignments.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/manage-using-glue-api/manage-warehouse-user-assignments/glue-api-retrieve-warehouse-user-assignments.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/manage-using-glue-api/manage-warehouse-user-assignments/glue-api-update-warehouse-user-assignments.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202212.0/release-notes-202212.0.md
Labels: new

#2374 SDK-5414: As a PBC developer I want to have a clear single onboarding…
  _data/sidebars/acp_user_sidebar.yml
  docs/acp/user/app-configuration-translation.md
  docs/acp/user/develop-an-app/code-snippets/configuration-json-file.md
  docs/acp/user/develop-an-app/code-snippets/manifest-json-file.md
  docs/acp/user/develop-an-app/code-snippets/translation-json-file.md
  docs/acp/user/develop-an-app/debug-an-app-with-xdebug.md
  docs/acp/user/develop-an-app/develop-an-app.md
  docs/acp/user/develop-an-app/set-up-the-message-broker.md
  docs/acp/user/developing-an-app/create-an-app-with-appkernel.md
  docs/acp/user/developing-an-app/developing-an-app.md
  docs/acp/user/intro-to-acp/acp-overview.md
  docs/scos/user/intro-to-spryker/docs-updates.md
Labels: new

#2326 SDK-5414: Fix the typos in documentation
  _data/sidebars/acp_user_sidebar.yml
  docs/acp/user/app-composition-platform-installation.md
  docs/acp/user/app-configuration-translation.md
  docs/acp/user/async-api.md
  docs/acp/user/develop-an-app/code-snippets/configuration-json-file.md
  docs/acp/user/develop-an-app/code-snippets/manifest-json-file.md
  docs/acp/user/develop-an-app/code-snippets/translation-json-file.md
  docs/acp/user/develop-an-app/debug-an-app-with-xdebug.md
  docs/acp/user/develop-an-app/develop-an-app.md
  docs/acp/user/develop-an-app/set-up-the-message-broker.md
  docs/acp/user/developing-an-app/create-an-app with-appkernel.md
  docs/acp/user/developing-an-app/developing-an-app.md
  docs/acp/user/intro-to-acp/acp-overview.md
  docs/scos/user/intro-to-spryker/docs-updates.md
Labels: small changes

#2400 SDK-5414: As a PBC developer I want to have a clear single onboarding…
  docs/acp/user/develop-an-app/develop-an-app.md
Labels: small changes

#2399 Email service section
  _data/sidebars/ca_dev_sidebar.yml
  docs/ca/dev/email-service/email-quota-restrictions.md
  docs/ca/dev/email-service/email-service.md
  docs/ca/dev/email-service/verify-email-addresses.md
  docs/ca/dev/preparation-for-going-live.md
  docs/ca/dev/set-up-dns.md
Labels: new

#2402 ACP security tips
  _data/sidebars/acp_user_sidebar.yml
  docs/acp/user/develop-an-app/develop-an-app.md
  docs/acp/user/intro-to-acp/acp-security-tips.md
Labels: new

#2393 Password reset workflow improvements
  _includes/pbc/all/install-features/202403.0/install-the-customer-account-management-feature.md
  _includes/pbc/all/install-features/202403.0/install-the-spryker-core-back-office-feature.md
  _includes/pbc/all/install-features/202403.0/marketplace/install-the-marketplace-merchant-portal-core-feature.md
Labels: tech review needed, updated

#2398 Update the security release notes of Q4
  docs/scos/user/intro-to-spryker/releases/release-notes/security-release-notes-202312.0.md
Labels: TW review needed, updated

#2405 Update data-exchange.md - Minor updates on Data Exchange API explanation.
  docs/pbc/all/data-exchange/202311.0/data-exchange.md
Labels: small changes

#2395 Add Jarvis deprecation notice.
  docs/scos/dev/updating-spryker/analyzing-and-upgrading-projects-with-spryker-jarvis.md
Labels: small changes

#2392 Add Spryker CI region information.
  docs/scu/dev/spryker-ci.md
  docs/scu/dev/spryker-code-upgrader.md
Labels: small changes

#2409 SDK-5637: Updated doc for security release integration
  docs/scu/dev/integrating-code-releases/integrating-security-releases.md
Labels: small changes

#2411 Update integrate-algolia.md
  docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
Labels: small changes
