Repository spryker/spryker-docs, pull requests merged in 2023-10, with the labels that each got.

#2209 Updating the changelog file
  .github/workflows/build-changelog.yml
Labels: small changes

#2210 Updating the changelog file
  .github/workflows/build-changelog.yml
Labels: small changes

#2215 PBC-3077 Update Vertex integration guide
  docs/pbc/all/tax-management/202400.0/base-shop/vertex/install-vertex.md
Labels: TW review needed, updated

#2221 FRW-6085 Adjusted documentations.
  docs/scos/dev/feature-integration-guides/202307.0/glue-api/data-exchange-api/install-the-data-exchange-api.md
  docs/scos/dev/glue-api-guides/202307.0/data-exchange-api/how-to-guides/how-to-send-request-in-data-exchange-api.md
Labels: updated

#2213 CC-29683 Extend the shipment feature IG.
  _includes/pbc/all/install-features/202400.0/install-the-shipment-feature.md
Labels: TW review needed, 202400

#2145 CC-30986 Added configuration to disable quote persisting during the `checkout-data` request
  _includes/pbc/all/install-features/202400.0/install-glue-api/install-the-checkout-glue-api.md
  _includes/pbc/all/install-features/202400.0/install-the-shipment-feature.md
Labels: updated, 202400

#2151 FRW-5799 Added Install the Data Exchange API + Inventory Management feature
  _data/sidebars/scos_dev_sidebar.yml
  _includes/pbc/all/install-features/202400.0/install-the-data-exchange-api-inventory-management-feature.md
  docs/scos/dev/feature-integration-guides/202307.0/glue-api/data-exchange-api/install-the-data-exchange-api-inventory-management-feature.md
Labels: in TW review, new

#2227 SDK-4691: updated minimum supported PHP version for Upgrader
  docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
Labels: small changes

#2216 Sec release notes q3
  _data/sidebars/scos_user_sidebar.yml
  docs/scos/user/intro-to-spryker/releases/release-notes/security-release-notes-202306.0.md
  docs/scos/user/intro-to-spryker/releases/release-notes/security-release-notes-202309.0.md
Labels: in TW review, new

#2225 fix: switch versions for Oryx reactivity docs
  docs/scos/dev/front-end-development/202212.0/oryx/architecture/reactivity/reactive-components.md
  docs/scos/dev/front-end-development/202307.0/oryx/architecture/reactivity/reactive-components.md
Labels: small changes

#2233 Fixing a link for tax management
  docs/pbc/all/tax-management/202307.0/base-shop/tax-feature-overview.md
Labels: small changes

#2205 Update spryker-middleware.md
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-middleware.md
Labels: small changes

#2204 Update install-and-configure-akeneo.md
  docs/pbc/all/product-information-management/202307.0/base-shop/third-party-integrations/akeneo/install-and-configure-akeneo.md
Labels: small changes

#2147 FRW-5858 Added description how to API specification file download in data exchange API.
  docs/scos/dev/drafts-dev/deapi_download_spec_button.png
  docs/scos/dev/drafts-dev/deapi_generation_in_progress.png
  docs/scos/dev/glue-api-guides/202307.0/data-exchange-api/how-to-guides/how-to-configure-data-exchange-api.md
Labels: in TW review, new

#2228 SDK-4621: Added info about configuration of the NPM checker
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/npm-checker.md
Labels: TW review needed, updated

#2238 SDK-4691: Added new requirement to Upgrader
  docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
Labels: TW review needed, small changes

#2219 Update spryker-cloud-commerce-os-management.md
  docs/cloud/dev/spryker-cloud-commerce-os/spryker-cloud-commerce-os-management.md
Labels: TW review needed, small changes

#2242 Data api howtos update
  _data/sidebars/pbc_all_sidebar.yml
  _data/sidebars/scos_dev_sidebar.yml
  docs/pbc/all/product-information-management/202204.0/base-shop/third-party-integrations/akeneo/akeneo-connector-eco-module-console-commands.md
  docs/pbc/all/product-information-management/202204.0/base-shop/third-party-integrations/akeneo/install-and-configure-akeneo-eco-module.md
  docs/pbc/all/product-information-management/202212.0/base-shop/third-party-integrations/akeneo/akeneo-connector-eco-module-console-commands.md
  docs/pbc/all/product-information-management/202212.0/base-shop/third-party-integrations/akeneo/install-and-configure-akeneo-eco-module.md
  docs/pbc/all/product-information-management/202307.0/base-shop/third-party-integrations/akeneo/akeneo-connector-eco-module-console-commands.md
  docs/pbc/all/product-information-management/202307.0/base-shop/third-party-integrations/akeneo/install-and-configure-akeneo-eco-module.md
  docs/scos/dev/back-end-development/data-manipulation/data-ingestion/spryker-link-middleware.md
  docs/scos/dev/glue-api-guides/202307.0/data-exchange-api/how-to-guides/how-to-configure-data-exchange-api.md
  docs/scos/dev/glue-api-guides/202307.0/data-exchange-api/how-to-guides/how-to-send-request-in-data-exchange-api.md
  docs/scos/dev/glue-api-guides/202307.0/dynamic-data-api/how-to-guides/how-to-configure-data-exchange-api.md
  docs/scos/dev/glue-api-guides/202307.0/dynamic-data-api/how-to-guides/how-to-send-request-in-data-exchange-api.md
Labels: small changes

#2187 docs: Oryx components
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202307.0/oryx/building-components/oryx-building-components.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-components/oryx-component-types.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-components/oryx-implementing-components.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-components/oryx-integrating-components.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-components/oryx-managing-component-options.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-components/oryx-providing-component-definitions.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-pages/oryx-pages.md
Labels: new

#2218 Update preparation-for-going-live.md
  docs/cloud/dev/spryker-cloud-commerce-os/preparation-for-going-live.md
Labels: small changes

#2232 SDK-2936: PYZ prefix issues
  _data/sidebars/scos_dev_sidebar.yml
  _data/sidebars/scu_dev_sidebar.yml
  docs/scos/dev/front-end-development/202307.0/oryx/building-components/oryx-implementing-components.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-components/oryx-integrating-components.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-components/oryx-providing-component-definitions.md
  docs/scu/dev/troubleshooting/entity-does-not-exist–pyz-prefix.md
Labels: TW review needed, new

#2236 FRW-2426 API Key authorization documentation
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/glue-api-guides/202307.0/authentication-and-authorization.md
  docs/scos/dev/glue-api-guides/202307.0/use-api-key-authorization.md
  docs/scos/dev/migration-concepts/migrate-to-decoupled-glue-infrastructure/decoupled-glue-infrastructure-integrate-api-key-authorization.md
Labels: in TW review, new

#2196 APPS-9624: Added new posible category.
  docs/acp/user/app-manifest.md
Labels: TW review needed, small changes

#2115 Testing guidelines update
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/guidelines/testing-guidelines/code-coverage.md
  docs/scos/dev/guidelines/testing-guidelines/executing-tests/execute-tests.md
  docs/scos/dev/guidelines/testing-guidelines/executing-tests/executing-tests.md
  docs/scos/dev/guidelines/testing-guidelines/executing-tests/test-console-commands.md
  docs/scos/dev/guidelines/testing-guidelines/executing-tests/test-the-publish-and-synchronization-process.md
  docs/scos/dev/guidelines/testing-guidelines/setting-up-tests.md
  docs/scos/dev/guidelines/testing-guidelines/test-framework.md
  docs/scos/dev/guidelines/testing-guidelines/test-helpers/available-test-helpers.md
  docs/scos/dev/guidelines/testing-guidelines/test-helpers/test-helpers-best-practices.md
  docs/scos/dev/guidelines/testing-guidelines/test-helpers/test-helpers.md
  docs/scos/dev/guidelines/testing-guidelines/testify.md
  docs/scos/dev/guidelines/testing-guidelines/testing-best-practices/best-practices-for-effective-testing.md
  docs/scos/dev/guidelines/testing-guidelines/testing-best-practices/test-types-best-practices.md
  docs/scos/dev/guidelines/testing-guidelines/testing-best-practices/testing-best-practices.md
  docs/scos/dev/guidelines/testing-guidelines/testing-best-practices/testing-concepts.md
Labels: tech review needed, new, updated

#2246 Data Exchange landing page and FAQ
  Rakefile
  _config.yml
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202311.0/install-the-data-exchange-api-inventory-management-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-data-exchange-api.md
  docs/pbc/all/data-exchange/202311.0/data-exchange-faq.md
  docs/pbc/all/data-exchange/202311.0/data-exchange.md
  docs/pbc/all/data-exchange/202311.0/install-and-upgrade/install-the-data-exchange-api-inventory-management-feature.md
  docs/pbc/all/data-exchange/202311.0/install-and-upgrade/install-the-data-exchange-api.md
  docs/pbc/all/data-exchange/202311.0/tutorials-and-howtoes/how-to-configure-data-exchange-api.md
  docs/pbc/all/data-exchange/202311.0/tutorials-and-howtoes/how-to-send-request-in-data-exchange-api.md
  docs/scos/dev/feature-integration-guides/202307.0/glue-api/data-exchange-api/install-the-data-exchange-api-inventory-management-feature.md
Labels: new

#2254 Fixing the data exchange docs
  docs/pbc/all/data-exchange/202311.0/data-exchange-faq.md
  docs/pbc/all/data-exchange/202311.0/data-exchange.md
Labels: small changes

#2241 PBC-1938 Added AsyncAPI test documentation.
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/guidelines/testing-guidelines/executing-tests/test-the-asynchronous-api.md
Labels: new

#2256 Fix wrong path for adding/overriding Zed translations
  docs/pbc/all/back-office/202307.0/back-office-translations-overview.md
Labels: TW review needed, small changes

#2257 fixing a code sample
  docs/pbc/all/tax-management/202400.0/third-party-integrations/vertex/install-vertex.md
Labels: small changes

#2231 SDK-4673: Integration of Code Releases into your project repository
  _data/sidebars/scu_dev_sidebar.yml
  algolia_config/_pbc_all.yml
  algolia_config/_scu_dev.yml
  algolia_config/_sdk_dev.yml
  docs/scos/dev/the-docker-sdk/202204.0/configure-services.md
  docs/scu/dev/integrating-code-releases/handling-upgrade-warnings.md
  docs/scu/dev/integrating-code-releases/integrating-code-releases.md
  docs/scu/dev/integrating-code-releases/integrating-security-releases.md
Labels: small changes

#2214 docs: Oryx's Responsive Design system
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202307.0/oryx/building-applications/styling/oryx-responsive-design.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-components/oryx-providing-component-definitions.md
Labels: new

#2208 SDK-2794: Add mentioning of the Spryker Code Upgrader on update Spryker page
  docs/scos/dev/back-end-development/extend-spryker/extend-spryker.md
  docs/scos/dev/updating-spryker/preventing-update-issues.md
  docs/scos/dev/updating-spryker/updating-spryker.md
  docs/scu/dev/spryker-code-upgrader-in-a-development-workflow.md
Labels: TW review needed, updated

#2250 Update Evaluator
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/additional-logic-in-dependency-provider.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/container-set-function.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/dead-code-checker.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/minimum-allowed-shop-version.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/multidimensional-array.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/npm-checker.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/open-source-vulnerabilities.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/php-version.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/plugin-registration-with-restrintions.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/single-plugin-argument.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/spryker-security-checker.md
Labels: updated

#2268 Updating the product feature ig
  _includes/pbc/all/install-features/202311.0/install-the-product-feature.md
  docs/pbc/all/product-information-management/202311.0/base-shop/install-and-upgrade/install-features/install-the-product-feature.md
Labels: updated

#2172 Update howto-schedule-cron-job-for-scheduled-prices.md
  docs/pbc/all/price-management/202307.0/base-shop/tutorials-and-howtos/howto-schedule-cron-job-for-scheduled-prices.md
Labels: small changes

#2177 Update configure-a-search-query.md
  docs/pbc/all/search/202307.0/base-shop/tutorials-and-howtos/configure-a-search-query.md
Labels: small changes

#2248 Update integrating-separate-endpoint-bootstraps.md
  docs/scos/dev/technical-enhancement-integration-guides/integrating-separate-endpoint-bootstraps.md
Labels: TW review needed, small changes

#2224 Install the Push Notification feature
  _includes/pbc/all/install-features/202311.0/install-the-push-notification-feature.md
Labels: TW review needed, updated, 202400

#2223 Install the Service Points Cart + Checkout feature
  _includes/pbc/all/install-features/202400.0/install-the-service-points-cart-checkout-feature.md
  _includes/pbc/all/install-features/202400.0/install-the-service-points-cart-feature.md
  docs/pbc/all/service-points/202400.0/unified-commerce/install-and-upgrade/install-the-service-points-cart-checkout-feature.md
Labels: TW review needed, updated, 202400

#2271 Adding redirects
  docs/pbc/all/data-exchange/202311.0/data-exchange.md
  docs/pbc/all/search/202311.0/base-shop/third-party-integrations/integrate-algolia.md
  docs/pbc/all/tax-management/202311.0/third-party-integrations/vertex/install-vertex.md
Labels: small changes

#2244 Update best-practises-jenkins-stability.md
  docs/ca/dev/best-practices/best-practises-jenkins-stability.md
  docs/pbc/all/content-management-system/202307.0/content-management-system.md
Labels: TW review needed, updated

#2273 SDK-4641 min requirements updates
  _includes/topnav.html
  docs/scu/dev/onboard-to-spryker-code-upgrader/prepare-a-project-for-spryker-code-upgrader.md
Labels: small changes

#2259 CC-30854 Setting address based on shipment type and service point selection
  _includes/pbc/all/install-features/202311.0/install-glue-api/install-the-checkout-glue-api.md
  _includes/pbc/all/install-features/202311.0/install-glue-api/install-the-shipment-glue-api.md
  _includes/pbc/all/install-features/202311.0/install-the-shipment-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-shipment-service-points-feature.md
Labels: TW review needed, updated, 202400

#2252 PBC-3110 Added description of data mapping between quote/order objects on Spryker side and Vertex API.
  docs/pbc/all/tax-management/202311.0/third-party-integrations/vertex/install-vertex.md
Labels: updated

#2270 Added information for product synchronization
  docs/pbc/all/search/202311.0/base-shop/third-party-integrations/integrate-algolia.md
Labels: updated

#2284 typo fix
  docs/pbc/all/search/202311.0/base-shop/third-party-integrations/integrate-algolia.md
Labels: small changes

#2267 How to guides
  _data/sidebars/pbc_all_sidebar.yml
  _data/sidebars/scos_dev_sidebar.yml
  _scripts/redirects_generator/redirect_from_generator.sh
  _scripts/redirects_generator/redirects_generator.sh
  docs/pbc/all/order-management-system/202212.0/base-shop/import-and-export-data/import-and-export-order-management-system-data.md
  docs/pbc/all/order-management-system/202212.0/base-shop/import-and-export-data/orders-data-export/export-file-details-order-expenses.csv.md
  docs/pbc/all/order-management-system/202212.0/base-shop/import-and-export-data/orders-data-export/export-file-details-order-items.csv.md
  docs/pbc/all/order-management-system/202212.0/base-shop/import-and-export-data/orders-data-export/export-file-details-orders.csv.md
  docs/pbc/all/order-management-system/202212.0/base-shop/import-and-export-data/orders-data-export/orders-data-export.md
  docs/pbc/all/order-management-system/202307.0/base-shop/import-and-export-data/import-and-export-order-management-system-data.md
  docs/pbc/all/order-management-system/202307.0/base-shop/import-and-export-data/orders-data-export/export-file-details-order-expenses.csv.md
  docs/pbc/all/order-management-system/202307.0/base-shop/import-and-export-data/orders-data-export/export-file-details-order-items.csv.md
  docs/pbc/all/order-management-system/202307.0/base-shop/import-and-export-data/orders-data-export/export-file-details-orders.csv.md
  docs/pbc/all/order-management-system/202307.0/base-shop/import-and-export-data/orders-data-export/orders-data-export.md
  docs/pbc/all/payment-service-provider/202212.0/base-shop/debug-payment-integrations-locally.md
  docs/pbc/all/payment-service-provider/202307.0/base-shop/debug-payment-integrations-locally.md
  docs/pbc/all/price-management/202204.0/base-shop/tutorials-and-howtos/howto-create-personalized-prices.md
  docs/pbc/all/price-management/202204.0/base-shop/tutorials-and-howtos/howto-handle-twenty-five-million-prices-in-spryker-commerce-os.md
  docs/pbc/all/price-management/202204.0/base-shop/tutorials-and-howtos/howto-manage-business-unit-specific-prices-via-data-import.md
  docs/pbc/all/price-management/202204.0/base-shop/tutorials-and-howtos/howto-schedule-cron-job-for-scheduled-prices.md
  docs/pbc/all/price-management/202212.0/base-shop/tutorials-and-howtos/create-personalized-prices.md
  docs/pbc/all/price-management/202212.0/base-shop/tutorials-and-howtos/handle-twenty-five-million-prices-in-spryker-commerce-os.md
  docs/pbc/all/price-management/202212.0/base-shop/tutorials-and-howtos/manage-business-unit-specific-prices-via-data-import.md
  docs/pbc/all/price-management/202212.0/base-shop/tutorials-and-howtos/schedule-cron-job-for-scheduled-prices.md
  docs/pbc/all/price-management/202307.0/base-shop/tutorials-and-howtos/create-personalized-prices.md
  docs/pbc/all/price-management/202307.0/base-shop/tutorials-and-howtos/handle-twenty-five-million-prices-in-spryker-commerce-os.md
  docs/pbc/all/price-management/202307.0/base-shop/tutorials-and-howtos/manage-business-unit-specific-prices-via-data-import.md
  docs/pbc/all/price-management/202307.0/base-shop/tutorials-and-howtos/schedule-cron-job-for-scheduled-prices.md
  docs/scos/dev/data-import/202212.0/data-export.md
  docs/scos/dev/glue-api-guides/202204.0/configure-cross-origin-resource-sharing-for-glue-api.md
  docs/scos/dev/glue-api-guides/202204.0/configure-the-included-section.md
  docs/scos/dev/glue-api-guides/202204.0/integrate-a-ciam-provider.md
  docs/scos/dev/glue-api-guides/202212.0/configure-cross-origin-resource-sharing-for-glue-api.md
  docs/scos/dev/glue-api-guides/202212.0/configure-the-included-section.md
  docs/scos/dev/glue-api-guides/202212.0/integrate-a-ciam-provider.md
  docs/scos/dev/glue-api-guides/202307.0/configure-cross-origin-resource-sharing-for-glue-api.md
  docs/scos/dev/glue-api-guides/202307.0/configure-the-included-section.md
  docs/scos/dev/glue-api-guides/202307.0/glue-api-guides.md
  docs/scos/dev/glue-api-guides/202307.0/integrate-a-ciam-provider.md
  docs/scos/dev/tutorials-and-howtos/howtos/about-howtos.md
  docs/scos/dev/tutorials-and-howtos/howtos/glue-api-howtos/glue-api-howtos.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-install-spryker-in-aws-environment.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/general-rules-and-guidance-for-adding-new-documents.md
Labels: updated

#2193 Install the Product Offer Service Points Availability feature
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202311.0/install-the-product-offer-service-points-availability-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-shipment-product-offer-service-points-availability-feature.md
  _includes/pbc/all/install-features/202311.0/marketplace/install-the-marketplace-merchant-product-offer-service-points-availability-feature.md
  docs/pbc/all/offer-management/202311.0/marketplace/install-and-upgrade/install-the-marketplace-merchant-product-offer-service-points-availability-feature.md
  docs/pbc/all/service-points/202311.0/unified-commerce/install-and-upgrade/install-the-product-offer-service-points-availability-feature.md
  docs/pbc/all/service-points/202311.0/unified-commerce/install-and-upgrade/install-the-shipment-product-offer-service-points-availability-feature.md
Labels: TW review needed, updated, 202400
