Repository spryker/spryker-docs, pull requests merged in 2023-11, with the labels that each got.

#2290 CC-25963 Update chart module migration
  _includes/pbc/all/upgrade-modules/upgrade-the-chart-module.md
  docs/pbc/all/order-management-system/202307.0/base-shop/import-and-export-data/orders-data-export/orders-data-export.md
Labels: updated

#2302 Update system-requirements.md
  docs/scos/dev/system-requirements/202307.0/system-requirements.md
  docs/scos/user/intro-to-spryker/whats-new/supported-versions-of-php.md
Labels: updated, 202400

#2299 Vertex configuration
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/configure-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/disconnect-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/install-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/vertex.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202311.0/release-notes-202311.0.md
Labels: new

#2304 Changelog file for 10.2023
  .github/workflows/build-changelog.yml
Labels: small changes

#2303 Docs updates 10.2023
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
  docs/scos/user/intro-to-spryker/docs-updates.md
Labels: small changes

#2281 Update environment-provisioning.md
  docs/ca/dev/environment-provisioning.md
Labels: updated

#2287 Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: updated

#2283 Update general-performance-guidelines.md
  docs/scos/dev/guidelines/performance-guidelines/general-performance-guidelines.md
Labels: TW review needed, updated

#2296 Akeneo PIM app configuration in Alumio
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/data-exchange/202311.0/data-exchange.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/configure-data-mapping-between-akeneo-and-sccos.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/configure-the-data-integration-path-between-akeneo-and-sccos.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/configure-the-smpa-connection-with-akeneo-pim-and-sccos.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/create-tasks-and-import-products-from-akeneo-to-sccos.md
Labels: new

#2311 Akeneo Multiselect attributes guide
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/configure-data-mapping-between-akeneo-and-sccos.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/configure-the-data-integration-path-between-akeneo-and-sccos.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/configure-the-smpa-connection-with-akeneo-pim-and-sccos.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/create-tasks-and-import-products-from-akeneo-to-sccos.md
Labels: small changes

#2313 Fixing akeneo pages
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/configure-data-mapping-between-akeneo-and-sccos.md
Labels: small changes

#2314 Update data-exchange.md
  docs/pbc/all/data-exchange/202311.0/data-exchange.md
Labels: small changes

#2286 Updated IGs.
  _includes/pbc/all/install-features/202311.0/install-the-product-offer-service-points-availability-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-product-offer-shipment-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-product-offer-shipments-availability-feature.md
  _includes/pbc/all/install-features/202311.0/marketplace/install-the-marketplace-product-offer-service-points-feature.md
Labels: TW review needed, updated

#2188 CC-30494 Update Shipment Type Service Point IG
  _includes/pbc/all/install-features/202311.0/install-the-shipment-service-points-feature.md
  docs/pbc/all/customer-relationship-management/202307.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-business-unit-addresses.md
  docs/pbc/all/customer-relationship-management/202307.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-business-units.md
  docs/pbc/all/customer-relationship-management/202307.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-companies.md
  docs/pbc/all/customer-relationship-management/202307.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-company-roles.md
  docs/pbc/all/customer-relationship-management/202307.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-company-users.md
  docs/pbc/all/customer-relationship-management/202307.0/base-shop/manage-using-glue-api/company-account/glue-api-search-by-company-users.md
  docs/pbc/all/customer-relationship-management/202307.0/base-shop/manage-using-glue-api/customers/glue-api-manage-customer-addresses.md
  docs/pbc/all/customer-relationship-management/202307.0/base-shop/manage-using-glue-api/customers/glue-api-manage-customers.md
  docs/pbc/all/customer-relationship-management/202307.0/base-shop/manage-using-glue-api/manage-customer-access-to-glue-api-resources.md
  docs/pbc/all/discount-management/202307.0/base-shop/create-discounts-based-on-shipment.md
  docs/pbc/all/discount-management/202307.0/base-shop/manage-via-glue-api/manage-discount-vouchers-in-carts-of-registered-users.md
  docs/pbc/all/discount-management/202307.0/base-shop/manage-via-glue-api/manage-discount-vouchers-in-guest-carts.md
  docs/pbc/all/discount-management/202307.0/base-shop/manage-via-glue-api/manage-discounts-via-glue-api.md
  docs/pbc/all/discount-management/202307.0/base-shop/manage-via-glue-api/retrieve-discounts-in-carts-of-registered-users.md
  docs/pbc/all/discount-management/202307.0/base-shop/manage-via-glue-api/retrieve-discounts-in-customer-carts.md
  docs/pbc/all/gift-cards/202307.0/manage-using-glue-api/manage-gift-cards-of-guest-users.md
  docs/pbc/all/gift-cards/202307.0/manage-using-glue-api/manage-gift-cards-of-registered-users.md
  docs/pbc/all/identity-access-management/202307.0/configure-basic-htaccess-authentication.md
  docs/pbc/all/identity-access-management/202307.0/identity-access-management.md
  docs/pbc/all/identity-access-management/202307.0/manage-using-glue-api/glue-api-authenticate-as-a-company-user.md
  docs/pbc/all/identity-access-management/202307.0/manage-using-glue-api/glue-api-authenticate-as-a-customer.md
  docs/pbc/all/identity-access-management/202307.0/manage-using-glue-api/glue-api-authenticate-as-an-agent-assist.md
  docs/pbc/all/identity-access-management/202307.0/manage-using-glue-api/glue-api-confirm-customer-registration.md
  docs/pbc/all/identity-access-management/202307.0/manage-using-glue-api/glue-api-delete-expired-refresh-tokens.md
  docs/pbc/all/identity-access-management/202307.0/manage-using-glue-api/glue-api-manage-agent-assist-authentication-tokens.md
  docs/pbc/all/identity-access-management/202307.0/manage-using-glue-api/glue-api-manage-company-user-authentication-tokens.md
  docs/pbc/all/identity-access-management/202307.0/manage-using-glue-api/glue-api-manage-customer-authentication-tokens-via-oauth-2.0.md
  docs/pbc/all/identity-access-management/202307.0/manage-using-glue-api/glue-api-manage-customer-authentication-tokens.md
  docs/pbc/all/identity-access-management/202307.0/manage-using-glue-api/glue-api-manage-customer-passwords.md
  docs/pbc/all/identity-access-management/202307.0/manage-using-glue-api/glue-api-retrieve-protected-resources.md
  docs/pbc/all/order-management-system/202307.0/base-shop/glue-api-retrieve-orders.md
Labels: TW review needed, updated, 202400

#2308 Vertex overview page
  _data/sidebars/pbc_all_sidebar.yml
  _data/sidebars/scos_user_sidebar.yml
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/configure-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/vertex-faq.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/vertex.md
  docs/pbc/all/tax-management/202311.0/tax-management.md
Labels: new

#2318 Vertex video fix
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/vertex.md
Labels: small changes

#2202 Updated guidelines for security, performance, quality, upgradability, coding and architecture
  docs/scos/dev/guidelines/coding-guidelines/code-architecture-guide.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/additional-logic-in-dependency-provider.md
  docs/scos/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/upgradability-guidelines.md
  docs/scos/dev/guidelines/performance-guidelines/architecture-performance-guidelines.md
  docs/scos/dev/guidelines/project-development-guidelines.md
  docs/scos/dev/guidelines/security-guidelines.md
Labels: in TW review, updated

#2322 Fixed Redirect
  docs/pbc/all/cart-and-checkout/202204.0/base-shop/feature-overviews/approval-process-feature-overview.md
Labels: small changes

#2321 Alumio landing pages
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/data-exchange/202311.0/custom-integrations-with-alumio-connectors.md
  _includes/pbc/all/data-exchange/202311.0/custom-integrations-with-custom-connectors.md
  _includes/pbc/all/data-exchange/202311.0/spryker-integration-apps.md
  _includes/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio.md
  docs/pbc/all/data-exchange/202311.0/data-exchange.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/akeneo-pim-integration-app.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/configure-data-mapping-between-akeneo-and-sccos.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/integration-apps.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/spryker-middleware-powered-by-alumio.md
Labels: new

#2331 Update vertex-faq.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/vertex-faq.md
Labels: small changes

#2333 Adding landing pages to sidebar
  _data/sidebars/pbc_all_sidebar.yml
Labels: small changes

#2298 CC-31740: Fixes to the FA and C&C integration guides.
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202311.0/install-the-inventory-management-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-product-offer-shipment-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-service-points-cart-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-service-points-feature.md
  _includes/pbc/all/install-features/202311.0/unified-commerce/install-the-warehouse-picking-feature.md
  _includes/pbc/all/install-features/202311.0/unified-commerce/install-the-warehouse-user-management-feature.md
Labels: TW review needed, updated, 202400

#2332 CC-31210: Introduced the updated OpenApi schema files for the upcoming release.
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/glue-api-guides/202311.0/backend-glue-infrastructure/backend-api-marketplace-b2b-demo-shop-reference.md
  docs/scos/dev/glue-api-guides/202311.0/backend-glue-infrastructure/backend-api-marketplace-b2c-demo-shop-reference.md
  docs/scos/dev/glue-api-guides/202311.0/old-glue-infrastructure/rest-api-marketplace-b2b-demo-shop-reference.md
  docs/scos/dev/glue-api-guides/202311.0/old-glue-infrastructure/rest-api-marketplace-b2c-demo-shop-reference.md
Labels: updated, 202400

#2336 Release notes 202311.0
  _data/sidebars/scos_user_sidebar.yml
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/akeneo-pim-integration-app.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202311.0/release-notes-202311.0.md
Labels: new

#2319 Fixed redirects in this page
  docs/sdk/dev/development-tools/development-tools.md
Labels: small changes

#2320 Redirect fixes on a couple of pages
  docs/scos/dev/architecture/module-api/performance-and-scalability.md
  docs/scos/dev/guidelines/performance-guidelines/front-end-performance-guidelines.md
  docs/scos/dev/guidelines/performance-guidelines/general-performance-guidelines.md
  docs/scos/dev/guidelines/performance-guidelines/performance-guidelines.md
Labels: small changes

#2324 Fixed Redirect
  docs/ca/dev/multi-store-setups/multistore-setup-options.md
Labels: small changes

#2338 Update ACP app-configuration page
  _data/sidebars/scos_user_sidebar.yml
  docs/acp/user/app-configuration.md
Labels: small changes

#2325 CC-31568: Extended the warehouse picking guide with the FA OAuth.
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202311.0/unified-commerce/install-the-warehouse-picking-feature.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/warehouse-picking-feature-overview.md
Labels: updated, 202400

#2340 fix deploy
  .github/workflows/ci.yml
  Gemfile
  Gemfile.lock
  Rakefile
Labels: small changes

#2174 CC-26648 Integration guides.
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202311.0/install-the-product-offer-service-points-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-product-offer-shipment-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-service-points-feature.md
  _includes/pbc/all/install-features/202311.0/marketplace/install-the-marketplace-merchant-portal-product-offer-management-feature.md
  _includes/pbc/all/install-features/202311.0/marketplace/install-the-marketplace-merchant-portal-product-offer-service-points-feature.md
  _includes/pbc/all/install-features/202311.0/marketplace/install-the-marketplace-merchant-portal-product-offer-shipment-feature.md
  docs/pbc/all/offer-management/202311.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-product-offer-shipment-feature.md
  docs/pbc/all/offer-management/202311.0/unified-commerce/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-product-offer-service-points-feature.md
  docs/pbc/all/offer-management/202311.0/unified-commerce/install-and-upgrade/install-features/install-the-marketplace-merchant-product-offer-service-points-availability-feature.md
  docs/pbc/all/offer-management/202311.0/unified-commerce/install-and-upgrade/install-features/install-the-marketplace-product-offer-service-points-feature.md
  docs/pbc/all/offer-management/202311.0/unified-commerce/install-and-upgrade/install-features/install-the-product-offer-service-points-feature.md
  docs/pbc/all/offer-management/202311.0/unified-commerce/install-and-upgrade/install-features/install-the-product-offer-shipment-feature.md
  docs/scos/user/intro-to-spryker/docs-updates.md
Labels: TW review needed, new, updated

#2342 Release notes 202311.0 fix
  _data/sidebars/pbc_all_sidebar.yml
  _includes/footer.html
  docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-configure-data-exchange-api.md
  docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-send-request-in-data-exchange-api.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202311.0/release-notes-202311.0.md
Labels: small changes

#2345 Fixing the service point PBC
  _config.yml
  _data/sidebars/pbc_all_sidebar.yml
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202311.0/release-notes-202311.0.md
Labels: small changes

#2341 202311 version links fix
  Rakefile
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio.md
  docs/pbc/all/back-office/202311.0/base-shop/back-office-translations-overview.md
  docs/pbc/all/back-office/202311.0/base-shop/install-and-upgrade/install-the-back-office-number-formatting.md
  docs/pbc/all/back-office/202311.0/base-shop/install-and-upgrade/install-the-spryker-core-back-office-feature.md
  docs/pbc/all/back-office/202311.0/base-shop/install-and-upgrade/upgrade-the-chart-module.md
  docs/pbc/all/back-office/202311.0/base-shop/manage-in-the-back-office/view-dashboard.md
  docs/pbc/all/back-office/202311.0/base-shop/spryker-core-back-office-feature-overview.md
  docs/pbc/all/carrier-management/202311.0/base-shop/import-and-export-data/import-file-details-shipment-method-shipment-type.csv.md
  docs/pbc/all/carrier-management/202311.0/base-shop/install-and-upgrade/install-features/install-the-shipment-cart-feature.md
  docs/pbc/all/carrier-management/202311.0/base-shop/install-and-upgrade/install-features/install-the-shipment-feature.md
  docs/pbc/all/carrier-management/202311.0/base-shop/shipment-feature-overview.md
  docs/pbc/all/data-exchange/202311.0/install-and-upgrade/install-the-data-exchange-api-inventory-management-feature.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/integration-apps.md
  docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-configure-data-exchange-api.md
  docs/pbc/all/merchant-management/202212.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-product-offer-management-feature.md
  docs/pbc/all/merchant-management/202311.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-core-feature.md
  docs/pbc/all/miscellaneous/202311.0/push-notification-feature-overview.md
  docs/pbc/all/offer-management/202307.0/marketplace/marketplace-product-offer-feature-overview.md
  docs/pbc/all/offer-management/202311.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-product-offer-management-feature.md
  docs/pbc/all/offer-management/202311.0/marketplace/install-and-upgrade/install-features/install-the-product-offer-shipment-availability-feature.md
  docs/pbc/all/offer-management/202311.0/marketplace/install-and-upgrade/install-features/install-the-product-offer-shipment-feature.md
  docs/pbc/all/offer-management/202311.0/marketplace/marketplace-product-offer-feature-overview.md
  docs/pbc/all/offer-management/202311.0/unified-commerce/install-features/install-the-product-offer-service-points-availability-feature.md
  docs/pbc/all/offer-management/202311.0/unified-commerce/install-features/install-the-product-offer-service-points-feature.md
  docs/pbc/all/order-management-system/202311.0/base-shop/install-and-upgrade/install-features/install-the-order-management-feature.md
  docs/pbc/all/product-information-management/202311.0/base-shop/manage-using-glue-api/abstract-products/glue-api-retrieve-abstract-products.md
  docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/install-features/install-the-service-points-cart-feature.md
  docs/pbc/all/tax-management/202311.0/base-shop/manage-using-glue-api/retrieve-tax-sets.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/install-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/vertex.md
  docs/pbc/all/tax-management/202311.0/tax-management.md
  docs/pbc/all/warehouse-management-system/202311.0/base-shop/install-and-upgrade/install-features/install-the-inventory-management-feature.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/install-and-upgrade/install-the-warehouse-user-management-feature.md
  docs/scos/dev/technical-enhancement-integration-guides/install-combined-product-offer-import.md
  docs/scos/user/intro-to-spryker/spryker-marketplace/merchant-onboarding.md
Labels: small changes

#2347 202311 release clean-up
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/offer-management/202311.0/unified-commerce/marketplace-merchant-portal-product-offer-service-point-feature-overview.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/enable-click-collect.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/import-and-export-data/import-file-details-service-point-address.csv.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202311.0/release-notes-202311.0.md
Labels: updated

#2348 Changing the main docs version
  _config.yml
  _data/sidebars/scos_dev_sidebar.yml
  _data/sidebars/scos_user_sidebar.yml
  docs/pbc/all/offer-management/202311.0/offer-management.md
  docs/scos/dev/tutorials-and-howtos/howtos/how-to-make-a-multi-language-setup.html.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202212.0/release-notes-202212.0.md
Labels: small changes

#2352 oryx: rename boilerplate urls
  docs/scos/dev/front-end-development/202311.0/oryx/getting-started/oryx-boilerplate.md
  docs/scos/dev/front-end-development/202311.0/oryx/getting-started/set-up-oryx.md
Labels: updated

#2358 Adjusted Oryx boilerplate guide according to latest changes
  docs/scos/dev/front-end-development/202212.0/oryx/getting-started/oryx-boilerplate.md
  docs/scos/dev/front-end-development/202307.0/oryx/getting-started/oryx-boilerplate.md
  docs/scos/dev/front-end-development/202311.0/oryx/getting-started/oryx-boilerplate.md
Labels: small changes

#2351 Removed mentioning Elastica does not handle 413
  docs/pbc/all/price-management/202204.0/base-shop/tutorials-and-howtos/howto-handle-twenty-five-million-prices-in-spryker-commerce-os.md
Labels: TW review needed, small changes

#2359 Updating the PHP version for deployment pipelines docs
  docs/ca/dev/configure-deployment-pipelines/deployment-pipelines.md
  docs/scos/dev/the-docker-sdk/202307.0/the-docker-sdk.md
  docs/scos/dev/the-docker-sdk/202311.0/the-docker-sdk.md
Labels: updated

#2361 Update acp-overview.md
  docs/acp/user/intro-to-acp/acp-overview.md
Labels: small changes

#2363 Algolia results set fix
  _includes/search/algolia_quicksearch.html
Labels: small changes

#2364 Update akeneo-pim-integration-app.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/akeneo-pim-integration-app.md
Labels: small changes
