Repository spryker/spryker-docs, pull requests merged in 2024-01, with the labels that each got.

#2306 Update oryx-versioning.md
  docs/scos/dev/front-end-development/202307.0/oryx/getting-started/oryx-versioning.md
Labels: small changes

#2417 Fixed withProviders usage wrapped with array
  docs/scos/dev/front-end-development/202212.0/oryx/building-pages/oryx-pages.md
  docs/scos/dev/front-end-development/202212.0/oryx/building-pages/oryx-routing.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-pages/oryx-pages.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-pages/oryx-routing.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-pages/oryx-pages.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-pages/oryx-routing.md
Labels: small changes

#2346 Install the Checkout Glue API
  Rakefile
  _includes/pbc/all/install-features/202403.0/install-glue-api/install-the-checkout-glue-api.md
  docs/pbc/all/cart-and-checkout/202311.0/base-shop/feature-overviews/checkout-feature-overview/checkout-feature-overview.md
  docs/pbc/all/cart-and-checkout/202403.0/base-shop/feature-overviews/checkout-feature-overview/checkout-feature-overview.md
  docs/pbc/all/cart-and-checkout/202403.0/base-shop/install-and-upgrade/install-glue-api/install-the-checkout-glue-api.md
Labels: TW review needed, updated, 202400

#2378 Service Points feature overview
  docs/pbc/all/carrier-management/202311.0/base-shop/shipment-feature-overview.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/enable-click-collect.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/service-points-cart-checkout-feature-overview.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/service-points-feature-overview.md
Labels: updated

#2419 Packages article fixes: added resources packages, fixed path.
  docs/scos/dev/front-end-development/202212.0/oryx/getting-started/oryx-packages.md
  docs/scos/dev/front-end-development/202307.0/oryx/getting-started/oryx-packages.md
  docs/scos/dev/front-end-development/202311.0/oryx/getting-started/oryx-packages.md
Labels: small changes

#2418 Actualized boilerplate: replaced root-app with oryx-app.
  docs/scos/dev/front-end-development/202212.0/oryx/getting-started/oryx-boilerplate.md
  docs/scos/dev/front-end-development/202307.0/oryx/getting-started/oryx-boilerplate.md
  docs/scos/dev/front-end-development/202311.0/oryx/getting-started/oryx-boilerplate.md
Labels: small changes

#2415 Fa overview
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/order-management-system/202307.0/base-shop/import-and-export-data/orders-data-export/orders-data-export.md
  docs/pbc/all/order-management-system/202311.0/base-shop/manage-in-the-back-office/orders/change-the-state-of-order-items.md
  docs/pbc/all/order-management-system/202311.0/marketplace/manage-in-the-back-office/manage-marketplace-orders.md
  docs/pbc/all/user-management/202311.0/base-shop/manage-in-the-back-office/manage-users/create-users.md
  docs/pbc/all/user-management/202311.0/base-shop/manage-in-the-back-office/manage-users/edit-users.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/fulfillment-app-overview.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/set-up-fulfillment-app.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/warehouse-picking-feature-overview.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/warehouse-user-management-feature-overview.md
  docs/scos/dev/front-end-development/202307.0/oryx/getting-started/set-up-oryx.md
  docs/scos/dev/front-end-development/202311.0/oryx/getting-started/set-up-oryx.md
  docs/scos/user/intro-to-spryker/docs-updates.md
  docs/scos/user/intro-to-spryker/releases/release-notes/release-notes-202311.0/release-notes-202311.0.md
Labels: new, updated

#2408 Glue API: Search the product catalog
  docs/pbc/all/search/202403.0/base-shop/manage-using-glue-api/glue-api-search-the-product-catalog.md
Labels: TW review needed, updated, 202400

#2424 Update supported-versions-of-php.md
  docs/scos/user/intro-to-spryker/whats-new/supported-versions-of-php.md
Labels: small changes

#2297 docs: Third party dependencies
  CODEOWNERS
  docs/scos/dev/front-end-development/202307.0/oryx/getting-started/oryx-packages.md
  docs/scos/dev/front-end-development/202311.0/oryx/getting-started/oryx-packages.md
Labels: updated

#2266 CC-31362 Click and collect developer overview
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202204.0/install-the-navigation-module.md
  _includes/pbc/all/install-features/202212.0/install-the-navigation-module.md
  _includes/pbc/all/install-features/202307.0/install-the-navigation-module.md
  _includes/pbc/all/install-features/202311.0/install-the-navigation-module.md
  docs/pbc/all/carrier-management/202311.0/base-shop/manage-using-glue-api/manage-shipment-types/glue-api-retrieve-shipment-types.md
  docs/pbc/all/miscellaneous/202311.0/manage-using-glue-api/manage-push-notification-providers/glue-api-delete-push-notification-providers.md
  docs/pbc/all/miscellaneous/202311.0/manage-using-glue-api/manage-push-notification-providers/glue-api-retrieve-push-notification-providers.md
  docs/pbc/all/miscellaneous/202311.0/manage-using-glue-api/manage-push-notification-providers/glue-api-update-push-notification-providers.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/click-collect-domains/click-collect-domains.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/click-collect-domains/click-collect-marketplace-merchant-product-offer-service-point-availability-subdomain.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/click-collect-domains/click-collect-product-offer-service-point-availability-subdomain.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/click-collect-domains/click-collect-product-offer-service-point-subdomain.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/click-collect-domains/click-collect-product-offer-shipment-type-availability-subdomain.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/click-collect-domains/click-collect-product-offer-shipment-type-subdomain.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/click-collect-domains/click-collect-service-point-cart-subdomain.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/click-collect-domains/click-collect-service-points-domain.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/click-collect-domains/click-collect-shipment-type-service-point-subdomain.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/click-collect-domains/click-collect-shipment-types-domain.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-service-types/glue-api-retrieve-service-types.md
  docs/pbc/all/warehouse-management-system/202311.0/unified-commerce/manage-using-glue-api/glue-api-authenticate-as-a-warehouse-user.md
Labels: updated, 202400

#2414 add two performance guidelines
  docs/scos/dev/guidelines/performance-guidelines/general-performance-guidelines.md
Labels: updated

#2406 CC-31953 Introduced How To guide for backend E2E testing
  _data/sidebars/scos_dev_sidebar.yml
  _data/sidebars/scu_dev_sidebar.yml
  _includes/pbc/all/glue-api-guides/202311.0/oreder-shipments-response-attributes.md
  _includes/pbc/all/glue-api-guides/202311.0/shipment-methods-response-attributes.md
  _includes/pbc/all/glue-api-guides/202311.0/shipments-response-attributes.md
  docs/pbc/all/carrier-management/202311.0/base-shop/manage-using-glue-api/glue-api-retrieve-shipments-and-shipment-methods-when-submitting-checkout-data.md
  docs/pbc/all/carrier-management/202311.0/base-shop/manage-using-glue-api/glue-api-retrieve-shipments-when-checking-out-purchases.md
  docs/pbc/all/cart-and-checkout/202311.0/base-shop/manage-using-glue-api/check-out/glue-api-check-out-purchases.md
  docs/scos/dev/guidelines/testing-guidelines/executing-tests/test-glue-api.md
  docs/scos/dev/guidelines/testing-guidelines/executing-tests/test-glue-backend-api.md
  docs/scos/dev/guidelines/testing-guidelines/test-helpers/available-test-helpers.md
Labels: TW review needed, new

#2432 Docs updates 12.2023
  _data/sidebars/acp_user_sidebar.yml
  docs/acp/user/develop-an-app/debug-an-app-with-xdebug.md
  docs/scos/user/intro-to-spryker/docs-updates.md
Labels: in progress, small changes

#2439 fixing redirects in search PBC
  docs/pbc/all/search/202311.0/base-shop/best-practices/generic-faceted-search.md
  docs/pbc/all/search/202311.0/base-shop/best-practices/other-best-practices.md
  docs/pbc/all/search/202311.0/base-shop/best-practices/precise-search-by-super-attributes.md
Labels: small changes

#2438 Update monitoring-issues-and-informing-about-alerts.md
  docs/ca/dev/monitoring-issues-and-informing-about-alerts.md
Labels: TW review needed, small changes

#2369 FRW-6331 Provided documentation for Complex endpoint method GET
  _includes/pbc/all/install-features/202311.0/install-the-data-exchange-api.md
  docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-configure-data-exchange-api.md
  docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-send-request-in-data-exchange-api.md
Labels: in TW review, updated

#2434 Example modules
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/example-modules.md
Labels: new

#2370 FRW-5940 Symfony 6 Security Compatibility
  _includes/pbc/all/install-features/202403.0/install-the-agent-assist-feature.md
  _includes/pbc/all/install-features/202403.0/install-the-customer-account-management-agent-assist-feature.md
  _includes/pbc/all/install-features/202403.0/install-the-spryker-core-back-office-feature.md
  _includes/pbc/all/install-features/202403.0/install-the-spryker-core-feature.md
  _includes/pbc/all/install-features/202403.0/marketplace/install-the-marketplace-merchant-portal-core-feature.md
  _includes/pbc/all/upgrade-modules/upgrade-the-http-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-security-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-validator-module.md
  docs/pbc/all/merchant-management/202403.0/marketplace/marketplace-merchant-portal-core-feature-overview/marketplace-merchant-portal-core-feature-overview.md
  docs/scos/dev/back-end-development/forms/forms.md
  docs/scos/dev/migration-concepts/migrate-from-auth-to-securitygui-module.md
Labels: in tech review, updated

#2446 Adding notes to IG guide template
  _templates/feature-installation-guide-template.md
Labels: small changes

#2433 Merchant portal login instructions
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/manage-in-the-back-office/merchant-management/manage-merchant-users/merchant-general-information-attributes.md
  _includes/pbc/all/manage-in-the-merchant-portal/log-into-the-merchant-portal.md
  _includes/pbc/all/manage-in-the-merchant-portal/logging-in-to-the-merchant-portal.md
  docs/pbc/all/merchant-management/202212.0/marketplace/manage-in-the-merchant-portal/edit-merchant-profiles.md
  docs/pbc/all/merchant-management/202212.0/marketplace/manage-in-the-merchant-portal/manage-merchants-in-the-merchant-portal.md
  docs/pbc/all/merchant-management/202307.0/marketplace/manage-in-the-merchant-portal/edit-merchant-profiles.md
  docs/pbc/all/merchant-management/202307.0/marketplace/manage-in-the-merchant-portal/manage-merchants-in-the-merchant-portal.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/log-into-the-back-office.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchant-users.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchant-users/create-merchant-users.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchant-users/edit-merchant-users.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchants-and-merchant-users-in-the-back-office.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchants.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchants/create-merchants.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchants/edit-merchants.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-merchant-portal/edit-merchant-profiles.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-merchant-portal/manage-merchants-in-the-merchant-portal.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-using-glue-api/glue-api-retrieve-merchants.md
  docs/pbc/all/merchant-management/202311.0/marketplace/marketplace-merchant-feature-overview/marketplace-merchant-feature-overview.md
  docs/pbc/all/merchant-management/202311.0/marketplace/marketplace-merchant-feature-overview/merchant-users-overview.md
  docs/pbc/all/offer-management/202311.0/marketplace/manage-in-the-merchant-portal/create-product-offers.md
  docs/pbc/all/offer-management/202311.0/marketplace/manage-in-the-merchant-portal/edit-product-offers.md
  docs/pbc/all/offer-management/202311.0/marketplace/manage-in-the-merchant-portal/manage-product-offers-in-the-merchant-portal.md
  docs/pbc/all/offer-management/202311.0/marketplace/manage-product-offers.md
  docs/pbc/all/offer-management/202311.0/marketplace/marketplace-product-offer-feature-overview.md
  docs/pbc/all/product-information-management/202311.0/marketplace/manage-in-the-merchant-portal/manage-products-in-the-merchant-portal.md
  docs/pbc/all/product-information-management/202311.0/marketplace/marketplace-product-feature-overview.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/oryx-application-orchestration/oryx-application-environment.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/oryx-application-orchestration/oryx-application-feature.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/oryx-application-orchestration/oryx-application-orchestration.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/oryx-application-orchestration/oryx-application-plugins.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/oryx-application-orchestration/oryx-application.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/styling/oryx-responsive-design.md
  docs/scos/user/intro-to-spryker/spryker-marketplace/merchant-onboarding.md
Labels: updated

#2448 Broken html comments and small fixes
  docs/scos/dev/front-end-development/202212.0/oryx/getting-started/oryx-versioning.md
  docs/scos/dev/front-end-development/202307.0/oryx/getting-started/oryx-versioning.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/oryx-application-orchestration/oryx-application-feature.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/oryx-application-orchestration/oryx-application-orchestration.md
  docs/scos/dev/front-end-development/202311.0/oryx/getting-started/oryx-versioning.md
Labels: small changes

#2430 ACP-2128: Updated Vertex documentation
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/configure-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/disconnect-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/install-vertex/install-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-the-acp-connector-module-for-tax-calculation.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-the-vertex-app.md
Labels: TW review needed, updated

#2282 CC-31652 Introduced `datasource.dependable` and `datasource.trigger` services.
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/front-end-development/202307.0/marketplace/ui-components-library/datasources/datasource-dependable.md
  docs/scos/dev/front-end-development/202307.0/marketplace/ui-components-library/datasources/datasource-http.md
  docs/scos/dev/front-end-development/202307.0/marketplace/ui-components-library/datasources/datasource-inline-table.md
  docs/scos/dev/front-end-development/202307.0/marketplace/ui-components-library/datasources/datasource-inline.md
  docs/scos/dev/front-end-development/202307.0/marketplace/ui-components-library/datasources/datasource-trigger/datasource-trigger-change.md
  docs/scos/dev/front-end-development/202307.0/marketplace/ui-components-library/datasources/datasource-trigger/datasource-trigger-input.md
  docs/scos/dev/front-end-development/202307.0/marketplace/ui-components-library/datasources/datasource-trigger/datasource-trigger.md
  docs/scos/dev/front-end-development/202307.0/marketplace/ui-components-library/datasources/datasources.md
  docs/scos/dev/front-end-development/202307.0/marketplace/ui-components-library/ui-components-library.md
  docs/scos/dev/front-end-development/202311.0/marketplace/ui-components-library/datasources/datasource-dependable.md
  docs/scos/dev/front-end-development/202311.0/marketplace/ui-components-library/datasources/datasource-http.md
  docs/scos/dev/front-end-development/202311.0/marketplace/ui-components-library/datasources/datasource-inline-table.md
  docs/scos/dev/front-end-development/202311.0/marketplace/ui-components-library/datasources/datasource-inline.md
  docs/scos/dev/front-end-development/202311.0/marketplace/ui-components-library/datasources/datasource-trigger/datasource-trigger-change.md
  docs/scos/dev/front-end-development/202311.0/marketplace/ui-components-library/datasources/datasource-trigger/datasource-trigger-input.md
  docs/scos/dev/front-end-development/202311.0/marketplace/ui-components-library/datasources/datasource-trigger/datasource-trigger.md
  docs/scos/dev/front-end-development/202311.0/marketplace/ui-components-library/datasources/datasources.md
  docs/scos/dev/front-end-development/202311.0/marketplace/ui-components-library/ui-components-library.md
Labels: TW review needed, new

#2390 Added translations in a vertex integration page.
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-the-vertex-app.md
Labels: TW review needed, small changes

#2453 Fix of the link
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchants/edit-merchants.md
Labels: small changes

#2389 Redirect fixes
  docs/pbc/all/carrier-management/202311.0/base-shop/install-and-upgrade/install-features/install-the-shipment-feature.md
  docs/pbc/all/merchant-management/202311.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-core-feature.md
  docs/pbc/all/product-information-management/202311.0/base-shop/feature-overviews/catalog-feature-overview.md
  docs/pbc/all/product-information-management/202311.0/base-shop/import-and-export-data/categories-data-import/import-file-details-category.csv.md
  docs/pbc/all/product-information-management/202311.0/base-shop/manage-in-the-back-office/products/manage-abstract-products-and-product-bundles/create-abstract-products-and-product-bundles.md
  docs/pbc/all/product-information-management/202311.0/marketplace/marketplace-product-approval-process-feature-overview.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/vertex.md
Labels: small changes

#2454 Fix the links
  docs/acp/user/develop-an-app/develop-an-app.md
  docs/scos/dev/the-docker-sdk/202212.0/configure-services.md
  docs/scos/dev/the-docker-sdk/202307.0/configure-services.md
  docs/scos/dev/the-docker-sdk/202311.0/configure-services.md
Labels: small changes

#2440 ACP-773: Stripe documentation mvp
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/configure-stripe.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/disconnect-stripe.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/install-stripe.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/stripe.md
Labels: new

#2444 SDK-5415: As a PBC developer I want to have clear and simple guidelin…
  _data/sidebars/acp_user_sidebar.yml
  docs/acp/user/connect-an-app.md
  docs/acp/user/develop-an-app/develop-an-app.md
  docs/acp/user/intro-to-acp/acp-architecture-overview.md
Labels: tech review needed, new

#2460 Update spryks.md
  docs/sdk/dev/spryks/spryks.md
Labels: small changes

#2429 new document for handling carts with large amount of items
  _data/sidebars/pbc_all_sidebar.yml
  docs/ca/dev/deploy-in-a-production-environment.md
  docs/ca/dev/security/generate-access-keys.md
  docs/pbc/all/cart-and-checkout/202204.0/base-shop/tutorials-and-howtos/handling-carts-with-a-big-number-of-items.md
  docs/pbc/all/cart-and-checkout/202212.0/base-shop/tutorials-and-howtos/handling-carts-with-a-big-number-of-items.md
  docs/pbc/all/cart-and-checkout/202307.0/base-shop/tutorials-and-howtos/handling-carts-with-a-big-number-of-items.md
  docs/pbc/all/cart-and-checkout/202311.0/base-shop/tutorials-and-howtos/handling-carts-with-a-big-number-of-items.md
  docs/scos/dev/front-end-development/202311.0/oryx/architecture/reactivity/key-concepts-of-reactivity.md
  docs/scos/dev/front-end-development/202311.0/oryx/architecture/reactivity/oryx-integration-of-backend-apis.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/oryx-application-orchestration/oryx-application-plugins.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/oryx-feature-sets.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/oryx-presets.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/styling/oryx-color-system.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/styling/oryx-icon-system.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/styling/oryx-responsive-design.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-pages/oryx-pages.md
  docs/scos/dev/front-end-development/202311.0/oryx/getting-started/oryx-technology.md
  docs/scos/dev/front-end-development/202311.0/oryx/getting-started/oryx-versioning.md
  docs/scos/dev/front-end-development/202311.0/oryx/getting-started/set-up-oryx.md
  docs/scos/dev/front-end-development/202311.0/oryx/oryx.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/edit-the-documentation-locally.md
Labels: new

#2463 Hotfixes for checkers
  Gemfile
  docs/pbc/all/offer-management/202311.0/unified-commerce/unified-commerce-create-and-edit-product-offers.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/manage-using-glue-api/manage-service-points/glue-api-retrieve-service-points.md
  docs/pbc/all/service-point-management/202311.0/unified-commerce/service-points-feature-overview.md
  docs/scos/dev/front-end-development/202311.0/oryx/architecture/reactivity/key-concepts-of-reactivity.md
Labels: small changes

#2464 Update ruby version
  Gemfile.lock
Labels: small changes

#2355 Improve NewRelic Integration
  docs/scos/dev/the-docker-sdk/202204.0/configure-services.md
  docs/scos/dev/the-docker-sdk/202311.0/configure-services.md
Labels: updated

#2466 fix: deploy
  .github/workflows/ci.yml
Labels: small changes

#2467 SDK-5418: Cleanuped documentation. The part was moved to code
  docs/acp/user/develop-an-app/develop-an-app.md
Labels: small changes

#2376 Install the Category Management feature
  _includes/pbc/all/install-features/202403.0/install-the-category-management-feature.md
  docs/pbc/all/product-information-management/202403.0/base-shop/feature-overviews/category-management-feature-overview.md
Labels: TW review needed, updated, 202400

#2412 SDK-5434: Update docs
  docs/acp/user/develop-an-app/develop-an-app.md
Labels: updated, small changes

#2468 Update install-the-spryker-core-glue-api.md
  _includes/pbc/all/install-features/202204.0/install-glue-api/install-the-spryker-core-glue-api.md
  _includes/pbc/all/install-features/202311.0/install-glue-api/install-the-spryker-core-glue-api.md
Labels: TW review needed, small changes

#2436 Update security-guidelines.md
  docs/scos/dev/guidelines/security-guidelines.md
Labels: TW review needed

#2387 CC-32129: Updated the security release notes.
  docs/scos/user/intro-to-spryker/releases/release-notes/security-release-notes-202312.0.md
Labels: TW review needed, updated

#2470 Stripe overview
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/configure-stripe.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/stripe.md
Labels: new

#2301 docs: Directionality in Oryx
  _data/sidebars/scos_dev_sidebar.yml
  docs/pbc/all/merchant-management/202212.0/marketplace/marketplace-merchant-feature-overview/merchant-users-overview.md
  docs/scos/dev/front-end-development/202212.0/oryx/internationalization/oryx-directionality.md
  docs/scos/dev/front-end-development/202212.0/oryx/internationalization/oryx-localization.md
  docs/scos/dev/front-end-development/202307.0/oryx/building-applications/styling/oryx-icon-system.md
  docs/scos/dev/front-end-development/202307.0/oryx/internationalization/oryx-directionality.md
  docs/scos/dev/front-end-development/202307.0/oryx/internationalization/oryx-localization.md
  docs/scos/dev/front-end-development/202311.0/oryx/building-applications/styling/oryx-icon-system.md
  docs/scos/dev/front-end-development/202311.0/oryx/internationalization/oryx-directionality.md
  docs/scos/dev/front-end-development/202311.0/oryx/internationalization/oryx-localization.md
Labels: new

#2459 Fixed sidebar typos
  _data/sidebars/ca_dev_sidebar.yml
  _data/sidebars/pbc_all_sidebar.yml
  _data/sidebars/scos_dev_sidebar.yml
Labels: TW review needed, small changes

#2427 ACP-383: adjusted PBCs docs
  _data/sidebars/acp_user_sidebar.yml
  docs/acp/user/app-composition-platform-installation.md
  docs/acp/user/receive-acp-messages.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/payone/integration-in-the-back-office/integrate-payone.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/install-stripe.md
  docs/pbc/all/ratings-reviews/202311.0/third-party-integrations/integrate-bazaarvoice.md
  docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-the-acp-connector-module-for-tax-calculation.md
  docs/pbc/all/usercentrics/integrate-usercentrics.md
Labels: new

#2482 Adjusting the ACP guides
  _data/sidebars/pbc_all_sidebar.yml
  docs/acp/user/app-composition-platform-installation.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/payone/integration-in-the-back-office/configure-payone.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/payone/integration-in-the-back-office/integrate-payone.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/integrate-stripe.md
  docs/pbc/all/ratings-reviews/202311.0/third-party-integrations/integrate-bazaarvoice.md
  docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/configure-algolia.md
  docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
  docs/pbc/all/usercentrics/configure-usercentrics.md
  docs/pbc/all/usercentrics/integrate-usercentrics.md
Labels: small changes

#2462 Bumped minimal php version from 8.0(end of life in 2023) to 8.1
  docs/scos/user/intro-to-spryker/releases/release-notes/security-release-notes-202306.0.md
  docs/scos/user/intro-to-spryker/whats-new/php8-as-a-minimum-version-for-all-spryker-projects.md
Labels: small changes

#2486 Update integrate-stripe.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/integrate-stripe.md
Labels: TW review needed, updated
