Repository spryker/spryker-docs, pull requests merged in 2024-11, with the labels that each got.

#2777 FRW-2465 Fixed performance problem related to ZED/Merchant portal navigation IG.
  _includes/pbc/all/install-features/202410.0/install-the-spryker-core-feature.md
Labels: updated, 202407

#2854 FRW-9176: Introduced View page for merchants in the BackOffice.
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202410.0/marketplace/install-the-marketplace-merchant-feature.md
  docs/pbc/all/merchant-management/202410.0/base-shop/manage-in-the-back-office/create-merchants.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/manage-merchants-and-merchant-users-in-the-back-office.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/manage-merchants/view-merchants.md
Labels: in TW review, new

#2790 FRW-7741: limitation guides for DMS
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202410.0/install-dynamic-multistore.md
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/dynamic-multistore-feature-overview.md
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/import-stores.md
Labels: TW review needed, new

#2581 Update technology-stack.md
  docs/dg/dev/architecture/technology-stack.md
Labels: updated, Bypassed TW Review

#2862 Update handle-data-with-publish-and-synchronization.md
  docs/dg/dev/backend-development/data-manipulation/data-publishing/handle-data-with-publish-and-synchronization.md
Labels: updated, Bypassed TW Review

#2863 Update handle-data-with-publish-and-synchronization.md
  docs/dg/dev/backend-development/data-manipulation/data-publishing/handle-data-with-publish-and-synchronization.md
Labels: updated, Bypassed TW Review

#2864 HTMLProofer Retries & Timeout
  Rakefile
Labels: new, Bypassed TW Review

#2869 Introduce PHPStorm Tools
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/sdks/sdk/development-tools/architecture-sniffer.md
  docs/dg/dev/sdks/sdk/development-tools/code-sniffer.md
  docs/dg/dev/sdks/sdk/development-tools/development-tools.md
  docs/dg/dev/sdks/sdk/development-tools/enable-development-tools-in-phpstorm.md
  docs/dg/dev/sdks/sdk/development-tools/formatter.md
  docs/dg/dev/sdks/sdk/development-tools/scss-linter.md
  docs/dg/dev/sdks/sdk/development-tools/static-security-checker.md
  docs/dg/dev/sdks/sdk/development-tools/tooling-configuration-file.md
  docs/dg/dev/sdks/sdk/development-tools/ts-linter.md
  docs/dg/dev/updating-spryker/testing-updates.md
Labels: TW review needed, new

#2878 ACP-4372: Updated ACP docs
  docs/dg/dev/acp/install-prerequisites-and-enable-acp.md
  docs/dg/dev/sdks/sdk/development-tools/development-tools.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/payone/app-composition-platform-integration/integrate-payone.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/install-and-configure-stripe-prerequisites.md
  docs/pbc/all/payment-service-provider/202410.0/marketplace/stripe-third-party-integration/install-and-configure-stripe-prerequisites-for-marketplace.md
Labels: TW review needed, small changes

#2877 FRW-8773 Migration guide: PHPUnit 11 upgrade.
  docs/dg/dev/upgrade-and-migrate/upgrade-to-phpunit-11.md
Labels: in TW review, new

#2871 Update install-and-configure-stripe-prerequisites.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/install-and-configure-stripe-prerequisites.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/install-and-configure-stripe-prerequisites.md
Labels: ready for merge

#2885 SEO Changes for the Homepage
  _includes/footer.html
  _layouts/home.html
Labels: TW review needed, small changes

#2887 Spryker About All high level Pages SEO
  docs/about/all/about-spryker.md
  docs/about/all/master-suite.md
  docs/about/all/supported-browsers.md
Labels: TW review needed, small changes

#2888 About the Docs SEO
  docs/about/all/about-the-docs/about-spryker-docs.md
  docs/about/all/about-the-docs/contribute-to-the-docs/add-global-sections-to-the-docs.md
  docs/about/all/about-the-docs/contribute-to-the-docs/add-images-and-other-media-to-the-docs.md
  docs/about/all/about-the-docs/contribute-to-the-docs/contribute-to-the-docs.md
  docs/about/all/about-the-docs/contribute-to-the-docs/edit-the-docs-locally.md
  docs/about/all/about-the-docs/contribute-to-the-docs/edit-the-docs-using-a-web-browser.md
  docs/about/all/about-the-docs/contribute-to-the-docs/report-docs-issues.md
  docs/about/all/about-the-docs/contribute-to-the-docs/review-docs-pull-requests.md
  docs/about/all/about-the-docs/run-the-docs-locally.md
  docs/about/all/about-the-docs/style-guide/general-rules-and-guidance-for-adding-docs.md
  docs/about/all/about-the-docs/style-guide/spryker-docs-style-guide.md
  docs/about/all/about-the-docs/style-guide/style-guide-examples.md
  docs/about/all/about-the-docs/style-guide/style-guide-spelling.md
  docs/about/all/about-the-docs/style-guide/word-list.md
Labels: TW review needed

#2886 FRW-9223 Added site.url configuration to the production config.
  _config_production.yml
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/unzer/extend-and-customize/customize-the-credit-card-display-in-your-payment-step.md
Labels: in TW review, small changes

#2890 About All Releases SEO Update
  docs/about/all/releases/product-and-code-releases.md
Labels: TW review needed

#2893 fix production config
  _config_production.yml
Labels: TW review needed, small changes

#2891 About all Spryker marketplace SEO Update
  docs/about/all/spryker-marketplace/spryker-marketplace.md
Labels: TW review needed

#2894 About All Support SEO Updates
  docs/about/all/support/gdpr-compliance-guidelines.md
  docs/about/all/support/getting-support.md
  docs/about/all/support/getting-the-most-out-of-spryker-support.md
  docs/about/all/support/how-spryker-support-works.md
  docs/about/all/support/preparing-for-heavy-loads-and-traffic.md
  docs/about/all/support/prioritzing-support-cases.md
  docs/about/all/support/project-level-and-core-level-fixes.md
  docs/about/all/support/share-secrets-with-the-spryker-support-team.md
  docs/about/all/support/support-case-escalations.md
  docs/about/all/support/support-ticket-statuses.md
  docs/about/all/support/understanding-slas.md
  docs/about/all/support/using-the-support-portal.md
Labels: TW review needed

#2898 Cloud Admin Higher Level Pages SEO Update
  _data/sidebars/ca_dev_sidebar.yml
  docs/ca/dev/add-variables-in-the-parameter-store.md
  docs/ca/dev/configure-data-import-from-an-s3-bucket.md
  docs/ca/dev/configure-debugging.md
  docs/ca/dev/connecting-the-docker-sdk.md
  docs/ca/dev/create-and-restore-database-backups.md
  docs/ca/dev/deploy-in-a-staging-environment.md
  docs/ca/dev/environment-scaling.md
  docs/ca/dev/getting-started-with-cloud-administration.md
  docs/ca/dev/monitoring-issues-and-informing-about-alerts.md
  docs/ca/dev/performance-testing-in-staging-enivronments.md
  docs/ca/dev/preparation-for-going-live.md
  docs/ca/dev/set-up-dns.md
  docs/ca/dev/set-up-notifications-for-5xx-errors.md
  docs/ca/dev/setting-up-a-custom-ssl-certificate.md
  docs/ca/dev/spryker-cloud-commerce-os-management.md
  docs/ca/dev/starting-asynchronous-commands.md
  docs/ca/dev/working-with-logs.md
Labels: TW review needed

#2905 OpenAI features IGs.
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/miscellaneous/202410.0/third-party-integrations/open-ai/integrate-openai.md
  docs/pbc/all/product-information-management/202410.0/base-shop/third-party-integrations/product-management-powered-by-openai/install-product-management-powered-by-openai.md
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/visual-search-powered-by-openai/install-visual-search-powered-by-openai.md
Labels: TW review needed, new

#2904 Cloud Admin Access and best Practices SEO updates
  docs/ca/dev/access/connect-to-services-via-ssh.md
  docs/ca/dev/best-practices/best-practices.md
  docs/ca/dev/best-practices/best-practises-jenkins-stability.md
  docs/ca/dev/best-practices/jenkins-operational-best-practices.md
Labels: TW review needed

#2906 Cloud Admin Configure Deployment Pipelines SEO Update
  docs/ca/dev/configure-deployment-pipelines/configure-azure-pipelines.md
  docs/ca/dev/configure-deployment-pipelines/configure-bitbucket-pipelines.md
  docs/ca/dev/configure-deployment-pipelines/configure-github-actions.md
  docs/ca/dev/configure-deployment-pipelines/configure-gitlab-pipelines.md
  docs/ca/dev/configure-deployment-pipelines/customize-deployment-pipelines.md
  docs/ca/dev/configure-deployment-pipelines/deployment-pipelines.md
Labels: TW review needed

#2908 Cloud Admin security and custom domain SEO updates
  docs/ca/dev/security/generate-access-keys.md
  docs/ca/dev/security/penetration-testing.md
  docs/ca/dev/security/set-up-multi-factor-authentication.md
  docs/ca/dev/security/web-application-firewall-waf.md
  docs/ca/dev/set-up-a-custom-domain-name/set-up-a-custom-domain-name-with-a-third-party-dns-zone-provider.md
  docs/ca/dev/set-up-a-custom-domain-name/set-up-a-custom-domain-name-with-route-53.md
  docs/ca/dev/set-up-a-custom-domain-name/set-up-a-custom-domain-name.md
Labels: TW review needed

#2909 Cloud Admin Troubleshooting SEO Update
  docs/ca/dev/troubleshooting/troubleshooting-deployment-issues/deployment-fails-due-to-a-failed-docker-authentication.md
  docs/ca/dev/troubleshooting/troubleshooting-deployment-issues/troubleshooting-deployment-issues.md
  docs/ca/dev/troubleshooting/troubleshooting-general-issues/changing-a-source-branch-fails.md
  docs/ca/dev/troubleshooting/troubleshooting-general-issues/email-address-is-not-verified.md
  docs/ca/dev/troubleshooting/troubleshooting-general-issues/fatal-error-allowed-memory-size-of-x-bytes-exhausted.md
  docs/ca/dev/troubleshooting/troubleshooting-general-issues/troubleshooting-general-issues.md
  docs/ca/dev/troubleshooting/troubleshooting-tutorials/troubleshooting-tutorials.md
  docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-403-error.md
  docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-a-failed-deployment.md
  docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-a-killed-process.md
  docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-an-unavailable-zed.md
  docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-failed-jenkins-jobs.md
  docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-failing-yves-authentication.md
  docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-unavailable-yves-or-glue.md
  docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-yves-or-zed-not-restarting-after-deployment.md
  docs/ca/dev/troubleshooting/troubleshooting.md
Labels: TW review needed

#2911 Update penetration-testing.md
  docs/ca/dev/security/penetration-testing.md
Labels: TW review needed

#2907 Cloud Admin Email Service & Manage Maintenance & Monitoring SEO Update
  docs/ca/dev/email-service/email-deliverability.md
  docs/ca/dev/email-service/email-quota-restrictions.md
  docs/ca/dev/email-service/email-service.md
  docs/ca/dev/manage-maintenance-mode/enable-and-disable-maintenance-mode.md
  docs/ca/dev/multi-store-setups/add-and-remove-databases-of-stores.md
  docs/ca/dev/multi-store-setups/checklist-for-a-new-store-implementation.md
  docs/ca/dev/multi-store-setups/multi-store-setups.md
  docs/ca/dev/multi-store-setups/multistore-setup-options.md
Labels: TW review needed

#2914 Update connect-a-code-repository.md
  docs/about/all/support/share-secrets-with-the-spryker-support-team.md
  docs/ca/dev/connect-a-code-repository.md
  docs/dg/dev/upgrade-and-migrate/upgrade-nodejs-to-v18-and-npm-to-v9.md
Labels: TW review needed

#2922 PBC Carrier Management SEO Update
  docs/pbc/all/carrier-management/202410.0/base-shop/domain-model-and-relationships/shipment-method-entities-in-the-database-reference-information.md
  docs/pbc/all/carrier-management/202410.0/base-shop/import-and-export-data/import-carrier-management-data.md
  docs/pbc/all/carrier-management/202410.0/base-shop/import-and-export-data/import-file-details-shipment-method-store.csv.md
  docs/pbc/all/carrier-management/202410.0/base-shop/import-and-export-data/import-file-details-shipment-price.csv.md
  docs/pbc/all/carrier-management/202410.0/base-shop/import-and-export-data/import-file-details-shipment.csv.md
  docs/pbc/all/carrier-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-shipment-approval-process-feature.md
  docs/pbc/all/carrier-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-shipment-cart-feature.md
  docs/pbc/all/carrier-management/202410.0/base-shop/install-and-upgrade/install-the-shipment-glue-api.md
  docs/pbc/all/carrier-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-shipmentgui-module.md
  docs/pbc/all/carrier-management/202410.0/base-shop/manage-in-the-back-office/add-carrier-companies.md
  docs/pbc/all/carrier-management/202410.0/base-shop/manage-in-the-back-office/add-delivery-methods.md
  docs/pbc/all/carrier-management/202410.0/base-shop/manage-in-the-back-office/edit-delivery-methods.md
  docs/pbc/all/carrier-management/202410.0/base-shop/manage-in-the-back-office/manage-carrier-companies-and-delivery-methods-in-the-back-office.md
  docs/pbc/all/carrier-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-shipments-and-shipment-methods-when-submitting-checkout-data.md
  docs/pbc/all/carrier-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-shipments-in-orders.md
  docs/pbc/all/carrier-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-shipments-when-checking-out-purchases.md
  docs/pbc/all/carrier-management/202410.0/base-shop/manage-using-glue-api/manage-shipment-types/glue-api-add-shipment-types.md
  docs/pbc/all/carrier-management/202410.0/base-shop/manage-using-glue-api/manage-shipment-types/glue-api-retrieve-shipment-types.md
  docs/pbc/all/carrier-management/202410.0/base-shop/manage-using-glue-api/manage-shipment-types/glue-api-update-shipment-types.md
  docs/pbc/all/carrier-management/202410.0/base-shop/shipment-cart-feature-overview.md
  docs/pbc/all/carrier-management/202410.0/base-shop/third-party-integrations/seven-senders/install-and-configure-seven-senders.md
  docs/pbc/all/carrier-management/202410.0/base-shop/third-party-integrations/seven-senders/integrate-seven-senders.md
  docs/pbc/all/carrier-management/202410.0/base-shop/third-party-integrations/seven-senders/seven-senders-api-requests.md
  docs/pbc/all/carrier-management/202410.0/base-shop/third-party-integrations/seven-senders/seven-senders-mappers.md
  docs/pbc/all/carrier-management/202410.0/base-shop/third-party-integrations/seven-senders/seven-senders-persistance-layer.md
  docs/pbc/all/carrier-management/202410.0/carrier-management.md
  docs/pbc/all/carrier-management/202410.0/marketplace/install-features/install-marketplace-shipment-feature.md
  docs/pbc/all/carrier-management/202410.0/marketplace/install-features/install-the-marketplace-shipment-cart-feature.md
  docs/pbc/all/carrier-management/202410.0/unified-commerce/shipment-service-points-feature-overview.md
Labels: TW review needed

#2920 PBC Back Office SEO Update
  docs/pbc/all/back-office/202410.0/base-shop/back-office-translations-overview.md
  docs/pbc/all/back-office/202410.0/base-shop/configure-the-timezone-in-the-back-office.md
  docs/pbc/all/back-office/202410.0/base-shop/install-and-upgrade/install-the-back-office-number-formatting.md
  docs/pbc/all/back-office/202410.0/base-shop/install-and-upgrade/install-the-spryker-core-back-office-comments-feature.md
  docs/pbc/all/back-office/202410.0/base-shop/install-and-upgrade/install-the-spryker-core-back-office-feature.md
  docs/pbc/all/back-office/202410.0/base-shop/install-and-upgrade/upgrade-the-chart-module.md
Labels: TW review needed

#2923 PBC Cart and checkout domain model and extend SEO update
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/cart-and-checkout-base-shop.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/domain-model-and-relationships/checkout-feature-module-relations.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/domain-model-and-relationships/comments-feature-module-relations.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/domain-model-and-relationships/persistent-cart-sharing-feature-module-relations.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/extend-and-customize/calculation-data-structure.md
Labels: TW review needed

#2918 Update getting-the-most-out-of-spryker-support.md
  docs/about/all/support/getting-the-most-out-of-spryker-support.md
Labels: TW review needed

#2821 CC-34041 Amazon Quicksight.
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202410.0/install-the-analytics-feature.md
  docs/about/all/releases/release-notes-202410.0.md
  docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/amazon-quicksight.md
  docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/best-practices-working-with-analytics.md
  docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/install-amazon-quicksight.md
  docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/set-up-amazon-quicksight.md
  docs/pbc/all/business-intelligence/202410.0/install-the-analytics-feature.md
Labels: TW review needed, new

#2926 PBC cart and checkout install and upgrade SEO update
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-cart-agent-assist-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-cart-feature-dynamic-multistore.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-cart-notes-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-cart-product-bundles-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-cart-product-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-cart-shipment-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-checkout-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-checkout-quotation-process-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-checkout-workflow-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-comments-merchant-b2b-contract-requests-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-comments-merchant-b2b-contracts-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-comments-spryker-core-back-office-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-multiple-carts-quotation-process-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-quick-add-to-cart-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-quick-add-to-cart-non-splittable-products-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-quick-add-to-cart-shopping-lists-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-resource-sharing-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-shared-carts-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-features/install-the-uuid-generation-console-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-cart-glue-api.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-checkout-glue-api.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-shared-carts-glue-api.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cart-module.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cartsrestapi-module.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cartvariant-module.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-checkoutpage-module.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-checkoutrestapi-module.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-multicartpage-module.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-persistentcart-module.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-quickorder-module.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-quickorderpage-module.md
Labels: TW review needed

#2927 PBC Cart and Checkout BO GLUEAPI and Tutorials SEO Update
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-in-the-back-office/define-global-thresholds.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-in-the-back-office/manage-threshold-settings.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-in-the-back-office/manage-thresholds-the-back-office.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-using-glue-api/check-out/glue-api-check-out-purchases.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-using-glue-api/check-out/glue-api-checkout-workflow.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-customer-carts.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-using-glue-api/share-company-user-carts/glue-api-manage-shared-company-user-carts.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-using-glue-api/share-company-user-carts/glue-api-retrieve-cart-permission-groups.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/manage-using-glue-api/share-company-user-carts/glue-api-share-company-user-carts.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/tutorials-and-howtos/add-additional-countries-to-checkout.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/tutorials-and-howtos/define-if-carts-are-deleted-after-placing-an-order.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/tutorials-and-howtos/enable-guest-checkout-in-the-b2b-demo-shop.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/tutorials-and-howtos/handling-carts-with-a-big-number-of-items.md
  docs/pbc/all/cart-and-checkout/202410.0/cart-and-checkout.md
Labels: TW review needed

#2928 PBC Cart and Checktout Marketplace SEO Update
  docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-features/install-the-cart-marketplace-product-offer-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-features/install-the-cart-marketplace-product-options-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-features/install-the-checkout-marketplace-product-offer-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-features/install-the-checkout-marketplace-product-options-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-features/install-the-quick-add-to-cart-marketplace-product-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-features/install-the-quick-add-to-cart-marketplace-product-offer-feature.md
  docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-glue-api/install-the-cart-marketplace-product-glue-api.md
  docs/pbc/all/cart-and-checkout/202410.0/marketplace/install/install-glue-api/install-the-cart-marketplace-product-offer-glue-api.md
  docs/pbc/all/cart-and-checkout/202410.0/marketplace/manage-using-glue-api/carts-of-registered-users/manage-items-in-carts-of-registered-users.md
  docs/pbc/all/cart-and-checkout/202410.0/marketplace/marketplace-cart-feature-module-relations.md
Labels: TW review needed

#2932 PBC CMS small page groups SEO Updates
  docs/pbc/all/content-management-system/202410.0/base-shop/cms-feature-overview/cms-pages-overview.md
  docs/pbc/all/content-management-system/202410.0/base-shop/cms-feature-overview/email-as-a-cms-block-overview.md
  docs/pbc/all/content-management-system/202410.0/base-shop/domain-model-and-relationships/content-item-types-module-relations.md
  docs/pbc/all/content-management-system/202410.0/base-shop/domain-model-and-relationships/product-sets-feature-domain-model-and-relationships.md
  docs/pbc/all/content-management-system/202410.0/base-shop/extend-and-customize/navigation-module-reference-information.md
  docs/pbc/all/content-management-system/202410.0/base-shop/navigation-feature-overview.md
  docs/pbc/all/content-management-system/202410.0/base-shop/product-sets-feature-overview.md
  docs/pbc/all/content-management-system/202410.0/content-management-system.md
Labels: TW review needed

#2934 PBC CMS Import Export SEO Update
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-content-management-system-data.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-block-category-postion.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-block-category.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-block-store.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-block.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-page-store.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-page.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-slot-block.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-slot-template.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-slot.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-cms-template.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-content-banner.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-content-navigation.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-content-product-abstract-list.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-content-product-set.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-mime-type.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-navigation-node.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-navigation.csv.md
  docs/pbc/all/content-management-system/202410.0/base-shop/import-and-export-data/import-file-details-product-set.csv.md
Labels: TW review needed

#2929 FRW-8551 Dynamic Multistore vs Multistore. + MultiDB.
  _data/sidebars/dg_dev_sidebar.yml
  _includes/pbc/all/install-features/202410.0/install-dynamic-multistore.md
  docs/ca/dev/multi-store-setups/multi-store-setups.md
  docs/dg/dev/internationalization-and-multi-store/managing-translations-with-twig-translator.md
  docs/dg/dev/internationalization-and-multi-store/tutorial-different-stores-different-logic-landing-pages.md
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/dynamic-multistore-feature-overview.md
  docs/pbc/all/product-information-management/202311.0/base-shop/tutorials-and-howtos/tutorial-product.md
  docs/pbc/all/product-information-management/202404.0/base-shop/tutorials-and-howtos/tutorial-product.md
  docs/pbc/all/product-information-management/202410.0/base-shop/tutorials-and-howtos/tutorial-product.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/extend-and-customize/manage-stocks-in-a-multi-store-environment-best-practices.md
Labels: TW review needed, updated

#2935 PBC CMS Install and upgrade SEO update
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-category-cms-blocks.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-cms-category-management-feature.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-cms-feature-dynamic-multistore.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-cms-feature.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-cms-product-lists-catalog-feature.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-product-sets-feature.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-cms-glue-api.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-multi-store-cms-blocks.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/install-product-cms-blocks.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cms-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cmsblockcategoryconnector-migration-console-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cmsblockcategoryconnector-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cmsblockwidget-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cmsgui-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cmspagesearch-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cmsstorage-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-content-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-contentbanner-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-contentbannergui-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-contentbannersrestapi-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-contentgui-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-contentstorage-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-navigation-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-navigationgui-module.md
  docs/pbc/all/content-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-navigationsrestapi-module.md
  docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/merchant-commission/import-file-details-merchant_commission_merchant.csv.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/back-office-import-merchant-commissions.md
Labels: TW review needed

#2936 PBC CMS manage in the back office SEO update
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/add-and-edit-mime-types.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/blocks/add-content-items-to-cms-blocks.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/blocks/create-category-cms-blocks.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/blocks/create-cms-blocks.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/blocks/create-email-cms-blocks.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/blocks/create-product-cms-blocks.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/blocks/edit-placeholders-in-cms-blocks.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/content-items/create-abstract-product-list-content-items.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/content-items/create-banner-content-items.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/content-items/create-file-list-content-items.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/content-items/create-navigation-content-items.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/content-items/create-product-set-content-items.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/manage-content-in-the-back-office.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/manage-slots.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/navigation/create-navigation-elements.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/navigation/create-navigation-nodes.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/navigation/delete-navigation-nodes.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/navigation/duplicate-navigation-elements.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/navigation/edit-navigation-elements.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/navigation/edit-navigation-nodes.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/pages/add-content-items-to-cms-pages.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/product-sets/create-product-sets.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/product-sets/delete-product-sets.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/product-sets/edit-product-sets.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/product-sets/reorder-product-sets.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/product-sets/view-product-sets.md
Labels: TW review needed

#2941 PBC CRM Part 2 SEO Update
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-roles/create-company-roles.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-roles/edit-company-roles.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-unit-addresses/create-company-unit-addresses.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-unit-addresses/edit-company-unit-addresses.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-units/create-company-units.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-units/edit-company-units.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-users/create-company-users.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/company-users/edit-company-users.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/customers/add-customer-addresses.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/customers/add-notes-to-customers.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/customers/create-customers.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/customers/edit-customer-addresses.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/customers/edit-customers.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/customers/view-customers.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/manage-companies-and-customers-in-the-back-office.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/manage-customer-access.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-in-the-back-office/manage-customer-groups.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-business-unit-addresses.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-business-units.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-companies.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-company-roles.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-company-users.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/company-account/glue-api-search-by-company-users.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/customers/glue-api-manage-customer-addresses.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/customers/glue-api-manage-customers.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/customers/glue-api-retrieve-customer-orders.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/manage-using-glue-api/manage-customer-access-to-glue-api-resources.md
  docs/pbc/all/customer-relationship-management/202410.0/customer-relationship-management.md
Labels: TW review needed

#2943 hotfix of the broken code in the `config_default.php`
  docs/dg/dev/acp/install-prerequisites-and-enable-acp.md
Labels: TW review needed

#2933 Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: TW review needed
