Repository spryker/spryker-docs, pull requests merged in 2024-05, with the labels that each got.

#2653 Update environments-overview.md
  docs/ca/dev/environments-overview.md
Labels: urgent, updated

#2654 Glue api includes 1
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/glue-api-guides/202307.0/product-labels-response-attributes.md
  _includes/pbc/all/glue-api-guides/202311.0/product-labels-response-attributes.md
  _includes/pbc/all/glue-api-guides/202404.0/abstract-product-image-sets-reponse-attributes.md
  _includes/pbc/all/glue-api-guides/202404.0/category-nodes-response-attributes.md
  _includes/pbc/all/glue-api-guides/202404.0/product-management-attributes-response-attributes.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-customer-carts.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/manage-carts-of-registered-users/glue-api-manage-carts-of-registered-users.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/manage-guest-carts/glue-api-manage-guest-carts.md
  docs/pbc/all/merchant-management/202404.0/base-shop/merchant-b2b-contracts-and-contract-requests-feature-overview.md
  docs/pbc/all/merchant-management/202404.0/marketplace/marketplace-merchant-b2b-contracts-and-contract-requests-feature-overview.md
  docs/pbc/all/product-information-management/202311.0/base-shop/manage-using-glue-api/glue-api-retrieve-product-labels.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/abstract-products/glue-api-retrieve-abstract-products.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/abstract-products/glue-api-retrieve-image-sets-of-abstract-products.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/categories/glue-api-retrieve-category-nodes.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/concrete-products/glue-api-retrieve-concrete-products.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-product-attributes.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-product-labels.md
  docs/pbc/all/product-relationship-management/202404.0/glue-api-retrieve-related-products.md
  docs/pbc/all/shopping-list-and-wishlist/202404.0/base-shop/manage-using-glue-api/glue-api-manage-wishlists.md
Labels: small changes

#2643 ACP-2252: Stripe refund support added
  docs/about/all/releases/release-notes-202404.0.md
  docs/dg/dev/acp/sccos-dependencies-required-for-the-acp.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/install-and-configure-stripe-prerequisites.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/stripe.md
Labels: updated

#2664 Temporary hiding ACP app development guides
  _data/sidebars/dg_dev_sidebar.yml
  _drafts/acp-apps-development/develop-an-app/app-configuration-translation.md
  _drafts/acp-apps-development/develop-an-app/app-configuration.md
  _drafts/acp-apps-development/develop-an-app/app-manifest.md
  _drafts/acp-apps-development/develop-an-app/async-api.md
  _drafts/acp-apps-development/develop-an-app/configuration-json-file.md
  _drafts/acp-apps-development/develop-an-app/connect-an-app.md
  _drafts/acp-apps-development/develop-an-app/debug-an-app-with-xdebug.md
  _drafts/acp-apps-development/develop-an-app/develop-an-app.md
  _drafts/acp-apps-development/develop-an-app/manifest-json-file.md
  _drafts/acp-apps-development/develop-an-app/sync-api.md
  _drafts/acp-apps-development/develop-an-app/translation-json-file.md
  docs/about/all/about-the-docs/docs-updates.md
Labels: small changes

#1430 AE-24 Project NFR and development guidelines
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/best-practices/non-functional-requirement-templates/monitorable-process-guidelines.md
  docs/dg/dev/best-practices/non-functional-requirement-templates/non-functional-requirement-templates.md
  docs/dg/dev/best-practices/non-functional-requirement-templates/operatable-feature-guidelines.md
  docs/dg/dev/best-practices/non-functional-requirement-templates/operational-and-deployment-guidelines.md
  docs/dg/dev/best-practices/non-functional-requirement-templates/process-documentation-guidelines.md
  docs/pbc/all/identity-access-management/202404.0/install-and-upgrade/install-the-spryker-core-back-office-feature.md
Labels: TW review needed, new

#2666 Dynamic multistore 202404.0
  _includes/pbc/all/install-features/202404.0/install-dynamic-multistore.md
  _includes/pbc/all/upgrade-modules/upgrade-the-country-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-currency-module.md
Labels: updated

#2631 FRW-7828 Updated IG for DMS.
  _includes/pbc/all/upgrade-modules/upgrade-the-locale-module.md
Labels: in tech review, small changes

#2645 CC-31928: Added the Marketplace Merchant Commission feature integration.
  Rakefile
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-marketplace-merchant-commission.md
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-commission.md
Labels: tech review needed, TW review needed, new, 202407

#2669 Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: TW review needed, small changes

#2656 Update precise-search-by-super-attributes.md
  docs/pbc/all/search/202311.0/base-shop/best-practices/precise-search-by-super-attributes.md
Labels: TW review needed, small changes

#2670 ACP-3053: updated Vertex documentation for app release (17.05.2024)
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/install-vertex/install-vertex.md
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-the-vertex-app.md
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/vertex-faq.md
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/vertex.md
Labels: updated

#2678 Fix issue for B2C Marketplace installation recipe
  docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-macos-and-linux.md
Labels: small changes

#2679 Fix wrong b2c marketplace path in windows installation guide
  docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-windows.md
Labels: small changes

#2681 Update performance-testing-in-staging-enivronments.md
  docs/ca/dev/performance-testing-in-staging-enivronments.md
Labels: TW review needed

#2676 Dynamic cart overview
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/cart-and-checkout/202407.0/base-shop/feature-overviews/cart-feature-overview/cart-feature-overview.md
  docs/pbc/all/cart-and-checkout/202407.0/base-shop/feature-overviews/cart-feature-overview/dynamic-cart-overview.md
Labels: new

#2674 Update using-the-support-portal.md
  docs/about/all/support/using-the-support-portal.md
Labels: TW review needed, updated

#2680 Create scaling-explained.md
  _data/sidebars/ca_dev_sidebar.yml
  docs/ca/dev/environment-scaling.md
Labels: TW review needed, new

#2683 Community contributions
  _data/sidebars/about_all_sidebar.yml
  docs/about/all/about-the-docs/contribute-to-the-docs/merge-docs-pull-requests.md
Labels: new

#2630 Create multi-factor-authentication.md
  _data/sidebars/ca_dev_sidebar.yml
  docs/about/all/about-the-docs/contribute-to-the-docs/merge-docs-pull-requests.md
  docs/ca/dev/security/set-up-multi-factor-authentication.md
Labels: in TW review
