Repository spryker/spryker-docs, pull requests merged in 2024-07, with the labels that each got.

#2723 Adding media to the docs
  _data/sidebars/about_all_sidebar.yml
  docs/about/all/about-the-docs/contribute-to-the-docs/add-images-and-other-media-to-the-docs.md
Labels: new

#2455 Explain how to use CLI
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/sdks/the-docker-sdk/running-commands-with-the-docker-sdk.md
Labels: TW review needed

#2725 Oms design pitfalls
  docs/dg/dev/sdks/the-docker-sdk/running-commands-with-the-docker-sdk.md
  docs/pbc/all/order-management-system/202311.0/base-shop/datapayload-conversion/state-machine/common-pitfalls-in-oms-design.md
Labels: updated

#2716 Update cart-feature-overview.md
  _data/sidebars/ca_dev_sidebar.yml
  docs/ca/dev/add-variables-in-the-parameter-store.md
  docs/ca/dev/managing-parameters-in-the-parameter-store.md
  docs/ca/dev/release-notes.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/feature-overviews/cart-feature-overview/cart-feature-overview.md
Labels: small changes

#2728 Update dynamic-cart-overview.md
  docs/pbc/all/cart-and-checkout/202407.0/base-shop/feature-overviews/cart-feature-overview/dynamic-cart-overview.md
Labels: TW review needed, small changes

#2726 Updated audit logging related IGs.
  _includes/pbc/all/install-features/202407.0/install-the-agent-assist-feature.md
  _includes/pbc/all/install-features/202407.0/install-the-customer-account-management-feature.md
  _includes/pbc/all/install-features/202407.0/install-the-spryker-core-back-office-feature.md
  _includes/pbc/all/install-features/202407.0/install-the-spryker-core-feature.md
  docs/pbc/all/back-office/202407.0/base-shop/install-and-upgrade/install-the-spryker-core-back-office-feature.md
  docs/pbc/all/customer-relationship-management/202407.0/base-shop/install-and-upgrade/install-features/install-the-customer-account-management-feature.md
  docs/pbc/all/miscellaneous/202407.0/install-and-upgrade/install-features/install-the-spryker-core-feature.md
  docs/pbc/all/user-management/202407.0/base-shop/install-and-upgrade/install-the-agent-assist-feature.md
Labels: TW review needed, new, 202407

#2734 Gifs to mp4
  _includes/pbc/all/install-features/202307.0/install-the-gift-cards-feature.md
  _includes/pbc/all/install-features/202307.0/install-the-spryker-core-back-office-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-gift-cards-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-spryker-core-back-office-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-gift-cards-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-spryker-core-back-office-feature.md
  _includes/pbc/all/install-features/202407.0/install-the-customer-account-management-feature.md
  _includes/pbc/all/install-features/202407.0/install-the-gift-cards-feature.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/company-account-feature-overview/business-on-behalf-overview.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/company-account-feature-overview/company-accounts-overview.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/customer-account-management-feature-overview/customer-accounts-overview.md
  docs/pbc/all/order-management-system/202404.0/marketplace/manage-merchant-orders.md
  docs/pbc/all/search/202404.0/base-shop/search-feature-overview/standard-filters-overview.md
  docs/pbc/all/shopping-list-and-wishlist/202404.0/base-shop/shopping-lists-feature-overview/shopping-lists-feature-overview.md
  docs/pbc/all/shopping-list-and-wishlist/202404.0/base-shop/wishlist-feature-overview.md
  docs/pbc/all/shopping-list-and-wishlist/202404.0/marketplace/marketplace-shopping-lists-feature-overview.md
  docs/pbc/all/shopping-list-and-wishlist/202404.0/marketplace/marketplace-wishlist-feature-overview.md
  docs/pbc/all/tax-management/202404.0/base-shop/tax-feature-overview.md
Labels: small changes

#2740 Add whitelisting of Third-party systems to Security guidelines
  docs/dg/dev/guidelines/security-guidelines.md
Labels: small changes

#2705 FRW-8335 Spryker module development documentation.
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/architecture/architectural-convention.md
  docs/dg/dev/developing-standalone-modules/create-standalone-modules.md
  docs/dg/dev/developing-standalone-modules/developing-standalone-modules.md
  docs/dg/dev/developing-standalone-modules/driving-the-usage-of-standalone-modules.md
  docs/dg/dev/developing-standalone-modules/ensuring-quality-in-standalone-modules.md
  docs/dg/dev/developing-standalone-modules/prepare-for-standalone-module-development.md
  docs/dg/dev/developing-standalone-modules/publish-standalone-modules-on-github.md
  docs/dg/dev/developing-standalone-modules/publish-standalone-modules-on-packagist.md
  docs/dg/dev/developing-standalone-modules/test-the-compatibility-of-standalone-modules.md
Labels: new

#2737 ACP-3511: Added missing Payone portal configuration description
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/payone/integration-in-the-back-office/configure-payone.md
Labels: updated

#2738 ACP-3375 Added docs on how to pass additionalPaymentData to Stripe.
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
Labels: updated

#2744 Audit Logs in AWS
  _includes/searching-by-logs.md
  docs/ca/dev/working-with-logs.md
Labels: updated

#2742 Update configure-services.md
  docs/dg/dev/integrate-and-configure/configure-services.md
Labels: TW review needed

#2743 ACP-2601: How to embed Stripe App payment page to your storefront application
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
  docs/pbc/all/search/202404.0/base-shop/install-and-upgrade/upgrade-search-initialization.md
Labels: updated

#2747 Update install-the-sales-data-export-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-sales-data-export-feature.md
Labels: TW review needed, small changes

#2748 Update system-requirements.md
  docs/dg/dev/system-requirements/202407.0/system-requirements.md
Labels: Bypassed TW Review

#2732 HowTos Audit Logs
  _data/sidebars/dg_dev_sidebar.yml
  docs/ca/dev/working-with-logs.md
  docs/dg/dev/backend-development/audit-logs/add-audit-log-types.md
  docs/dg/dev/backend-development/audit-logs/audit-logs.md
  docs/dg/dev/backend-development/audit-logs/extend-the-audit-log-structure.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
Labels: in tech review, new, 202407

#2745 Gifs to mp4 2
  docs/ca/dev/configure-deployment-pipelines/deployment-in-states.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/feature-overviews/approval-process-feature-overview.md
  docs/pbc/all/merchant-management/202404.0/marketplace/marketplace-merchant-feature-overview/marketplace-merchant-feature-overview.md
  docs/pbc/all/request-for-quote/202404.0/request-for-quote.md
  docs/pbc/all/return-management/202404.0/marketplace/marketplace-return-management-feature-overview.md
  docs/pbc/all/search/202404.0/base-shop/manage-in-the-back-office/category-filters/assign-and-deassign-filters-from-categories.md
  docs/pbc/all/search/202404.0/base-shop/manage-in-the-back-office/category-filters/reorder-category-filters.md
Labels: small changes
