Repository spryker/spryker-docs, pull requests merged in 2024-04, with the labels that each got.

#2591 Changed SF to 6.4 LTS
  docs/dg/dev/upgrade-and-migrate/upgrade-to-symfony-6.md
Labels: small changes

#2593 Update code contribution guidelines and howto
  docs/dg/dev/code-contribution-guide.md
Labels: ready for merge, urgent, updated

#2595 Update build-changelog.yml
  .github/workflows/build-changelog.yml
Labels: small changes

#2589 Acp overview
  docs/dg/dev/acp/acp-overview.md
  docs/dg/dev/acp/app-composition-platform.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/stripe.md
Labels: updated

#2565 AE-62 Defining conventions
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/architecture/architectural-convention-reference.md
Labels: new

#2603 AE-62 Fixed dropdown box style format error with empty lines
  docs/dg/dev/architecture/architectural-convention-reference.md
Labels: small changes

#2573 Merchant relation requests
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchants/manage-in-the-back-office/create-merchant-relations.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchants/manage-in-the-back-office/create-merchants.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchants/manage-in-the-back-office/edit-merchant-relations.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchants/manage-in-the-back-office/edit-merchants.md
  docs/pbc/all/merchant-management/202311.0/marketplace/manage-in-the-back-office/manage-merchants/manage-in-the-back-office/manage-merchants-in-the-back-office.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-merchant-portal/manage-merchant-relation-requests.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-merchant-portal/manage-merchant-relations.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/create-merchant-relations.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/edit-merchant-relations.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchant-relation-requests.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchant-relations/create-merchant-relations.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchant-relations/edit-merchant-relations.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchant-users/create-merchant-users.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchant-users/edit-merchant-users.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchants/create-merchants.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchants/edit-merchants.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchants/manage-in-the-back-office/create-merchant-relations.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchants/manage-in-the-back-office/create-merchants.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchants/manage-in-the-back-office/edit-merchant-relations.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchants/manage-in-the-back-office/edit-merchants.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchants/manage-in-the-back-office/manage-merchants-in-the-back-office.md
  docs/pbc/all/merchant-management/202404.0/marketplace/merchant-b2b-contracts-and-contract-requests-features-overview.md
Labels: in progress, new

#2605 ACP installation update
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/acp/app-composition-platform-installation.md
  docs/dg/dev/acp/app-composition-platform.md
  docs/dg/dev/acp/sccos-dependencies-required-for-the-acp.md
Labels: updated

#2539 FRW-7296 Adjusted error response messages
  _includes/pbc/all/install-features/202311.0/install-the-data-exchange-api.md
  docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-send-request-in-data-exchange-api.md
Labels: in TW review, updated

#2607 adding version to the sidebar
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-merchant-portal/manage-merchant-relations.md
  docs/pbc/all/merchant-management/202404.0/marketplace/merchant-b2b-contracts-and-contract-requests-features-overview.md
Labels: small changes

#2601 Update configure-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/configure-vertex.md
Labels: small changes

#2610 Issues fix
  _data/sidebars/pbc_all_sidebar.yml
  docs/dg/dev/acp/sccos-dependencies-required-for-the-acp.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-merchant-portal/manage-merchant-relation-requests.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/create-merchant-relations.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/edit-merchant-relations.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchant-relations/create-merchant-relations.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchant-relations/manage-merchant-relation-requests.md
  docs/pbc/all/merchant-management/202404.0/marketplace/merchant-b2b-contracts-and-contract-requests-features-overview.md
Labels: small changes

#2600 Penetration testing
  _data/sidebars/ca_dev_sidebar.yml
  docs/ca/dev/security/penetration-testing.md
Labels: new

#2343 Create cannot-resolve-host-zed-calls-are-forbidden
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/could-not-resolve-host-zed-calls-are-forbidden-from-zed.md
Labels: new

#2602 Update jenkins-operational-best-practices.md
  docs/ca/dev/best-practices/jenkins-operational-best-practices.md
Labels: TW review needed

#2582 CC-33168 Angular 17 migration
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/upgrade-and-migrate/upgrade-to-angular-17.md
  docs/dg/dev/upgrade-and-migrate/upgrade-to-stylelint-16-and-css-loader-6.md
Labels: in TW review, new

#2613 Update upgrade-to-angular-17.md
  docs/dg/dev/upgrade-and-migrate/upgrade-to-angular-17.md
Labels: small changes

#2614 Update upgrade-to-stylelint-16-and-css-loader-6.md
  docs/dg/dev/upgrade-and-migrate/upgrade-to-stylelint-16-and-css-loader-6.md
Labels: small changes

#2612 ACP-2532: Update integrate-algolia.md
  docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
Labels: updated

#2615 Update _config.yml
  _config.yml
Labels: small changes

#2547 Update create-and-configure-zed-tables.md
  docs/dg/dev/backend-development/zed-ui-tables/create-and-configure-zed-tables.md
Labels: TW review needed, small changes

#2477 Update module-configuration-convention.md
  docs/dg/dev/guidelines/module-configuration-convention.md
Labels: TW review needed

#2561 Update create-discounts.md
  docs/pbc/all/discount-management/202311.0/base-shop/manage-in-the-back-office/create-discounts.md
Labels: TW review needed

#2458 Explain how to run spryk in non-interactive mode
  docs/dg/dev/sdks/sdk/spryks/spryks.md
Labels: TW review needed, updated

#2344 Update plugins.md
  docs/dg/dev/backend-development/plugins/plugins.md
Labels: small changes

#2373 Typo on `HowTo Create an Angular module` page
  docs/dg/dev/frontend-development/202212.0/create-angular-modules.md
  docs/dg/dev/frontend-development/202311.0/create-angular-modules.md
Labels: small changes

#2375 Update glue-api-manage-items-in-carts-of-registered-users.md
  docs/pbc/all/cart-and-checkout/202311.0/base-shop/manage-using-glue-api/manage-carts-of-registered-users/glue-api-manage-items-in-carts-of-registered-users.md
Labels: small changes

#2525 Update environments-overview.md
  docs/about/all/releases/security-release-notes-202312.0.md
  docs/ca/dev/environments-overview.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
Labels: small changes

#2621 Update deploy-file-reference.md
  docs/dg/dev/sdks/the-docker-sdk/deploy-file/deploy-file-reference.md
Labels: TW review needed

#2557 Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: TW review needed, small changes

#2604 FRW-7688 Updated system requirements.
  docs/dg/dev/system-requirements/202407.0/system-requirements.md
Labels: in tech review, new, small changes

#2413 CC-32127 Added Cookies configuration fixes for payment providers.
  docs/pbc/all/payment-service-provider/202307.0/base-shop/third-party-integrations/adyen/install-and-configure-adyen.md
  docs/pbc/all/payment-service-provider/202307.0/base-shop/third-party-integrations/computop/install-and-configure-computop.md
  docs/pbc/all/payment-service-provider/202307.0/base-shop/third-party-integrations/unzer/install-unzer/install-and-configure-unzer.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/adyen/install-and-configure-adyen.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/computop/install-and-configure-computop.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/unzer/install-unzer/install-and-configure-unzer.md
Labels: in tech review

#2276 Web Application Firewall (WAF)
  docs/ca/dev/security/web-application-firewall-waf.md
Labels: small changes

#2529 Update Bypass the key-value storage documentation
  docs/dg/dev/backend-development/data-manipulation/data-publishing/bypass-the-key-value-storage.md
Labels: TW review needed, small changes

#2622 CC-33273 Add Checkout + Non-splittable Products IG
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202404.0/install-the-checkout-non-splittable-products-feature.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/install-and-upgrade/install-features/install-the-checkout-non-splittable-products-feature.md
Labels: TW review needed, new, 202400

#2624 ACP-2478: Mention that algolia indexes won't be removed after disconnect
  docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/disconnect-algolia.md
Labels: small changes

#2559 Install the Warehouse picking feature formatting fixes
  _includes/pbc/all/install-features/202311.0/unified-commerce/install-the-warehouse-picking-feature.md
Labels: TW review needed, updated, small changes

#2594 Update guidelines-for-gdpr-compliance.md
  _data/sidebars/about_all_sidebar.yml
  docs/about/all/support/gdpr-compliance-guidelines.md
  docs/about/all/support/guidelines-for-gdpr-compliance.md
  docs/ca/dev/preparation-for-going-live.md
Labels: updated

#2628 Placeholder for the release notes
  docs/about/all/releases/release-notes-202404.0.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-merchant-portal/manage-merchant-relation-requests.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchant-relations/manage-merchant-relation-requests.md
  docs/pbc/all/merchant-management/202404.0/marketplace/merchant-b2b-contracts-and-contract-requests-features-overview.md
  docs/pbc/all/user-management/202404.0/base-shop/agent-assist-feature-overview.md
  docs/pbc/all/user-management/202404.0/marketplace/merchant-portal-agent-assist-feature-overview.md
Labels: small changes

#2632 Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: in TW review, small changes

#2642 Update merchant-b2b-contracts-feature-overview.md
  docs/pbc/all/merchant-management/202404.0/base-shop/merchant-b2b-contracts-feature-overview.md
Labels: TW review needed, small changes

#2644 Release notes 202404
  _archive/release-notes/release-notes-202211.0.md
  _archive/release-notes/release-notes-202212.0/patch-release-notes-202212.0.md
  _archive/release-notes/release-notes-202212.0/release-notes-202212.0.md
  _archive/release-notes/release-notes-202212.0/security-release-notes-202212.0.md
  _data/sidebars/about_all_sidebar.yml
  _data/sidebars/pbc_all_sidebar.yml
  docs/about/all/releases/release-notes-202404.0.md
  docs/dg/dev/acp/sccos-dependencies-required-for-the-acp.md
  docs/pbc/all/merchant-management/202404.0/base-shop/merchant-b2b-contracts-feature-overview.md
  docs/pbc/all/request-for-quote/202311.0/import-and-export-data/file-details-quote-request-version.csv.md
  docs/pbc/all/request-for-quote/202311.0/import-and-export-data/file-details-quote-request.csv.md
Labels: new

#2634 Update penetration-testing.md
  _includes/pbc/all/install-features/202311.0/install-the-multi-store-products-feature.md
  docs/ca/dev/security/penetration-testing.md
Labels: TW review needed

#2640 Update merchant-b2b-contracts-feature-overview.md
  docs/pbc/all/merchant-management/202404.0/base-shop/merchant-b2b-contracts-feature-overview.md
Labels: TW review needed, small changes

#2641 Update merchant-b2b-contracts-and-contract-requests-features-overview.md
  docs/pbc/all/merchant-management/202404.0/marketplace/merchant-b2b-contracts-and-contract-requests-features-overview.md
Labels: TW review needed, updated

#2649 Update heroku deployment action
  .github/workflows/ci.yml
Labels: small changes
