Repository spryker/spryker-docs, pull requests merged in 2024-02, with the labels that each got.

#2489 Fixing a title
  _data/sidebars/scos_user_sidebar.yml
Labels: small changes

#2481 Import big databases
  _data/sidebars/scos_dev_sidebar.yml
  docs/scos/dev/developer-getting-started-guide.md
  docs/scos/dev/tutorials-and-howtos/howtos/howto-import-big-databases-between-environments.md
  docs/scos/dev/tutorials-and-howtos/howtos/transfer-big-databases-between-environments.md
  docs/scos/user/intro-to-spryker/docs-updates.md
Labels: updated

#2479 FRW-6430 Data Exchange API Complex Endpoints for POST, PUT and PATCH
  _includes/pbc/all/install-features/202311.0/install-the-data-exchange-api.md
  docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-send-request-in-data-exchange-api.md
Labels: in TW review, updated

#2488 FRW-6532 public announcement of the Flysystem major
  docs/scos/user/intro-to-spryker/whats-new/upcoming-major-module-releases.md
Labels: small changes

#2487 CC-32057: BAPI authorization alignment with latest updates.
  _includes/pbc/all/install-features/202403.0/marketplace/install-the-merchant-portal-agent-assist-feature.md
  _includes/pbc/all/install-features/202403.0/unified-commerce/install-the-warehouse-user-management-feature.md
Labels: TW review needed, updated, 202400

#2501 Update build-changelog.yml
  .github/workflows/build-changelog.yml
Labels: small changes

#2502 Rename login BO instructions
  _data/sidebars/pbc_all_sidebar.yml
  docs/dg/dev/developer-getting-started-guide.md
  docs/pbc/all/carrier-management/202212.0/base-shop/manage-in-the-back-office/manage-carrier-companies-and-delivery-methods-in-the-back-office.md
  docs/pbc/all/carrier-management/202307.0/base-shop/manage-in-the-back-office/manage-carrier-companies-and-delivery-methods-in-the-back-office.md
  docs/pbc/all/carrier-management/202311.0/base-shop/manage-in-the-back-office/manage-carrier-companies-and-delivery-methods-in-the-back-office.md
  docs/pbc/all/cart-and-checkout/202204.0/base-shop/tutorials-and-howtos/handling-carts-with-a-big-number-of-items.md
  docs/pbc/all/cart-and-checkout/202212.0/base-shop/manage-in-the-back-office/manage-thresholds-the-back-office.md
  docs/pbc/all/cart-and-checkout/202307.0/base-shop/manage-in-the-back-office/manage-thresholds-the-back-office.md
  docs/pbc/all/cart-and-checkout/202311.0/base-shop/manage-in-the-back-office/manage-thresholds-the-back-office.md
  docs/pbc/all/content-management-system/202212.0/base-shop/manage-in-the-back-office/log-into-the-back-office.md
  docs/pbc/all/content-management-system/202212.0/base-shop/manage-in-the-back-office/manage-content-in-the-back-office.md
  docs/pbc/all/content-management-system/202307.0/base-shop/manage-in-the-back-office/log-into-the-back-office.md
  docs/pbc/all/content-management-system/202307.0/base-shop/manage-in-the-back-office/manage-content-in-the-back-office.md
  docs/pbc/all/content-management-system/202311.0/base-shop/manage-in-the-back-office/log-into-the-back-office.md
  docs/pbc/all/content-management-system/202311.0/base-shop/manage-in-the-back-office/manage-content-in-the-back-office.md
  docs/pbc/all/customer-relationship-management/202212.0/base-shop/manage-in-the-back-office/manage-companies-and-customers-in-the-back-office.md
  docs/pbc/all/customer-relationship-management/202307.0/base-shop/manage-in-the-back-office/manage-companies-and-customers-in-the-back-office.md
  docs/pbc/all/customer-relationship-management/202311.0/base-shop/manage-in-the-back-office/manage-companies-and-customers-in-the-back-office.md
  docs/pbc/all/discount-management/202212.0/base-shop/manage-in-the-back-office/manage-discounts-in-the-back-office.md
  docs/pbc/all/discount-management/202307.0/base-shop/manage-in-the-back-office/manage-discounts-in-the-back-office.md
  docs/pbc/all/discount-management/202311.0/base-shop/manage-in-the-back-office/manage-discounts-in-the-back-office.md
  docs/pbc/all/merchant-management/202212.0/base-shop/manage-in-the-back-office/manage-merchants-in-the-back-office.md
  docs/pbc/all/merchant-management/202307.0/base-shop/manage-in-the-back-office/manage-merchants-in-the-back-office.md
  docs/pbc/all/merchant-management/202311.0/base-shop/manage-in-the-back-office/manage-merchants-in-the-back-office.md
  docs/pbc/all/miscellaneous/202212.0/manage-in-the-back-office/manage-translations-in-the-back-office.md
  docs/pbc/all/miscellaneous/202307.0/manage-in-the-back-office/manage-translations-in-the-back-office.md
  docs/pbc/all/miscellaneous/202311.0/manage-in-the-back-office/manage-translations-in-the-back-office.md
  docs/pbc/all/order-management-system/202212.0/base-shop/manage-in-the-back-office/manage-orders-in-the-back-office.md
  docs/pbc/all/order-management-system/202307.0/base-shop/manage-in-the-back-office/manage-orders-in-the-back-office.md
  docs/pbc/all/order-management-system/202311.0/base-shop/manage-in-the-back-office/manage-orders-in-the-back-office.md
  docs/pbc/all/tax-management/202311.0/base-shop/manage-in-the-back-office/create-tax-rates.md
Labels: small changes

#2505 Docs updates 01.2024
  docs/pbc/all/customer-relationship-management/202403.0/base-shop/install-and-upgrade/install-features/install-the-customer-account-management-agent-assist-feature.md
  docs/pbc/all/customer-relationship-management/202403.0/base-shop/install-and-upgrade/install-glue-api/install-the-company-account-glue-api.md
  docs/pbc/all/miscellaneous/202403.0/install-and-upgrade/install-features/install-the-spryker-core-feature.md
  docs/pbc/all/user-management/202403.0/base-shop/install-and-upgrade/install-the-agent-assist-feature.md
  docs/scos/user/intro-to-spryker/docs-updates.md
Labels: small changes

#2507 Update docs-updates.md
  docs/scos/user/intro-to-spryker/docs-updates.md
Labels: small changes

#2504 Vertex: Fixed incorrect method naming for the TaxAppDependencyProvider
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-the-vertex-app.md
Labels: TW review needed, small changes

#2500 Stripe guides update
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202403.0/marketplace/install-the-merchant-portal-agent-assist-feature.md
  docs/acp/user/intro-to-acp/acp-overview.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/configure-stripe.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/disconnect-stripe.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/manage-stripe-configurations-in-the-acp-catalog.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/sccos-prerequisites-for-the-stripe-app.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/stripe.md
Labels: updated

#2485 CC-32589 Add integration guide for Data Exchange + Category Management feature
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202311.0/install-the-data-exchange-api-inventory-management-feature.md
  _includes/pbc/all/install-features/202403.0/install-the-data-exchange-api-category-management-feature.md
  docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-configure-data-exchange-api.md
  docs/pbc/all/data-exchange/202403.0/install-and-upgrade/install-the-data-exchange-api-category-management-feature.md
Labels: TW review needed, new, 202400

#2506 Update module-configuration-convention.md
  docs/dg/dev/guidelines/module-configuration-convention.md
Labels: TW review needed, small changes

#2514 Development guide: Updating Spryker
  _data/sidebars/dg_dev_sidebar.yml
  _data/sidebars/scos_dev_sidebar.yml
  _scripts/redirects_generator/redirect_from_generator.sh
  _scripts/redirects_generator/redirects_generator.sh
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/upgradability-guidelines.md
  docs/dg/dev/guidelines/project-development-guidelines.md
  docs/dg/dev/updating-spryker/analyzing-and-upgrading-projects-with-spryker-jarvis.md
  docs/dg/dev/updating-spryker/feature-or-module-updates.md
  docs/dg/dev/updating-spryker/installing-features-and-updating-modules.md
  docs/dg/dev/updating-spryker/planning-updates.md
  docs/dg/dev/updating-spryker/switch-demo-shop-version.md
  docs/dg/dev/updating-spryker/testing-updates.md
  docs/dg/dev/updating-spryker/troubleshooting-updates.md
  docs/dg/dev/updating-spryker/updating-spryker.md
  docs/scos/dev/updating-spryker/preventing-update-issues.md
  docs/scos/user/intro-to-spryker/docs-updates.md
  docs/scu/dev/spryker-code-upgrader-in-a-development-workflow.md
Labels: small changes

#2517 Add global sections to the documentation
  _data/sidebars/scos_user_sidebar.yml
  docs/dg/dev/backend-development/messages-and-errors/registering-a-new-service.md
  docs/dg/dev/guidelines/performance-guidelines/architecture-performance-guidelines.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/add-global-sections-to-the-documentation.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/build-the-documentation-site.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/contribute-to-the-documentation.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/edit-documentation-via-pull-requests.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/general-rules-and-guidance-for-adding-new-documents.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/install-recommended-vs-code-extensions.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/markdown-syntax.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/report-documentation-issues.md
  docs/scos/user/intro-to-spryker/contribute-to-the-documentation/review-pull-requests.md
Labels: updated

#2498 Feature/acp 2289/master refactor message names to follow our defined structure all new message names
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/sccos-prerequisites-for-the-stripe-app.md
Labels: do not merge, small changes

#2515 Add new security recommendation (add new external package to the project
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/guidelines/coding-guidelines/secure-coding-practices-for-external-packages.md
Labels: new

#2519 Update project-guidelines-for-stripe.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
Labels: small changes

#2403 [WIP] Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: updated

#2511 [monitoring-doc-improvements] Updating monitoring services
  docs/ca/dev/monitoring-issues-and-informing-about-alerts.md
Labels: 202400

#2523 Hits per page in the new search
  _includes/search/algolia_quicksearch.html
Labels: small changes

#2524 Update stripe.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/stripe.md
Labels: updated

#2530 feat: search integration
  Gemfile.lock
  _includes/search/algolia-quicksearch.html
  _includes/search/algolia_config.html
  _includes/search/algolia_deprecated-quicksearch.html
  _includes/topnav.html
  _layouts/deprecated-home.html
  _layouts/home.html
  _layouts/search.html
  algolia_config/_ca_dev.yml
  algolia_config/_ca_devscu.yml
  algolia_config/_dg_dev.yml
  algolia_config/_pbc_all.yml
  algolia_config/_scos_dev.yml
  algolia_config/_scos_user.yml
  algolia_config/_sdk_dev.yml
  css/components/_search-section.scss
  index.md
  index_ds.md
  js/algolia-search.js
  js/algolia-suggestions.js
  js/customscripts.js
Labels: javascript, updated

#2536 FRW-6879 Updated docs
  docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-send-request-in-data-exchange-api.md
  docs/scos/dev/glue-api-guides/202311.0/use-default-glue-parameters.md
Labels: updated

#1881 Docker SDK: Robot Framework
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/guidelines/testing-guidelines/running-tests-with-robot-framework.md
  docs/dg/dev/sdks/the-docker-sdk/docker-sdk-quick-start-guide.md
  docs/dg/dev/sdks/the-docker-sdk/the-docker-sdk.md
Labels: new
