Repository spryker/spryker-docs, pull requests merged in 2024-10, with the labels that each got.

#2834 Adjusted redis-session-lock-excpetions.md
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/troubleshooting/troubleshooting-performance-issues/redis-session-lock-excpetions.md
  docs/dg/dev/troubleshooting/troubleshooting-performance-issues/redis-session-lock.md
Labels: TW review needed, urgent, updated

#2838 Update configuration-of-price-modes-and-types.md
  docs/pbc/all/price-management/202404.0/base-shop/extend-and-customize/configuration-of-price-modes-and-types.md
Labels: TW review needed, updated

#2840 ACP-3930: Different foreign oms for each Business Model.
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/install-and-configure-stripe-prerequisites.md
  docs/pbc/all/payment-service-provider/202404.0/marketplace/stripe-third-party-integration/install-and-configure-stripe-prerequisites-for-marketplace.md
Labels: small changes

#2842 CC-34423 Adjust merchant Commissions IG
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-marketplace-merchant-commission-feature.md
Labels: TW review needed, updated, 202407

#2844 Update install-the-spryker-core-back-office-feature.md
  _data/sidebars/ca_dev_sidebar.yml
  _includes/pbc/all/install-features/202407.0/install-the-spryker-core-back-office-feature.md
  docs/ca/dev/monitoring-issues-and-informing-about-alerts.md
  docs/ca/dev/monitoring/customize-aws-cloudwatch-dashboards.md
  docs/ca/dev/monitoring/monitoring.md
  docs/ca/dev/monitoring/performance-and-availability-monitoring-via-new-relic.md
Labels: TW review needed, updated

#2845 CC-34259 Product comparison IG
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202407.0/install-the-product-comparison-feature.md
  _includes/pbc/all/install-features/202407.0/install-the-product-feature.md
  docs/ca/dev/connect-a-code-repository.md
  docs/pbc/all/data-exchange/202404.0/data-exchange-faq.md
  docs/pbc/all/product-information-management/202407.0/base-shop/install-and-upgrade/install-features/install-the-product-comparison-feature.md
Labels: TW review needed, new, 202407

#2853 Update monitoring-issues-and-informing-about-alerts.md
  docs/ca/dev/monitoring-issues-and-informing-about-alerts.md
Labels: TW review needed

#2770 Fix missing part in HOW TO create custom content item
  docs/pbc/all/content-management-system/202404.0/base-shop/tutorials-and-howtos/create-a-custom-content-item.md
Labels: tech review needed, small changes

#2850 Staging Merge - October
  Rakefile
  _config.yml
  _config_staging.yml
  _includes/head.html
  robots.txt
Labels: new, Bypassed TW Review

#2857 FRW-9135 Added AI tools how-to.
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/ai-coding-assistants.md
Labels: new

#2861 product-comparison-feature-overivew
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/product-information-management/202410.0/base-shop/feature-overviews/product-comparison-feature-overview.md
  docs/pbc/all/product-information-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-product-comparison-feature.md
Labels: new

#2859 Update implement-publish-and-synchronization.md
  docs/dg/dev/backend-development/data-manipulation/data-publishing/implement-publish-and-synchronization.md
Labels: updated, Bypassed TW Review

#2810 FRW-1633 Updated PostgreSql version.
  docs/dg/dev/integrate-and-configure/configure-services.md
  docs/dg/dev/sdks/the-docker-sdk/deploy-file/deploy-file-reference.md
  docs/dg/dev/system-requirements/202311.0/system-requirements.md
  docs/dg/dev/system-requirements/202404.0/system-requirements.md
  docs/dg/dev/system-requirements/202410.0/system-requirements.md
Labels: TW review needed

#2868 FRW-6475 Fixed product label localized attributes.
  _includes/pbc/all/install-features/202410.0/install-the-product-labels-feature.md
Labels: in TW review, small changes

#2872 Release notes 202410
  _data/sidebars/about_all_sidebar.yml
  docs/about/all/releases/release-notes-202404.0.md
  docs/about/all/releases/release-notes-202410.0.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/feature-overviews/cart-feature-overview/dynamic-cart-overview.md
  docs/pbc/all/dynamic-multistore/202404.0/base-shop/dynamic-multistore-feature-overview.md
Labels: new
