Repository spryker/spryker-docs, pull requests merged in 2024-08, with the labels that each got.

#2749 ACP-3514: Updated limitation for payone & fixed navigation
  _data/sidebars/pbc_all_sidebar.yml
  docs/dg/dev/backend-development/audit-logs/audit-logs.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/payone/integration-in-the-back-office/payone-integration-in-the-back-office.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/payone/payone.md
Labels: TW review needed, small changes

#2731 CC-33931 Merchant Commission How To
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/tutorials-and-howtos/create-merchant-commission-calculator-type-plugins.md
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/tutorials-and-howtos/create-merchant-commission-collector-rule.md
Labels: TW review needed, new, 202407

#2423 Update common-pitfalls-in-oms-design.md
  docs/pbc/all/order-management-system/202311.0/base-shop/datapayload-conversion/state-machine/common-pitfalls-in-oms-design.md
Labels: TW review needed, updated

#2441 CC-32477 Add new Helper and adjust E2E testing guides
  docs/dg/dev/guidelines/testing-guidelines/executing-tests/test-glue-api.md
  docs/dg/dev/guidelines/testing-guidelines/executing-tests/test-glue-backend-api.md
  docs/dg/dev/guidelines/testing-guidelines/test-helpers/test-helpers.md
Labels: tech review needed, updated, 202400

#2746 FRW-8409 Adjusted DEX documentation and added howtos.
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202404.0/install-the-data-exchange-api.md
  docs/pbc/all/data-exchange/202404.0/create-post-plugins-for-data-exchange-api.md
  docs/pbc/all/payment-service-provider/202404.0/marketplace/stripe-third-party-integration/install-and-configure-stripe-prerequisites-for-marketplace.md
Labels: TW review needed, new

#2757 Update Spryker Demo Install Version to 202404.0
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-macos-and-linux.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-windows.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-macos-and-linux.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-windows.md
  docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-macos-and-linux.md
  docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-windows.md
Labels: small changes

#2761 ACP-3589: Adjusted retrieve-and-use-payment-details-from-third-party-…
  docs/pbc/all/payment-service-provider/202404.0/base-shop/retrieve-and-use-payment-details-from-third-party-psps.md
Labels: TW review needed, small changes

#2759 Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: TW review needed

#2762 ACP-2626 Added missing message configuration
  docs/pbc/all/payment-service-provider/202404.0/marketplace/stripe-third-party-integration/install-and-configure-stripe-prerequisites-for-marketplace.md
Labels: updated

#2735 Merchant commission PBC docs
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-marketplace-merchant-commission.md
  docs/pbc/all/merchant-management/202407.0/marketplace/import-and-export-data/merchant-commissions/import-file-details-merchant-comission.csv.md
  docs/pbc/all/merchant-management/202407.0/marketplace/import-and-export-data/merchant-commissions/import-file-details-merchant_commission_amount.csv.md
  docs/pbc/all/merchant-management/202407.0/marketplace/import-and-export-data/merchant-commissions/import-file-details-merchant_commission_group.csv.md
  docs/pbc/all/merchant-management/202407.0/marketplace/import-and-export-data/merchant-commissions/import-file-details-merchant_commission_merchant.csv.md
  docs/pbc/all/merchant-management/202407.0/marketplace/import-and-export-data/merchant-commissions/import-file-details-merchant_commission_store.csv.md
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/manage-in-the-back-office/back-office-import-merchant-commissions.md
  docs/pbc/all/merchant-management/202407.0/marketplace/marketplace-merchant-commission-feature-overview.md
Labels: new

#2758 Update environment-provisioning.md
  docs/ca/dev/environment-provisioning.md
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/manage-in-the-back-office/back-office-import-merchant-commissions.md
Labels: TW review needed

#2766 related articles
  docs/pbc/all/merchant-management/202407.0/marketplace/import-and-export-data/merchant-commissions/import-file-details-merchant-comission.csv.md
  docs/pbc/all/merchant-management/202407.0/marketplace/marketplace-merchant-commission-feature-overview.md
Labels: updated

#2765 Update general-performance-guidelines.md
  docs/dg/dev/guidelines/performance-guidelines/general-performance-guidelines.md
Labels: updated, 202400, small changes

#2756 ACP-2626: Added the marketplace payment IG.
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-category-management-marketplace-merchant-commission.md
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-marketplace-merchant-commission-feature.md
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-marketplace-merchant-commission.md
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-marketplace-merchant-feature.md
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-prices-marketplace-merchant-commission-feature.md
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-product-marketplace-merchant-commission-feature.md
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-commission-feature.md
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-feature.md
  docs/pbc/all/payment-service-provider/202404.0/marketplace/stripe-third-party-integration/install-and-configure-stripe-prerequisites-for-marketplace.md
Labels: tech review needed, updated, 202407

#2528 Update best-practises-jenkins-stability.md
  docs/ca/dev/best-practices/best-practises-jenkins-stability.md
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/manage-in-the-back-office/back-office-import-merchant-commissions.md
Labels: updated, small changes

#2657 Update search-best-practices.md
  docs/dg/dev/frontend-development/202404.0/oryx/getting-started/oryx-versioning.md
  docs/pbc/all/merchant-management/202407.0/marketplace/import-and-export-data/merchant-commissions/import-file-details-merchant_commission_group.csv.md
  docs/pbc/all/merchant-management/202407.0/marketplace/import-and-export-data/merchant-commissions/import-file-details-merchant_commission_merchant.csv.md
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/manage-in-the-back-office/back-office-import-merchant-commissions.md
  docs/pbc/all/merchant-management/202407.0/marketplace/marketplace-merchant-commission-feature-overview.md
  docs/pbc/all/search/202311.0/base-shop/best-practices/search-best-practices.md
  docs/pbc/all/search/202404.0/base-shop/best-practices/search-best-practices.md
Labels: small changes

#2764 Feature Overview
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/payment-service-provider/202404.0/marketplace/stripe-third-party-integration/stripe-for-marketplace-overview.md
Labels: TW review needed

#2667 Update howto-make-a-product-searchable-and-shown-on-the-storefront.md
  _data/sidebars/pbc_all_sidebar.yml
  docs/about/all/about-spryker.md
  docs/ca/dev/performance-testing-in-staging-enivronments.md
  docs/dg/dev/backend-development/data-manipulation/data-publishing/handle-data-with-publish-and-synchronization.md
  docs/pbc/all/product-information-management/202307.0/base-shop/feature-overviews/packaging-units-feature-overview.md
  docs/pbc/all/product-information-management/202307.0/base-shop/feature-overviews/product-groups-feature-overview.md
  docs/pbc/all/product-information-management/202307.0/base-shop/import-and-export-data/import-file-details-product-packaging-unit-type.csv.md
  docs/pbc/all/product-information-management/202307.0/base-shop/manage-in-the-back-office/products/create-service-offerings-best-practices.md
  docs/pbc/all/product-information-management/202307.0/base-shop/manage-in-the-back-office/products/manage-product-variants/create-product-variants.md
  docs/pbc/all/product-information-management/202307.0/base-shop/tutorials-and-howtos/howto-display-product-groups-by-color-on-the-storefront.md
  docs/pbc/all/product-information-management/202307.0/base-shop/tutorials-and-howtos/howto-import-packaging-units.md
  docs/pbc/all/product-information-management/202307.0/base-shop/tutorials-and-howtos/make-products-searchable-and-shown-on-the-storefront.md
  docs/pbc/all/product-information-management/202307.0/marketplace/manage-in-the-back-office/products/create-product-variants.md
  docs/pbc/all/product-information-management/202311.0/base-shop/feature-overviews/packaging-units-feature-overview.md
  docs/pbc/all/product-information-management/202311.0/base-shop/feature-overviews/product-groups-feature-overview.md
  docs/pbc/all/product-information-management/202311.0/base-shop/import-and-export-data/import-file-details-product-packaging-unit-type.csv.md
  docs/pbc/all/product-information-management/202311.0/base-shop/manage-in-the-back-office/products/create-service-offerings-best-practices.md
  docs/pbc/all/product-information-management/202311.0/base-shop/manage-in-the-back-office/products/manage-product-variants/create-product-variants.md
  docs/pbc/all/product-information-management/202311.0/base-shop/tutorials-and-howtos/howto-display-product-groups-by-color-on-the-storefront.md
  docs/pbc/all/product-information-management/202311.0/base-shop/tutorials-and-howtos/howto-import-packaging-units.md
  docs/pbc/all/product-information-management/202311.0/base-shop/tutorials-and-howtos/make-products-searchable-and-shown-on-the-storefront.md
  docs/pbc/all/product-information-management/202311.0/marketplace/manage-in-the-back-office/products/create-product-variants.md
  docs/pbc/all/product-information-management/202404.0/base-shop/feature-overviews/packaging-units-feature-overview.md
  docs/pbc/all/product-information-management/202404.0/base-shop/feature-overviews/product-groups-feature-overview.md
  docs/pbc/all/product-information-management/202404.0/base-shop/import-and-export-data/file-details-product-packaging-unit.csv.md
  docs/pbc/all/product-information-management/202404.0/base-shop/import-and-export-data/import-file-details-product-packaging-unit-type.csv.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-in-the-back-office/products/create-service-offerings-best-practices.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-in-the-back-office/products/manage-product-variants/create-product-variants.md
  docs/pbc/all/product-information-management/202404.0/base-shop/tutorials-and-howtos/howto-display-product-groups-by-color-on-the-storefront.md
  docs/pbc/all/product-information-management/202404.0/base-shop/tutorials-and-howtos/howto-import-packaging-units.md
  docs/pbc/all/product-information-management/202404.0/base-shop/tutorials-and-howtos/make-products-searchable-and-shown-on-the-storefront.md
  docs/pbc/all/product-information-management/202404.0/marketplace/manage-in-the-back-office/products/create-product-variants.md
  docs/pbc/all/return-management/202307.0/base-shop/return-management-feature-overview.md
  docs/pbc/all/return-management/202311.0/base-shop/return-management-feature-overview.md
  docs/pbc/all/return-management/202404.0/base-shop/return-management-feature-overview.md
Labels: small changes

#2776 Gif to mp4
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/manage-in-the-back-office/back-office-import-merchant-commissions.md
  docs/pbc/all/offer-management/202404.0/marketplace/manage-in-the-merchant-portal/create-product-offers.md
  docs/pbc/all/offer-management/202404.0/marketplace/manage-in-the-merchant-portal/edit-product-offers.md
  docs/pbc/all/offer-management/202404.0/unified-commerce/unified-commerce-create-and-edit-product-offers.md
  docs/pbc/all/return-management/202404.0/base-shop/return-management-feature-overview.md
Labels: small changes

#2496 FRW-6532 Update package flysystem MG
  _includes/pbc/all/upgrade-modules/upgrade-the-flysystem-module.md
Labels: TW review needed, updated

#2778 Gifs to mp4
  docs/ca/dev/configure-deployment-pipelines/deployment-in-states.md
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/manage-in-the-back-office/back-office-import-merchant-commissions.md
  docs/pbc/all/order-management-system/202404.0/base-shop/order-management-feature-overview/order-cancellation-overview.md
  docs/pbc/all/product-information-management/202404.0/base-shop/feature-overviews/configurable-bundle-feature-overview.md
  docs/pbc/all/product-information-management/202404.0/base-shop/feature-overviews/product-groups-feature-overview.md
Labels: small changes

#2767 Update margin top for headings
  css/pages/_content.scss
Labels: small changes

#2784 Update preparation-for-going-live.md
  css/pages/_content.scss
  docs/ca/dev/preparation-for-going-live.md
Labels: TW review needed

#2782 ACP-3580: Updated Payone ACP app integration guide.
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/payone/integration-in-the-back-office/integrate-payone.md
Labels: TW review needed, updated, 202407
