Repository spryker/spryker-docs, pull requests merged in 2024-03, with the labels that each got.

#1882 Create missing data import docs
  Rakefile
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202307.0/install-the-shopping-lists-feature.md
  docs/pbc/all/customer-relationship-management/202212.0/base-shop/import-and-export-data/file-details-company-business-unit.csv.md
  docs/pbc/all/customer-relationship-management/202212.0/base-shop/import-and-export-data/file-details-company-user.csv.md
  docs/pbc/all/customer-relationship-management/202212.0/base-shop/import-and-export-data/file-details-company.csv.md
  docs/pbc/all/customer-relationship-management/202212.0/base-shop/import-and-export-data/file-details-customer.csv.md
  docs/pbc/all/customer-relationship-management/202311.0/base-shop/import-and-export-data/file-details-company-business-unit.csv.md
  docs/pbc/all/customer-relationship-management/202311.0/base-shop/import-and-export-data/file-details-company-user.csv.md
  docs/pbc/all/customer-relationship-management/202311.0/base-shop/import-and-export-data/file-details-company.csv.md
  docs/pbc/all/customer-relationship-management/202311.0/base-shop/import-and-export-data/file-details-customer.csv.md
  docs/pbc/all/product-information-management/202212.0/base-shop/import-and-export-data/file-details-configurable-bundle-template-image.csv.md
  docs/pbc/all/product-information-management/202212.0/base-shop/import-and-export-data/file-details-configurable-bundle-template-slot.csv.md
  docs/pbc/all/product-information-management/202212.0/base-shop/import-and-export-data/file-details-configurable-bundle-template.csv.md
  docs/pbc/all/product-information-management/202212.0/base-shop/import-and-export-data/file-details-product-list-to-category.csv.md
  docs/pbc/all/product-information-management/202212.0/base-shop/import-and-export-data/file-details-product-list-to-concrete-product.csv.md
  docs/pbc/all/product-information-management/202212.0/base-shop/import-and-export-data/file-details-product-list.csv.md
  docs/pbc/all/product-information-management/202212.0/base-shop/import-and-export-data/file-details-product-measurement-unit.csv.md
  docs/pbc/all/product-information-management/202212.0/base-shop/import-and-export-data/file-details-product-packaging-unit.csv.md
  docs/pbc/all/product-information-management/202311.0/base-shop/import-and-export-data/file-details-configurable-bundle-template-image.csv.md
  docs/pbc/all/product-information-management/202311.0/base-shop/import-and-export-data/file-details-configurable-bundle-template-slot.csv.md
  docs/pbc/all/product-information-management/202311.0/base-shop/import-and-export-data/file-details-configurable-bundle-template.csv.md
  docs/pbc/all/product-information-management/202311.0/base-shop/import-and-export-data/file-details-product-list-to-category.csv.md
  docs/pbc/all/product-information-management/202311.0/base-shop/import-and-export-data/file-details-product-list-to-concrete-product.csv.md
  docs/pbc/all/product-information-management/202311.0/base-shop/import-and-export-data/file-details-product-list.csv.md
  docs/pbc/all/product-information-management/202311.0/base-shop/import-and-export-data/file-details-product-measurement-unit.csv.md
  docs/pbc/all/product-information-management/202311.0/base-shop/import-and-export-data/file-details-product-packaging-unit.csv.md
  docs/pbc/all/request-for-quote/202204.0/import-and-export-data/file-details-quote-request-version.csv.md
  docs/pbc/all/request-for-quote/202204.0/import-and-export-data/file-details-quote-request.csv.md
  docs/pbc/all/request-for-quote/202212.0/import-and-export-data/file-details-quote-request-version.csv.md
  docs/pbc/all/request-for-quote/202212.0/import-and-export-data/file-details-quote-request.csv.md
  docs/pbc/all/request-for-quote/202311.0/import-and-export-data/file-details-quote-request-version.csv.md
  docs/pbc/all/request-for-quote/202311.0/import-and-export-data/file-details-quote-request.csv.md
  docs/pbc/all/shopping-list-and-wishlist/202204.0/base-shop/import-and-export-data/file-details-shopping-list-company-business-unit.csv.md
  docs/pbc/all/shopping-list-and-wishlist/202204.0/base-shop/import-and-export-data/file-details-shopping-list-company-user.csv.md
  docs/pbc/all/shopping-list-and-wishlist/202204.0/base-shop/import-and-export-data/file-details-shopping-list-item.csv.md
  docs/pbc/all/shopping-list-and-wishlist/202204.0/base-shop/import-and-export-data/file-details-shopping-list.csv.md
  docs/pbc/all/shopping-list-and-wishlist/202212.0/base-shop/import-and-export-data/file-details-shopping-list-company-business-unit.csv.md
  docs/pbc/all/shopping-list-and-wishlist/202212.0/base-shop/import-and-export-data/file-details-shopping-list-company-user.csv.md
  docs/pbc/all/shopping-list-and-wishlist/202212.0/base-shop/import-and-export-data/file-details-shopping-list-item.csv.md
  docs/pbc/all/shopping-list-and-wishlist/202212.0/base-shop/import-and-export-data/file-details-shopping-list.csv.md
  docs/pbc/all/shopping-list-and-wishlist/202311.0/base-shop/import-and-export-data/file-details-shopping-list-company-business-unit.csv.md
  docs/pbc/all/shopping-list-and-wishlist/202311.0/base-shop/import-and-export-data/file-details-shopping-list-company-user.csv.md
  docs/pbc/all/shopping-list-and-wishlist/202311.0/base-shop/import-and-export-data/file-details-shopping-list-item.csv.md
  docs/pbc/all/shopping-list-and-wishlist/202311.0/base-shop/import-and-export-data/file-details-shopping-list.csv.md
Labels: PO review needed, new

#2541 Docs updates Feb 2024
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/guidelines/coding-guidelines/secure-coding-practices-for-external-packages.md
  docs/pbc/all/customer-relationship-management/202311.0/base-shop/import-and-export-data/file-details-customer.csv.md
  docs/pbc/all/request-for-quote/202311.0/import-and-export-data/file-details-quote-request-version.csv.md
  docs/scos/user/intro-to-spryker/docs-updates.md
Labels: small changes

#2544 Docs updated pages
  docs/scos/user/intro-to-spryker/docs-updates.md
Labels: small changes

#2447 Oryx contribution guide
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/frontend-development/202212.0/oryx/contribute-to-oryx.md
  docs/dg/dev/frontend-development/202307.0/oryx/contribute-to-oryx.md
  docs/dg/dev/frontend-development/202311.0/oryx/contribute-to-oryx.md
Labels: new

#2545 Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: small changes

#2548 Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: small changes

#2549 fixing the infoblock
  docs/ca/dev/preparation-for-going-live.md
Labels: small changes

#2533 Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: small changes

#2229 Create an explanation how to enable filter.
  _data/sidebars/scos_dev_sidebar.yml
  docs/ca/dev/preparation-for-going-live.md
  docs/scos/dev/troubleshooting/troubleshooting-general-technical-issues/prices-filter-and-sorting-does-t-work-on-frontend.md
Labels: new

#2379 fixed redirect
  docs/pbc/all/order-management-system/202212.0/marketplace/marketplace-order-management-feature-overview/marketplace-and-merchant-state-machines-overview/marketplace-and-merchant-state-machines-interaction.md
Labels: small changes

#2551 Adjusted upgrader docs
  docs/ca/devscu/spryker-code-upgrader.md
  docs/dg/dev/updating-spryker/analyzing-and-upgrading-projects-with-spryker-jarvis.md
Labels: small changes

#2553 Create jenkins-stability-checklist.md
  _data/sidebars/ca_dev_sidebar.yml
  docs/ca/dev/best-practices/jenkins-stability-checklist.md
Labels: TW review needed, new

#2554 Intro to Spryker
  docs/dg/dev/backend-development/cronjobs/cronjobs.md
  docs/dg/dev/data-import/202212.0/data-import-optimization-guidelines.md
  docs/dg/dev/data-import/202307.0/data-import-optimization-guidelines.md
  docs/dg/dev/data-import/202311.0/data-import-optimization-guidelines.md
  docs/dg/dev/frontend-development/202311.0/yves/atomic-frontend/customizing-spryker-frontend.md
  docs/dg/dev/glue-api/202212.0/configure-the-included-section.md
  docs/dg/dev/glue-api/202212.0/glue-api-tutorials/extend-a-rest-api-resource.md
  docs/dg/dev/glue-api/202307.0/configure-the-included-section.md
  docs/dg/dev/glue-api/202307.0/glue-api-tutorials/extend-a-rest-api-resource.md
  docs/dg/dev/glue-api/202311.0/configure-the-included-section.md
  docs/dg/dev/glue-api/202311.0/glue-api-tutorials/extend-a-rest-api-resource.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-windows.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-windows.md
  docs/pbc/all/content-management-system/202212.0/base-shop/cms-feature-overview/email-as-a-cms-block-overview.md
  docs/pbc/all/content-management-system/202307.0/base-shop/cms-feature-overview/email-as-a-cms-block-overview.md
  docs/pbc/all/content-management-system/202311.0/base-shop/cms-feature-overview/email-as-a-cms-block-overview.md
  docs/pbc/all/search/202212.0/base-shop/search-feature-overview/standard-filters-overview.md
  docs/pbc/all/search/202307.0/base-shop/search-feature-overview/standard-filters-overview.md
  docs/pbc/all/search/202311.0/base-shop/search-feature-overview/standard-filters-overview.md
  docs/scos/user/intro-to-spryker/intro-to-spryker.md
Labels: updated

#2556 Update jenkins-stability-checklist.md
  _data/sidebars/ca_dev_sidebar.yml
  docs/ca/dev/best-practices/best-practises-jenkins-stability.md
  docs/ca/dev/best-practices/jenkins-operational-best-practices-handbook.md
  docs/ca/dev/best-practices/jenkins-stability-checklist.md
Labels: TW review needed, updated

#2564 Fixed typo for Data Exchange API doc
  docs/pbc/all/data-exchange/202311.0/tutorials-and-howtos/how-to-send-request-in-data-exchange-api.md
Labels: in TW review, small changes

#2567 Fixing typo on the "About the query container" page
  docs/dg/dev/backend-development/zed/persistence-layer/query-container/query-container.md
Labels: small changes

#2568 Developing with spryker
  _drafts/getting-started-guide/developing-spryker-projects/adding-functionality.md
  _drafts/getting-started-guide/developing-spryker-projects/customizing-functionality.md
  _drafts/getting-started-guide/developing-spryker-projects/installing-spryker-locally.md
  _drafts/getting-started-guide/developing-spryker-projects/pushing-and-deploying.md
  _drafts/getting-started-guide/get-support.md
  _drafts/getting-started-guide/using-the-docs.md
Labels: small changes

#2569 Update code-contribution-guide.md
  docs/dg/dev/code-contribution-guide.md
Labels: updated

#2576 SUPESC-38 Added Phone field for Company Business Unit.
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-in-the-back-office/company-units/create-company-units.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-in-the-back-office/company-units/edit-company-units.md
Labels: TW review needed, updated

#2566 NewRelic performance guideline fix
  docs/dg/dev/guidelines/performance-guidelines/elastic-computing/new-relic-transaction-grouping-by-queue-names.md
Labels: TW review needed, small changes

#2522 Test Glue Backend API doc code example fix
  docs/dg/dev/guidelines/testing-guidelines/executing-tests/test-glue-backend-api.md
Labels: TW review needed, updated, small changes

#2558 Remove invalid redirect config
  docs/pbc/all/warehouse-management-system/202311.0/base-shop/install-and-upgrade/install-features/install-the-inventory-management-feature.md
Labels: TW review needed, updated, small changes

#2578 Update install-the-return-management-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-return-management-feature.md
Labels: small changes

#2575 Security release notes for Q1
  _data/sidebars/about_all_sidebar.yml
  docs/about/all/releases/security-release-notes-202403.0.md
Labels: TW review needed, new

#2574 ACP-2521 Added SalesPaymentDetail docs and update Stripe docs.
  _data/sidebars/pbc_all_sidebar.yml
  docs/about/all/about-the-docs/docs-updates.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/retrieve-and-use-payment-details-from-third-party-psps.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/connect-and-configure-stripe.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/disconnect-stripe.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/install-and-configure-stripe-prerequisites.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/stripe.md
Labels: new, updated

#2585 Update release-notes-202311.0.md
  docs/about/all/releases/release-notes-202311.0.md
Labels: urgent, small changes

#2391 Update create-email-cms-blocks.md
  _includes/pbc/all/install-features/202311.0/install-the-gift-cards-feature.md
  docs/pbc/all/content-management-system/202311.0/base-shop/manage-in-the-back-office/blocks/create-email-cms-blocks.md
Labels: small changes

#2538 ACP-2269 Added notes for Stripe.
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/stripe.md
Labels: small changes

#2586 ACP-2929 Added missing documentation for OAuth access token.
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/stripe/install-and-configure-stripe-prerequisites.md
Labels: small changes
