Repository spryker/spryker-docs, pull requests merged in 2024-09, with the labels that each got.

#2768 CC-33982: Added direct synchronization and flaxibale chunk size configuration to improve P&S performance.
  _data/sidebars/pbc_all_sidebar.yml
  docs/dg/dev/backend-development/data-manipulation/data-publishing/publish-and-synchronization.md
  docs/dg/dev/backend-development/data-manipulation/queue/queue.md
Labels: TW review needed, updated

#2785 Added incremental installer description page
  _data/sidebars/dg_dev_sidebar.yml
  css/pages/_content.scss
  docs/dg/dev/data-import/202404.0/implement-incremental-installers.md
  docs/pbc/all/offer-management/202404.0/unified-commerce/unified-commerce-create-and-edit-product-offers.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/payone/app-composition-platform-integration/integrate-payone.md
Labels: new

#2792 fixed implement-incremental-installers.md
  css/pages/_content.scss
  docs/dg/dev/data-import/202404.0/implement-incremental-installers.md
Labels: small changes

#2752 Update redis-session-lock.md
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/troubleshooting/troubleshooting-performance-issues/redis-session-lock-excpetions.md
  docs/dg/dev/troubleshooting/troubleshooting-performance-issues/redis-session-lock.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/payone/app-composition-platform-integration/integrate-payone.md
  docs/pbc/all/payment-service-provider/202404.0/marketplace/stripe-third-party-integration/configure-merchant-transfers-for-stripe.md
  docs/pbc/all/payment-service-provider/202404.0/marketplace/stripe-third-party-integration/stripe-oms-configuration-in-marketplaces.md
Labels: tech review needed

#2787 FRW-8938 Adjusted for Data import from other sources.
  docs/ca/dev/configure-data-import-from-an-s3-bucket.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-adapt-the-filesystem-based-features.md
Labels: in TW review, small changes

#2793 Update configure-services.md
  css/pages/_content.scss
  docs/dg/dev/integrate-and-configure/configure-services.md
Labels: TW review needed

#2796 Update extend-a-core-module-that-is-used-by-another.md
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/backend-development/extend-spryker/spryker-os-module-customisation/extend-a-core-module-that-is-used-by-another-module.md
  docs/dg/dev/backend-development/extend-spryker/spryker-os-module-customisation/spryker-os-module-customisation.md
  docs/pbc/all/payment-service-provider/202307.0/base-shop/third-party-integrations/arvato/install-and-configure-arvato.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/arvato/install-and-configure-arvato.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/arvato/install-and-configure-arvato.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
  docs/pbc/all/product-relationship-management/202307.0/third-party-integrations/econda/export-econda-data.md
  docs/pbc/all/product-relationship-management/202311.0/third-party-integrations/econda/export-econda-data.md
  docs/pbc/all/product-relationship-management/202404.0/third-party-integrations/econda/export-econda-data.md
Labels: TW review needed, updated

#2794 CC-34258: Multi-select attribute values (Fixathon)
  _includes/pbc/all/install-features/202407.0/install-glue-api/install-the-product-glue-api.md
  _includes/pbc/all/install-features/202407.0/install-the-product-feature.md
  docs/pbc/all/product-information-management/202407.0/base-shop/install-and-upgrade/install-features/install-the-product-feature.md
  docs/pbc/all/product-information-management/202407.0/base-shop/install-and-upgrade/install-glue-api/install-the-product-glue-api.md
Labels: TW review needed, updated

#2795 ACP-3754: Updated ACL plugins for stripe
  docs/pbc/all/payment-service-provider/202404.0/marketplace/stripe-third-party-integration/install-and-configure-stripe-prerequisites-for-marketplace.md
Labels: TW review needed, small changes

#2800 added important message for the Dynatrace integration feature
  docs/about/all/releases/release-notes-202311.0.md
Labels: TW review needed, updated

#2801 Fixed explanation for configuration in install-the-push-notification-…
  _includes/pbc/all/install-features/202311.0/install-the-push-notification-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-push-notification-feature.md
Labels: small changes

#2802 Update install-the-push-notification-feature.md
  _data/sidebars/dg_dev_sidebar.yml
  docs/pbc/all/miscellaneous/202404.0/install-and-upgrade/install-features/install-the-push-notification-feature.md
Labels: TW review needed, small changes

#2803 Feature: Update add-publish-events.md
  docs/dg/dev/backend-development/data-manipulation/data-publishing/add-publish-events.md
Labels: TW review needed

#2805 Update listen-to-events.md
  docs/dg/dev/backend-development/data-manipulation/event/listen-to-events.md
Labels: TW review needed, small changes

#2779 ACP-2642: Added fixes to IG.
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-marketplace-merchant-commission-feature.md
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-marketplace-merchant-feature.md
  docs/pbc/all/merchant-management/202407.0/marketplace/marketplace-merchant-commission-feature-overview.md
  docs/pbc/all/payment-service-provider/202404.0/marketplace/stripe-third-party-integration/install-and-configure-stripe-prerequisites-for-marketplace.md
Labels: updated, 202407

#2809 FRW-8703 Fixed sitemap generation.
  sitemap.xml
Labels: small changes

#2807 Update redis-session-lock-excpetions.md
  docs/dg/dev/troubleshooting/troubleshooting-performance-issues/redis-session-lock-excpetions.md
Labels: TW review needed

#2811 Security release notes for Q3
  _data/sidebars/about_all_sidebar.yml
  css/pages/_content.scss
  docs/about/all/releases/security-release-notes-202409.0.md
Labels: TW review needed, new

#2812 FRW-8703 Fixed sitemap.
  sitemap.xml
Labels: small changes

#2813 Update operational-and-deployment-guidelines.md with Scalability quality
  docs/dg/dev/best-practices/non-functional-requirement-templates/operational-and-deployment-guidelines.md
Labels: tech review needed, TW review needed, updated

#2808 FRW-7700 Updated project guidlines
  docs/dg/dev/guidelines/project-development-guidelines.md
Labels: ready for merge, Bypassed TW Review

#2816 Update security-guidelines.md
  docs/dg/dev/guidelines/security-guidelines.md
Labels: TW review needed

#2817 Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: TW review needed

#2829 CC-34423 Merchant Portal - Marketplace Product feature IG
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-merchant-portal-marketplace-product-feature.md
Labels: updated, 202407

#2825 Update project-development-guidelines.md
  docs/dg/dev/guidelines/project-development-guidelines.md
Labels: TW review needed

#2814 FRW-8801 PHP 8.3 version upgrade.
  Rakefile
  _includes/pbc/all/upgrade-modules/upgrade-the-country-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-currency-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-locale-module.md
  docs/ca/devscu/prepare-a-project-for-spryker-code-upgrader.md
  docs/dg/dev/developing-standalone-modules/ensuring-quality-in-standalone-modules.md
  docs/dg/dev/developing-standalone-modules/publish-standalone-modules-on-packagist.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/php-version.md
  docs/dg/dev/integrate-and-configure/Integrate-profiler-module.md
  docs/dg/dev/supported-versions-of-php.md
  docs/dg/dev/system-requirements/202411.0/system-requirements.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-upgrade-the-php-version.md
  docs/dg/dev/upgrade-and-migrate/upgrade-to-php-81.md
  docs/dg/dev/upgrade-and-migrate/upgrade-to-symfony-6.md
Labels: in TW review, small changes

#2836 Edit mp concrete products
  _data/sidebars/pbc_all_sidebar.yml
  docs/about/all/spryker-marketplace/merchant-onboarding.md
  docs/pbc/all/discount-management/202404.0/base-shop/manage-in-the-back-office/create-discounts.md
  docs/pbc/all/discount-management/202407.0/base-shop/manage-in-the-back-office/create-discounts.md
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/install-features/install-the-merchant-portal-marketplace-product-feature.md
  docs/pbc/all/product-information-management/202307.0/marketplace/manage-in-the-merchant-portal/abstract-products/create-marketplace-abstract-products.md
  docs/pbc/all/product-information-management/202307.0/marketplace/manage-in-the-merchant-portal/concrete-products/create-marketplace-concrete-products.md
  docs/pbc/all/product-information-management/202307.0/marketplace/manage-in-the-merchant-portal/concrete-products/edit-marketplace-concrete-products.md
  docs/pbc/all/product-information-management/202307.0/marketplace/manage-in-the-merchant-portal/concrete-products/manage-marketplace-concrete-product-attributes.md
  docs/pbc/all/product-information-management/202307.0/marketplace/manage-in-the-merchant-portal/concrete-products/manage-marketplace-concrete-product-prices.md
  docs/pbc/all/product-information-management/202307.0/marketplace/manage-in-the-merchant-portal/manage-products-in-the-merchant-portal.md
  docs/pbc/all/product-information-management/202307.0/marketplace/marketplace-product-feature-overview.md
  docs/pbc/all/product-information-management/202311.0/marketplace/manage-in-the-merchant-portal/abstract-products/create-marketplace-abstract-products.md
  docs/pbc/all/product-information-management/202311.0/marketplace/manage-in-the-merchant-portal/concrete-products/create-marketplace-concrete-products.md
  docs/pbc/all/product-information-management/202311.0/marketplace/manage-in-the-merchant-portal/concrete-products/edit-marketplace-concrete-products.md
  docs/pbc/all/product-information-management/202311.0/marketplace/manage-in-the-merchant-portal/concrete-products/manage-marketplace-concrete-product-attributes.md
  docs/pbc/all/product-information-management/202311.0/marketplace/manage-in-the-merchant-portal/concrete-products/manage-marketplace-concrete-product-prices.md
  docs/pbc/all/product-information-management/202311.0/marketplace/manage-in-the-merchant-portal/manage-products-in-the-merchant-portal.md
  docs/pbc/all/product-information-management/202311.0/marketplace/marketplace-product-feature-overview.md
  docs/pbc/all/product-information-management/202404.0/marketplace/manage-in-the-merchant-portal/abstract-products/create-marketplace-abstract-products.md
  docs/pbc/all/product-information-management/202404.0/marketplace/manage-in-the-merchant-portal/concrete-products/create-marketplace-concrete-products.md
  docs/pbc/all/product-information-management/202404.0/marketplace/manage-in-the-merchant-portal/concrete-products/edit-marketplace-concrete-products.md
  docs/pbc/all/product-information-management/202404.0/marketplace/manage-in-the-merchant-portal/concrete-products/manage-marketplace-concrete-product-attributes.md
  docs/pbc/all/product-information-management/202404.0/marketplace/manage-in-the-merchant-portal/concrete-products/manage-marketplace-concrete-product-prices.md
  docs/pbc/all/product-information-management/202404.0/marketplace/manage-in-the-merchant-portal/concrete-products/manage-marketplace-concrete-products.md
  docs/pbc/all/product-information-management/202404.0/marketplace/manage-in-the-merchant-portal/manage-products-in-the-merchant-portal.md
  docs/pbc/all/product-information-management/202404.0/marketplace/marketplace-product-feature-overview.md
Labels: 202400

#2804 ACP-3661 Added the ACL entity synchronization command to the IG.
  _includes/pbc/all/install-features/202407.0/install-the-acl-feature.md
  docs/pbc/all/user-management/202407.0/base-shop/install-and-upgrade/install-the-acl-feature.md
Labels: updated, 202407

#2835 Add vulnerability in security release notes of Q3
  docs/about/all/releases/security-release-notes-202409.0.md
Labels: TW review needed
