Repository spryker/spryker-docs, pull requests merged in 2024-06, with the labels that each got.

#2687 Update email-service.md
  docs/ca/dev/email-service/email-service.md
Labels: TW review needed, updated

#2689 Docker SDK version update
  .github/dependabot.yml
  _data/sidebars/dg_dev_sidebar.yml
  _includes/pbc/all/glue-api-guides/202404.0/addresses-response-attributes.md
  _includes/pbc/all/glue-api-guides/202404.0/cart-permission-groups-response-attributes.md
  _includes/pbc/all/glue-api-guides/202404.0/cms-pages-response-attributes.md
  _includes/pbc/all/glue-api-guides/202404.0/companies-response-attributes.md
  _includes/pbc/all/glue-api-guides/202404.0/company-business-unit-addresses-response-attributes.md
  _includes/pbc/all/glue-api-guides/202404.0/company-business-units-response-attributes.md
  _includes/pbc/all/glue-api-guides/202404.0/company-roles-response-attributes.md
  _includes/pbc/all/glue-api-guides/202404.0/shared-carts-response-attributes.md
  docs/dg/dev/sdks/the-docker-sdk/update-the-docker-sdk.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/check-out/glue-api-submit-checkout-data.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-customer-carts.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/manage-carts-of-registered-users/glue-api-manage-carts-of-registered-users.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/manage-carts-of-registered-users/glue-api-manage-items-in-carts-of-registered-users.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/manage-guest-carts/glue-api-manage-guest-cart-items.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/manage-guest-carts/glue-api-manage-guest-carts.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/share-company-user-carts/glue-api-retrieve-cart-permission-groups.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-using-glue-api/share-company-user-carts/glue-api-share-company-user-carts.md
  docs/pbc/all/content-management-system/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-abstract-product-list-content-items.md
  docs/pbc/all/content-management-system/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-cms-pages.md
  docs/pbc/all/content-management-system/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-navigation-trees.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-using-glue-api/company-account/cart-feature-overview.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-business-unit-addresses.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-business-units.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-companies.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-company-roles.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-using-glue-api/company-account/glue-api-retrieve-company-users.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-using-glue-api/company-account/glue-api-search-by-company-users.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-using-glue-api/customers/glue-api-manage-customer-addresses.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-using-glue-api/customers/glue-api-manage-customers.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-using-glue-api/customers/glue-api-retrieve-customer-orders.md
  docs/pbc/all/discount-management/202404.0/base-shop/manage-using-glue-api/glue-api-add-items-with-discounts-to-carts-of-registered-users.md
  docs/pbc/all/discount-management/202404.0/base-shop/manage-using-glue-api/glue-api-add-items-with-discounts-to-guest-carts.md
  docs/pbc/all/discount-management/202404.0/base-shop/manage-using-glue-api/glue-api-manage-discount-vouchers-in-carts-of-registered-users.md
  docs/pbc/all/discount-management/202404.0/base-shop/manage-using-glue-api/glue-api-manage-discount-vouchers-in-guest-carts.md
  docs/pbc/all/discount-management/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-discounts-in-carts-of-registered-users.md
  docs/pbc/all/discount-management/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-discounts-in-customer-carts.md
  docs/pbc/all/discount-management/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-discounts-in-guest-carts.md
  docs/pbc/all/gift-cards/202404.0/manage-using-glue-api/glue-api-retrieve-gift-cards-in-carts-of-registered-users.md
  docs/pbc/all/gift-cards/202404.0/manage-using-glue-api/glue-api-retrieve-gift-cards-in-guest-carts.md
  docs/pbc/all/order-management-system/202404.0/marketplace/glue-api-retrieve-marketplace-orders.md
  docs/pbc/all/search/202404.0/base-shop/manage-using-glue-api/glue-api-search-the-product-catalog.md
Labels: TW review needed, new

#2694 Update the Back Office landing page example
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/glue-api-guides/202404.0/shopping-list-items-response-attributes.md
  _includes/pbc/all/glue-api-guides/202404.0/shopping-lists-response-attributes.md
  _includes/pbc/all/glue-api-guides/202404.0/vouchers-cart-rules-response-attributes.md
  _includes/pbc/all/manage-in-the-back-office/log-into-the-back-office.md
  docs/about/all/about-the-docs/contribute-to-the-docs/edit-the-docs-locally.md
  docs/pbc/all/back-office/202404.0/base-shop/manage-in-the-back-office/view-dashboard.md
  docs/pbc/all/carrier-management/202404.0/base-shop/manage-in-the-back-office/manage-carrier-companies-and-delivery-methods-in-the-back-office.md
  docs/pbc/all/cart-and-checkout/202307.0/base-shop/manage-using-glue-api/glue-api-retrieve-customer-carts.md
  docs/pbc/all/cart-and-checkout/202307.0/base-shop/manage-using-glue-api/manage-carts-of-registered-users/glue-api-manage-carts-of-registered-users.md
  docs/pbc/all/cart-and-checkout/202307.0/base-shop/manage-using-glue-api/manage-carts-of-registered-users/glue-api-manage-items-in-carts-of-registered-users.md
  docs/pbc/all/cart-and-checkout/202307.0/base-shop/manage-using-glue-api/manage-guest-carts/glue-api-manage-guest-cart-items.md
  docs/pbc/all/cart-and-checkout/202311.0/base-shop/manage-using-glue-api/glue-api-retrieve-customer-carts.md
  docs/pbc/all/cart-and-checkout/202311.0/base-shop/manage-using-glue-api/manage-carts-of-registered-users/glue-api-manage-carts-of-registered-users.md
  docs/pbc/all/cart-and-checkout/202311.0/base-shop/manage-using-glue-api/manage-carts-of-registered-users/glue-api-manage-items-in-carts-of-registered-users.md
  docs/pbc/all/cart-and-checkout/202404.0/base-shop/manage-in-the-back-office/manage-thresholds-the-back-office.md
  docs/pbc/all/content-management-system/202404.0/base-shop/manage-in-the-back-office/manage-content-in-the-back-office.md
  docs/pbc/all/customer-relationship-management/202404.0/base-shop/manage-in-the-back-office/manage-companies-and-customers-in-the-back-office.md
  docs/pbc/all/discount-management/202307.0/base-shop/manage-using-glue-api/glue-api-add-items-with-discounts-to-carts-of-registered-users.md
  docs/pbc/all/discount-management/202404.0/base-shop/manage-in-the-back-office/manage-discounts-in-the-back-office.md
  docs/pbc/all/merchant-management/202404.0/base-shop/manage-in-the-back-office/manage-merchants-in-the-back-office.md
  docs/pbc/all/merchant-management/202404.0/marketplace/manage-in-the-back-office/manage-merchants-and-merchant-users-in-the-back-office.md
  docs/pbc/all/order-management-system/202404.0/base-shop/manage-in-the-back-office/manage-orders-in-the-back-office.md
  docs/pbc/all/price-management/202307.0/base-shop/manage-in-the-back-office/manage-prices-in-the-back-office.md
  docs/pbc/all/price-management/202311.0/base-shop/manage-in-the-back-office/manage-prices-in-the-back-office.md
  docs/pbc/all/price-management/202404.0/base-shop/manage-in-the-back-office/manage-prices-in-the-back-office.md
  docs/pbc/all/product-information-management/202307.0/base-shop/manage-in-the-back-office/manage-products-in-the-back-office.md
  docs/pbc/all/product-information-management/202311.0/base-shop/manage-in-the-back-office/manage-products-in-the-back-office.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-in-the-back-office/manage-products-in-the-back-office.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/abstract-products/glue-api-retrieve-abstract-products.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/concrete-products/glue-api-retrieve-image-sets-of-concrete-products.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/concrete-products/glue-api-retrieve-sales-units.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-alternative-products.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-configurable-bundle-templates.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-measurement-units.md
  docs/pbc/all/product-information-management/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-product-labels.md
  docs/pbc/all/product-relationship-management/202307.0/manage-in-the-back-office/manage-product-relations-in-the-back-office.md
  docs/pbc/all/product-relationship-management/202311.0/manage-in-the-back-office/manage-product-relations-in-the-back-office.md
  docs/pbc/all/product-relationship-management/202404.0/glue-api-retrieve-related-products.md
  docs/pbc/all/product-relationship-management/202404.0/manage-in-the-back-office/manage-product-relations-in-the-back-office.md
  docs/pbc/all/ratings-reviews/202307.0/manage-in-the-back-office/log-into-the-back-office.md
  docs/pbc/all/ratings-reviews/202307.0/manage-product-reviews-in-the-back-office.md
  docs/pbc/all/ratings-reviews/202307.0/ratings-and-reviews.md
  docs/pbc/all/ratings-reviews/202311.0/manage-in-the-back-office/log-into-the-back-office.md
  docs/pbc/all/ratings-reviews/202311.0/manage-product-reviews-in-the-back-office.md
  docs/pbc/all/ratings-reviews/202311.0/ratings-and-reviews.md
  docs/pbc/all/ratings-reviews/202404.0/manage-in-the-back-office/log-into-the-back-office.md
  docs/pbc/all/ratings-reviews/202404.0/manage-product-reviews-in-the-back-office.md
  docs/pbc/all/ratings-reviews/202404.0/manage-using-glue-api/glue-api-retrieve-product-reviews-when-retrieving-abstract-products.md
  docs/pbc/all/ratings-reviews/202404.0/manage-using-glue-api/glue-api-retrieve-product-reviews-when-retrieving-concrete-products.md
  docs/pbc/all/ratings-reviews/202404.0/ratings-and-reviews.md
  docs/pbc/all/return-management/202404.0/base-shop/manage-using-glue-api/glue-api-retrieve-return-reasons.md
  docs/pbc/all/shopping-list-and-wishlist/202404.0/base-shop/manage-using-glue-api/glue-api-manage-shopping-list-items.md
  docs/pbc/all/shopping-list-and-wishlist/202404.0/base-shop/manage-using-glue-api/glue-api-manage-shopping-lists.md
  docs/pbc/all/shopping-list-and-wishlist/202404.0/marketplace/manage-using-glue-api/glue-api-manage-marketplace-shopping-list-items.md
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/install-vertex/install-vertex.md
Labels: small changes

#2695 ACP-3286: Adjusted vertax doc with additional value
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-the-vertex-app.md
Labels: small changes

#2696 Update split-products-by-stores.md
  docs/pbc/all/product-information-management/202311.0/base-shop/tutorials-and-howtos/split-products-by-stores.md
  docs/pbc/all/product-information-management/202404.0/base-shop/tutorials-and-howtos/split-products-by-stores.md
Labels: TW review needed, small changes

#2690 FRW-7373 Non-transactional mode for Data Exchange API.
  docs/pbc/all/data-exchange/202404.0/tutorials-and-howtos/how-to-send-request-in-data-exchange-api.md
Labels: updated

#2697 Fix typo within installation instructions
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-macos-and-linux.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-windows.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-windows.md
Labels: small changes

#2699 Update contribute-to-oryx.md
  docs/dg/dev/frontend-development/202404.0/oryx/contribute-to-oryx.md
Labels: small changes

#2698 Back OFfice landing pages
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/order-management-system/202404.0/base-shop/manage-in-the-back-office/manage-orders-in-the-back-office.md
  docs/pbc/all/product-relationship-management/202307.0/manage-in-the-back-office/manage-product-relations-in-the-back-office.md
  docs/pbc/all/product-relationship-management/202404.0/manage-in-the-back-office/manage-product-relations-in-the-back-office.md
  docs/pbc/all/return-management/202307.0/base-shop/manage-in-the-back-office/manage-returns-in-the-back-office.md
  docs/pbc/all/return-management/202311.0/base-shop/manage-in-the-back-office/manage-returns-in-the-back-office.md
  docs/pbc/all/return-management/202311.0/marketplace/manage-in-the-back-office/manage-marketplace-returns-in-the-back-office.md
  docs/pbc/all/return-management/202404.0/base-shop/manage-in-the-back-office/manage-returns-in-the-back-office.md
  docs/pbc/all/return-management/202404.0/marketplace/manage-in-the-back-office/manage-marketplace-returns-in-the-back-office.md
  docs/pbc/all/search/202307.0/base-shop/manage-in-the-back-office/manage-filters-and-search-preferences-in-the-back-office.md
  docs/pbc/all/search/202311.0/base-shop/manage-in-the-back-office/manage-filters-and-search-preferences-in-the-back-office.md
  docs/pbc/all/search/202404.0/base-shop/manage-in-the-back-office/log-into-the-back-office.md
  docs/pbc/all/search/202404.0/base-shop/manage-in-the-back-office/manage-filters-and-search-preferences-in-the-back-office.md
  docs/pbc/all/tax-management/202307.0/base-shop/manage-in-the-back-office/manage-taxes-in-the-back-office.md
  docs/pbc/all/tax-management/202311.0/base-shop/manage-in-the-back-office/manage-taxes-in-the-back-office.md
  docs/pbc/all/tax-management/202404.0/base-shop/manage-in-the-back-office/manage-taxes-in-the-back-office.md
  docs/pbc/all/user-management/202307.0/base-shop/manage-in-the-back-office/manage-users-in-the-back-office.md
  docs/pbc/all/user-management/202311.0/base-shop/manage-in-the-back-office/manage-users-in-the-back-office.md
  docs/pbc/all/user-management/202404.0/base-shop/manage-in-the-back-office/log-into-the-back-office.md
  docs/pbc/all/user-management/202404.0/base-shop/manage-in-the-back-office/manage-users-in-the-back-office.md
  docs/pbc/all/user-management/202404.0/marketplace/back-office-create-users.md
  docs/pbc/all/warehouse-management-system/202307.0/base-shop/manage-in-the-back-office/manage-warehouses-in-the-back-office.md
  docs/pbc/all/warehouse-management-system/202311.0/base-shop/manage-in-the-back-office/manage-warehouses-in-the-back-office.md
  docs/pbc/all/warehouse-management-system/202404.0/base-shop/manage-in-the-back-office/manage-warehouses-in-the-back-office.md
Labels: small changes

#2702 Update share-secrets-with-the-spryker-support-team.md
  _includes/pbc/all/data-exchange/202311.0/custom-integrations-with-alumio-connectors.md
  _includes/pbc/all/data-exchange/202404.0/custom-integrations-with-alumio-connectors.md
  docs/about/all/support/share-secrets-with-the-spryker-support-team.md
Labels: TW review needed

#2659 Update publish-and-synchronization.md
  docs/dg/dev/backend-development/data-manipulation/data-publishing/publish-and-synchronization.md
Labels: updated, Bypassed TW Review

#2706 Update using-the-support-portal.md
  docs/about/all/support/using-the-support-portal.md
Labels: TW review needed

#2651 Update install-the-data-exchange-api.md
  _includes/pbc/all/install-features/202311.0/install-the-data-exchange-api.md
Labels: small changes

#2711 Fix newrelic_set_appname license parameter type
  docs/dg/dev/integrate-and-configure/configure-services.md
Labels: small changes

#2625 HowTo do an incremental import in Alumio
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202311.0/install-the-data-exchange-api-inventory-management-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-data-exchange-api.md
  _includes/pbc/all/install-features/202404.0/install-the-data-exchange-api-inventory-management-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-data-exchange-api.md
  docs/about/all/about-the-docs/docs-updates.md
  docs/pbc/all/data-exchange/202311.0/configure-data-exchange-api.md
  docs/pbc/all/data-exchange/202311.0/install-and-upgrade/install-the-data-exchange-api.md
  docs/pbc/all/data-exchange/202311.0/sending-requests-with-data-exchange-api.md
  docs/pbc/all/data-exchange/202311.0/spryker-middleware-powered-by-alumio/integration-apps/akeneo-pim-integration-app/configure-the-akeneo-pim-integration-app/configure-the-data-integration-path-between-akeneo-and-sccos.md
  docs/pbc/all/data-exchange/202404.0/configure-data-exchange-api.md
  docs/pbc/all/data-exchange/202404.0/install-and-upgrade/install-the-data-exchange-api.md
  docs/pbc/all/data-exchange/202404.0/sending-requests-with-data-exchange-api.md
  docs/pbc/all/data-exchange/202404.0/spryker-middleware-powered-by-alumio/incrementally-import-products-with-spryker-middleware-powered-by-alumio.md
  docs/pbc/all/data-exchange/202404.0/spryker-middleware-powered-by-alumio/integration-apps/integration-apps.md
Labels: new

#2686 FRW-7201 [DEX API] DELETE method support.
  _includes/pbc/all/install-features/202404.0/install-the-data-exchange-api-inventory-management-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-data-exchange-api.md
  docs/pbc/all/data-exchange/202404.0/configure-data-exchange-api.md
  docs/pbc/all/data-exchange/202404.0/sending-requests-with-data-exchange-api.md
Labels: ready for merge, TW review needed, updated

#2710 Update using-the-support-portal.md
  docs/about/all/support/using-the-support-portal.md
Labels: TW review needed

#2709 Update preparing-for-heavy-loads-and-traffic.md
  docs/about/all/support/preparing-for-heavy-loads-and-traffic.md
Labels: TW review needed

#2707 Update deploy-file-reference.md
  docs/dg/dev/sdks/the-docker-sdk/deploy-file/deploy-file-reference.md
Labels: TW review needed

#2620 Vertex project guidelines
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/configure-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/connect-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/disconnect-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-the-vertex-app.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/project-configuration-for-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/troubleshooting-vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/vertex.md
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/configure-vertex.md
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/connect-vertex.md
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/disconnect-vertex.md
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-the-vertex-app.md
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/project-configuration-for-vertex.md
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/troubleshooting-vertex.md
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/vertex.md
Labels: updated

#2712 Article about Increasing Email Deliverability
  _data/sidebars/ca_dev_sidebar.yml
  docs/ca/dev/email-service/email-deliverability.md
Labels: TW review needed, new

#2715 Refined DNS, removed IPSec, removed demo shops and boilerplates
  docs/ca/dev/environment-provisioning.md
  docs/pbc/all/data-exchange/202404.0/spryker-middleware-powered-by-alumio/spryker-middleware-powered-by-alumio.md
Labels: updated

#2718 Update environments-overview.md
  docs/ca/dev/environments-overview.md
Labels: TW review needed

#2704 Update vertex.md
  docs/pbc/all/tax-management/202311.0/base-shop/third-party-integrations/vertex/vertex.md
  docs/pbc/all/tax-management/202404.0/base-shop/third-party-integrations/vertex/vertex.md
Labels: updated

#2722 CC-33281 Add IGs for Connector modules
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-category-management-marketplace-merchant-commission.md
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-prices-marketplace-merchant-commission-feature.md
  _includes/pbc/all/install-features/202407.0/marketplace/install-the-product-marketplace-merchant-commission-feature.md
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/install-features/install-the-category-management-marketplace-merchant-commission.md
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/install-features/install-the-prices-marketplace-merchant-commission-feature.md
  docs/pbc/all/merchant-management/202407.0/marketplace/install-and-upgrade/install-features/install-the-product-marketplace-merchant-commission-feature.md
Labels: tech review needed, new, 202407
