Repository spryker/spryker-docs, pull requests merged in 2024-12, with the labels that each got.

#2945 PBC DMS SEO Update
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/add-fields-to-back-office-forms.md
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/delete-stores.md
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/dynamic-multistore-feature-overview.md
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/install-and-upgrade/install-features/install-dynamic-multistore.md
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/install-and-upgrade/install-the-dynamic-multistore-glue-api.md
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-country-module.md
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-currency-module.md
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-locale-module.md
  docs/pbc/all/dynamic-multistore/202410.0/dynamic-multistore.md
Labels: TW review needed

#2944 PBC Discount Management SEO Update
  docs/pbc/all/discount-management/202410.0/base-shop/import-and-export-data/import-discount-management-data.md
  docs/pbc/all/discount-management/202410.0/base-shop/import-and-export-data/import-file-details-discount-amount.csv.md
  docs/pbc/all/discount-management/202410.0/base-shop/import-and-export-data/import-file-details-discount-store.csv.md
  docs/pbc/all/discount-management/202410.0/base-shop/import-and-export-data/import-file-details-discount-voucher.csv.md
  docs/pbc/all/discount-management/202410.0/base-shop/import-and-export-data/import-file-details-discount.csv.md
  docs/pbc/all/discount-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-promotions-and-discounts-category-management-feature.md
  docs/pbc/all/discount-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-discount-module.md
  docs/pbc/all/discount-management/202410.0/base-shop/manage-in-the-back-office/best-practices-promote-products-with-discounts.md
  docs/pbc/all/discount-management/202410.0/base-shop/manage-in-the-back-office/create-discounts.md
  docs/pbc/all/discount-management/202410.0/base-shop/manage-in-the-back-office/export-voucher-codes.md
  docs/pbc/all/discount-management/202410.0/base-shop/manage-in-the-back-office/manage-discounts-in-the-back-office.md
  docs/pbc/all/discount-management/202410.0/base-shop/manage-using-glue-api/glue-api-add-items-with-discounts-to-guest-carts.md
  docs/pbc/all/discount-management/202410.0/base-shop/manage-using-glue-api/glue-api-manage-discount-vouchers-in-guest-carts.md
  docs/pbc/all/discount-management/202410.0/base-shop/manage-using-glue-api/glue-api-manage-discounts.md
  docs/pbc/all/discount-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-discounts-in-guest-carts.md
  docs/pbc/all/discount-management/202410.0/discount-management.md
Labels: TW review needed

#2950 PBC IAM SEO Update
  docs/pbc/all/identity-access-management/202410.0/identity-access-management.md
  docs/pbc/all/identity-access-management/202410.0/install-and-upgrade/install-the-customer-access-glue-api.md
  docs/pbc/all/identity-access-management/202410.0/install-and-upgrade/install-the-customer-account-management-glue-api.md
  docs/pbc/all/identity-access-management/202410.0/install-and-upgrade/install-the-spryker-core-back-office-feature.md
  docs/pbc/all/identity-access-management/202410.0/install-and-upgrade/upgrade-the-oauth-module.md
  docs/pbc/all/identity-access-management/202410.0/install-and-upgrade/upgrade-the-oauthcompanyuser-module.md
  docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-authenticate-as-a-back-office-user.md
  docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-authenticate-as-a-company-user.md
  docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-authenticate-as-an-agent-assist.md
  docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-confirm-customer-registration.md
  docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-create-customers.md
  docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-delete-expired-refresh-tokens.md
  docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-manage-agent-assist-authentication-tokens.md
  docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-manage-company-user-authentication-tokens.md
  docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-manage-customer-authentication-tokens.md
  docs/pbc/all/identity-access-management/202410.0/manage-using-glue-api/glue-api-manage-customer-passwords.md
Labels: TW review needed

#2948 important qs fixes
  docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/back-office-refresh-analytics-datasets.md
  docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/best-practices-working-with-analytics.md
  docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/manage-analytics-users-and-roles.md
Labels: TW review needed

#2961 Gpsr updates
  docs/about/all/support/general-product-safety-regulation.md
Labels: TW review needed

#2924 Azure pipeline documentation update
  docs/ca/dev/configure-deployment-pipelines/configure-azure-pipelines.md
Labels: TW review needed

#2947 PBC Gift Cards SEO Update
  docs/pbc/all/gift-cards/202410.0/import-and-export-data/import-file-details-gift-card-abstract-configuration.csv.md
  docs/pbc/all/gift-cards/202410.0/import-and-export-data/import-file-details-gift-card-concrete-configuration.csv.md
  docs/pbc/all/gift-cards/202410.0/import-and-export-data/import-gift-cards-data.md
  docs/pbc/all/gift-cards/202410.0/install-and-upgrade/enable-gift-cards.md
  docs/pbc/all/gift-cards/202410.0/install-and-upgrade/install-the-gift-cards-feature.md
  docs/pbc/all/gift-cards/202410.0/manage-using-glue-api/glue-api-retrieve-gift-cards-in-carts-of-registered-users.md
  docs/pbc/all/gift-cards/202410.0/manage-using-glue-api/glue-api-retrieve-gift-cards-in-guest-carts.md
Labels: TW review needed

#2962 PBC PSP pt1 SEO Update
  docs/pbc/all/payment-service-provider/202410.0/base-shop/import-and-export-data/import-file-details-payment-method-store.csv.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/import-and-export-data/import-file-details-payment-method.csv.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/import-and-export-data/payment-service-provider-data-import-and-export.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/install-and-upgrade/install-the-payments-feature.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/install-and-upgrade/install-the-payments-glue-api.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/install-and-upgrade/upgrade-the-payment-module.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/manage-in-the-back-office/manage-payment-methods-in-the-back-office.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/manage-in-the-back-office/view-payment-methods.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/adyen/install-and-configure-adyen.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/adyen/integrate-adyen.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/afterpay/install-and-configure-afterpay.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/afterpay/integrate-afterpay.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/billie.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/billpay/billpay-switch-invoice-payments-to-a-preauthorize-mode.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/billpay/billpay.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/billpay/integrate-billpay.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/braintree/integrate-braintree.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/computop/install-and-configure-computop.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/computop/integrate-computop.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/computop/integrate-payment-methods-for-computop/integrate-the-ideal-payment-method-for-computop.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/computop/integrate-payment-methods-for-computop/integrate-the-paypal-payment-method-for-computop.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/computop/integrate-payment-methods-for-computop/integrate-the-sofort-payment-method-for-computop.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/crefopay/crefopay-callbacks.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/crefopay/crefopay-enable-b2b-payments.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/crefopay/crefopay.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/heidelpay/heidelpay-oms-workflow.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/heidelpay/heidelpay-workflow-for-errors.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/heidelpay/integrate-payment-methods-for-heidelpay/integrate-the-ideal-payment-method-for-heidelpay.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/heidelpay/integrate-payment-methods-for-heidelpay/integrate-the-sofort-payment-method-for-heidelpay.md
Labels: TW review needed

#2960 PBC OMS Pt2 SEO Update
  docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/manage-orders-in-the-back-office.md
  docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/change-the-state-of-order-items.md
  docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/comment-orders.md
  docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/create-returns.md
  docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/create-shipments.md
  docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/edit-billing-addresses-in-orders.md
  docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/edit-shipments.md
  docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/orders/view-returns-of-an-order.md
  docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/reclamations/create-reclamations.md
  docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/reclamations/view-reclamations.md
  docs/pbc/all/order-management-system/202410.0/base-shop/manage-in-the-back-office/view-refunds.md
  docs/pbc/all/order-management-system/202410.0/base-shop/order-management-feature-overview/custom-order-reference-overview.md
  docs/pbc/all/order-management-system/202410.0/base-shop/order-management-feature-overview/oms-order-management-system-matrix.md
  docs/pbc/all/order-management-system/202410.0/base-shop/order-management-feature-overview/order-cancellation-overview.md
  docs/pbc/all/order-management-system/202410.0/base-shop/order-management-feature-overview/order-management-feature-overview.md
  docs/pbc/all/order-management-system/202410.0/base-shop/state-machine-cookbook/state-machine-cookbook-state-machine-fundamentals.md
  docs/pbc/all/order-management-system/202410.0/base-shop/state-machine-cookbook/state-machine-cookbook.md
  docs/pbc/all/order-management-system/202410.0/base-shop/third-party-integrations/nekom-cc-gmbh.md
  docs/pbc/all/order-management-system/202410.0/marketplace/create-merchant-oms-flows.md
  docs/pbc/all/order-management-system/202410.0/marketplace/glue-api-retrieve-marketplace-orders.md
  docs/pbc/all/order-management-system/202410.0/marketplace/import-and-export-data/export-file-details-merchant-order-expenses.csv.md
  docs/pbc/all/order-management-system/202410.0/marketplace/import-and-export-data/export-file-details-merchant-orders.csv.md
  docs/pbc/all/order-management-system/202410.0/marketplace/import-and-export-data/marketplace-import-and-export-order-management-system-data.md
  docs/pbc/all/order-management-system/202410.0/marketplace/install-features/install-the-marketplace-order-management-merchant-portal-feature.md
  docs/pbc/all/order-management-system/202410.0/marketplace/manage-in-the-back-office/manage-marketplace-orders-in-the-back-office.md
  docs/pbc/all/order-management-system/202410.0/marketplace/marketplace-order-management-feature-overview/marketplace-order-management-feature-overview.md
  docs/pbc/all/order-management-system/202410.0/marketplace/marketplace-order-management-feature-overview/marketplace-order-overview.md
  docs/pbc/all/order-management-system/202410.0/order-management-system.md
Labels: TW review needed

#2938 PBC CRM Part 1 SEO Update
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/customer-account-management-feature-overview/customer-accounts-overview.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/customer-account-management-feature-overview/customer-login-overview.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/customer-account-management-feature-overview/customer-registration-overview.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/customer-account-management-feature-overview/password-management-overview.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/domain-model-and-relationships/company-account-module-relations.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/domain-model-and-relationships/customer-login-by-token-reference-information.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/generate-login-tokens.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/import-and-export-data/file-details-customer.csv.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-company-account-feature.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-company-account-merchant-b2b-contract-requests-feature.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-company-account-merchant-b2b-contracts-feature.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-company-account-glue-api.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-customer-account-management-glue-api.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-companybusinessunit-module.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-companyuserauthrestapi-module.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-companyusersrestapi-module.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-sharedcartpage-module.md
Labels: TW review needed

#2946 PBC Email SEO Update
  docs/pbc/all/emails/202410.0/emails.md
  docs/pbc/all/emails/202410.0/howto-create-and-register-a-mail-provider.md
  docs/pbc/all/emails/202410.0/third-party-integrations/install-and-configure-inxmail.md
  docs/pbc/all/emails/202410.0/third-party-integrations/integrate-inxmail.md
  docs/pbc/all/emails/202410.0/third-party-integrations/inxmail-api-requests.md
  docs/pbc/all/emails/202410.0/third-party-integrations/inxmail-order-referenced-commands.md
Labels: TW review needed

#2952 PBC Merchant Management Base Shop SEO Update
  docs/pbc/all/merchant-management/202410.0/base-shop/install-and-upgrade/install-the-merchant-b2b-contract-requests-comments-feature.md
  docs/pbc/all/merchant-management/202410.0/base-shop/install-and-upgrade/install-the-merchant-b2b-contract-requests-company-account-feature.md
  docs/pbc/all/merchant-management/202410.0/base-shop/install-and-upgrade/install-the-merchant-b2b-contracts-comments-feature.md
  docs/pbc/all/merchant-management/202410.0/base-shop/install-and-upgrade/install-the-merchant-b2b-contracts-company-account-feature.md
  docs/pbc/all/merchant-management/202410.0/base-shop/install-and-upgrade/install-the-merchant-feature.md
  docs/pbc/all/merchant-management/202410.0/base-shop/install-and-upgrade/install-the-merchants-and-merchant-relations-feature.md
  docs/pbc/all/merchant-management/202410.0/base-shop/manage-in-the-back-office/create-merchant-relations.md
  docs/pbc/all/merchant-management/202410.0/base-shop/manage-in-the-back-office/create-merchants.md
  docs/pbc/all/merchant-management/202410.0/base-shop/manage-in-the-back-office/edit-merchant-relations.md
  docs/pbc/all/merchant-management/202410.0/base-shop/manage-in-the-back-office/edit-merchants.md
  docs/pbc/all/merchant-management/202410.0/base-shop/manage-in-the-back-office/manage-merchants-in-the-back-office.md
Labels: TW review needed

#2953 PBC Pt1 Merchant Management Marketplace SEO Update
  docs/pbc/all/merchant-management/202410.0/marketplace/domain-model-and-relationships/marketplace-merchant-feature-domain-model.md
  docs/pbc/all/merchant-management/202410.0/marketplace/domain-model-and-relationships/merchant-category-feature-domain-model.md
  docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/import-file-details-merchant-category.csv.md
  docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/import-file-details-merchant-profile-address.csv.md
  docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/import-merchant-management-data.md
  docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/merchant-commission/import-file-details-merchant-comission.csv.md
  docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/merchant-commission/import-file-details-merchant_commission_amount.csv.md
  docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/merchant-commission/import-file-details-merchant_commission_group.csv.md
  docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/merchant-commission/import-file-details-merchant_commission_merchant.csv.md
  docs/pbc/all/merchant-management/202410.0/marketplace/import-and-export-data/merchant-commission/import-file-details-merchant_commission_store.csv.md
  docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-commission-product-feature.md
  docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-feature.md
  docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-core-feature.md
  docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-product-offer-management-feature.md
  docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-merchant-portal-marketplace-merchant-portal-product-offer-management-merchant-portal-order-management-feature.md
  docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-merchant-portal-marketplace-order-management-feature.md
  docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-merchant-portal-marketplace-product-inventory-management-feature.md
  docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-merchant-portal-marketplace-product-tax-feature.md
  docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-the-merchant-portal.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/back-office-import-merchant-commissions.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/manage-merchant-relations/create-merchant-relations.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/manage-merchant-relations/edit-merchant-relations.md
Labels: TW review needed

#2959 PBC OMS pt1 SEO Update
  docs/pbc/all/order-management-system/202410.0/base-shop/datapayload-conversion/multi-language-setup.md
  docs/pbc/all/order-management-system/202410.0/base-shop/datapayload-conversion/state-machine/state-machine-console-commands.md
  docs/pbc/all/order-management-system/202410.0/base-shop/datapayload-conversion/step-engine/step-engine-workflow-overview.md
  docs/pbc/all/order-management-system/202410.0/base-shop/display-custom-names-for-order-item-states-on-the-storefront.md
  docs/pbc/all/order-management-system/202410.0/base-shop/domain-model-and-relationships/custom-order-reference-module-relations.md
  docs/pbc/all/order-management-system/202410.0/base-shop/glue-api-retrieve-orders.md
  docs/pbc/all/order-management-system/202410.0/base-shop/import-and-export-data/import-and-export-order-management-system-data.md
  docs/pbc/all/order-management-system/202410.0/base-shop/import-and-export-data/orders-data-export/export-file-details-order-expenses.csv.md
  docs/pbc/all/order-management-system/202410.0/base-shop/import-and-export-data/orders-data-export/export-file-details-order-items.csv.md
  docs/pbc/all/order-management-system/202410.0/base-shop/import-and-export-data/orders-data-export/export-file-details-orders.csv.md
  docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-reclamations-feature.md
  docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-sales-data-export-feature.md
  docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-splittable-order-items-feature.md
  docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-checkout-glue-api.md
  docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-order-management-glue-api.md
  docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-shipment-glue-api.md
  docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-oms-module.md
  docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-ordersrestapi-module.md
  docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-sales-module.md
  docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-salesquantity-module.md
  docs/pbc/all/order-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-salessplit-module.md
Labels: TW review needed

#2963 PBC PSP pt2 SEO Update
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/klarna/klarna-payment-workflow.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/payolution/integrate-payolution.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/payolution/integrate-the-invoice-payment-method-for-payolution.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/payolution/payolution-request-flow.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/payone/app-composition-platform-integration/configure-payone.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/payone/app-composition-platform-integration/disconnect-payone.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/payone/app-composition-platform-integration/integrate-payone.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/payone/payone.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/ratepay/disable-address-updates-from-the-backend-application-for-ratepay.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/ratepay/integrate-payment-methods-for-ratepay/integrate-the-invoice-payment-method-for-ratepay.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/ratepay/integrate-payment-methods-for-ratepay/integrate-the-prepayment-payment-method-for-ratepay.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/ratepay/ratepay-core-module-structure-diagram.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/ratepay/ratepay-facade-methods.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/ratepay/ratepay-payment-workflow.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/ratepay/ratepay-state-machines.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/disconnect-stripe.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/install-and-configure-stripe-prerequisites.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/stripe.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/unzer/configure-in-the-back-office/add-unzer-marketplace-credentials.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/unzer/configure-in-the-back-office/add-unzer-standard-credentails.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/unzer/install-unzer/install-and-configure-unzer.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/unzer/install-unzer/integrate-unzer-glue-api.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/unzer/install-unzer/integrate-unzer.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/unzer/unzer-domain-model-and-relationships.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/unzer/unzer.md
  docs/pbc/all/payment-service-provider/202410.0/marketplace/stripe-third-party-integration/configure-merchant-transfers-for-stripe.md
  docs/pbc/all/payment-service-provider/202410.0/marketplace/stripe-third-party-integration/connect-and-configure-stripe-for-marketplace.md
  docs/pbc/all/payment-service-provider/202410.0/marketplace/stripe-third-party-integration/onboard-to-stripe-in-the-merchant-portal.md
  docs/pbc/all/payment-service-provider/202410.0/marketplace/stripe-third-party-integration/stripe-for-marketplace-overview.md
  docs/pbc/all/payment-service-provider/202410.0/marketplace/stripe-third-party-integration/stripe-for-marketplace.md
  docs/pbc/all/payment-service-provider/202410.0/marketplace/stripe-third-party-integration/stripe-oms-configuration-in-marketplaces.md
  docs/pbc/all/payment-service-provider/202410.0/payment-service-provider.md
Labels: TW review needed

#2954 PBC Pt2 Merchant Management Marketplace SEO update
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/manage-merchant-users/create-merchant-users.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/manage-merchant-users/edit-merchant-users.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-back-office/manage-merchants/create-merchants.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-merchant-portal/manage-merchant-relation-requests.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-merchant-portal/manage-merchant-relations.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-in-the-merchant-portal/manage-merchants-in-the-merchant-portal.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-using-glue-api/glue-api-retrieve-merchant-addresses.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-using-glue-api/glue-api-retrieve-merchant-opening-hours.md
  docs/pbc/all/merchant-management/202410.0/marketplace/manage-using-glue-api/glue-api-retrieve-merchants.md
  docs/pbc/all/merchant-management/202410.0/marketplace/marketplace-merchant-commission-feature-overview.md
  docs/pbc/all/merchant-management/202410.0/marketplace/marketplace-merchant-portal-core-feature-overview/gui-modules.md
  docs/pbc/all/merchant-management/202410.0/marketplace/marketplace-merchant-portal-core-feature-overview/merchant-user.md
  docs/pbc/all/merchant-management/202410.0/marketplace/marketplace-merchant-portal-core-feature-overview/persistence-acl-configuration.md
  docs/pbc/all/merchant-management/202410.0/marketplace/merchant-category-feature-overview.md
  docs/pbc/all/merchant-management/202410.0/marketplace/third-party-integrations/channelpilot-marketplace.md
  docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/create-gui-modules.md
  docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/create-gui-table-column-types.md
  docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/create-gui-table-filter-types.md
  docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/create-gui-tables.md
  docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/create-merchant-commission-calculator-type-plugins.md
  docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/create-merchant-commission-collector-rule.md
  docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/extend-gui-tables.md
  docs/pbc/all/merchant-management/202410.0/marketplace/tutorials-and-howtos/extend-merchant-portal-dashboard.md
  docs/pbc/all/merchant-management/202410.0/merchant-management.md
Labels: TW review needed

#2957 PBC Offer Management SEO Update
  docs/pbc/all/offer-management/202410.0/base-shop/upgrade-modules/upgrade-the-offer-module.md
  docs/pbc/all/offer-management/202410.0/base-shop/upgrade-modules/upgrade-the-offergui-module.md
  docs/pbc/all/offer-management/202410.0/marketplace/glue-api-retrieve-product-offers.md
  docs/pbc/all/offer-management/202410.0/marketplace/import-and-export-data/import-file-details-product-offer-shipment-type.csv.md
  docs/pbc/all/offer-management/202410.0/marketplace/import-and-export-data/import-offer-management-data.md
  docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-product-offer-management-feature.md
  docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-product-offer-management-merchant-portal-order-management-merchant-portal-feature.md
  docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-offer-cart-feature.md
  docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-offer-checkout-feature.md
  docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-offer-marketplace-product-feature.md
  docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-offer-quick-add-to-cart-feature.md
  docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-product-offer-shipment-availability-feature.md
  docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-glue-api/install-the-marketplace-product-offer-cart-glue-api.md
  docs/pbc/all/offer-management/202410.0/marketplace/install-and-upgrade/install-glue-api/install-the-marketplace-product-offer-wishlist-glue-api.md
  docs/pbc/all/offer-management/202410.0/marketplace/manage-in-the-merchant-portal/create-product-offers.md
  docs/pbc/all/offer-management/202410.0/marketplace/manage-in-the-merchant-portal/manage-product-offers-in-the-merchant-portal.md
  docs/pbc/all/offer-management/202410.0/marketplace/marketplace-product-offer-feature-domain-model-and-relationships/marketplace-product-offer-feature-domain-model-and-relationships.md
  docs/pbc/all/offer-management/202410.0/marketplace/product-offer-shipment-availability-feature-overview.md
  docs/pbc/all/offer-management/202410.0/marketplace/render-merchant-product-offers-on-the-storefront.md
  docs/pbc/all/offer-management/202410.0/offer-management.md
  docs/pbc/all/offer-management/202410.0/unified-commerce/glue-api-retrieve-product-offer-service-point-availability.md
  docs/pbc/all/offer-management/202410.0/unified-commerce/import-file-details-product-offer-service.csv.md
  docs/pbc/all/offer-management/202410.0/unified-commerce/install-features/install-the-marketplace-product-offer-service-points-feature.md
  docs/pbc/all/offer-management/202410.0/unified-commerce/product-offer-service-feature-overview.md
  docs/pbc/all/offer-management/202410.0/unified-commerce/product-offer-service-points-availability-feature.md
  docs/pbc/all/offer-management/202410.0/unified-commerce/unified-commerce-create-and-edit-product-offers.md
Labels: TW review needed

#2965 PBC Price Management SEO Update
  docs/pbc/all/pbc.md
  docs/pbc/all/price-management/202410.0/base-shop/extend-and-customize/configuration-of-price-modes-and-types.md
  docs/pbc/all/price-management/202410.0/base-shop/extend-and-customize/multiple-currencies-per-store-configuration.md
  docs/pbc/all/price-management/202410.0/base-shop/import-and-export-data/import-and-export-price-management-data.md
  docs/pbc/all/price-management/202410.0/base-shop/import-and-export-data/import-file-details-currency.csv.md
  docs/pbc/all/price-management/202410.0/base-shop/import-and-export-data/import-file-details-product-price-schedule.csv.md
  docs/pbc/all/price-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-prices-feature-dynamic-multistore.md
  docs/pbc/all/price-management/202410.0/base-shop/install-and-upgrade/install-features/install-the-scheduled-prices-feature.md
  docs/pbc/all/price-management/202410.0/base-shop/install-and-upgrade/install-the-product-price-glue-api.md
  docs/pbc/all/price-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-currency-module.md
  docs/pbc/all/price-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-price-module.md
  docs/pbc/all/price-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-pricecartconnector-module.md
  docs/pbc/all/price-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-priceproduct-module.md
  docs/pbc/all/price-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-priceproductstorage-module.md
  docs/pbc/all/price-management/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-to-multi-currency.md
  docs/pbc/all/price-management/202410.0/base-shop/manage-in-the-back-office/add-scheduled-prices-to-abstract-products-and-product-bundles.md
  docs/pbc/all/price-management/202410.0/base-shop/manage-in-the-back-office/add-volume-prices-to-abstract-products-and-product-bundles.md
  docs/pbc/all/price-management/202410.0/base-shop/manage-in-the-back-office/manage-prices-in-the-back-office.md
  docs/pbc/all/price-management/202410.0/base-shop/manage-in-the-back-office/manage-scheduled-prices.md
  docs/pbc/all/price-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-abstract-product-prices.md
  docs/pbc/all/price-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-concrete-product-prices.md
  docs/pbc/all/price-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-prices-when-retrieving-abstract-products.md
  docs/pbc/all/price-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-prices-when-retrieving-concrete-products.md
  docs/pbc/all/price-management/202410.0/base-shop/tutorials-and-howtos/manage-business-unit-specific-prices-via-data-import.md
  docs/pbc/all/price-management/202410.0/base-shop/tutorials-and-howtos/schedule-cron-job-for-scheduled-prices.md
  docs/pbc/all/price-management/202410.0/marketplace/domain-model-and-relationships/marketplace-merchant-custom-prices-feature-domain-model-and-relationships.md
  docs/pbc/all/price-management/202410.0/marketplace/domain-model-and-relationships/marketplace-product-offer-prices-feature-domain-model-and-relationships.md
  docs/pbc/all/price-management/202410.0/marketplace/glue-api-retrieve-product-offer-prices.md
  docs/pbc/all/price-management/202410.0/marketplace/install-and-upgrade/install-glue-api/install-the-marketplace-product-offer-prices-wishlist-glue-api.md
  docs/pbc/all/price-management/202410.0/marketplace/install-and-upgrade/install-glue-api/install-the-prices-marketplace-wishlist-glue-api.md
  docs/pbc/all/price-management/202410.0/marketplace/marketplace-product-offer-prices-feature-overview.md
  docs/pbc/all/price-management/202410.0/price-management.md
Labels: TW review needed

#2967 PBC PIM Domain Model feature overviews and import export SEO Update
  docs/pbc/all/product-information-management/202410.0/base-shop/domain-model-and-relationships/product-sets-module-relations.md
  docs/pbc/all/product-information-management/202410.0/base-shop/feature-overviews/catalog-feature-overview.md
  docs/pbc/all/product-information-management/202410.0/base-shop/feature-overviews/category-management-feature-overview.md
  docs/pbc/all/product-information-management/202410.0/base-shop/feature-overviews/configurable-product-feature-overview/configurable-product-feature-overview.md
  docs/pbc/all/product-information-management/202410.0/base-shop/feature-overviews/product-approval-process-feature-overview.md
  docs/pbc/all/product-information-management/202410.0/base-shop/feature-overviews/product-bundles-feature-overview.md
  docs/pbc/all/product-information-management/202410.0/base-shop/feature-overviews/product-comparison-feature-overview.md
  docs/pbc/all/product-information-management/202410.0/base-shop/feature-overviews/product-feature-overview/product-attributes-overview.md
  docs/pbc/all/product-information-management/202410.0/base-shop/feature-overviews/product-feature-overview/product-feature-overview.md
  docs/pbc/all/product-information-management/202410.0/base-shop/feature-overviews/product-labels-feature-overview.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/categories-data-import/categories-data-import.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/categories-data-import/import-file-details-category-template.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/categories-data-import/import-file-details-category.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/import-file-details-product-alternative.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/import-file-details-product-concrete-pre-configuration.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/import-file-details-product-discontinued.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/import-file-details-product-group.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/import-file-details-product-label.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/import-file-details-product-packaging-unit-type.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/import-product-data-with-a-single-file.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/product-information-management-data-import.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/product-options/import-file-details-product-option-price.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/product-options/import-file-details-product-option.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/product-options/product-options-data-import.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/products-data-import/import-file-details-product-abstract-store.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/products-data-import/import-file-details-product-abstract.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/products-data-import/import-file-details-product-attribute-key.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/products-data-import/import-file-details-product-concrete.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/products-data-import/import-file-details-product-image.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/products-data-import/import-file-details-product-management-attribute.csv.md
  docs/pbc/all/product-information-management/202410.0/base-shop/import-and-export-data/products-data-import/products-data-import.md
Labels: TW review needed

#2970 PBC PIM Manage BO and Manage GLUE SEO Update
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/attributes/create-product-attributes.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/attributes/edit-product-attributes.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/categories/create-categories.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/categories/delete-categories.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/categories/edit-categories.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/categories/order-products-in-categories.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/configurable-bundle-templates/create-configurable-bundle-templates.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/configurable-bundle-templates/edit-configurable-bundle-templates.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/configurable-bundle-templates/edit-slots-in-configurable-bundle-templates.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/manage-products-in-the-back-office.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/product-labels/create-product-labels.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/product-labels/edit-product-labels.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/product-lists/create-product-lists.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/product-lists/edit-product-lists.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/product-options/create-product-options.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/product-options/edit-product-options.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/products/create-service-offerings-best-practices.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/products/manage-product-variants/discontinue-products.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-in-the-back-office/products/manage-product-variants/edit-product-variants.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-using-glue-api/abstract-products/glue-api-retrieve-image-sets-of-abstract-products.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-using-glue-api/categories/glue-api-retrieve-category-nodes.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-using-glue-api/categories/glue-api-retrieve-category-trees.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-using-glue-api/concrete-products/glue-api-retrieve-concrete-products.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-using-glue-api/concrete-products/glue-api-retrieve-image-sets-of-concrete-products.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-using-glue-api/concrete-products/glue-api-retrieve-sales-units.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-using-glue-api/glue-api-manage-products.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-alternative-products.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-bundled-products.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-configurable-bundle-templates.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-product-attributes.md
  docs/pbc/all/product-information-management/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-product-labels.md
Labels: TW review needed

#2975 PBC Return Management SEO Update
  docs/pbc/all/return-management/202410.0/base-shop/build-a-return-management-process-best-practices.md
  docs/pbc/all/return-management/202410.0/base-shop/manage-in-the-back-office/change-the-state-of-order-items-in-returns.md
  docs/pbc/all/return-management/202410.0/base-shop/manage-in-the-back-office/manage-returns-in-the-back-office.md
  docs/pbc/all/return-management/202410.0/base-shop/manage-in-the-back-office/manage-returns.md
  docs/pbc/all/return-management/202410.0/base-shop/set-number-of-days-for-a-return-policy.md
  docs/pbc/all/return-management/202410.0/marketplace/glue-api-manage-marketplace-returns.md
Labels: TW review needed

#2971 PBC PIM Marketplace SEO Update
  docs/pbc/all/product-information-management/202410.0/base-shop/third-party-integrations/akeneo/akeneo-connector-eco-module-console-commands.md
  docs/pbc/all/product-information-management/202410.0/base-shop/third-party-integrations/censhare-pim.md
  docs/pbc/all/product-information-management/202410.0/base-shop/tutorials-and-howtos/howto-display-product-groups-by-color-on-the-storefront.md
  docs/pbc/all/product-information-management/202410.0/base-shop/tutorials-and-howtos/howto-render-configurable-bundle-templates-in-the-storefront.md
  docs/pbc/all/product-information-management/202410.0/base-shop/tutorials-and-howtos/product-data-from-import-to-frontend-views.md
  docs/pbc/all/product-information-management/202410.0/base-shop/tutorials-and-howtos/split-products-by-stores.md
  docs/pbc/all/product-information-management/202410.0/base-shop/tutorials-and-howtos/tutorial-product.md
  docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-marketplace-product-offer-feature.md
  docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-merchant-portal-tax-feature.md
  docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-options-cart-feature.md
  docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-options-feature.md
  docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-quick-add-to-cart-feature.md
  docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-product-marketplace-merchant-commission-feature.md
  docs/pbc/all/product-information-management/202410.0/marketplace/install-and-upgrade/install-glue-api/install-the-marketplace-product-cart-glue-api.md
  docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/manage-marketplace-products-in-the-back-office.md
  docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/product-options/manage-product-options.md
  docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/product-options/product-options.md
  docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/products/abstract-products/abstract-products.md
  docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/products/abstract-products/create-abstract-products.md
  docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/products/abstract-products/edit-abstract-products.md
  docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/products/create-product-variants.md
  docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-back-office/products/products.md
  docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-merchant-portal/concrete-products/edit-marketplace-concrete-products.md
  docs/pbc/all/product-information-management/202410.0/marketplace/manage-in-the-merchant-portal/manage-products-in-the-merchant-portal.md
  docs/pbc/all/product-information-management/202410.0/marketplace/manage-using-glue-api/glue-api-retrieve-concrete-products.md
  docs/pbc/all/product-information-management/202410.0/marketplace/manage-using-glue-api/glue-api-retrieve-product-offers-of-concrete-products.md
  docs/pbc/all/product-information-management/202410.0/marketplace/marketplace-product-feature-overview.md
  docs/pbc/all/product-information-management/202410.0/product-information-management.md
Labels: TW review needed

#2972 PBC PRM SEO Update
  docs/pbc/all/product-relationship-management/202410.0/build-your-own-product-relation-type.md
  docs/pbc/all/product-relationship-management/202410.0/import-file-details-product-relation.csv.md
  docs/pbc/all/product-relationship-management/202410.0/install-and-upgrade/install-the-product-relations-feature.md
  docs/pbc/all/product-relationship-management/202410.0/install-and-upgrade/upgrade-the-productrelationstorage-module.md
  docs/pbc/all/product-relationship-management/202410.0/manage-in-the-back-office/best-practices-promote-products-with-product-relations.md
  docs/pbc/all/product-relationship-management/202410.0/manage-in-the-back-office/create-product-relations.md
  docs/pbc/all/product-relationship-management/202410.0/manage-in-the-back-office/edit-product-relations.md
  docs/pbc/all/product-relationship-management/202410.0/manage-in-the-back-office/manage-product-relations-in-the-back-office.md
  docs/pbc/all/product-relationship-management/202410.0/manage-in-the-back-office/view-product-relations.md
  docs/pbc/all/product-relationship-management/202410.0/product-relations-module-relations.md
  docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/8select.md
  docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/contentserv.md
  docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/econda/export-econda-data.md
  docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/econda/install-econda.md
  docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/econda/integrate-econda-cross-selling.md
  docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/econda/integrate-econda.md
  docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/nosto.md
Labels: TW review needed

#2973 PBC Ratings and Reviews SEO Update
  docs/pbc/all/ratings-reviews/202410.0/import-and-export-data/import-file-details-product-review.csv.md
  docs/pbc/all/ratings-reviews/202410.0/import-and-export-data/ratings-and-reviews-data-import.md
  docs/pbc/all/ratings-reviews/202410.0/manage-product-reviews-in-the-back-office.md
  docs/pbc/all/ratings-reviews/202410.0/manage-using-glue-api/glue-api-manage-product-reviews.md
  docs/pbc/all/ratings-reviews/202410.0/manage-using-glue-api/glue-api-retrieve-product-reviews-when-retrieving-concrete-products.md
  docs/pbc/all/ratings-reviews/202410.0/ratings-and-reviews.md
  docs/pbc/all/ratings-reviews/202410.0/third-party-integrations/bazaarvoice.md
  docs/pbc/all/ratings-reviews/202410.0/third-party-integrations/configure-bazaarvoice.md
  docs/pbc/all/ratings-reviews/202410.0/third-party-integrations/disconnect-bazaarvoice.md
  docs/pbc/all/ratings-reviews/202410.0/third-party-integrations/integrate-bazaarvoice.md
  docs/pbc/all/ratings-reviews/202410.0/tutorials-and-howtos/howto-configure-product-reviews.md
Labels: TW review needed

#2974 PBC RFQ SEO Update
  docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/install-features/install-the-quotation-process-approval-process-feature.md
  docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/install-features/install-the-quotation-process-feature.md
  docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/install-features/install-the-quotation-process-glue-api.md
  docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/install-features/install-the-quotation-process-multiple-carts-feature.md
  docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/upgrade-modules/upgrade-the-quoterequest-module.md
  docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/upgrade-modules/upgrade-the-quoterequestagent-module.md
  docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/upgrade-modules/upgrade-the-quoterequestagentpage-module.md
  docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/upgrade-modules/upgrade-the-quoterequestagentwidget-module.md
  docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/upgrade-modules/upgrade-the-quoterequestpage-module.md
  docs/pbc/all/request-for-quote/202410.0/install-and-upgrade/upgrade-modules/upgrade-the-quoterequestwidget-module.md
  docs/pbc/all/request-for-quote/202410.0/request-for-quote.md
  docs/pbc/all/request-for-quote/202410.0/use-cases-request-for-quote-processes.md
Labels: TW review needed

#2895 ACP-3963: Algolia personalization.
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/algolia-personalization-with-headless-frontends.md
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/algolia.md
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/configure-algolia.md
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/customize-algolia.md
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/integrate-algolia-personalization.md
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
Labels: TW review needed

#2940 FRW-7936 Updated documentation
  _includes/pbc/all/install-features/202410.0/install-dynamic-multistore.md
  docs/pbc/all/dynamic-multistore/202410.0/dynamic-multistore.md
Labels: TW review needed, updated

#2988 Update integrate-algolia-personalization.md
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/integrate-algolia-personalization.md
Labels: TW review needed

#2984 FRW-9287 Updated twig integration guide.
  _includes/pbc/all/upgrade-modules/upgrade-the-twig-module.md
  docs/dg/dev/integrate-and-configure/twig-and-twigextension.md
Labels: updated

#2977 PBC Service Point SEO Update
  docs/pbc/all/service-point-management/202410.0/service-point-management.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/enable-click-collect.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/import-and-export-data/import-file-details-service-point-address.csv.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/import-and-export-data/import-file-details-service-point-store.csv.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/import-and-export-data/import-file-details-service-point.csv.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/import-and-export-data/import-file-details-service-type.csv.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/import-and-export-data/import-file-details-service.csv.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/install-features/install-the-service-points-cart-feature.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/install-features/install-the-service-points-feature.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-point-addresses/glue-api-add-service-point-addresses.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-point-addresses/glue-api-retrieve-service-point-addresses.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-point-addresses/glue-api-update-service-point-addresses.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-points/glue-api-add-service-points.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-points/glue-api-retrieve-service-points.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-points/glue-api-update-service-points.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-types/glue-api-add-service-types.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-types/glue-api-retrieve-service-types.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-service-types/glue-api-update-service-types.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-services/glue-api-add-services.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-services/glue-api-retrieve-services.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/manage-using-glue-api/manage-services/glue-api-update-services.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/service-points-cart-checkout-feature-overview.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/service-points-cart-feature-overview.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/service-points-feature-overview.md
  docs/pbc/all/service-point-management/202410.0/unified-commerce/service-points-order-management-feature.md
Labels: TW review needed

#2882 PayPal Express, Payment flows, Payment APIs
  _data/sidebars/dg_dev_sidebar.yml
  _data/sidebars/pbc_all_sidebar.yml
  _drafts/docs-updates.md
  _includes/pbc/all/install-features/202410.0/install-glue-api/install-the-payments-glue-api.md
  _includes/pbc/all/install-features/202410.0/install-the-customer-account-management-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-payments-feature.md
  docs/about/all/releases/release-notes-202410.0.md
  docs/dg/dev/acp/apis-and-flows-for-payment-service-providers/apis-and-flows-for-payment-service-providers.md
  docs/dg/dev/acp/apis-and-flows-for-payment-service-providers/asynchronous-api-for-payment-service-providers.md
  docs/dg/dev/acp/apis-and-flows-for-payment-service-providers/configure-and-disconnect-flows-for-payment-service-providers.md
  docs/dg/dev/acp/apis-and-flows-for-payment-service-providers/headless-express-checkout-payment-flow-for-payment-service-providers.md
  docs/dg/dev/acp/apis-and-flows-for-payment-service-providers/headless-payment-flow-for-payment-service-providers.md
  docs/dg/dev/acp/apis-and-flows-for-payment-service-providers/hosted-payment-page-flow-for-payment-service-providers.md
  docs/dg/dev/acp/apis-and-flows-for-payment-service-providers/oms-payment-flow-for-payment-service-providers.md
  docs/dg/dev/acp/apis-and-flows-for-payment-service-providers/synchronous-api-for-payment-service-providers.md
  docs/dg/dev/acp/apis-and-overview-diagrams-for-payment-service-providers.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/define-return-urls-for-payments.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/embed-the-stripe-payment-page-as-an-iframe.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/implement-stripe-checkout-as-a-hosted-payment-page.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/oms-configuration-for-stripe.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/processing-refunds-with-stripe.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/project-guidelines-for-stripe.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/sending-additional-data-to-stripe.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/stripe-checkout-with-third-party-frontends.md
  docs/pbc/all/payment-service-provider/202404.0/marketplace/stripe-third-party-integration/stripe-oms-configuration-in-marketplaces.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/define-return-urls-for-payments.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/payment-method-strategies.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/payone/app-composition-platform-integration/payment-method-flows/payone-credit-card-payment-flow.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/payone/app-composition-platform-integration/payment-method-flows/payone-paypal-express-payment-flow-in-headless-applications.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/payone/app-composition-platform-integration/payment-method-flows/payone-paypal-payment-flow.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/payone/app-composition-platform-integration/payone-acp-app.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/embed-the-stripe-payment-page-as-an-iframe.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/oms-configuration-for-stripe.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/processing-refunds-with-stripe.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/project-guidelines-for-stripe.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/project-prerequisites-for-implementing-Stripe-checkout-as-a-hosted-payment-page.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/sending-additional-data-to-stripe.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/stripe-checkout-with-third-party-frontends.md
  docs/pbc/all/payment-service-provider/202410.0/marketplace/stripe-third-party-integration/stripe-oms-configuration-in-marketplaces.md
Labels: updated

#2978 PBC Wishlist SEO Update
  docs/pbc/all/shopping-list-and-wishlist/202410.0/base-shop/install-and-upgrade/install-features/install-the-shopping-list-agent-assist-feature.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/base-shop/install-and-upgrade/install-features/install-the-shopping-lists-feature.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/base-shop/install-and-upgrade/install-features/install-the-shopping-lists-quick-add-to-cart-feature.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/base-shop/install-and-upgrade/install-features/install-the-wishlist-alternative-products-feature.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/base-shop/install-and-upgrade/install-glue-api/install-the-shopping-lists-glue-api.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-shoppinglist-module.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-shoppinglistwidget-module.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/base-shop/manage-using-glue-api/glue-api-manage-shopping-list-items.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/base-shop/manage-using-glue-api/glue-api-manage-shopping-lists.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/base-shop/manage-using-glue-api/glue-api-manage-wishlists.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/base-shop/shopping-lists-feature-overview/shopping-lists-feature-overview.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/marketplace/domain-model-and-relationships/marketplace-shopping-lists-feature-domain-model-and-relationships.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-wishlist-feature.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/marketplace/install-and-upgrade/install-glue-api/install-the-marketplace-wishlist-prices-glue-api.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/marketplace/install-and-upgrade/install-glue-api/install-the-marketplace-wishlist-product-offer-glue-api.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/marketplace/install-and-upgrade/install-glue-api/install-the-wishlist-marketplace-product-offer-prices-glue-api.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/marketplace/manage-using-glue-api/glue-api-manage-marketplace-shopping-list-items.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/marketplace/manage-using-glue-api/glue-api-manage-marketplace-shopping-lists.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/marketplace/marketplace-wishlist-feature-overview.md
  docs/pbc/all/shopping-list-and-wishlist/202410.0/shopping-list-and-wishlist.md
Labels: TW review needed

#2979 PBC Tax Management SEO Update
  docs/pbc/all/tax-management/202410.0/base-shop/import-and-export-data/import-file-details-product-abstract.csv.md
  docs/pbc/all/tax-management/202410.0/base-shop/import-and-export-data/import-file-details-product-option.csv.md
  docs/pbc/all/tax-management/202410.0/base-shop/import-and-export-data/import-file-details-shipment.csv.md
  docs/pbc/all/tax-management/202410.0/base-shop/import-and-export-data/import-file-details-tax-sets.csv.md
  docs/pbc/all/tax-management/202410.0/base-shop/import-and-export-data/tax-management-data-import.md
  docs/pbc/all/tax-management/202410.0/base-shop/install-and-upgrade/upgrade-the-producttaxsetsrestapi-module.md
  docs/pbc/all/tax-management/202410.0/base-shop/install-and-upgrade/upgrade-the-tax-module.md
  docs/pbc/all/tax-management/202410.0/base-shop/manage-in-the-back-office/create-tax-rates.md
  docs/pbc/all/tax-management/202410.0/base-shop/manage-in-the-back-office/create-tax-sets.md
  docs/pbc/all/tax-management/202410.0/base-shop/manage-in-the-back-office/edit-tax-rates.md
  docs/pbc/all/tax-management/202410.0/base-shop/manage-in-the-back-office/edit-tax-sets.md
  docs/pbc/all/tax-management/202410.0/base-shop/manage-in-the-back-office/manage-taxes-in-the-back-office.md
  docs/pbc/all/tax-management/202410.0/base-shop/manage-using-glue-api/retrieve-tax-sets.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/avalara/apply-avalara-tax-codes.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/avalara/avalara.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/avalara/install-avalara-product-options.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/avalara/install-avalara-shipment.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/avalara/install-avalara.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/connect-vertex.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/disconnect-vertex.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-the-acp-connector-module-for-tax-calculation.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/troubleshooting-vertex.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/vertex-faq.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/vertex.md
Labels: TW review needed

#2980 PBC User Management SEO Update
  docs/pbc/all/user-management/202410.0/base-shop/install-and-upgrade/install-the-agent-assist-glue-api.md
  docs/pbc/all/user-management/202410.0/base-shop/install-and-upgrade/install-the-agent-assist-shopping-list-feature.md
  docs/pbc/all/user-management/202410.0/base-shop/manage-in-the-back-office/manage-user-groups/create-user-groups.md
  docs/pbc/all/user-management/202410.0/base-shop/manage-in-the-back-office/manage-user-groups/edit-user-groups.md
  docs/pbc/all/user-management/202410.0/base-shop/manage-in-the-back-office/manage-user-roles/create-user-roles.md
  docs/pbc/all/user-management/202410.0/base-shop/manage-in-the-back-office/manage-user-roles/edit-user-roles.md
  docs/pbc/all/user-management/202410.0/base-shop/manage-in-the-back-office/manage-users-in-the-back-office.md
  docs/pbc/all/user-management/202410.0/base-shop/manage-in-the-back-office/manage-users/create-users.md
  docs/pbc/all/user-management/202410.0/base-shop/manage-in-the-back-office/manage-users/delete-users.md
  docs/pbc/all/user-management/202410.0/base-shop/manage-in-the-back-office/manage-users/edit-users.md
  docs/pbc/all/user-management/202410.0/base-shop/manage-using-glue-api/glue-api-impersonate-customers-as-an-agent-assist.md
  docs/pbc/all/user-management/202410.0/marketplace/back-office-create-users.md
  docs/pbc/all/user-management/202410.0/marketplace/persistence-acl-feature-domain-model-and-relationships.md
  docs/pbc/all/user-management/202410.0/marketplace/persistence-acl-feature-overview/persistence-acl-feature-configuration.md
  docs/pbc/all/user-management/202410.0/user-management.md
Labels: TW review needed

#2983 PBC WMS SEO Update
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/domain-model-and-relationships/availability-notification-domain-model-and-relationships.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/import-and-export-data/import-file-details-product-stock.csv.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/import-and-export-data/import-file-details-warehouse-address.csv.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/import-and-export-data/import-file-details-warehouse-store.csv.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/import-and-export-data/import-file-details-warehouse.csv.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-availability-notification-glue-api.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/install-and-upgrade/install-features/install-the-inventory-management-feature.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-availability-module.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/manage-in-the-back-office/check-availability-of-products.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/manage-in-the-back-office/create-warehouses.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/manage-in-the-back-office/edit-warehouses.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/manage-in-the-back-office/manage-warehouses-in-the-back-office.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/manage-using-glue-api/glue-api-manage-availability-notifications.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-abstract-product-availability.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-availability-when-retrieving-abstract-products.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-availability-when-retrieving-concrete-products.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-concrete-product-availability.md
  docs/pbc/all/warehouse-management-system/202410.0/base-shop/manage-using-glue-api/glue-api-retrieve-subscriptions-to-availability-notifications.md
  docs/pbc/all/warehouse-management-system/202410.0/marketplace/glue-api-retrieve-product-offer-availability.md
  docs/pbc/all/warehouse-management-system/202410.0/marketplace/install-features/install-the-inventory-management-merchant-portal-marketplace-product-feature.md
  docs/pbc/all/warehouse-management-system/202410.0/marketplace/marketplace-inventory-management-feature-domain-model.md
  docs/pbc/all/warehouse-management-system/202410.0/marketplace/marketplace-inventory-management-feature-overview.md
  docs/pbc/all/warehouse-management-system/202410.0/unified-commerce/fulfillment-app-fulfill-orders.md
  docs/pbc/all/warehouse-management-system/202410.0/unified-commerce/fulfillment-app-overview.md
  docs/pbc/all/warehouse-management-system/202410.0/unified-commerce/install-and-upgrade/install-the-warehouse-picking-feature.md
  docs/pbc/all/warehouse-management-system/202410.0/unified-commerce/install-and-upgrade/install-the-warehouse-user-management-feature.md
  docs/pbc/all/warehouse-management-system/202410.0/unified-commerce/manage-using-glue-api/glue-api-authenticate-as-a-warehouse-user.md
  docs/pbc/all/warehouse-management-system/202410.0/unified-commerce/manage-using-glue-api/manage-picklists/glue-api-pick-picklist-items.md
  docs/pbc/all/warehouse-management-system/202410.0/unified-commerce/manage-using-glue-api/manage-picklists/glue-api-retrieve-picklists.md
  docs/pbc/all/warehouse-management-system/202410.0/unified-commerce/manage-using-glue-api/manage-picklists/glue-api-start-picking.md
  docs/pbc/all/warehouse-management-system/202410.0/unified-commerce/manage-using-glue-api/manage-warehouse-user-assignments/glue-api-create-warehouse-user-assignments.md
  docs/pbc/all/warehouse-management-system/202410.0/unified-commerce/manage-using-glue-api/manage-warehouse-user-assignments/glue-api-retrieve-warehouse-user-assignments.md
  docs/pbc/all/warehouse-management-system/202410.0/unified-commerce/manage-using-glue-api/manage-warehouse-user-assignments/glue-api-update-warehouse-user-assignments.md
  docs/pbc/all/warehouse-management-system/202410.0/unified-commerce/set-up-fulfillment-app.md
  docs/pbc/all/warehouse-management-system/202410.0/unified-commerce/warehouse-user-management-feature-overview.md
  docs/pbc/all/warehouse-management-system/202410.0/warehouse-management-system.md
Labels: TW review needed

#2987 DEV Migrate pt1 SEO Update
  docs/dg/dev/upgrade-and-migrate/migrate-from-auth-to-securitygui-module.md
  docs/dg/dev/upgrade-and-migrate/migrate-from-tslint-to-eslint.md
  docs/dg/dev/upgrade-and-migrate/migrate-from-yarn-to-npm.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-adapt-the-filesystem-based-features.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-add-frontend-assets.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-choose-a-multi-store-setup.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-finalize-the-migration.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-integrate-the-docker-sdk.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-migrate-database.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-migrate-non-standard-services.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-restore-es-and-redis.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-upgrade-the-php-version.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-wire-custom-services.md
Labels: TW review needed

#2989 DEV Migrate pt2 SEO update
  docs/dg/dev/upgrade-and-migrate/migrate-to-decoupled-glue-infrastructure/decoupled-glue-infrastructure-integrate-api-key-authorization.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-decoupled-glue-infrastructure/decoupled-glue-infrastructure-integrate-the-documentation-generator.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-docker/adjust-jenkins-for-a-docker-environment.md
  docs/dg/dev/upgrade-and-migrate/migrating-from-twig-v1-to-twig-v3.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/router/router.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-errorhandler-module.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-form-module.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-http-module.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-locale-module.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-messenger-module.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-propel-module.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-router-module.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-security-module.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-session-module.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-store-module.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-translator-module.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-twig-module.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-validator-module.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/upgrade-modules/upgrade-the-webprofiler-module.md
  docs/dg/dev/upgrade-and-migrate/upgrade-nodejs-to-v18-and-npm-to-v9.md
  docs/dg/dev/upgrade-and-migrate/upgrade-to-angular-12.md
  docs/dg/dev/upgrade-and-migrate/upgrade-to-angular-15.md
  docs/dg/dev/upgrade-and-migrate/upgrade-to-angular-17.md
  docs/dg/dev/upgrade-and-migrate/upgrade-to-stylelint-16-and-css-loader-6.md
  docs/dg/dev/upgrade-and-migrate/upgrade-to-symfony-6.md
  docs/dg/dev/upgrade-and-migrate/upgrade-to-webpack-v5.md
  docs/dg/dev/zed-api/integrate-zed-api/integrate-zed-api-for-merchant-relationships.md
  docs/dg/dev/zed-api/tutorial-using-zed-api.md
  docs/dg/dev/zed-api/zed-api-configuration.md
  docs/dg/dev/zed-api/zed-api-resources.md
  docs/dg/dev/zed-api/zed-api.md
Labels: TW review needed

#2991 DEV troubleshooting SEO Update
  docs/dg/dev/troubleshooting/troubleshooting-docker-issues/troubleshooting-debugging-in-docker/nc-command-does-not-give-any-output.md
  docs/dg/dev/troubleshooting/troubleshooting-docker-issues/troubleshooting-debugging-in-docker/nc-command-tells-that-the-port-is-opened.md
  docs/dg/dev/troubleshooting/troubleshooting-docker-issues/troubleshooting-debugging-in-docker/xdebug-does-not-work.md
  docs/dg/dev/troubleshooting/troubleshooting-docker-issues/troubleshooting-running-applications-in-docker/413-request-entity-too-large.md
  docs/dg/dev/troubleshooting/troubleshooting-docker-issues/troubleshooting-running-applications-in-docker/an-application-is-not-reachable-via-http.md
  docs/dg/dev/troubleshooting/troubleshooting-docker-issues/troubleshooting-running-applications-in-docker/mutagen-error.md
  docs/dg/dev/troubleshooting/troubleshooting-docker-issues/troubleshooting-running-applications-in-docker/mutagen-synchronization-issue.md
  docs/dg/dev/troubleshooting/troubleshooting-docker-issues/troubleshooting-running-applications-in-docker/port-is-already-occupied-on-host.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/composer-version-2-compatibility-issues.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/could-not-resolve-host-zed-calls-are-forbidden-from-zed.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/error-remove-spryker-logs-volume-is-in-use.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/fail-whale-on-the-frontend.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/no-data-on-the-storefront.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/phpstan-memory-issues.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/prices-filter-and-sorting-does-t-work-on-frontend.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/processtimedoutexception-after-queue-task-start.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/the-spy-oms-transition-log-table-takes-up-too-much-space.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-rabbitmq/troubleshooting-rabbitmq.md
  docs/dg/dev/troubleshooting/troubleshooting-performance-issues/external-calls-several-calls-to-zed.md
  docs/dg/dev/troubleshooting/troubleshooting-performance-issues/external-calls-take-a-lot-of-time.md
  docs/dg/dev/troubleshooting/troubleshooting-performance-issues/n+1-problem.md
  docs/dg/dev/troubleshooting/troubleshooting-performance-issues/not-optimised-composer-on-the-production-environment.md
  docs/dg/dev/troubleshooting/troubleshooting-performance-issues/slow-publish-and-synchronization.md
  docs/dg/dev/troubleshooting/troubleshooting-performance-issues/troubleshooting-performance-issues.md
  docs/dg/dev/troubleshooting/troubleshooting.md
  docs/dg/dev/updating-spryker/feature-or-module-updates.md
  docs/dg/dev/updating-spryker/installing-features-and-updating-modules.md
  docs/dg/dev/updating-spryker/planning-updates.md
  docs/dg/dev/updating-spryker/switch-demo-shop-version.md
  docs/dg/dev/updating-spryker/testing-updates.md
  docs/dg/dev/updating-spryker/troubleshooting-updates.md
Labels: TW review needed

#2993 Dev Set up Locally SEO Update
  _data/sidebars/pbc_all_sidebar.yml
  docs/about/all/releases/release-notes-202410.0.md
  docs/dg/dev/set-up-spryker-locally/configure-after-installing/configure-debugging/configure-debugging.md
  docs/dg/dev/set-up-spryker-locally/configure-after-installing/configure-debugging/set-up-xdebug-profiling.md
  docs/dg/dev/set-up-spryker-locally/configure-after-installing/configure-spryker-after-installing.md
  docs/dg/dev/set-up-spryker-locally/database-access-credentials.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install-docker-prerequisites/install-docker-prerequisites-on-windows-with-wsl1.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install-docker-prerequisites/install-docker-prerequisites-on-windows-with-wsl2.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install-docker-prerequisites/install-docker-prerequisites.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/choose-an-installation-mode.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-macos-and-linux.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-windows.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-macos-and-linux.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-windows.md
  docs/dg/dev/set-up-spryker-locally/manage-dependencies-with-composer.md
  docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-macos-and-linux.md
  docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-windows.md
  docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guides-install-spryker.md
  docs/dg/dev/set-up-spryker-locally/set-up-spryker-locally.md
  docs/dg/dev/set-up-spryker-locally/troubleshooting-installation/an-error-during-front-end-setup.md
  docs/dg/dev/set-up-spryker-locally/troubleshooting-installation/demo-data-was-imported-incorrectly.md
  docs/dg/dev/set-up-spryker-locally/troubleshooting-installation/docker-daemon-is-not-running.md
  docs/dg/dev/set-up-spryker-locally/troubleshooting-installation/docker-sync-cannot-start.md
  docs/dg/dev/set-up-spryker-locally/troubleshooting-installation/error-403-no-valid-crumb-was-included-in-the-request.md
  docs/dg/dev/set-up-spryker-locally/troubleshooting-installation/node-saas-does-not-yet-support-your-current-environment.md
  docs/dg/dev/set-up-spryker-locally/troubleshooting-installation/setup-of-new-indexes-throws-an-exception.md
  docs/dg/dev/set-up-spryker-locally/troubleshooting-installation/troubleshooting-installation.md
  docs/dg/dev/set-up-spryker-locally/troubleshooting-installation/vendor-folder-synchronization-error.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/stripe/project-guidelines-for-stripe/project-prerequisites-for-implementing-Stripe-checkout-as-a-hosted-payment-page.md
Labels: TW review needed

#2919 FRW-8550 Dynamic Multistore documentation.
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202410.0/install-dynamic-multistore.md
  docs/ca/dev/multi-store-setups/multistore-setup-options.md
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/dynamic-multistore-feature-overview.md
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/enable-dynamic-multistore.md
Labels: TW review needed, new

#2951 Create add-new-store-in-multi-db-setup.md
  docs/dg/dev/internationalization-and-multi-store/add-new-store-in-multi-db-setup.md
Labels: TW review needed
