Repository spryker/spryker-docs, pull requests merged in 2025-04, with the labels that each got.

#3068 CC-34826: Added Reorder and Order Amendment IGs.
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202410.0/install-the-product-bundles-cart-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-cart-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-multiple-carts-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-multiple-carts-reorder-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-order-amendment-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-order-management-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-product-bundles-cart-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-reorder-feature.md
  docs/pbc/all/order-management-system/202505.0/base-shop/install-and-upgrade/install-features/install-the-order-amendment-feature.md
  docs/pbc/all/order-management-system/202505.0/base-shop/order-amendment-feature-overview.md
Labels: TW review needed

#3085 CC-34508: Adjust Price behavior during Order Amendment.
  Rakefile
  _includes/pbc/all/install-features/202505.0/install-the-order-amendment-feature.md
Labels: TW review needed

#3087 Adjusted play book pitcture for migration from on-prem to paas based …
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud.md
Labels: TW review needed

#3090 Update opentelemetry-instrumentation.md
  _includes/pbc/all/install-features/202505.0/install-the-order-amendment-feature.md
  docs/ca/dev/monitoring/opentelemetry-instrumentation.md
Labels: small changes

#3079 FRW-10104 Fixed issues with OTel doc and added overview
  docs/ca/dev/monitoring/opentelemetry-instrumentation.md
Labels: Bypassed TW Review

#3014 Added project architecture sniffer docs
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/sdks/sdk/development-tools/project-architecture-sniffer.md
Labels: TW review needed, urgent, new

#3072 CC-34706 Agent assist marketplace
  _includes/pbc/all/install-features/202410.0/marketplace/install-the-merchant-portal-agent-assist-feature.md
Labels: TW review needed

#3067 Update create-and-configure-zed-tables.md
  docs/dg/dev/backend-development/zed-ui-tables/create-and-configure-zed-tables.md
Labels: TW review needed, small changes

#3098 Security release notes description fix
  docs/about/all/releases/security-release-notes-202412.0.md
Labels: TW review needed

#3082 Update connect-to-services-via-ssh.md
  docs/about/all/self-service-portal.md
  docs/ca/dev/access/connect-to-services-via-ssh.md
Labels: in TW review

#3104 CC-26244 [Performance] Quote is validated twice in Yves CartController
  _includes/pbc/all/install-features/202505.0/install-the-cart-feature.md
Labels: TW review needed, small changes

#3105 Removed User Centrics from ACP Dev page
  docs/dg/dev/acp/app-composition-platform.md
Labels: TW review needed

#3106 Update generate-access-keys.md
  docs/ca/dev/security/generate-access-keys.md
Labels: TW review needed

#3107 distribute ssp
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202505.0/install-self-service-portal.md
  _includes/pbc/all/install-features/202505.0/install-the-ssp-asset-management-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-ssp-dashboard-management-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-ssp-file-management-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-ssp-inquiry-management-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-ssp-service-management-feature.md
  docs/about/all/self-service-portal.md
  docs/pbc/all/self-service-portal/202505.0/self-service-portal.md
  docs/pbc/all/self-service-portal/202505.0/ssp-dashboard-management-feature-overview.md
  docs/pbc/all/self-service-portal/202505.0/ssp-inquiry-management-feature-overview.md
  docs/pbc/all/self-service-portal/202505.0/ssp-service-management-feature-overview.md
Labels: in TW review

#3097 B2B - accessibility improvements
  _data/sidebars/dg_dev_sidebar.yml
  _data/sidebars/pbc_all_sidebar.yml
  docs/dg/dev/integrate-and-configure/integrate-accessibility-improvements.md
  docs/dg/dev/integrate-and-configure/tutorial-integrate-accessiblity-improvements-into-b2b-demoshop.md
  docs/pbc/all/miscellaneous/202505.0/sitemap-feature-overview.md
Labels: TW review needed

#3109 CC-34508 Added missing plugins.
  _includes/pbc/all/install-features/202505.0/install-the-order-amendment-feature.md
  docs/about/all/about-the-docs/contribute-to-the-docs/edit-the-docs-locally.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/feature-overviews/multiple-carts-feature-overview.md
Labels: TW review needed

#3113 Update generate-access-keys.md
  docs/ca/dev/preparation-for-going-live.md
  docs/ca/dev/security/generate-access-keys.md
Labels: TW review needed

#3116 Added PHP version to Otel documentation
  docs/ca/dev/monitoring/spryker-monitoring-integration/opentelemetry-instrumentation.md
Labels: Bypassed TW Review

#3117 Performance optimization update
  docs/dg/dev/guidelines/performance-guidelines/general-performance-guidelines.md
Labels: TW review needed

#3102 Create semantic-versioning-zero-major-version.md
  .vale.ini
  _data/sidebars/dg_dev_sidebar.yml
  _data/sidebars/pbc_all_sidebar.yml
  docs/about/all/releases/release-notes-202404.0.md
  docs/about/all/spryker-marketplace/spryker-marketplace.md
  docs/about/all/support/support-case-escalations.md
  docs/about/all/support/understanding-slas.md
  docs/ca/dev/configure-deployment-pipelines/configure-gitlab-pipelines.md
  docs/ca/dev/monitoring/monitoring-issues-and-informing-about-alerts.md
  docs/ca/dev/performance-testing-in-staging-enivronments.md
  docs/ca/devscu/how-spryker-code-upgrader-works.md
  docs/dg/dev/architecture/conceptual-overview.md
  docs/dg/dev/architecture/module-api/module-api.md
  docs/dg/dev/architecture/module-api/semantic-versioning-major-vs.-minor-vs.-patch-release.md
  docs/dg/dev/architecture/module-api/semantic-versioning-zero-major-version.md
  docs/dg/dev/backend-development/client/client.md
  docs/dg/dev/backend-development/cronjobs/optimizing-jenkins-execution.md
  docs/dg/dev/backend-development/data-manipulation/data-publishing/debug-listeners.md
  docs/dg/dev/backend-development/yves/implementing-widgets-and-widget-plugins.md
  docs/dg/dev/backend-development/yves/modular-frontend.md
  docs/dg/dev/best-practices/non-functional-requirement-templates/monitorable-process-guidelines.md
  docs/dg/dev/code-contribution-guide.md
  docs/dg/dev/data-import/202410.0/importing-data-with-the-queue-data-importer.md
  docs/dg/dev/glue-api/202410.0/old-glue-infrastructure/glue-rest-api.md
  docs/dg/dev/guidelines/testing-guidelines/testing-best-practices/testing-concepts.md
  docs/dg/dev/integrate-and-configure/configure-dynamic-yves-zed-tokens.md
  docs/dg/dev/integrate-and-configure/forcing-https.md
  docs/dg/dev/sdks/sdk/customization-strategies-and-upgradability.md
  docs/dg/dev/sdks/the-docker-sdk/choosing-a-docker-sdk-version.md
  docs/dg/dev/sdks/the-docker-sdk/choosing-a-mount-mode.md
  docs/dg/dev/sdks/the-docker-sdk/docker-sdk-quick-start-guide.md
  docs/dg/dev/sdks/the-docker-sdk/running-tests-with-the-docker-sdk.md
  docs/dg/dev/sdks/the-docker-sdk/update-the-docker-sdk.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/choose-an-installation-mode.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/container.md
  docs/dg/dev/upgrade-and-migrate/silex-replacement/silex-replacement.md
  docs/pbc/all/data-exchange/202404.0/data-exchange-faq.md
  docs/pbc/all/data-exchange/202410.0/data-exchange-faq.md
  docs/pbc/all/data-exchange/202410.0/data-exchange.md
  docs/pbc/all/miscellaneous/202410.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/exporting-product-data-for-fact-finder.md
  docs/pbc/all/order-management-system/202410.0/base-shop/order-management-feature-overview/oms-order-management-system-matrix.md
  docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/econda/export-econda-data.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/connect-vertex.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/project-configuration-for-vertex.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/vertex-faq.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/vertex.md
  vale/styles/Spryker/NoQuestionInHeadings.yml
Labels: TW review needed, new

#3112 CC-34245 Bootsrtap 5 migration guide
  _data/sidebars/pbc_all_sidebar.yml
  docs/pbc/all/back-office/202410.0/base-shop/install-and-upgrade/upgrade-the-back-office-to-bootstrap-5.md
  docs/pbc/all/data-exchange/202311.0/data-exchange-faq.md
Labels: TW review needed

#3118 FRW-10298: Added section for redis compression
  docs/dg/dev/set-up-spryker-locally/redis-configuration.md
Labels: TW review needed
