Repository spryker/spryker-docs, pull requests merged in 2025-06, with the labels that each got.

#3154 Fixing table format for the new store config
  docs/dg/dev/internationalization-and-multi-store/adding-stores-in-a-multi-database-setup.md
Labels: updated, small changes, Bypassed TW Review

#3159 fix bazaarvoice links
  docs/pbc/all/ratings-reviews/202311.0/third-party-integrations/bazaarvoice.md
  docs/pbc/all/ratings-reviews/202311.0/third-party-integrations/configure-bazaarvoice.md
  docs/pbc/all/ratings-reviews/202404.0/third-party-integrations/bazaarvoice.md
  docs/pbc/all/ratings-reviews/202404.0/third-party-integrations/configure-bazaarvoice.md
  docs/pbc/all/ratings-reviews/202410.0/third-party-integrations/bazaarvoice.md
  docs/pbc/all/ratings-reviews/202410.0/third-party-integrations/configure-bazaarvoice.md
Labels: updated, small changes, Bypassed TW Review

#3161 SUPESC-971: Fixed min php version for upgrader
  docs/ca/devscu/prepare-a-project-for-spryker-code-upgrader.md
Labels: TW review needed, small changes

#3158 FRW-10439: Adjusted documentation to include Twig warm-up
  docs/dg/dev/backend-development/console-commands/console-commands.md
  docs/dg/dev/guidelines/performance-guidelines/general-performance-guidelines.md
Labels: updated, Bypassed TW Review

#3151 SUPESC-899 Svg sprite asset generation integration
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/guidelines/performance-guidelines/general-performance-guidelines.md
  docs/dg/dev/integrate-and-configure/integrate-automated-svg-sprite-extraction.md
Labels: TW review needed

#3157 Update set-up-a-self-signed-ssl-certificate with updated date
  Rakefile
  docs/dg/dev/set-up-spryker-locally/configure-after-installing/set-up-a-self-signed-ssl-certificate.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/billpay/billpay-switch-invoice-payments-to-a-preauthorize-mode.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/powerpay.md
Labels: TW review needed

#3163 Update dynamic-cart-overview.md
  docs/pbc/all/cart-and-checkout/202505.0/base-shop/feature-overviews/cart-feature-overview/dynamic-cart-overview.md
Labels: TW review needed

#3173 Update the reporting-and-handling-security-issues page
  _drafts/deprecated-devvm/troubleshooting-spryker-in-vagrant-issues/troubleshooting-spryker-in-vagrant-installation-issues.md
  docs/about/all/support/reporting-and-handling-security-issues.md
  docs/ca/dev/connect-a-code-repository.md
  docs/ca/dev/create-and-restore-database-backups.md
  docs/ca/dev/getting-started-with-cloud-administration.md
  docs/ca/dev/security/generate-access-keys.md
  docs/ca/dev/security/multi-factor-authentication-and-passwords.md
  docs/ca/dev/set-up-a-custom-domain-name/set-up-a-custom-domain-name-with-route-53.md
  docs/ca/dev/setting-up-a-custom-ssl-certificate.md
  docs/ca/devscu/prepare-a-project-for-spryker-code-upgrader.md
  docs/ca/devscu/troubleshooting/a-php-extension-is-missing-from-your-system.md
  docs/ca/devscu/troubleshooting/the-process-exceeded-the-timeout.md
  docs/ca/devscu/troubleshooting/transportexception-cannot-move-pack.md
  docs/ca/devscu/troubleshooting/you-have-an-unprocessed-pr-from-a-previous-update.md
  docs/dg/dev/code-contribution-guide.md
  docs/dg/dev/guidelines/performance-guidelines/general-performance-guidelines.md
  docs/dg/dev/troubleshooting/troubleshooting-docker-issues/troubleshooting-docker-issues.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-general-technical-issues.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-rabbitmq/messages-are-moved-to-error-queues.md
  docs/dg/dev/troubleshooting/troubleshooting.md
  docs/dg/dev/updating-spryker/troubleshooting-updates.md
  docs/pbc/all/miscellaneous/202311.0/third-party-integrations/operational-tools-monitoring-legal/loggly/configure-loggly.md
  docs/pbc/all/miscellaneous/202404.0/third-party-integrations/operational-tools-monitoring-legal/loggly/configure-loggly.md
  docs/pbc/all/miscellaneous/202410.0/third-party-integrations/operational-tools-monitoring-legal/loggly/configure-loggly.md
  docs/pbc/all/order-management-system/202311.0/base-shop/datapayload-conversion/state-machine/common-pitfalls-in-oms-design.md
  docs/pbc/all/order-management-system/202404.0/base-shop/datapayload-conversion/state-machine/common-pitfalls-in-oms-design.md
  docs/pbc/all/order-management-system/202410.0/base-shop/datapayload-conversion/state-machine/common-pitfalls-in-oms-design.md
  docs/pbc/all/order-management-system/202505.0/base-shop/order-amendment-feature-overview.md
  docs/pbc/all/search/202311.0/base-shop/third-party-integrations/algolia/getting-access-to-algolia-dashboard.md
  docs/pbc/all/search/202404.0/base-shop/third-party-integrations/algolia/getting-access-to-algolia-dashboard.md
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/getting-access-to-algolia-dashboard.md
  docs/pbc/all/search/202410.0/base-shop/tutorials-and-howtos/configure-elasticsearch.md
Labels: ready for merge, TW review needed

#3175 FRW-10389 Adjusted redis doc.
  docs/dg/dev/set-up-spryker-locally/redis-configuration.md
Labels: TW review needed

#3174 SSP-1226: Update of the Self Service Portal IGs.
  Rakefile
  _includes/pbc/all/install-features/202505.0/install-the-ssp-asset-management-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-ssp-dashboard-management-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-ssp-file-management-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-ssp-inquiry-management-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-ssp-service-management-feature.md
  docs/pbc/all/self-service-portal/202505.0/self-service-portal.md
Labels: TW review needed, updated

#3179 CC-35703, CC-35700 customer discounts IG.
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202505.0/install-the-customer-account-management-promotions-and-discounts-feature.md
  docs/pbc/all/customer-relationship-management/202505.0/base-shop/install-and-upgrade/install-features/install-the-customer-account-management-promotions-and-discounts-feature.md
  docs/pbc/all/order-management-system/202505.0/base-shop/install-and-upgrade/install-features/install-the-reorder-feature.md
Labels: TW review needed, new

#3186 FRW-10455: Added information how to enable StorageGui module
  docs/dg/dev/set-up-spryker-locally/redis-configuration.md
Labels: TW review needed, small changes

#3189 CC-34706: Added FE related docs for agent assist mode at MP
  _includes/pbc/all/install-features/202410.0/marketplace/install-the-merchant-portal-agent-assist-feature.md
Labels: TW review needed
