Repository spryker/spryker-docs, pull requests merged in 2025-07, with the labels that each got.

#3164 FRW-9500 Multi-Factor Authentication for Backoffice and Agent Storefront.
  .vale.ini
  _data/sidebars/pbc_all_sidebar.yml
  _drafts/drafts-dev/roadmap.md
  _includes/pbc/all/install-features/202311.0/install-the-cms-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-cms-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-company-account-order-management-feature.md
  _includes/pbc/all/install-features/202410.0/marketplace/install-marketplace-shipment-feature.md
  _includes/scos/user/intro-to-spryker/releases/release-notes/release-notes-202212.0/patch-release-notes-202212.0.md
  docs/about/all/releases/security-releases/security-release-notes-202312.0.md
  docs/about/all/releases/security-releases/security-release-notes-202403.0.md
  docs/ca/dev/environment-scaling.md
  docs/dg/dev/architecture/architectural-convention.md
  docs/dg/dev/glue-api/202410.0/decoupled-glue-api.md
  docs/dg/dev/integrate-and-configure/integrate-separate-endpoint-bootstraps.md
  docs/dg/dev/sdks/the-docker-sdk/deploy-file/deploy-file-reference.md
  docs/dg/dev/troubleshooting/troubleshooting-docker-issues/troubleshooting-running-applications-in-docker/an-application-is-not-reachable-via-http.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-adapt-the-filesystem-based-features.md
  docs/pbc/all/back-office/202505.0/base-shop/install-and-upgrade/install-back-office-dropdown-navigation.md
  docs/pbc/all/multi-factor-authentication/202505.0/create-multi-factor-authentication-methods.md
  docs/pbc/all/multi-factor-authentication/202505.0/install-customer-email-multi-factor-authentication-method.md
  docs/pbc/all/multi-factor-authentication/202505.0/install-email-multi-factor-authentication-method.md
  docs/pbc/all/multi-factor-authentication/202505.0/install-multi-factor-authentication-feature.md
  docs/pbc/all/multi-factor-authentication/202505.0/manage-using-glue-api/glue-api-activate-and-deactivate-mfa.md
  docs/pbc/all/multi-factor-authentication/202505.0/manage-using-glue-api/glue-api-authenticate-through-mfa.md
  docs/pbc/all/multi-factor-authentication/202505.0/manage-using-glue-api/glue-api-retrieve-mfa-methods.md
  docs/pbc/all/multi-factor-authentication/202505.0/manage-using-glue-api/manage-multi-factor-authentication-using-glue-api.md
  docs/pbc/all/multi-factor-authentication/202505.0/multi-factor-authentication.md
  docs/pbc/all/price-management/202410.0/marketplace/domain-model-and-relationships/marketplace-product-offer-prices-feature-domain-model-and-relationships.md
  docs/pbc/all/product-information-management/202410.0/marketplace/domain-model-and-relationships/marketplace-product-options-feature-domain-model-and-relationships.md
  docs/pbc/all/return-management/202311.0/marketplace/marketplace-return-management-feature-domain-model-and-relationships.md
  docs/pbc/all/return-management/202404.0/marketplace/marketplace-return-management-feature-domain-model-and-relationships.md
  docs/pbc/all/return-management/202410.0/marketplace/marketplace-return-management-feature-domain-model-and-relationships.md
  vale/styles/terms/BackOffice.yml
Labels: TW review needed, in tech review, updated

#3190 SUPESC-891 Added troublshooting page to resolve session locking issue…
  _data/sidebars/dg_dev_sidebar.yml
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/latest/enable-gift-cards.md
  _includes/pbc/all/install-features/latest/enable-the-content-widget.md
  _includes/pbc/all/install-features/latest/install-dynamic-multistore-the-availability-notification-feature.md
  _includes/pbc/all/install-features/latest/install-dynamic-multistore-the-cart-feature.md
  _includes/pbc/all/install-features/latest/install-dynamic-multistore-the-customer-account-management-feature.md
  _includes/pbc/all/install-features/latest/install-dynamic-multistore-the-prices-feature.md
  _includes/pbc/all/install-features/latest/install-dynamic-multistore-the-product-feature.md
  _includes/pbc/all/install-features/latest/install-microsoft-azure-active-directory.md
  _includes/pbc/all/install-features/latest/install-multiple-abstract-products-as-promotional-products-and-discounts-feature.md
  _includes/pbc/all/install-features/latest/install-the-spryker-core-feature0.md
  _includes/pbc/all/install-features/latest/marketplace/install-marketplace-shipment-feature.md
  _scripts/sidebar_checker/sidebar_checker.sh
  docs/about/all/self-service-portal.md
  docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-failing-yves-authentication.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/session-locking-issues.md
  docs/dg/dev/troubleshooting/troubleshooting-general-technical-issues/troubleshooting-general-technical-issues.md
  docs/pbc/all/back-office/latest/base-shop/install-and-upgrade/install-back-office-dropdown-navigation.md
  docs/pbc/all/back-office/latest/base-shop/install-and-upgrade/install-the-spryker-core-back-office-comments-feature.md
  docs/pbc/all/multi-factor-authentication/latest/create-multi-factor-authentication-methods.md
  docs/pbc/all/multi-factor-authentication/latest/install-email-multi-factor-authentication-method.md
  docs/pbc/all/multi-factor-authentication/latest/install-multi-factor-authentication-feature.md
  docs/pbc/all/multi-factor-authentication/latest/manage-using-glue-api/glue-api-activate-and-deactivate-mfa.md
  docs/pbc/all/multi-factor-authentication/latest/manage-using-glue-api/glue-api-authenticate-through-mfa.md
  docs/pbc/all/multi-factor-authentication/latest/manage-using-glue-api/glue-api-retrieve-mfa-methods.md
  docs/pbc/all/multi-factor-authentication/latest/manage-using-glue-api/manage-multi-factor-authentication-using-glue-api.md
  docs/pbc/all/multi-factor-authentication/latest/multi-factor-authentication.md
  docs/pbc/all/product-information-management/latest/base-shop/feature-overviews/category-management-feature-overview.md
Labels: tech review needed, TW review needed, new

#3181 Batch Processing Traits in Propel ORM
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/architecture/technology-stack.md
  docs/dg/dev/backend-development/client/use-and-configure-redis-or-valkey-as-a-key-value-store.md
  docs/dg/dev/guidelines/performance-guidelines/general-performance-guidelines.md
  docs/dg/dev/guidelines/performance-guidelines/performance-guidelines-batch-processing-propel-entities.md
Labels: TW review needed

#3191 Update install-the-mailing-and-notifications-feature.md
  docs/dg/dev/glue-api/latest/glue-api-tutorials/document-glue-api-resources.md
  docs/pbc/all/emails/202410.0/install-the-mailing-and-notifications-feature.md
  docs/pbc/all/emails/latest/install-the-mailing-and-notifications-feature.md
Labels: tech review needed, TW review needed

#3219 ACP-5302: Added missing and adjusted incorrect ACP installation steps
  _data/sidebars/about_all_sidebar.yml
  docs/about/all/releases/release-notes-202507.0.md
  docs/dg/dev/acp/install-prerequisites-and-enable-acp.md
  docs/dg/dev/acp/receive-acp-messages.md
Labels: TW review needed

#3226 CC-35690 Adjusted Quicksight IG.
  _includes/pbc/all/install-features/latest/install-self-service-portal.md
  _includes/pbc/all/install-features/latest/install-the-ssp-asset-management-feature.md
  _includes/pbc/all/install-features/latest/install-the-ssp-dashboard-management-feature.md
  _includes/pbc/all/install-features/latest/install-the-ssp-file-management-feature.md
  _includes/pbc/all/install-features/latest/install-the-ssp-inquiry-management-feature.md
  _includes/pbc/all/install-features/latest/install-the-ssp-service-management-feature.md
  docs/about/all/self-service-portal.md
  docs/dg/dev/acp/app-composition-platform.md
  docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/install-amazon-quicksight.md
  docs/pbc/all/self-service-portal/latest/self-service-portal.md
  docs/pbc/all/self-service-portal/latest/ssp-asset-management-feature-overview.md
  docs/pbc/all/self-service-portal/latest/ssp-dashboard-management-feature-overview.md
  docs/pbc/all/self-service-portal/latest/ssp-file-management-feature-overview.md
  docs/pbc/all/self-service-portal/latest/ssp-inquiry-management-feature-overview.md
  docs/pbc/all/self-service-portal/latest/ssp-service-management-feature-overview.md
Labels: TW review needed, updated
