Repository spryker/spryker-docs, pull requests merged in 2025-01, with the labels that each got.

#2996 CC-34976 Product offer discount IG
  Rakefile
  _config.yml
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202505.0/marketplace/install-the-marketplace-product-offer-promotions-and-discounts-feature.md
  docs/pbc/all/dynamic-multistore/202410.0/base-shop/enable-dynamic-multistore.md
  docs/pbc/all/offer-management/202505.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-product-offer-promotions-and-discounts-feature.md
Labels: TW review needed, in tech review, new

#2990 CC-34932 Add Merchant Promotions & Discount feature IG
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202505.0/marketplace/install-the-marketplace-merchant-promotions-and-discounts-feature.md
  docs/about/all/about-the-docs/contribute-to-the-docs/install-recommended-vs-code-extensions.md
  docs/ca/dev/access/connect-to-services-via-ssh.md
  docs/ca/dev/getting-started-with-cloud-administration.md
  docs/pbc/all/merchant-management/202505.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-promotions-and-discounts-feature.md
  docs/pbc/all/miscellaneous/202410.0/third-party-integrations/operational-tools-monitoring-legal/data-virtuality.md
Labels: TW review needed, new, 202400

#2998 Update configure-elasticsearch.md
  _includes/checking-elasticsearch-indices-via-a-cli.md
  _includes/checking-elasticsearch-status-via-aws-management-console.md
  _includes/pbc/all/install-features/202410.0/install-the-product-feature.md
  _includes/pbc/all/upgrade-modules/upgrade-the-productpagesearch-module.md
  docs/ca/dev/create-and-restore-database-backups.md
  docs/ca/dev/monitoring-issues-and-informing-about-alerts.md
  docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-an-unavailable-zed.md
  docs/ca/dev/troubleshooting/troubleshooting-tutorials/tutorial-troubleshooting-unavailable-yves-or-glue.md
  docs/dg/dev/backend-development/data-manipulation/data-publishing/implement-synchronization-plugins.md
  docs/dg/dev/development-getting-started-guide.md
  docs/dg/dev/integrate-and-configure/configure-services.md
  docs/dg/dev/upgrade-and-migrate/migrate-to-cloud/migrate-to-cloud-migrate-non-standard-services.md
  docs/pbc/all/content-management-system/202311.0/base-shop/tutorials-and-howtos/create-a-custom-content-item.md
  docs/pbc/all/content-management-system/202404.0/base-shop/tutorials-and-howtos/create-a-custom-content-item.md
  docs/pbc/all/content-management-system/202410.0/base-shop/tutorials-and-howtos/create-a-custom-content-item.md
  docs/pbc/all/miscellaneous/202311.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/installing-and-configuring-the-fact-finder-ng-api.md
  docs/pbc/all/miscellaneous/202404.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/installing-and-configuring-the-fact-finder-ng-api.md
  docs/pbc/all/miscellaneous/202410.0/third-party-integrations/marketing-and-conversion/analytics/fact-finder/installing-and-configuring-the-fact-finder-ng-api.md
  docs/pbc/all/price-management/202311.0/base-shop/tutorials-and-howtos/handle-twenty-five-million-prices-in-spryker-commerce-os.md
  docs/pbc/all/price-management/202404.0/base-shop/tutorials-and-howtos/handle-twenty-five-million-prices-in-spryker-commerce-os.md
  docs/pbc/all/price-management/202410.0/base-shop/tutorials-and-howtos/handle-twenty-five-million-prices-in-spryker-commerce-os.md
  docs/pbc/all/search/202410.0/base-shop/tutorials-and-howtos/configure-elasticsearch.md
Labels: TW review needed

#2976 PBC Search SEO Update
  .github/PULL_REQUEST_TEMPLATE.md
  docs/dg/dev/internationalization-and-multi-store/add-new-store-in-multi-db-setup.md
  docs/pbc/all/search/202410.0/base-shop/best-practices/personalization-dynamic-pricing.md
  docs/pbc/all/search/202410.0/base-shop/best-practices/precise-search-by-super-attributes.md
  docs/pbc/all/search/202410.0/base-shop/best-practices/search-best-practices.md
  docs/pbc/all/search/202410.0/base-shop/import-and-export-data/import-file-details-product-search-attribute-map.csv.md
  docs/pbc/all/search/202410.0/base-shop/import-and-export-data/import-file-details-product-search-attribute.csv.md
  docs/pbc/all/search/202410.0/base-shop/import-and-export-data/search-data-import.md
  docs/pbc/all/search/202410.0/base-shop/install-and-upgrade/install-features-and-glue-api/install-the-catalog-category-management-feature.md
  docs/pbc/all/search/202410.0/base-shop/install-and-upgrade/install-features-and-glue-api/install-the-catalog-glue-api.md
  docs/pbc/all/search/202410.0/base-shop/install-and-upgrade/install-features-and-glue-api/install-the-search-widget-for-concrete-products.md
  docs/pbc/all/search/202410.0/base-shop/install-and-upgrade/search-migration-concept.md
  docs/pbc/all/search/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-categorypagesearch-module.md
  docs/pbc/all/search/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-cmspagesearch-module.md
  docs/pbc/all/search/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-elastica-module.md
  docs/pbc/all/search/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-productlabelsearch-module.md
  docs/pbc/all/search/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-productpagesearch-module.md
  docs/pbc/all/search/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-productreviewsearch-module.md
  docs/pbc/all/search/202410.0/base-shop/install-and-upgrade/upgrade-modules/upgrade-the-productsetpagesearch-module.md
  docs/pbc/all/search/202410.0/base-shop/manage-in-the-back-office/best-practices-promote-products-with-search-preferences.md
  docs/pbc/all/search/202410.0/base-shop/manage-in-the-back-office/category-filters/reorder-category-filters.md
  docs/pbc/all/search/202410.0/base-shop/manage-in-the-back-office/define-search-preferences.md
  docs/pbc/all/search/202410.0/base-shop/manage-in-the-back-office/edit-search-preferences.md
  docs/pbc/all/search/202410.0/base-shop/manage-in-the-back-office/filter-preferences/edit-filter-preferences.md
  docs/pbc/all/search/202410.0/base-shop/manage-in-the-back-office/filter-preferences/reorder-filter-preferences.md
  docs/pbc/all/search/202410.0/base-shop/manage-in-the-back-office/manage-filters-and-search-preferences-in-the-back-office.md
  docs/pbc/all/search/202410.0/base-shop/search-feature-overview/search-feature-overview.md
  docs/pbc/all/search/202410.0/base-shop/search-feature-overview/search-types-overview.md
  docs/pbc/all/search/202410.0/base-shop/search-feature-overview/standard-filters-overview.md
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/configure-algolia.md
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/disconnect-algolia.md
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/getting-access-to-algolia-dashboard.md
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
  docs/pbc/all/search/202410.0/base-shop/tutorials-and-howtos/configure-a-search-query.md
  docs/pbc/all/search/202410.0/base-shop/tutorials-and-howtos/configure-search-for-multi-currency.md
  docs/pbc/all/search/202410.0/base-shop/tutorials-and-howtos/expand-search-data.md
  docs/pbc/all/search/202410.0/base-shop/tutorials-and-howtos/facet-filter-overview-and-configuration.md
  docs/pbc/all/search/202410.0/marketplace/glue-api-search-the-product-catalog.md
  docs/pbc/all/search/202410.0/search.md
Labels: TW review needed

#2995 DEV Integrate SEO Update
  Rakefile
  docs/dg/dev/architecture/tutorial-architectural-walkthrough.md
  docs/dg/dev/integrate-and-configure/Integrate-profiler-module.md
  docs/dg/dev/integrate-and-configure/configure-database-connections.md
  docs/dg/dev/integrate-and-configure/configure-queue-worker-signal-handling.md
  docs/dg/dev/integrate-and-configure/configure-services.md
  docs/dg/dev/integrate-and-configure/forcing-https.md
  docs/dg/dev/integrate-and-configure/integrate-and-configure.md
  docs/dg/dev/integrate-and-configure/integrate-authorization-enabler.md
  docs/dg/dev/integrate-and-configure/integrate-cms-block-widgets.md
  docs/dg/dev/integrate-and-configure/integrate-custom-location-for-static-assets.md
  docs/dg/dev/integrate-and-configure/integrate-development-tools/integrate-development-tools.md
  docs/dg/dev/integrate-and-configure/integrate-development-tools/integrate-formatter.md
  docs/dg/dev/integrate-and-configure/integrate-development-tools/integrate-scss-linter.md
  docs/dg/dev/integrate-and-configure/integrate-development-tools/integrate-ts-linter.md
  docs/dg/dev/integrate-and-configure/integrate-development-tools/integrate-web-profiler-for-zed.md
  docs/dg/dev/integrate-and-configure/integrate-development-tools/integrate-web-profiler-widget-for-yves.md
  docs/dg/dev/integrate-and-configure/integrate-elastic-computing.md
  docs/dg/dev/integrate-and-configure/integrate-multi-database-logic.md
  docs/dg/dev/integrate-and-configure/integrate-multi-queue-publish-structure.md
  docs/dg/dev/integrate-and-configure/integrate-propel-clean-command.md
  docs/dg/dev/integrate-and-configure/integrate-separate-endpoint-bootstraps.md
  docs/dg/dev/integrate-and-configure/remove-the-support-of-ie11.md
  docs/dg/dev/integrate-and-configure/switch-to-a-case-sensitive-file-system-on-mac-os.md
  docs/dg/dev/integrate-and-configure/switch-to-arm-architecture-m1-chip.md
  docs/dg/dev/integrate-and-configure/twig-and-twigextension.md
  docs/dg/dev/internationalization-and-multi-store/set-up-multiple-stores.md
  docs/dg/dev/miscellaneous-guides/using-database-transaction.md
  docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/amazon-quicksight.md
  robots.txt
Labels: TW review needed

#3019 SUPESC-930: Updated doc to use json value without whitespaces.
  docs/ca/devscu/configure-spryker-code-upgrader.md
Labels: TW review needed, small changes

#3016 Update environment-scaling.md
  docs/ca/dev/environment-scaling.md
Labels: TW review needed

#3018 Update getting-the-most-out-of-spryker-support.md
  docs/about/all/support/getting-the-most-out-of-spryker-support.md
Labels: TW review needed

#3004 CI Build Error Fixes
  docs/about/all/support/general-product-safety-regulation.md
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/integrate-algolia-personalization.md
Labels: TW review needed

#3005 Update common-pitfalls-in-oms-design.md
  docs/pbc/all/order-management-system/202410.0/base-shop/datapayload-conversion/state-machine/common-pitfalls-in-oms-design.md
Labels: TW review needed

#2999 DEV Guidelines Pt1 SEO Update
  docs/dg/dev/guidelines/module-configuration-convention.md
  docs/dg/dev/guidelines/performance-guidelines/architecture-performance-guidelines.md
  docs/dg/dev/guidelines/performance-guidelines/elastic-computing/new-relic-transaction-grouping-by-queue-names.md
  docs/dg/dev/guidelines/performance-guidelines/elastic-computing/ram-aware-batch-processing.md
  docs/dg/dev/guidelines/performance-guidelines/elastic-computing/storage-caching-for-primary-replica-db-setups.md
  docs/dg/dev/guidelines/performance-guidelines/front-end-performance-guidelines.md
  docs/dg/dev/guidelines/performance-guidelines/general-performance-guidelines.md
  docs/dg/dev/guidelines/performance-guidelines/performance-guidelines.md
  docs/dg/dev/guidelines/security-guidelines.md
  docs/dg/dev/guidelines/testing-guidelines/code-coverage.md
  docs/dg/dev/guidelines/testing-guidelines/data-builders.md
  docs/dg/dev/guidelines/testing-guidelines/executing-tests/execute-tests.md
  docs/dg/dev/guidelines/testing-guidelines/executing-tests/test-console-commands.md
  docs/dg/dev/guidelines/testing-guidelines/executing-tests/test-glue-api.md
  docs/dg/dev/guidelines/testing-guidelines/executing-tests/test-glue-backend-api.md
  docs/dg/dev/guidelines/testing-guidelines/executing-tests/test-the-asynchronous-api.md
  docs/dg/dev/guidelines/testing-guidelines/executing-tests/testing-the-publish-and-synchronization-process.md
  docs/dg/dev/guidelines/testing-guidelines/running-tests-with-robot-framework.md
  docs/dg/dev/guidelines/testing-guidelines/setting-up-tests.md
  docs/dg/dev/guidelines/testing-guidelines/test-framework.md
  docs/dg/dev/guidelines/testing-guidelines/test-helpers/test-helpers-best-practices.md
  docs/dg/dev/guidelines/testing-guidelines/test-helpers/test-helpers.md
  docs/dg/dev/guidelines/testing-guidelines/test-helpers/using-test-helpers.md
  docs/dg/dev/guidelines/testing-guidelines/testify.md
  docs/dg/dev/guidelines/testing-guidelines/testing-best-practices/best-practices-for-effective-testing.md
  docs/dg/dev/guidelines/testing-guidelines/testing-best-practices/testing-best-practices.md
  docs/dg/dev/guidelines/testing-guidelines/testing-best-practices/testing-concepts.md
  docs/dg/dev/guidelines/testing-guidelines/testing-guidelines.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-macos-and-linux.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-demo-mode-on-windows.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-macos-and-linux.md
  docs/dg/dev/set-up-spryker-locally/install-spryker/install/install-in-development-mode-on-windows.md
  docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-macos-and-linux.md
  docs/dg/dev/set-up-spryker-locally/quickstart-guides-install-spryker/quickstart-guide-install-spryker-on-windows.md
Labels: TW review needed

#3015 ACP-4656 Added Payment History description for SalesPaymentDetails.
  docs/pbc/all/payment-service-provider/202410.0/base-shop/retrieve-and-use-payment-details-from-third-party-psps.md
Labels: TW review needed

#3001 Dev Guidelines Pt2 SEO Update
  docs/dg/dev/architecture/tutorial-architectural-walkthrough.md
  docs/dg/dev/guidelines/coding-guidelines/code-architecture-guide.md
  docs/dg/dev/guidelines/coding-guidelines/code-quality.md
  docs/dg/dev/guidelines/coding-guidelines/code-style-guide.md
  docs/dg/dev/guidelines/coding-guidelines/coding-guidelines.md
  docs/dg/dev/guidelines/coding-guidelines/secure-coding-practices-for-external-packages.md
  docs/dg/dev/guidelines/coding-guidelines/secure-coding-practices.md
  docs/dg/dev/guidelines/data-processing-guidelines.md
  docs/dg/dev/guidelines/guidelines.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/extension-scenarios/event-subscribers-registration.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/extension-scenarios/modules-configuration.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/extension-scenarios/plugins-registration.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/ignore-evaluation-errors.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/keeping-a-project-upgradable.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/run-the-evaluator-tool.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/additional-logic-in-dependency-provider.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/container-set-function.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/dead-code-checker.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/discouraged-packages-checker.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/minimum-allowed-shop-version.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/multidimensional-array.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/npm-checker.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/open-source-vulnerabilities.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/php-version.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/plugin-registration-with-restrintions.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/single-plugin-argument.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/spryker-dev-packages-checker.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/spryker-security-checker.md
  docs/dg/dev/guidelines/keeping-a-project-upgradable/upgradability-guidelines/upgradability-guidelines.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/feature-overviews/checkout-feature-overview/multi-step-checkout-overview.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/feature-overviews/comments-feature-overview.md
  docs/pbc/all/cart-and-checkout/202410.0/base-shop/feature-overviews/shared-carts-feature-overview.md
  docs/pbc/all/content-management-system/202410.0/base-shop/manage-in-the-back-office/content-items/create-banner-content-items.md
  docs/pbc/all/customer-relationship-management/202410.0/base-shop/company-account-feature-overview/company-user-roles-and-permissions-overview.md
Labels: TW review needed

#2982 Added Decoupling of Checkout endpoint and OMS commands to architectur…
  Rakefile
  docs/dg/dev/guidelines/performance-guidelines/architecture-performance-guidelines.md
  docs/pbc/all/order-management-system/202410.0/base-shop/datapayload-conversion/state-machine/common-pitfalls-in-oms-design.md
Labels: TW review needed, updated

#3022 Update environment-scaling.md
  docs/ca/dev/environment-scaling.md
Labels: TW review needed

#112 BO-2260: Added IG for merchant portal forgot password functionality.
  _data/sidebars/pbc_all_sidebar.yml
  _includes/pbc/all/install-features/202410.0/marketplace/install-the-marketplace-merchant-portal-core-cms-feature.md
  _includes/pbc/all/install-features/202410.0/marketplace/install-the-marketplace-merchant-portal-core-feature.md
  docs/pbc/all/merchant-management/202410.0/marketplace/install-and-upgrade/install-features/install-the-marketplace-merchant-portal-core-cms-feature.md
Labels: TW review needed

#3023 CC-20504 Fixed SQL Exception when opening the Quote Products dataset.
  docs/pbc/all/business-intelligence/202410.0/amazon-quicksight-third-party-integration/install-amazon-quicksight.md
Labels: TW review needed, updated

#2985 improved phpstan.md article
  docs/dg/dev/sdks/sdk/development-tools/phpstan.md
Labels: TW review needed, updated

#2839 Update upgrade-the-price-module.md
  _includes/pbc/all/upgrade-modules/upgrade-the-price-module.md
  docs/pbc/all/product-information-management/202404.0/marketplace/manage-in-the-merchant-portal/concrete-products/edit-marketplace-concrete-products.md
Labels: TW review needed, small changes

#3029 Update access-the-aws-management-console.md
  docs/ca/dev/access/access-the-aws-management-console.md
  docs/pbc/all/product-relationship-management/202410.0/third-party-integrations/econda/integrate-econda-cross-selling.md
Labels: TW review needed

#3031 Update preparation-for-going-live.md
  docs/ca/dev/preparation-for-going-live.md
Labels: TW review needed

#3027 Update best-practices-for-effective-testing.md with clean facade
  docs/dg/dev/architecture/architectural-convention.md
  docs/dg/dev/guidelines/testing-guidelines/test-framework.md
  docs/dg/dev/guidelines/testing-guidelines/testing-best-practices/best-practices-for-effective-testing.md
Labels: in tech review, small changes

#3030 added versioning way for implement-versioning-for-rest-api-resources.md
  docs/dg/dev/glue-api/202410.0/glue-api-tutorials/implement-versioning-for-rest-api-resources.md
  docs/dg/dev/guidelines/testing-guidelines/testing-best-practices/best-practices-for-effective-testing.md
Labels: TW review needed, updated

#3032 ACP-4782 Added warning for PayOne App PayPal Express without PayOne a…
  _includes/pbc/all/install-features/202410.0/install-the-payments-feature.md
Labels: tech review needed, TW review needed

#3035 Update environment-scaling.md
  docs/ca/dev/environment-scaling.md
Labels: TW review needed

#3037 Update share-secrets-with-the-spryker-support-team.md
  docs/about/all/support/share-secrets-with-the-spryker-support-team.md
Labels: TW review needed
