Repository spryker/spryker-docs, pull requests merged in 2025-03, with the labels that each got.

#3047 AE-157 Documentation for Strategy Resolver
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/architecture/programming-concepts.md
  docs/dg/dev/miscellaneous-guides/miscellaneous-guides.md
  docs/dg/dev/miscellaneous-guides/strategy-resolvers.md
Labels: TW review needed, new

#3059 Update documentation for the algolia integration
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
Labels: TW review needed

#3060 Fixaton performance fix - installation
  docs/dg/dev/guidelines/performance-guidelines/general-performance-guidelines.md
Labels: TW review needed

#3069 Update using-the-support-portal.md
  Rakefile
  docs/about/all/support/using-the-support-portal.md
Labels: TW review needed

#3050 Monitoring main documentation
  _data/sidebars/ca_dev_sidebar.yml
  docs/ca/dev/monitoring/monitoring-issues-and-informing-about-alerts.md
  docs/ca/dev/monitoring/monitoring.md
  docs/ca/dev/monitoring/spryker-monitoring-integration.md
  docs/dg/dev/integrate-and-configure/configure-services.md
Labels: new, updated

#3071 CC-35345: Updated Promotions & Discounts + Order Management feature IG.
  _includes/pbc/all/install-features/202505.0/install-the-order-management-promotions-and-discounts-feature.md
Labels: in TW review

#3077 Removed UserCentrics from sidebar
  _data/sidebars/pbc_all_sidebar.yml
  _scripts/sidebar_checker/excludelist.yml
Labels: TW review needed

#3075 ACP-4931: Added new configuration setting for Algolia, required data …
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/configure-algolia.md
Labels: TW review needed, small changes

#3081 MFA enforcement note
  _data/sidebars/ca_dev_sidebar.yml
  docs/ca/dev/security/multi-factor-authentication-and-passwords.md
Labels: TW review needed

#3053 Feature/acp 4802/master over underpaid
  _data/sidebars/ca_dev_sidebar.yml
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/acp/apis-and-flows-for-payment-service-providers/asynchronous-api-for-payment-service-providers.md
  docs/dg/dev/acp/integrate-acp-payment-apps-with-spryker-oms-configuration.md
  docs/dg/dev/backend-development/data-manipulation/data-manipulation.md
  docs/dg/dev/backend-development/data-manipulation/set-up-an-order-management-system.md
  docs/pbc/all/order-management-system/202311.0/marketplace/create-merchant-oms-flows.md
  docs/pbc/all/order-management-system/202404.0/marketplace/create-merchant-oms-flows.md
  docs/pbc/all/order-management-system/202410.0/base-shop/state-machine-cookbook/state-machine-cookbook.md
  docs/pbc/all/order-management-system/202410.0/marketplace/create-merchant-oms-flows.md
  docs/pbc/all/payment-service-provider/202311.0/base-shop/third-party-integrations/heidelpay/heidelpay-oms-workflow.md
  docs/pbc/all/payment-service-provider/202404.0/base-shop/third-party-integrations/heidelpay/heidelpay-oms-workflow.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/heidelpay/heidelpay-oms-workflow.md
Labels: TW review needed, in TW review

#3078 Security release notes for Q1 2025
  _data/sidebars/about_all_sidebar.yml
  docs/about/all/releases/security-release-notes-202503.0.md
Labels: TW review needed, in TW review

#3065 FRW-10007 Sitemap.
  _data/sidebars/dg_dev_sidebar.yml
  docs/dg/dev/integrate-and-configure/integrate-sitemap-generation.md
  vale/styles/Spryker/NoColonsInHeadings.yml
Labels: TW review needed, in tech review, new
