Repository spryker/spryker-docs, pull requests merged in 2025-05, with the labels that each got.

#3088 ACP-4918 PayOne cancellation of a payment in the payone step lead to abandonate orders
  Rakefile
  _data/sidebars/pbc_all_sidebar.yml
  docs/about/all/releases/release-notes-202311.0.md
  docs/pbc/all/order-management-system/202410.0/base-shop/order-management-feature-overview/invoice-generation-overview.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/configure-handling-of-browser-back-button-action-at-hosted-payment-page.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/payone/app-composition-platform-integration/payone-acp-app.md
  docs/pbc/all/payment-service-provider/202410.0/base-shop/third-party-integrations/stripe/stripe.md
Labels: TW review needed

#3123 Fixed/refreshed ACP Algolia integration guide
  docs/pbc/all/search/202410.0/base-shop/third-party-integrations/algolia/integrate-algolia.md
Labels: TW review needed

#3124 CC-35627: Adjusted Order Amendment feature integration guide.
  _includes/pbc/all/install-features/202505.0/install-the-order-amendment-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-reorder-feature.md
Labels: in tech review

#3128 CC-34515 Enable Order Amendment for features connected to Cart (Multi-Cart) IGs.
  _includes/pbc/all/install-features/202311.0/install-dynamic-multistore-the-availability-notification-feature.md
  _includes/pbc/all/install-features/202311.0/install-dynamic-multistore-the-customer-account-management-feature.md
  _includes/pbc/all/install-features/202311.0/install-dynamic-multistore.md
  _includes/pbc/all/install-features/202311.0/install-glue-api/install-the-checkout-glue-api.md
  _includes/pbc/all/install-features/202311.0/install-glue-api/install-the-shipment-glue-api.md
  _includes/pbc/all/install-features/202311.0/install-the-approval-process-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-availability-notification-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-comments-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-comments-order-management-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-configurable-bundle-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-file-manager-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-product-lists-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-quotation-process-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-scheduled-prices-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-shipment-approval-process-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-shipment-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-shipment-service-points-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-spryker-core-back-office-feature.md
  _includes/pbc/all/install-features/202311.0/install-the-spryker-core-feature.md
  _includes/pbc/all/install-features/202311.0/marketplace/install-marketplace-shipment-feature.md
  _includes/pbc/all/install-features/202404.0/install-dynamic-multistore-the-availability-notification-feature.md
  _includes/pbc/all/install-features/202404.0/install-dynamic-multistore-the-customer-account-management-feature.md
  _includes/pbc/all/install-features/202404.0/install-dynamic-multistore.md
  _includes/pbc/all/install-features/202404.0/install-glue-api/install-the-shipment-glue-api.md
  _includes/pbc/all/install-features/202404.0/install-the-approval-process-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-availability-notification-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-comments-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-comments-order-management-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-configurable-bundle-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-file-manager-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-product-lists-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-quotation-process-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-scheduled-prices-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-shipment-approval-process-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-shipment-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-shipment-service-points-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-spryker-core-back-office-feature.md
  _includes/pbc/all/install-features/202404.0/install-the-spryker-core-feature.md
  _includes/pbc/all/install-features/202404.0/marketplace/install-marketplace-shipment-feature.md
  _includes/pbc/all/install-features/202410.0/install-dynamic-multistore-the-availability-notification-feature.md
  _includes/pbc/all/install-features/202410.0/install-dynamic-multistore-the-customer-account-management-feature.md
  _includes/pbc/all/install-features/202410.0/install-glue-api/install-the-shipment-glue-api.md
  _includes/pbc/all/install-features/202410.0/install-the-approval-process-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-availability-notification-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-comments-order-management-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-file-manager-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-product-lists-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-quotation-process-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-scheduled-prices-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-shipment-approval-process-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-shipment-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-shipment-service-points-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-spryker-core-back-office-feature.md
  _includes/pbc/all/install-features/202410.0/install-the-spryker-core-feature.md
  _includes/pbc/all/install-features/202410.0/marketplace/install-marketplace-shipment-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-order-amendment-feature.md
  _includes/pbc/all/install-features/202505.0/install-the-reorder-feature.md
  docs/dg/dev/sdks/the-docker-sdk/choosing-a-docker-sdk-version.md
Labels: TW review needed, updated

#3129 Update add-variables-in-the-parameter-store.md
  docs/ca/dev/add-variables-in-the-parameter-store.md
Labels: TW review needed

#3133 ACP-4918 Updated docs.
  docs/pbc/all/payment-service-provider/202410.0/base-shop/configure-handling-of-browser-back-button-action-at-hosted-payment-page.md
Labels: TW review needed

#3131 Update security-guidelines.md
  docs/ca/dev/configure-deployment-pipelines/deployment-pipelines.md
  docs/dg/dev/integrate-and-configure/configure-services.md
  docs/pbc/all/customer-relationship-management/202505.0/base-shop/install-and-upgrade/install-features/install-the-reorder-feature.md
  docs/pbc/all/order-management-system/202505.0/base-shop/order-amendment-feature-overview.md
  docs/pbc/all/product-information-management/202505.0/base-shop/install-and-upgrade/install-features/install-the-product-bundles-cart-feature.md
Labels: TW review needed

#3138 Update connect-a-code-repository.md
  docs/ca/dev/connect-a-code-repository.md
Labels: TW review needed

#3132 Removed uc pages from site
  _data/sidebars/pbc_all_sidebar.yml
  _internal/usercentrics/configure-usercentrics.md
  _internal/usercentrics/disconnect-usercentrics.md
  _internal/usercentrics/integrate-usercentrics.md
  _internal/usercentrics/usercentrics.md
  docs/dg/dev/integrate-and-configure/configure-services.md
  docs/pbc/all/miscellaneous/202311.0/third-party-integrations/operational-tools-monitoring-legal/usercentrics.md
  docs/pbc/all/pbc.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-vertex-validator.md
Labels: TW review needed

#3143 removed beta from top nav
  Gemfile.lock
  _includes/topnav.html
  docs/pbc/all/multi-factor-authentication/202505.0/multi-factor-authentication.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/install-vertex/install-vertex.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-the-vertex-app.md
  docs/pbc/all/tax-management/202410.0/base-shop/third-party-integrations/vertex/install-vertex/integrate-vertex-validator.md
Labels: TW review needed

#3144 updated docs for removing uc
  _internal/usercentrics.md
  docs/pbc/all/miscellaneous/202410.0/third-party-integrations/operational-tools-monitoring-legal/usercentrics.md
  docs/pbc/all/pbc.md
Labels: TW review needed

#3145 SUPESC-963: Introduced configurable session lock mechanism for the Yves.
  _includes/pbc/all/install-features/202505.0/install-the-spryker-core-feature.md
  docs/dg/dev/frontend-development/202311.0/oryx/architecture/reactivity/key-concepts-of-reactivity.md
  docs/dg/dev/frontend-development/202311.0/oryx/building-components/oryx-implementing-components.md
  docs/dg/dev/frontend-development/202404.0/oryx/architecture/reactivity/key-concepts-of-reactivity.md
  docs/dg/dev/frontend-development/202404.0/oryx/building-components/oryx-implementing-components.md
  docs/dg/dev/frontend-development/202410.0/oryx/architecture/reactivity/key-concepts-of-reactivity.md
  docs/dg/dev/frontend-development/202410.0/oryx/building-components/oryx-implementing-components.md
  docs/pbc/all/miscellaneous/202505.0/install-and-upgrade/install-features/install-the-spryker-core-feature.md
Labels: TW review needed

#3089 Update security-release-notes-202503.0.md
  docs/about/all/releases/security-release-notes-202503.0.md
Labels: TW review needed

#3141 Order placement performance optimization
  docs/dg/dev/guidelines/performance-guidelines/general-performance-guidelines.md
Labels: TW review needed

#3153 Update install-dynamic-multistore-the-customer-account-management-fea…
  _includes/pbc/all/install-features/202410.0/install-dynamic-multistore-the-customer-account-management-feature.md
Labels: updated, small changes, Bypassed TW Review
